// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

#ifndef indigo_test_runner_h
#define indigo_test_runner_h

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <ftw.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

typedef void (*indigo_test_function)(void);

typedef struct {
	const char *name;
	indigo_test_function function;
} indigo_test_case;

static int indigo_test_failures = 0;

// Name of the test case currently executing, or NULL outside indigo_run_tests().
// Shared helpers use it to label per-case diagnostic artifacts.
static const char *indigo_current_test_name = NULL;

// The assertion macros copy their arguments into locals prefixed indigo_assert_, a name no caller
// uses. With plain names such as expected_value, a helper that passed its own expected_value
// parameter expanded to 'const char *expected_value = (expected_value);', which initializes the
// local from itself: in the pmc8 TCP case it happened to hold the right pointer on macOS, the
// previous call's value at -O0 and NULL at -O3 on Linux, where it crashed the suite.
#define ASSERT_TRUE(condition) do { \
	if (!(condition)) { \
		fprintf(stderr, "%s:%d: assertion failed: %s\n", __FILE__, __LINE__, #condition); \
		indigo_test_failures++; \
		return; \
	} \
} while (0)

#define ASSERT_FALSE(condition) ASSERT_TRUE(!(condition))

#define ASSERT_EQ_INT(expected, actual) do { \
	int indigo_assert_expected = (expected); \
	int indigo_assert_actual = (actual); \
	if (indigo_assert_expected != indigo_assert_actual) { \
		fprintf(stderr, "%s:%d: expected %d, got %d\n", __FILE__, __LINE__, indigo_assert_expected, indigo_assert_actual); \
		indigo_test_failures++; \
		return; \
	} \
} while (0)

#define ASSERT_EQ_TOKEN(expected, actual) do { \
	indigo_token indigo_assert_expected = (expected); \
	indigo_token indigo_assert_actual = (actual); \
	if (indigo_assert_expected != indigo_assert_actual) { \
		fprintf(stderr, "%s:%d: expected 0x%llx, got 0x%llx\n", __FILE__, __LINE__, indigo_assert_expected, indigo_assert_actual); \
		indigo_test_failures++; \
		return; \
	} \
} while (0)

#define ASSERT_NEAR(expected, actual, tolerance) do { \
	double indigo_assert_expected = (expected); \
	double indigo_assert_actual = (actual); \
	double indigo_assert_tolerance = (tolerance); \
	if (fabs(indigo_assert_expected - indigo_assert_actual) > indigo_assert_tolerance) { \
		fprintf(stderr, "%s:%d: expected %.12g, got %.12g, tolerance %.12g\n", __FILE__, __LINE__, indigo_assert_expected, indigo_assert_actual, indigo_assert_tolerance); \
		indigo_test_failures++; \
		return; \
	} \
} while (0)

#define ASSERT_STREQ(expected, actual) do { \
	const char *indigo_assert_expected = (expected); \
	const char *indigo_assert_actual = (actual); \
	if (strcmp(indigo_assert_expected, indigo_assert_actual)) { \
		fprintf(stderr, "%s:%d: expected \"%s\", got \"%s\"\n", __FILE__, __LINE__, indigo_assert_expected, indigo_assert_actual); \
		indigo_test_failures++; \
		return; \
	} \
} while (0)

// Driver build numbers are bumped on every behaviour fix, so a test that pins the exact
// DRIVER_VERSION fails on the next bump for no reason and has to be edited along with the driver.
// Assert the API generation a driver reports instead: the top byte of DRIVER_VERSION, which only
// changes when the driver is migrated to another INDIGO driver API.
#define INDIGO_DRIVER_API_GENERATION(version) ((version) & 0xFF000000)
#define INDIGO_DRIVER_API_2 0x02000000
#define INDIGO_DRIVER_API_3 0x03000000

// The framework derives its configuration folder from HOME and caches the answer the first time it
// is asked, so a test that lets a driver save, load or restore configuration must redirect HOME
// before the bus starts. Redirecting indigo_uni_config_folder() at compile time is NOT enough: the
// framework is linked both into the test binary and into libindigo, the redirection reaches only
// one of the two copies, and CONFIG SAVE then writes a file that CONFIG LOAD does not read. See the
// "Configuration Isolation" section of indigo_test/AGENTS.md.
static char indigo_test_home[1024];

static int indigo_test_remove_entry(const char *path, const struct stat *status, int flag, struct FTW *ftw) {
	(void)status;
	(void)flag;
	(void)ftw;
	return remove(path);
}

// Remove a directory the test created, with everything below it.
static void indigo_test_remove_tree(const char *path) {
	if (path != NULL && *path) {
		nftw(path, indigo_test_remove_entry, 16, FTW_DEPTH | FTW_PHYS);
	}
}

// Point the framework's configuration at a directory the test already owns. The saved files land
// in <path>/.indigo, so the directory has to be removed with indigo_test_remove_tree().
static bool indigo_test_set_private_home(const char *path) {
	if (setenv("HOME", path, 1) != 0) {
		perror("setenv");
		return false;
	}
	// indigo_ccd_attach() points CCD_LOCAL_MODE at $HOME/indigo_image_cache/ and the framework
	// only checks that the folder is writable, it never creates it. An empty private home
	// therefore makes every CCD driver publish CCD_LOCAL_MODE in ALERT, and a CONFIG LOAD that
	// restores it never settles, which is what failed the ccd_svb config roundtrip. A real home
	// has the folder, so a private one gets it too.
	char image_cache[PATH_MAX];
	snprintf(image_cache, sizeof(image_cache), "%s/indigo_image_cache", path);
	if (mkdir(image_cache, 0755) != 0 && errno != EEXIST) {
		perror(image_cache);
		return false;
	}
	return true;
}

// mkdtemp() plus the HOME redirection, for a test that keeps a temporary directory of its own and
// wants the framework's configuration inside it. Returns the directory or NULL, like mkdtemp().
static char *indigo_test_mkdtemp_home(char *template_path) {
	char *path = mkdtemp(template_path);
	if (path != NULL && !indigo_test_set_private_home(path)) {
		return NULL;
	}
	return path;
}

// Call this as the first statement of main(), before indigo_start() and before any property is
// saved or restored. Returns false when the private directory cannot be created.
static bool indigo_test_use_private_home(void) {
	snprintf(indigo_test_home, sizeof(indigo_test_home), "/tmp/indigo-test-home.XXXXXX");
	if (mkdtemp(indigo_test_home) == NULL) {
		perror("mkdtemp");
		return false;
	}
	return indigo_test_set_private_home(indigo_test_home);
}

// Call this before main() returns, so a run leaves no configuration behind.
static void indigo_test_remove_private_home(void) {
	if (*indigo_test_home) {
		indigo_test_remove_tree(indigo_test_home);
		*indigo_test_home = 0;
	}
}

// INDIGO_TEST_RESULTS=<path> makes every suite append a machine readable record of its run to
// <path>, which is what tools/run_driver_test.py reads to record a driver test run. One record is
// one tab separated line:
//
//   plan    <count>  <suite>   the suite is about to run <count> cases
//   pass    <suite>  <case>    the case passed
//   fail    <suite>  <case>    the case failed
//   filter  <value>            only the cases matching <value> were selected
//
// The file is opened in append mode and every record is written with a single write(), so forked
// cases running concurrently append whole lines to the same file. A case that crashes or is killed
// by its watchdog leaves a plan without a result, which is how a reader tells the planned count
// from the completed one: the result of a run is the number of pass records out of the sum of the
// plan records.
static void indigo_test_record(const char *format, ...) {
	const char *path = getenv("INDIGO_TEST_RESULTS");
	if (path == NULL || *path == 0) {
		return;
	}
	char line[1024];
	va_list args;
	va_start(args, format);
	int length = vsnprintf(line, sizeof(line) - 1, format, args);
	va_end(args);
	if (length < 0) {
		return;
	}
	if (length > (int)sizeof(line) - 2) {
		length = (int)sizeof(line) - 2;
	}
	line[length++] = '\n';
	int file = open(path, O_WRONLY | O_APPEND | O_CREAT, 0644);
	if (file < 0) {
		perror(path);
		return;
	}
	if (write(file, line, length) != length) {
		perror(path);
	}
	close(file);
}

// Set once a runner has recorded the plan for cases it runs in forked children. The children
// inherit it, so the indigo_run_tests() call each of them makes does not plan its case again.
static bool indigo_test_plan_recorded = false;

// A runner that forks its cases calls this in the parent, before the first fork, with the number of
// cases it selected and the filter it selected them by (NULL when it runs all of them). A case whose
// child never reports then counts as planned but not passed, instead of disappearing from the run.
static void indigo_test_plan(const char *suite_name, int count, const char *filter) {
	if (filter != NULL) {
		indigo_test_record("filter\t%s", filter);
	}
	indigo_test_record("plan\t%d\t%s", count, suite_name);
	indigo_test_plan_recorded = true;
}

static int indigo_run_tests(const char *suite_name, const indigo_test_case *tests, int count) {
	int initial_failures = indigo_test_failures;
	// INDIGO_TEST_CASE_FILTER runs only the cases whose name contains it, which is how a
	// single case is repeated while a flaky or failing one is being tracked down.
	const char *filter = getenv("INDIGO_TEST_CASE_FILTER");
	if (!indigo_test_plan_recorded) {
		int selected = 0;
		for (int i = 0; i < count; i++) {
			if (filter == NULL || strstr(tests[i].name, filter) != NULL) {
				selected++;
			}
		}
		if (filter != NULL) {
			indigo_test_record("filter\t%s", filter);
		}
		indigo_test_record("plan\t%d\t%s", selected, suite_name);
	}
	printf("Running %s\n", suite_name);
	for (int i = 0; i < count; i++) {
		if (filter != NULL && strstr(tests[i].name, filter) == NULL) {
			continue;
		}
		int before = indigo_test_failures;
		indigo_current_test_name = tests[i].name;
		tests[i].function();
		indigo_current_test_name = NULL;
		if (indigo_test_failures == before) {
			printf("  PASS %s\n", tests[i].name);
			indigo_test_record("pass\t%s\t%s", suite_name, tests[i].name);
		} else {
			printf("  FAIL %s\n", tests[i].name);
			indigo_test_record("fail\t%s\t%s", suite_name, tests[i].name);
		}
	}
	if (indigo_test_failures == initial_failures) {
		printf("%s: all tests passed\n", suite_name);
		return 0;
	}
	printf("%s: %d test(s) failed\n", suite_name, indigo_test_failures - initial_failures);
	return 1;
}

#endif /* indigo_test_runner_h */
