# Copyright (c) 2026 INDIGO initiative
# All rights reserved.
#
# You may use this software under the terms of 'INDIGO Astronomy
# open-source license' (see LICENSE.md).
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Code is generated by AI

"""Run: python3 -B -m unittest discover -s indigo_tools/driver_editor -v"""

import hashlib
import http.client
import json
import os
import re
from pathlib import Path
import subprocess
import sys
import tempfile
import threading
import unittest
from unittest.mock import patch

from driver_editor import Server
from driver_format import FormatError, attributes, edit, parse, schema, structure, walk
from editor import Conflict, Editor, GenerationError, ROOT, generate, output_names
from source_map import build_mapping

GENERATOR = ROOT / 'build' / 'bin' / ('indigo_generator.exe' if os.name == 'nt' else 'indigo_generator')
FIXTURE = '''// Preserve this license and comment. 🚀
driver sample {
	label = "Example";
	author = "INDIGO";
	copyright = "Copyright (c) 2026 INDIGO";
	version = 1;
	aux {
		name = "Example";
		interface = INDIGO_INTERFACE_AUX_GPIO;
		number X_TEST {
			name = "X_TEST";
			label = "Test";
			persistent = true;
			item X_VALUE { name = "X_VALUE"; label = "Value"; value = 0; min = 0; max = 10; step = 1; }
			on_change { indigo_send_message(device, X_TEST_PROPERTY, "Changed"); }
			on_detach { /* detach marker context */ }
		}
		inherited AUX_OUTLET_NAMES { on_change { } }
	}
}
'''

def named(root, name):
	return next(node for node in walk(root) if node['name'] == name)

def selected_text(mapping, identity, text):
	lines = text.splitlines()
	return '\n'.join(lines[number - 1] for block in mapping['ranges'][identity] for number in range(block['startLine'], block['endLine'] + 1))

class ParserTests(unittest.TestCase):
	def test_repository_corpus_and_template(self):
		paths = list((ROOT / 'indigo_drivers').rglob('*.driver')) + [ROOT / 'indigo_tools/template.driver']
		self.assertGreaterEqual(len(paths), 61)
		for path in paths:
			with self.subTest(file=path.name):
				source = path.read_bytes().decode('utf-8')
				root = parse(source)
				identities = [node['id'] for node in walk(root)]
				self.assertEqual(len(identities), len(set(identities)))
				for node in walk(root):
					self.assertTrue(source[node['start']:node['end']].startswith(node['kind']))
				for node in walk(root):
					if node['attributes']:
						attribute = node['attributes'][0]
						updated, _ = edit(source, root, node['id'], [dict(field='attribute', name=attribute['name'], value=attribute['value'])])
						self.assertEqual(source, updated)
						break

	def test_delete_attribute_preserves_neighbors_and_can_be_added_again(self):
		for eol in ('\n', '\r\n'):
			source = eol.join(['driver a {', '\tversion = 1;', '\tlabel = "Camera"; // keep this comment', '\tauthor = "Author";', '}'])
			root = parse(source)
			updated, root = edit(source, root, root['id'], [dict(field='attribute', name='version', value='1', remove=True)])
			self.assertEqual(updated, source.replace('\tversion = 1;' + eol, ''))
			self.assertNotIn('version', attributes(root))
			updated, root = edit(updated, root, root['id'], [dict(field='attribute', name='label', value='', remove=True)])
			self.assertIn('// keep this comment', updated)
			self.assertEqual(attributes(root), {'author': '"Author"'})
			updated, root = edit(updated, root, root['id'], [dict(field='attribute', name='version', value='2')])
			self.assertEqual(attributes(root)['version'], '2')
			with self.assertRaises(ValueError):
				edit(updated, root, root['id'], [dict(field='attribute', name='missing', value='', remove=True)])
		source = 'driver a { version = 1; label = "Camera"; }'
		root = parse(source)
		updated, _ = edit(source, root, root['id'], [dict(field='attribute', name='version', value='', remove=True)])
		self.assertEqual(updated, 'driver a {  label = "Camera"; }')

	def test_structural_contexts_shorthand_and_preservation(self):
		for eol in ('\n', '\r\n'):
			source = eol.join(['// keep header', 'driver sample {', '\taux;', '}'])
			root = parse(source)
			updated, root, selected = structure(source, root, named(root, 'aux')['id'], 'add', 'number', 'X_VALUE')
			self.assertIn('aux {', updated)
			updated, root, item_id = structure(updated, root, selected, 'add', 'item', 'VALUE')
			self.assertIn('item VALUE {', updated)
			with self.assertRaises(ValueError):
				structure(updated, root, selected, 'add', 'item', 'value')
			with self.assertRaises(ValueError):
				structure(updated, root, item_id, 'add', 'item', 'NESTED')
			with self.assertRaises(ValueError):
				structure(updated, root, root['id'], 'remove')
			updated, root, parent_id = structure(updated, root, item_id, 'remove')
			self.assertEqual(parent_id, selected)
			self.assertNotIn('item VALUE', updated)
			self.assertTrue(updated.startswith('// keep header' + eol))
			inherited_source, inherited_root, inherited_id = structure(updated, root, named(root, 'aux')['id'], 'add', 'inherited', 'CONNECTION')
			with self.assertRaises(ValueError):
				structure(inherited_source, inherited_root, inherited_id, 'add', 'item', 'CONNECT')
			with self.assertRaises(ValueError):
				structure(updated, root, named(root, 'aux')['id'], 'add', 'number', 'BAD_CUSTOM')
			with self.assertRaises(ValueError):
				structure(updated, root, root['id'], 'add', 'aux')

	def test_strings_comments_nested_expressions_and_code(self):
		source = r'''driver a { constant = ((int[]){1, 2})[0]; code { // } is not a delimiter
		char c = '}'; /* { */ const char *s = "escaped \" } ;"; if (1) { work(); }
	} aux; }'''
		root = parse(source)
		self.assertEqual(attributes(root)['constant'], '((int[]){1, 2})[0]')
		self.assertIn('work();', source[named(root, 'code')['bodyStart']:named(root, 'code')['bodyEnd']])

	def test_shorthand_and_repeated_nodes(self):
		root = parse('driver a { serial { pattern; pattern; } aux { inherited X_SAME; } wheel { inherited X_SAME; } }')
		ids = [node['id'] for node in walk(root)]
		self.assertEqual(len(ids), len(set(ids)))
		self.assertEqual(len([node for node in walk(root) if node['name'] == 'X_SAME']), 2)

	def test_continued_line_comment_does_not_close_code_block(self):
		source = 'driver x { code { // continued \\\n } still a comment\n int value; } aux; }'
		root = parse(source)
		self.assertIn('int value;', source[named(root, 'code')['bodyStart']:named(root, 'code')['bodyEnd']])

	def test_lossless_attribute_and_code_edit_with_unicode_crlf(self):
		source = FIXTURE.replace('\n', '\r\n')
		root = parse(source)
		a = root['attributes'][0]
		updated, tree = edit(source, root, root['id'], [dict(field='attribute', name='label', value='"Edited 🚀"')])
		self.assertEqual(updated, source[:a['start']] + '"Edited 🚀"' + source[a['end']:])
		code = named(tree, 'on_change')
		changed, _ = edit(updated, tree, code['id'], [dict(field='code', value=' return; ')])
		self.assertEqual(changed, updated[:code['bodyStart']] + ' return; ' + updated[code['bodyEnd']:])

	def test_invalid_structure_reports_position(self):
		for source in ['driver x {', 'driver x { aux { name = ; } }', 'driver x { code { "bad } }', 'driver x { /* missing', 'driver x { aux; } trailing', 'driver x { aux { name = 1 } }']:
			with self.subTest(source=source), self.assertRaises(FormatError) as error:
				parse(source)
			self.assertGreater(error.exception.line, 0)
			self.assertGreater(error.exception.column, 0)

	def test_unknown_content_preserved_and_source_edits(self):
		source = 'driver x { future_attribute = SOME_MACRO(1); future_block { newer = 2; } aux; }'
		root = parse(source)
		updated, _ = edit(source, root, named(root, 'future_block')['id'], [dict(field='source', value='future_block { newer = 3; }')])
		self.assertEqual(updated, source.replace('newer = 2', 'newer = 3'))

	def test_template_catalog_includes_all_attributes_and_current_extensions(self):
		template = (ROOT / 'indigo_tools/template.driver').read_text()
		catalog = schema(template)
		for node in walk(parse(template)):
			context = 'device' if node['kind'] == 'XXXXX' else node['kind']
			if context == 'item':
				context = 'item:' + node['id'].split('/')[-2].split(':')[0]
			for attribute in node['attributes']:
				if attribute['name'] != 'XXXXX':
					self.assertIn(attribute['name'], catalog[context])
		self.assertIn('supported_architecture', catalog['driver'])
		self.assertIn('attach_if', catalog['device'])
		self.assertIn('format', catalog['item:number'])

	def test_template_matches_generator_attribute_contexts(self):
		generator = (ROOT / 'indigo_tools/indigo_generator.c').read_text()
		catalog = schema((ROOT / 'indigo_tools/template.driver').read_text())
		def accepted(function):
			body = generator.split('bool ' + function + '(')[1].split('\nbool ')[0]
			return {name: {'bool': 'boolean', 'int': 'integer'}.get(kind, kind) for kind, name in re.findall(r'parse_(\w+)_attribute\("([^"]+)"', body)}
		for context in ('device', 'serial', 'pattern', 'sdk', 'hid', 'libusb'):
			self.assertEqual({name: entry['type'] for name, entry in catalog[context].items()}, accepted('parse_' + context + '_block'))
		for kind in ('inherited', 'number', 'text', 'switch', 'light'):
			expected = accepted('parse_property_block')
			if kind == 'inherited':
				for name in ('group', 'pointer', 'always_defined'):
					del expected[name]
			self.assertEqual({name: entry['type'] for name, entry in catalog[kind].items()}, expected)
			if kind != 'inherited':
				expected = accepted('parse_item_block')
				if kind != 'number':
					for name in ('min', 'max', 'step', 'format'):
						del expected[name]
				self.assertEqual({name: entry['type'] for name, entry in catalog['item:' + kind].items()}, expected)
		self.assertEqual({name: entry['type'] for name, entry in catalog['driver'].items()}, {'author': 'string', 'copyright': 'string', 'label': 'string', 'supported_architecture': 'string', 'version': 'integer'})

class EditorTests(unittest.TestCase):
	def setUp(self):
		self.temporary = tempfile.TemporaryDirectory(prefix='driver editor test ')
		self.addCleanup(self.temporary.cleanup)
		self.path = Path(self.temporary.name) / 'input with spaces.driver'
		self.path.write_text(FIXTURE, encoding='utf-8')
		self.editor = Editor(self.path, GENERATOR)

	def change_label(self, value='"Edited"'):
		return self.editor.apply(self.editor.revision, self.editor.root['id'], [dict(field='attribute', name='label', value=value)])

	def test_edits_stay_in_memory_and_save_round_trip(self):
		self.change_label()
		self.assertEqual(self.path.read_text(), FIXTURE)
		self.assertTrue(self.editor.state()['dirty'])
		self.editor.save(2)
		self.assertEqual(Editor(self.path, GENERATOR).source, FIXTURE.replace('label = "Example"', 'label = "Edited"', 1))
		self.assertFalse(self.editor.state()['dirty'])

	def test_stale_revision_and_invalid_edit_leave_state_untouched(self):
		with self.assertRaises(Conflict):
			self.editor.save(0)
		with self.assertRaises(FormatError):
			self.change_label('"unterminated')
		self.assertEqual(self.editor.revision, 1)
		self.assertEqual(self.editor.source, FIXTURE)

	@unittest.skipUnless(GENERATOR.is_file(), 'Build indigo_generator first')
	def test_add_rename_generate_remove_nodes(self):
		state = self.editor.change_structure(1, self.editor.root['id'], 'add', 'wheel')
		device = state['selected']
		state = self.editor.change_structure(state['revision'], device, 'add', 'number', 'X_TEST')
		prop = state['selected']
		state = self.editor.change_structure(state['revision'], prop, 'add', 'item', 'VALUE')
		item = state['selected']
		state = self.editor.apply(state['revision'], item, [dict(field='identifier', value='RENAMED_VALUE')])
		item = state['renamed'][item]
		state = self.editor.apply(state['revision'], prop, [dict(field='identifier', value='X_RENAMED'), dict(field='attribute', name='label', value='"Renamed"')])
		self.assertIn(item, state['renamed'])
		prop = state['renamed'][prop]
		preview = self.editor.refresh(state['revision'])['preview']
		self.assertIn('X_RENAMED_PROPERTY', preview['source'])
		self.assertIn('RENAMED_VALUE_ITEM', preview['source'])
		before = self.editor.source
		with self.assertRaises(ValueError):
			self.editor.apply(self.editor.revision, prop, [dict(field='identifier', value='bad name')])
		self.assertEqual(self.editor.source, before)
		with self.assertRaises(Conflict):
			self.editor.change_structure(1, device, 'remove')
		state = self.editor.change_structure(self.editor.revision, device, 'remove')
		self.assertEqual(state['selected'], self.editor.root['id'])
		self.assertNotIn('X_RENAMED', self.editor.source)
		self.assertTrue(state['preview']['stale'])
		self.assertEqual(self.path.read_text(), FIXTURE)

	def test_disk_conflict_and_failed_atomic_save(self):
		self.change_label()
		self.path.write_text(FIXTURE + '// external edit\n')
		with self.assertRaises(Conflict):
			self.editor.save(2)
		self.assertTrue(self.path.read_text().endswith('// external edit\n'))
		self.path.write_text(FIXTURE, encoding='utf-8')
		with patch('editor.os.replace', side_effect=PermissionError('read only')), self.assertRaises(PermissionError):
			self.editor.save(2)
		self.assertEqual(self.path.read_text(), FIXTURE)
		self.assertEqual([path.name for path in self.path.parent.iterdir()], [self.path.name])

	@unittest.skipUnless(GENERATOR.is_file(), 'Build indigo_generator first')
	def test_generation_isolated_publish_and_reopen(self):
		before = self.path.read_bytes()
		state = self.editor.refresh(1)
		self.assertIn('indigo_init_number_property', state['preview']['source'])
		self.assertEqual(self.path.read_bytes(), before)
		self.assertEqual(len(list(self.path.parent.iterdir())), 1)
		self.change_label()
		self.assertTrue(self.editor.state()['preview']['stale'])
		with self.assertRaises(Conflict):
			self.editor.publish(2)
		self.editor.save(2)
		with self.assertRaises(Conflict):
			self.editor.publish(2)
		self.editor.refresh(2)
		result = self.editor.publish(2)
		self.assertEqual(len(result['written']), 3)
		for name, data in self.editor.outputs.items():
			self.assertEqual((self.path.parent / name).read_bytes(), data)
		self.assertIn('"Edited"', Editor(self.path, GENERATOR).source)

	@unittest.skipUnless(GENERATOR.is_file(), 'Build indigo_generator first')
	def test_publish_conflict_and_rollback(self):
		self.editor.refresh(1)
		names = output_names(self.editor.root)
		(self.path.parent / names[1]).write_text('external')
		with self.assertRaises(Conflict):
			self.editor.publish(1)
		self.assertFalse((self.path.parent / names[0]).exists())
		(self.path.parent / names[1]).unlink()
		original_replace = os.replace
		calls = 0
		def fail_second(source, destination):
			nonlocal calls
			calls += 1
			if calls == 2:
				raise PermissionError('second output failed')
			return original_replace(source, destination)
		with patch('editor.os.replace', side_effect=fail_second), self.assertRaises(PermissionError):
			self.editor.publish(1)
		self.assertEqual([path.name for path in self.path.parent.iterdir()], [self.path.name])
		self.editor.publish(1)
		self.assertEqual(len(list(self.path.parent.iterdir())), 4)

	def test_missing_generator_timeout_and_failed_output(self):
		for failure in [FileNotFoundError('missing'), subprocess.TimeoutExpired('generator', 1)]:
			with patch('editor.subprocess.run', side_effect=failure), self.assertRaises(GenerationError):
				self.editor.refresh(1)
		self.assertEqual(self.path.read_text(), FIXTURE)
		for result in [subprocess.CompletedProcess([], 7, b'', b'bad input'), subprocess.CompletedProcess([], 0, b'', b'')]:
			with patch('editor.subprocess.run', return_value=result), self.assertRaises(GenerationError):
				self.editor.refresh(1)

	def test_actual_timeout_reaps_process_and_removes_workspace(self):
		workspaces = []
		original_run = subprocess.run
		def observed_run(*args, **kwargs):
			workspaces.append(Path(kwargs['cwd']).parents[1])
			return original_run(*args, **kwargs)
		with patch('editor.subprocess.run', side_effect=observed_run), self.assertRaisesRegex(GenerationError, 'terminated'):
			generate('import time\ntime.sleep(10)\n', 'wait.driver', parse(FIXTURE), Path(sys.executable), ROOT, 0.1)
		self.assertTrue(workspaces)
		self.assertTrue(all(not path.exists() for path in workspaces))

	def test_incomplete_repository_is_reported(self):
		with self.assertRaisesRegex(GenerationError, 'Missing base driver source'):
			generate(FIXTURE, self.path.name, parse(FIXTURE), GENERATOR, self.path.parent, 10)

	def test_edit_during_generation_discards_old_result(self):
		started, release = threading.Event(), threading.Event()
		errors = []
		def delayed(*args):
			started.set()
			if not release.wait(3):
				raise RuntimeError('Test synchronization timed out')
			return {'indigo_aux_sample.c': b'// old preview\n'}, ''
		def refresh():
			try:
				self.editor.refresh(1)
			except Exception as error:
				errors.append(error)
		with patch('editor.generate', side_effect=delayed):
			thread = threading.Thread(target=refresh)
			thread.start()
			try:
				self.assertTrue(started.wait(3))
				self.change_label()
			finally:
				release.set()
				thread.join(3)
		self.assertFalse(thread.is_alive())
		self.assertIsInstance(errors[0], Conflict)
		self.assertIsNone(self.editor.preview)

	@unittest.skipUnless(GENERATOR.is_file(), 'Build indigo_generator first')
	def test_failed_generation_retains_last_preview_and_recovers(self):
		self.editor.refresh(1)
		old = self.editor.preview['source']
		with patch('editor.subprocess.run', side_effect=FileNotFoundError('missing')), self.assertRaises(GenerationError):
			self.editor.refresh(1)
		self.assertEqual(self.editor.preview['source'], old)
		self.assertTrue(self.editor.state()['preview']['stale'])
		self.editor.refresh(1)
		self.assertFalse(self.editor.state()['preview']['stale'])

@unittest.skipUnless(GENERATOR.is_file(), 'Build indigo_generator first')
class MappingTests(unittest.TestCase):
	def test_serial_patterns_parent_union_and_no_output(self):
		source = FIXTURE.replace('version = 1;', 'version = 1; serial { pattern { vendor = "One"; } pattern { product = "Two"; } pattern; }')
		root = parse(source)
		outputs, _ = generate(source, 'serial.driver', root, GENERATOR, ROOT, 10)
		text = outputs['indigo_aux_sample.c'].decode()
		mapping = build_mapping(root, text)
		serial = named(root, 'serial')
		patterns = serial['children']
		first = selected_text(mapping, patterns[0]['id'], text)
		second = selected_text(mapping, patterns[1]['id'], text)
		self.assertIn('patterns[0].vendor_string', first)
		self.assertNotIn('patterns[1]', first)
		self.assertIn('patterns[1].product_string', second)
		self.assertFalse(mapping['ranges'][patterns[2]['id']])
		self.assertIn(first, selected_text(mapping, serial['id'], text))

	def test_repeated_code_blocks_report_shared_mapping(self):
		source = FIXTURE.replace('version = 1;', 'version = 1; define { #define ONE 1\n } define { #define TWO 2\n }')
		root = parse(source)
		outputs, _ = generate(source, 'repeated.driver', root, GENERATOR, ROOT, 10)
		mapping = build_mapping(root, outputs['indigo_aux_sample.c'].decode())
		self.assertTrue(any('Repeated define' in warning for warning in mapping['warnings']))

	def test_preview_matches_normal_generator_working_directory(self):
		path = ROOT / 'indigo_drivers/wheel_manual/indigo_wheel_manual.driver'
		source = path.read_text()
		root = parse(source)
		outputs, _ = generate(source, path.name, root, GENERATOR, ROOT, 10)
		with tempfile.TemporaryDirectory() as temporary:
			copy = Path(temporary) / path.name
			copy.write_text(source)
			result = subprocess.run([str(GENERATOR), str(copy)], cwd=path.parent, capture_output=True, timeout=10)
			self.assertEqual(result.returncode, 0, result.stderr.decode())
			for name, content in outputs.items():
				self.assertEqual((copy.parent / name).read_bytes(), content)

	def test_property_lifecycle_and_detach_marker(self):
		root = parse(FIXTURE)
		outputs, _ = generate(FIXTURE, 'test.driver', root, GENERATOR, ROOT, 10)
		text = outputs['indigo_aux_sample.c'].decode()
		mapping = build_mapping(root, text)
		prop = named(root, 'X_TEST')
		selected = selected_text(mapping, prop['id'], text)
		for fragment in ['#define X_TEST_PROPERTY', 'indigo_property *x_test_property', 'indigo_init_number_property', 'indigo_init_number_item', 'indigo_define_property', 'indigo_delete_property', 'indigo_release_property', 'indigo_save_property', 'aux_x_test_handler', 'return INDIGO_FAILED', 'return INDIGO_OK']:
			self.assertIn(fragment, selected)
		detach = named(prop, 'on_detach')
		self.assertIn('detach marker context', selected_text(mapping, detach['id'], text))
		self.assertGreater(len(mapping['ranges'][prop['id']]), 4)
		self.assertEqual(mapping['ranges'][root['id']], [dict(startLine=1, endLine=len(text.splitlines()))])

	def test_duplicate_property_names_are_scoped_and_references_excluded(self):
		source = '''driver multi { label = "Multi"; author = "Test"; copyright = "Test"; version = 1;
		aux { inherited X_SAME { on_change { /* AUX owner */ } } code { void other() { USE(X_SAME_PROPERTY); } } }
		wheel { inherited X_SAME { on_change { /* WHEEL owner */ } } }
		}'''
		root = parse(source)
		outputs, _ = generate(source, 'multi.driver', root, GENERATOR, ROOT, 10)
		text = outputs['indigo_aux_multi.c'].decode()
		mapping = build_mapping(root, text)
		props = [node for node in walk(root) if node['name'] == 'X_SAME']
		first, second = [selected_text(mapping, node['id'], text) for node in props]
		self.assertIn('AUX owner', first)
		self.assertNotIn('WHEEL owner', first)
		self.assertIn('WHEEL owner', second)
		self.assertNotIn('USE(X_SAME_PROPERTY)', first)

	def test_all_real_drivers_generate_without_modification(self):
		generator_hash = hashlib.sha256(GENERATOR.read_bytes()).hexdigest()
		for path in sorted((ROOT / 'indigo_drivers').rglob('*.driver')):
			with self.subTest(file=path.name):
				before = path.read_bytes()
				source = before.decode('utf-8')
				root = parse(source)
				outputs, _ = generate(source, path.name, root, GENERATOR, ROOT, 15)
				text = outputs[output_names(root)[0]].decode('utf-8')
				mapping = build_mapping(root, text)
				self.assertEqual(path.read_bytes(), before)
				for node in walk(root):
					for block in mapping['ranges'][node['id']]:
						self.assertTrue(1 <= block['startLine'] <= block['endLine'] <= len(text.splitlines()))
					if node['kind'] in {'inherited', 'switch', 'number', 'light', 'text'}:
						self.assertTrue(mapping['ranges'][node['id']], node['id'])
		self.assertEqual(hashlib.sha256(GENERATOR.read_bytes()).hexdigest(), generator_hash)

class HTTPTests(unittest.TestCase):
	def setUp(self):
		self.temporary = tempfile.TemporaryDirectory()
		self.addCleanup(self.temporary.cleanup)
		path = Path(self.temporary.name) / 'test.driver'
		path.write_text(FIXTURE, encoding='utf-8')
		self.editor = Editor(path, GENERATOR)
		self.server = Server(self.editor)
		self.thread = threading.Thread(target=self.server.serve_forever)
		self.thread.start()
		self.addCleanup(self.stop)

	def stop(self):
		self.server.shutdown()
		self.thread.join(3)
		self.server.server_close()

	def request(self, path='/api/state', data=None, headers=None):
		connection = http.client.HTTPConnection('127.0.0.1', self.server.server_port, timeout=5)
		request_headers = {'X-Editor-Token': self.server.token, 'Origin': self.server.origin, 'Content-Type': 'application/json'}
		request_headers.update(headers or {})
		connection.request('POST' if data is not None else 'GET', path, json.dumps(data) if data is not None else None, request_headers)
		response = connection.getresponse()
		body = response.read()
		status = response.status
		connection.close()
		return status, body

	def test_assets_state_and_traversal(self):
		for path in ['/', '/app.js', '/style.css', '/api/state']:
			self.assertEqual(self.request(path)[0], 200)
		for name in ['bootstrap.min.css', 'bootstrap.min.js', 'indigo.css', 'script.png']:
			status, content = self.request('/' + name)
			self.assertEqual(status, 200)
			self.assertEqual(content, (ROOT / 'indigo_server/resource' / name).read_bytes())
		for path in ['/../editor.py', '/editor.py', '/api/unknown', '/%2e%2e/editor.py']:
			self.assertEqual(self.request(path)[0], 404)
		state = json.loads(self.request()[1])
		self.assertEqual(state['revision'], 1)
		self.assertEqual(state['source'], FIXTURE)

	def test_open_driver_listing_empty_session_and_conflicts(self):
		repository = Path(self.temporary.name)
		for directory in ('indigo_drivers/camera', 'indigo_aux_drivers/nested', 'other_drivers'):
			folder = repository / directory
			folder.mkdir(parents=True)
			(folder / 'sample.driver').write_text(FIXTURE)
		outside = repository / 'outside.driver'
		outside.write_text(FIXTURE)
		(repository / 'indigo_drivers/escape.driver').symlink_to(outside)
		self.server.repository = repository
		self.server.editor = None
		state = json.loads(self.request()[1])
		self.assertIsNone(state['tree'])
		self.assertEqual(self.request('/api/save', {'revision': 0})[0], 400)
		files = json.loads(self.request('/api/drivers')[1])['files']
		self.assertEqual(files, ['indigo_aux_drivers/nested/sample.driver', 'indigo_drivers/camera/sample.driver'])
		self.assertEqual(self.request('/api/open', {'file': '../outside.driver', 'revision': 0})[0], 400)
		status, body = self.request('/api/open', {'file': files[0], 'revision': 0, 'document': state['document']})
		self.assertEqual(status, 200)
		opened = json.loads(body)
		self.assertEqual(opened['revision'], 1)
		self.assertNotEqual(opened['document'], state['document'])
		self.assertEqual(self.request('/api/save', {'revision': 1, 'document': state['document']})[0], 409)
		self.server.editor.apply(1, self.server.editor.root['id'], [dict(field='attribute', name='version', value='2')])
		self.assertEqual(self.request('/api/open', {'file': files[1], 'revision': 2})[0], 409)
		bad = repository / 'indigo_drivers/broken.driver'
		bad.write_text('driver {')
		self.assertEqual(self.request('/api/open', {'file': 'indigo_drivers/broken.driver', 'revision': 2, 'discard': True})[0], 400)
		self.assertEqual(self.server.editor.revision, 2)
		self.assertEqual(self.request('/api/open', {'file': files[1], 'revision': 2, 'discard': True})[0], 200)
		self.assertEqual((repository / files[0]).read_text(), FIXTURE)

	def test_origin_token_host_and_revision(self):
		self.assertEqual(self.request(headers={'X-Editor-Token': ''})[0], 403)
		self.assertEqual(self.request(headers={'Host': 'other.example'})[0], 403)
		self.assertEqual(self.request('/api/save', {'revision': 1}, {'Origin': 'https://other.example'})[0], 403)
		self.assertEqual(self.request('/api/save', {'revision': 0})[0], 409)
		self.assertEqual(self.request('/api/save', {'revision': 1})[0], 200)
		self.assertEqual(self.request('/api/edit', [1, 2])[0], 400)
		self.assertEqual(self.request('/api/edit', {'revision': 1, 'node': self.editor.root['id'], 'changes': []})[0], 400)

if __name__ == '__main__':
	unittest.main()
