// Deep Sky Dad AF focuser simulator
//
// Copyright (c) 2026 CloudMakers, s. r. o.
// All rights reserved.
//
// You can use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// Protocol: commands are framed "[XXXX<argument>]", replies "(...)"; errors
// are "!NNN)". Documented behaviour (INDI Deep Sky Dad AF1/AF2/AF3 drivers):
// [STRG] answers "(OK)" or "!101)" when the move exceeds the maximum move,
// [SMOV] answers "(OK)", [STOP] reply is not read, currents of AF1/AF2 are
// reported with a '%' suffix, AF3 uses current multipliers. Simulator
// assumptions (undocumented): "!100)" for unknown or unsupported commands,
// "!102)" for invalid arguments, motion targets are clamped to the maximum
// position and a temperature of -127 means that no sensor is attached.
//
// Test hooks (all optional, named by environment variables):
//   INDIGO_DSD_EVENTS   event log: "<time> RX|TX|STATE|FAULT|CONTROL <text>"
//   INDIGO_DSD_FAULT    "<COMMAND|ANY> <silent|error|malformed|partial|garbage|close> [count]"
//   INDIGO_DSD_CONTROL  lines "<position|temperature|stall|max_move|board> <value>"

#include <errno.h>
#include <limits.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/select.h>
#include <unistd.h>

#include "../../../indigo_test/simulator_common/serial_motion.h"
#include "../../../indigo_test/simulator_common/serial_simulator_common.h"

#define MAX_REQUEST 64

static const char *ready_file, *fault_file, *control_file;
static FILE *events;
static bool trace, headless, stalled;
static volatile sig_atomic_t running = 1;
static int serial_fd = -1;
static int model = 2;
static char board[64] = "DSD AF2", firmware[32] = "2.0.0";
static int max_position = 100000, max_move = 50000, target = 1000, speed = 2, step_mode = 8, coils_mode = 0;
static int move_current = 50, hold_current = 40, move_multiplier = 60, hold_multiplier = 30, settle_time = 0, coils_timeout = 60000, reverse = 0;
static double temperature = 21.5;
static serial_motion motion;

static void event(const char *kind, const char *format, ...) {
	if (!events) {
		return;
	}
	fprintf(events, "%.6f %s ", serial_motion_time(), kind);
	va_list args;
	va_start(args, format);
	vfprintf(events, format, args);
	va_end(args);
	fputc('\n', events);
	fflush(events);
}

static void stop_signal(int signal) {
	(void)signal;
	running = 0;
}

static int current_position(void) {
	return (int)(stalled ? motion.position : serial_motion_update(&motion));
}

static bool is_moving(void) {
	current_position();
	return stalled || motion.duration > 0;
}

static bool write_text(const char *text) {
	event("TX", "%s", text);
	serial_simulator_trace_line(trace, "<-", text);
	return serial_simulator_write_all(serial_fd, text, strlen(text));
}

static bool reply(const char *format, ...) {
	char buffer[128];
	va_list args;
	va_start(args, format);
	int length = vsnprintf(buffer, sizeof(buffer), format, args);
	va_end(args);
	return length >= 0 && length < (int)sizeof(buffer) && write_text(buffer);
}

static bool fault(const char *key) {
	if (!fault_file) {
		return false;
	}
	FILE *file = fopen(fault_file, "r");
	if (!file) {
		return false;
	}
	char command[16] = "", action[16] = "";
	int count = 1;
	int fields = fscanf(file, "%15s %15s %d", command, action, &count);
	fclose(file);
	if (fields < 2 || (strcmp(command, key) && strcmp(command, "ANY"))) {
		return false;
	}
	if (--count <= 0) {
		unlink(fault_file);
	} else {
		char temporary[PATH_MAX];
		snprintf(temporary, sizeof(temporary), "%s.sim", fault_file);
		file = fopen(temporary, "w");
		if (file) {
			fprintf(file, "%s %s %d\n", command, action, count);
			fclose(file);
			rename(temporary, fault_file);
		}
	}
	event("FAULT", "%s %s", key, action);
	if (!strcmp(action, "silent")) {
		return true;
	}
	if (!strcmp(action, "error")) {
		write_text("!100)");
	} else if (!strcmp(action, "malformed")) {
		write_text("(12x)");
	} else if (!strcmp(action, "partial")) {
		write_text("(12");
	} else if (!strcmp(action, "garbage")) {
		write_text("(ERR)");
	} else if (!strcmp(action, "close")) {
		running = 0;
	}
	return true;
}

static bool parse_value(const char *argument, const char *suffix, int *value) {
	char *end;
	errno = 0;
	long result = strtol(argument, &end, 10);
	if (end == argument || errno || result < INT_MIN || result > INT_MAX || strcmp(end, suffix)) {
		return false;
	}
	*value = (int)result;
	return true;
}

static void reject(const char *reason) {
	event("REJECT", "%s", reason);
	write_text("!102)");
}

static void unsupported(const char *request) {
	event("REJECT", "unsupported %s", request);
	write_text("!100)");
}

static bool valid_step_mode(int value) {
	int maximum = model == 3 ? 256 : 8;
	for (int mode = 1; mode <= maximum; mode *= 2) {
		if (value == mode) {
			return true;
		}
	}
	return false;
}

static double motion_rate(void) {
	return 2000.0 * speed;
}

static void dispatch(const char *request) {
	event("RX", "%s", request);
	serial_simulator_trace_line(trace, "->", request);
	size_t length = strlen(request);
	if (length < 6 || request[0] != '[' || request[length - 1] != ']') {
		unsupported(request);
		return;
	}
	char key[5], argument[MAX_REQUEST];
	memcpy(key, request + 1, 4);
	key[4] = 0;
	snprintf(argument, sizeof(argument), "%.*s", (int)(length - 6), request + 5);
	if (fault(key)) {
		return;
	}
	bool af12 = model < 3;
	bool query = argument[0] == 0;
	int value = 0;
	if (!strcmp(key, "GFRM") && query) {
		reply("(Board=%s, Version=%s)", board, firmware);
	} else if (!strcmp(key, "GPOS") && query) {
		reply("(%d)", current_position());
	} else if (!strcmp(key, "GMOV") && query) {
		reply("(%d)", is_moving() ? 1 : 0);
	} else if (!strcmp(key, "GTMC") && query && model > 1) {
		reply("(%.2f)", temperature);
	} else if (!strcmp(key, "GMXP") && query) {
		reply("(%d)", max_position);
	} else if (!strcmp(key, "GMXM") && query) {
		reply("(%d)", max_move);
	} else if (!strcmp(key, "GSPD") && query) {
		reply("(%d)", speed);
	} else if (!strcmp(key, "GSTP") && query) {
		reply("(%d)", step_mode);
	} else if (!strcmp(key, "GCLM") && query && af12) {
		reply("(%d)", coils_mode);
	} else if (!strcmp(key, "GCMV") && !strcmp(argument, "%") && af12) {
		reply("(%d%%)", move_current);
	} else if (!strcmp(key, "GCHD") && !strcmp(argument, "%") && af12) {
		reply("(%d%%)", hold_current);
	} else if (!strcmp(key, "GMMM") && query && !af12) {
		reply("(%d)", move_multiplier);
	} else if (!strcmp(key, "GMHM") && query && !af12) {
		reply("(%d)", hold_multiplier);
	} else if (!strcmp(key, "GBUF") && query) {
		reply("(%d)", settle_time);
	} else if (!strcmp(key, "GIDC") && query && af12) {
		reply("(%d)", coils_timeout);
	} else if (!strcmp(key, "STRG")) {
		if (!parse_value(argument, "", &value) || value < 0) {
			reject(request);
		} else if (abs(value - current_position()) > max_move) {
			event("STATE", "target=%d exceeds max_move=%d", value, max_move);
			write_text("!101)");
		} else {
			target = value;
			event("STATE", "target=%d", target);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SMOV") && query) {
		int destination = target > max_position ? max_position : target;
		stalled = false;
		serial_motion_start(&motion, destination, motion_rate());
		event("MOVE", "from=%d to=%d speed=%d", (int)motion.origin, destination, speed);
		write_text("(OK)");
	} else if (!strcmp(key, "STOP") && query) {
		serial_motion_stop(&motion);
		stalled = false;
		target = current_position();
		event("STATE", "stop position=%d", target);
	} else if (!strcmp(key, "SPOS")) {
		if (!parse_value(argument, "", &value) || value < 0 || value > max_position) {
			reject(request);
		} else {
			serial_motion_sync(&motion, value);
			stalled = false;
			target = value;
			event("STATE", "sync=%d", value);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SREV")) {
		if (!parse_value(argument, "", &value) || (value != 0 && value != 1)) {
			reject(request);
		} else {
			reverse = value;
			event("STATE", "reverse=%d", reverse);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SMXM")) {
		if (!parse_value(argument, "", &value) || value < 1) {
			reject(request);
		} else {
			max_move = value;
			event("STATE", "max_move=%d", max_move);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SMXP")) {
		if (!parse_value(argument, "", &value) || value < 1) {
			reject(request);
		} else {
			max_position = value;
			event("STATE", "max_position=%d", max_position);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SSPD")) {
		if (!parse_value(argument, "", &value) || value < 1 || value > (af12 ? 3 : 5)) {
			reject(request);
		} else {
			speed = value;
			event("STATE", "speed=%d", speed);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SSTP")) {
		if (!parse_value(argument, "", &value) || !valid_step_mode(value)) {
			reject(request);
		} else {
			step_mode = value;
			event("STATE", "step_mode=%d", step_mode);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SCLM") && af12) {
		if (!parse_value(argument, "", &value) || value < 0 || value > 2) {
			reject(request);
		} else {
			coils_mode = value;
			event("STATE", "coils_mode=%d", coils_mode);
			write_text("(OK)");
		}
	} else if ((!strcmp(key, "SCMV") || !strcmp(key, "SCHD")) && af12) {
		if (!parse_value(argument, "%", &value) || value < 10 || value > 100) {
			reject(request);
		} else {
			*(key[2] == 'M' ? &move_current : &hold_current) = value;
			event("STATE", "move_current=%d hold_current=%d", move_current, hold_current);
			write_text("(OK)");
		}
	} else if ((!strcmp(key, "SMMM") || !strcmp(key, "SMHM")) && !af12) {
		if (!parse_value(argument, "", &value) || value < 1 || value > 100) {
			reject(request);
		} else {
			*(key[2] == 'M' ? &move_multiplier : &hold_multiplier) = value;
			event("STATE", "move_multiplier=%d hold_multiplier=%d", move_multiplier, hold_multiplier);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SBUF")) {
		if (!parse_value(argument, "", &value) || value < 0 || value > 99999) {
			reject(request);
		} else {
			settle_time = value;
			event("STATE", "settle_time=%d", settle_time);
			write_text("(OK)");
		}
	} else if (!strcmp(key, "SIDC") && af12) {
		if (!parse_value(argument, "", &value) || value < 0 || value > 999999) {
			reject(request);
		} else {
			coils_timeout = value;
			event("STATE", "coils_timeout=%d", coils_timeout);
			write_text("(OK)");
		}
	} else {
		unsupported(request);
	}
}

static void apply_control(void) {
	if (!control_file) {
		return;
	}
	FILE *file = fopen(control_file, "r");
	if (!file) {
		return;
	}
	char key[32], value[64];
	while (fscanf(file, "%31s %63[^\n]", key, value) == 2) {
		if (!strcmp(key, "position")) {
			serial_motion_sync(&motion, atoi(value));
			target = atoi(value);
		} else if (!strcmp(key, "temperature")) {
			temperature = atof(value);
		} else if (!strcmp(key, "stall")) {
			if (atoi(value)) {
				current_position();
				stalled = true;
			} else {
				stalled = false;
				serial_motion_stop(&motion);
			}
		} else if (!strcmp(key, "max_move")) {
			max_move = atoi(value);
		} else if (!strcmp(key, "board")) {
			snprintf(board, sizeof(board), "%s", value);
		}
		event("CONTROL", "%s %s", key, value);
	}
	fclose(file);
	unlink(control_file);
}

static bool parse_arguments(int argc, char **argv) {
	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "--headless")) {
			headless = true;
		} else if (!strcmp(argv[i], "--trace")) {
			trace = true;
		} else if (i + 1 < argc && !strcmp(argv[i], "--ready-file")) {
			ready_file = argv[++i];
		} else if (i + 1 < argc && !strcmp(argv[i], "--model")) {
			const char *name = argv[++i];
			if (!strcmp(name, "af1")) {
				model = 1;
				speed = 2;
				step_mode = 4;
				snprintf(board, sizeof(board), "DSD AF1");
				snprintf(firmware, sizeof(firmware), "1.3.3");
			} else if (!strcmp(name, "af2")) {
				model = 2;
			} else if (!strcmp(name, "af3")) {
				model = 3;
				speed = 3;
				step_mode = 16;
				snprintf(board, sizeof(board), "DSD AF3");
				snprintf(firmware, sizeof(firmware), "3.1.0");
			} else {
				fprintf(stderr, "Unknown model '%s'\n", name);
				return false;
			}
		} else if (i + 1 < argc && !strcmp(argv[i], "--position")) {
			target = atoi(argv[++i]);
		} else if (i + 1 < argc && !strcmp(argv[i], "--temperature")) {
			temperature = atof(argv[++i]);
		} else if (!strcmp(argv[i], "--help") || !strcmp(argv[i], "-h")) {
			printf("Usage: %s [--headless] [--trace] [--ready-file PATH] [--model af1|af2|af3] [--position N] [--temperature T]\n", argv[0]);
			exit(0);
		} else {
			fprintf(stderr, "Unknown/incomplete option '%s'\n", argv[i]);
			return false;
		}
	}
	return true;
}

int main(int argc, char **argv) {
	if (!parse_arguments(argc, argv)) {
		return 1;
	}
	serial_motion_sync(&motion, target);
	fault_file = getenv("INDIGO_DSD_FAULT");
	control_file = getenv("INDIGO_DSD_CONTROL");
	const char *event_file = getenv("INDIGO_DSD_EVENTS");
	events = event_file ? fopen(event_file, "a") : NULL;
	signal(SIGTERM, stop_signal);
	signal(SIGINT, stop_signal);
	char port[PATH_MAX], request[MAX_REQUEST + 1];
	size_t used = 0;
	serial_fd = serial_simulator_open_pty(port, sizeof(port));
	if (serial_fd < 0 || (ready_file && !serial_simulator_write_ready_file(ready_file, "focuser_dsd_simulator", port))) {
		return 1;
	}
	event("OPEN", "model=af%d", model);
	if (!headless) {
		printf("Deep Sky Dad AF%d focuser simulator is listening on %s\n", model, port);
		fflush(stdout);
	}
	while (running) {
		apply_control();
		if (!stalled) {
			serial_motion_update(&motion);
		}
		fd_set fds;
		FD_ZERO(&fds);
		FD_SET(serial_fd, &fds);
		struct timeval timeout = { 0, 20000 };
		if (select(serial_fd + 1, &fds, NULL, NULL, &timeout) <= 0) {
			continue;
		}
		char byte;
		if (read(serial_fd, &byte, 1) != 1) {
			continue;
		}
		if (!used && byte != '[') {
			event("REJECT", "out-of-frame 0x%02x", (unsigned char)byte);
			continue;
		}
		if (used == MAX_REQUEST) {
			request[used] = 0;
			event("REJECT", "overlong %s", request);
			used = 0;
			continue;
		}
		request[used++] = byte;
		if (byte == ']') {
			request[used] = 0;
			dispatch(request);
			used = 0;
		}
	}
	event("STATE", "position=%d target=%d speed=%d reverse=%d step_mode=%d", current_position(), target, speed, reverse, step_mode);
	event("CLOSE", "simulator");
	close(serial_fd);
	if (events) {
		fclose(events);
	}
	return 0;
}
