//
//  indigo_ica_nikon.h
//  IndigoApps
//
//  Created by Peter Polakovic on 11/07/2017.
//  Copyright © 2017 CloudMakers, s. r. o. All rights reserved.
//

#import <Foundation/Foundation.h>

#import "indigo_ica_ptp.h"

enum PTPNikonOperationCodeEnum {
  PTPRequestCodeNikonGetProfileAllData = 0x9006,
  PTPRequestCodeNikonSendProfileData = 0x9007,
  PTPRequestCodeNikonDeleteProfile = 0x9008,
  PTPRequestCodeNikonSetProfileData = 0x9009,
  PTPRequestCodeNikonAdvancedTransfer = 0x9010,
  PTPRequestCodeNikonGetFileInfoInBlock = 0x9011,
  PTPRequestCodeNikonCapture = 0x90C0,
  PTPRequestCodeNikonAfDrive = 0x90C1,
  PTPRequestCodeNikonSetControlMode = 0x90C2,
  PTPRequestCodeNikonDelImageSDRAM = 0x90C3,
  PTPRequestCodeNikonGetLargeThumb = 0x90C4,
  PTPRequestCodeNikonCurveDownload = 0x90C5,
  PTPRequestCodeNikonCurveUpload = 0x90C6,
  PTPRequestCodeNikonCheckEvent = 0x90C7,
  PTPRequestCodeNikonDeviceReady = 0x90C8,
  PTPRequestCodeNikonSetPreWBData = 0x90C9,
  PTPRequestCodeNikonGetVendorPropCodes = 0x90CA,
  PTPRequestCodeNikonAfCaptureSDRAM = 0x90CB,
  PTPRequestCodeNikonGetPictCtrlData = 0x90CC,
  PTPRequestCodeNikonSetPictCtrlData = 0x90CD,
  PTPRequestCodeNikonDelCstPicCtrl = 0x90CE,
  PTPRequestCodeNikonGetPicCtrlCapability = 0x90CF,
  PTPRequestCodeNikonGetPreviewImg = 0x9200,
  PTPRequestCodeNikonStartLiveView = 0x9201,
  PTPRequestCodeNikonEndLiveView = 0x9202,
  PTPRequestCodeNikonGetLiveViewImg = 0x9203,
  PTPRequestCodeNikonMfDrive = 0x9204,
  PTPRequestCodeNikonChangeAfArea = 0x9205,
  PTPRequestCodeNikonAfDriveCancel = 0x9206,
  PTPRequestCodeNikonInitiateCaptureRecInMedia = 0x9207,
  PTPRequestCodeNikonGetVendorStorageIDs = 0x9209,
  PTPRequestCodeNikonStartMovieRecInCard = 0x920a,
  PTPRequestCodeNikonEndMovieRec = 0x920b,
  PTPRequestCodeNikonTerminateCapture = 0x920c,
  PTPRequestCodeNikonGetDevicePTPIPInfo = 0x90E0,
  PTPRequestCodeNikonGetPartialObjectHiSpeed = 0x9400,
};

enum PTPNikonResponseCodeEnum {
  PTPResponseCodeNikonHardwareError = 0xA001,
  PTPResponseCodeNikonOutOfFocus = 0xA002,
  PTPResponseCodeNikonChangeCameraModeFailed = 0xA003,
  PTPResponseCodeNikonInvalidStatus = 0xA004,
  PTPResponseCodeNikonSetPropertyNotSupported = 0xA005,
  PTPResponseCodeNikonWbResetError = 0xA006,
  PTPResponseCodeNikonDustReferenceError = 0xA007,
  PTPResponseCodeNikonShutterSpeedBulb = 0xA008,
  PTPResponseCodeNikonMirrorUpSequence = 0xA009,
  PTPResponseCodeNikonCameraModeNotAdjustFNumber = 0xA00A,
  PTPResponseCodeNikonNotLiveView = 0xA00B,
  PTPResponseCodeNikonMfDriveStepEnd = 0xA00C,
  PTPResponseCodeNikonMfDriveStepInsufficiency = 0xA00E,
  PTPResponseCodeNikonAdvancedTransferCancel = 0xA022,
};

enum PTPNikonEventCodeEnum {
  PTPEventCodeNikonObjectAddedInSDRAM = 0xC101,
  PTPEventCodeNikonCaptureCompleteRecInSdram = 0xC102,
  PTPEventCodeNikonAdvancedTransfer = 0xC103,
  PTPEventCodeNikonPreviewImageAdded = 0xC104,
};

enum PTPNikonPropertyCode {
  PTPPropertyCodeNikonShootingBank = 0xD010,
  PTPPropertyCodeNikonShootingBankNameA = 0xD011,
  PTPPropertyCodeNikonShootingBankNameB = 0xD012,
  PTPPropertyCodeNikonShootingBankNameC = 0xD013,
  PTPPropertyCodeNikonShootingBankNameD = 0xD014,
  PTPPropertyCodeNikonResetBank0 = 0xD015,
  PTPPropertyCodeNikonRawCompression = 0xD016,
  PTPPropertyCodeNikonWhiteBalanceAutoBias = 0xD017,
  PTPPropertyCodeNikonWhiteBalanceTungstenBias = 0xD018,
  PTPPropertyCodeNikonWhiteBalanceFluorescentBias = 0xD019,
  PTPPropertyCodeNikonWhiteBalanceDaylightBias = 0xD01A,
  PTPPropertyCodeNikonWhiteBalanceFlashBias = 0xD01B,
  PTPPropertyCodeNikonWhiteBalanceCloudyBias = 0xD01C,
  PTPPropertyCodeNikonWhiteBalanceShadeBias = 0xD01D,
  PTPPropertyCodeNikonWhiteBalanceColorTemperature = 0xD01E,
  PTPPropertyCodeNikonWhiteBalancePresetNo = 0xD01F,
  PTPPropertyCodeNikonWhiteBalancePresetName0 = 0xD020,
  PTPPropertyCodeNikonWhiteBalancePresetName1 = 0xD021,
  PTPPropertyCodeNikonWhiteBalancePresetName2 = 0xD022,
  PTPPropertyCodeNikonWhiteBalancePresetName3 = 0xD023,
  PTPPropertyCodeNikonWhiteBalancePresetName4 = 0xD024,
  PTPPropertyCodeNikonWhiteBalancePresetVal0 = 0xD025,
  PTPPropertyCodeNikonWhiteBalancePresetVal1 = 0xD026,
  PTPPropertyCodeNikonWhiteBalancePresetVal2 = 0xD027,
  PTPPropertyCodeNikonWhiteBalancePresetVal3 = 0xD028,
  PTPPropertyCodeNikonWhiteBalancePresetVal4 = 0xD029,
  PTPPropertyCodeNikonImageSharpening = 0xD02A,
  PTPPropertyCodeNikonToneCompensation = 0xD02B,
  PTPPropertyCodeNikonColorModel = 0xD02C,
  PTPPropertyCodeNikonHueAdjustment = 0xD02D,
  PTPPropertyCodeNikonNonCPULensDataFocalLength = 0xD02E,
  PTPPropertyCodeNikonNonCPULensDataMaximumAperture = 0xD02F,
  PTPPropertyCodeNikonShootingMode = 0xD030,
  PTPPropertyCodeNikonJPEGCompressionPolicy = 0xD031,
  PTPPropertyCodeNikonColorSpace = 0xD032,
  PTPPropertyCodeNikonAutoDXCrop = 0xD033,
  PTPPropertyCodeNikonFlickerReduction = 0xD034,
  PTPPropertyCodeNikonRemoteMode = 0xD035,
  PTPPropertyCodeNikonVideoMode = 0xD036,
  PTPPropertyCodeNikonEffectMode = 0xD037,
  PTPPropertyCodeNikon1Mode = 0xD038,
  PTPPropertyCodeNikonCSMMenuBankSelect = 0xD040,
  PTPPropertyCodeNikonMenuBankNameA = 0xD041,
  PTPPropertyCodeNikonMenuBankNameB = 0xD042,
  PTPPropertyCodeNikonMenuBankNameC = 0xD043,
  PTPPropertyCodeNikonMenuBankNameD = 0xD044,
  PTPPropertyCodeNikonResetBank = 0xD045,
  PTPPropertyCodeNikonAFCModePriority = 0xD048,
  PTPPropertyCodeNikonAFSModePriority = 0xD049,
  PTPPropertyCodeNikonGroupDynamicAF = 0xD04A,
  PTPPropertyCodeNikonAFActivation = 0xD04B,
  PTPPropertyCodeNikonFocusAreaIllumManualFocus = 0xD04C,
  PTPPropertyCodeNikonFocusAreaIllumContinuous = 0xD04D,
  PTPPropertyCodeNikonFocusAreaIllumWhenSelected = 0xD04E,
  PTPPropertyCodeNikonFocusAreaWrap = 0xD04F,
  PTPPropertyCodeNikonVerticalAFON = 0xD050,
  PTPPropertyCodeNikonAFLockOn = 0xD051,
  PTPPropertyCodeNikonFocusAreaZone = 0xD052,
  PTPPropertyCodeNikonEnableCopyright = 0xD053,
  PTPPropertyCodeNikonISOAutoTime = 0xD054,
  PTPPropertyCodeNikonEVISOStep = 0xD055,
  PTPPropertyCodeNikonEVStep = 0xD056,
  PTPPropertyCodeNikonEVStepExposureComp = 0xD057,
  PTPPropertyCodeNikonExposureCompensation = 0xD058,
  PTPPropertyCodeNikonCenterWeightArea = 0xD059,
  PTPPropertyCodeNikonExposureBaseMatrix = 0xD05A,
  PTPPropertyCodeNikonExposureBaseCenter = 0xD05B,
  PTPPropertyCodeNikonExposureBaseSpot = 0xD05C,
  PTPPropertyCodeNikonLiveViewAFArea = 0xD05D,
  PTPPropertyCodeNikonAELockMode = 0xD05E,
  PTPPropertyCodeNikonAELAFLMode = 0xD05F,
  PTPPropertyCodeNikonLiveViewAFFocus = 0xD061,
  PTPPropertyCodeNikonMeterOff = 0xD062,
  PTPPropertyCodeNikonSelfTimer = 0xD063,
  PTPPropertyCodeNikonMonitorOff = 0xD064,
  PTPPropertyCodeNikonImgConfTime = 0xD065,
  PTPPropertyCodeNikonAutoOffTimers = 0xD066,
  PTPPropertyCodeNikonAngleLevel = 0xD067,
  PTPPropertyCodeNikonShootingSpeed = 0xD068,
  PTPPropertyCodeNikonMaximumShots = 0xD069,
  PTPPropertyCodeNikonExposureDelayMode = 0xD06A,
  PTPPropertyCodeNikonLongExposureNoiseReduction = 0xD06B,
  PTPPropertyCodeNikonFileNumberSequence = 0xD06C,
  PTPPropertyCodeNikonControlPanelFinderRearControl = 0xD06D,
  PTPPropertyCodeNikonControlPanelFinderViewfinder = 0xD06E,
  PTPPropertyCodeNikonIllumination = 0xD06F,
  PTPPropertyCodeNikonNrHighISO = 0xD070,
  PTPPropertyCodeNikonSHSETCHGUIDDISP = 0xD071,
  PTPPropertyCodeNikonArtistName = 0xD072,
  PTPPropertyCodeNikonCopyrightInfo = 0xD073,
  PTPPropertyCodeNikonFlashSyncSpeed = 0xD074,
  PTPPropertyCodeNikonFlashShutterSpeed = 0xD075,
  PTPPropertyCodeNikonAAFlashMode = 0xD076,
  PTPPropertyCodeNikonModelingFlash = 0xD077,
  PTPPropertyCodeNikonBracketSet = 0xD078,
  PTPPropertyCodeNikonManualModeBracketing = 0xD079,
  PTPPropertyCodeNikonBracketOrder = 0xD07A,
  PTPPropertyCodeNikonAutoBracketSelection = 0xD07B,
  PTPPropertyCodeNikonBracketingSet = 0xD07C,
  PTPPropertyCodeNikonCenterButtonShootingMode = 0xD080,
  PTPPropertyCodeNikonCenterButtonPlaybackMode = 0xD081,
  PTPPropertyCodeNikonMultiselector = 0xD082,
  PTPPropertyCodeNikonPhotoInfoPlayback = 0xD083,
  PTPPropertyCodeNikonAssignFuncButton = 0xD084,
  PTPPropertyCodeNikonCustomizeCommDials = 0xD085,
  PTPPropertyCodeNikonReverseCommandDial = 0xD086,
  PTPPropertyCodeNikonApertureSetting = 0xD087,
  PTPPropertyCodeNikonMenusAndPlayback = 0xD088,
  PTPPropertyCodeNikonButtonsAndDials = 0xD089,
  PTPPropertyCodeNikonNoCFCard = 0xD08A,
  PTPPropertyCodeNikonCenterButtonZoomRatio = 0xD08B,
  PTPPropertyCodeNikonFunctionButton2 = 0xD08C,
  PTPPropertyCodeNikonAFAreaPoint = 0xD08D,
  PTPPropertyCodeNikonNormalAFOn = 0xD08E,
  PTPPropertyCodeNikonCleanImageSensor = 0xD08F,
  PTPPropertyCodeNikonImageCommentString = 0xD090,
  PTPPropertyCodeNikonImageCommentEnable = 0xD091,
  PTPPropertyCodeNikonImageRotation = 0xD092,
  PTPPropertyCodeNikonManualSetLensNo = 0xD093,
  PTPPropertyCodeNikonMovScreenSize = 0xD0A0,
  PTPPropertyCodeNikonMovVoice = 0xD0A1,
  PTPPropertyCodeNikonMovMicrophone = 0xD0A2,
  PTPPropertyCodeNikonMovFileSlot = 0xD0A3,
  PTPPropertyCodeNikonMovRecProhibitCondition = 0xD0A4,
  PTPPropertyCodeNikonManualMovieSetting = 0xD0A6,
  PTPPropertyCodeNikonMovHiQuality = 0xD0A7,
  PTPPropertyCodeNikonMovMicSensitivity = 0xD0A8,
  PTPPropertyCodeNikonMovWindNoiceReduction = 0xD0AA,
  PTPPropertyCodeNikonLiveViewScreenDisplaySetting = 0xD0B2,
  PTPPropertyCodeNikonMonitorOffDelay = 0xD0B3,
  PTPPropertyCodeNikonISOSensitivity = 0xD0B5,
  PTPPropertyCodeNikonBracketing = 0xD0C0,
  PTPPropertyCodeNikonAutoExposureBracketStep = 0xD0C1,
  PTPPropertyCodeNikonAutoExposureBracketProgram = 0xD0C2,
  PTPPropertyCodeNikonAutoExposureBracketCount = 0xD0C3,
  PTPPropertyCodeNikonWhiteBalanceBracketStep = 0xD0C4,
  PTPPropertyCodeNikonWhiteBalanceBracketProgram = 0xD0C5,
  PTPPropertyCodeNikonLensID = 0xD0E0,
  PTPPropertyCodeNikonLensSort = 0xD0E1,
  PTPPropertyCodeNikonLensType = 0xD0E2,
  PTPPropertyCodeNikonFocalLengthMin = 0xD0E3,
  PTPPropertyCodeNikonFocalLengthMax = 0xD0E4,
  PTPPropertyCodeNikonMaxApAtMinFocalLength = 0xD0E5,
  PTPPropertyCodeNikonMaxApAtMaxFocalLength = 0xD0E6,
  PTPPropertyCodeNikonFinderISODisp = 0xD0F0,
  PTPPropertyCodeNikonAutoOffPhoto = 0xD0F2,
  PTPPropertyCodeNikonAutoOffMenu = 0xD0F3,
  PTPPropertyCodeNikonAutoOffInfo = 0xD0F4,
  PTPPropertyCodeNikonSelfTimerShootNum = 0xD0F5,
  PTPPropertyCodeNikonVignetteCtrl = 0xD0F7,
  PTPPropertyCodeNikonAutoDistortionControl = 0xD0F8,
  PTPPropertyCodeNikonSceneMode = 0xD0F9,
  PTPPropertyCodeNikonSceneMode2 = 0xD0FD,
  PTPPropertyCodeNikonSelfTimerInterval = 0xD0FE,
  PTPPropertyCodeNikonExposureTime = 0xD100,
  PTPPropertyCodeNikonACPower = 0xD101,
  PTPPropertyCodeNikonWarningStatus = 0xD102,
  PTPPropertyCodeNikonRemainingShots = 0xD103,
  PTPPropertyCodeNikonAFLockStatus = 0xD104,
  PTPPropertyCodeNikonAELockStatus = 0xD105,
  PTPPropertyCodeNikonFVLockStatus = 0xD106,
  PTPPropertyCodeNikonAutofocusLCDTopMode2 = 0xD107,
  PTPPropertyCodeNikonAutofocusSensor = 0xD108,
  PTPPropertyCodeNikonFlexibleProgram = 0xD109,
  PTPPropertyCodeNikonLightMeter = 0xD10A,
  PTPPropertyCodeNikonSaveMedia = 0xD10B,
  PTPPropertyCodeNikonUSBSpeed = 0xD10C,
  PTPPropertyCodeNikonCCDNumber = 0xD10D,
  PTPPropertyCodeNikonCameraInclination = 0xD10E,
  PTPPropertyCodeNikonGroupPtnType = 0xD10F,
  PTPPropertyCodeNikonFNumberLock = 0xD110,
  PTPPropertyCodeNikonExposureApertureLock = 0xD111,
  PTPPropertyCodeNikonTVLockSetting = 0xD112,
  PTPPropertyCodeNikonAVLockSetting = 0xD113,
  PTPPropertyCodeNikonIllumSetting = 0xD114,
  PTPPropertyCodeNikonFocusPointBright = 0xD115,
  PTPPropertyCodeNikonExternalFlashAttached = 0xD120,
  PTPPropertyCodeNikonExternalFlashStatus = 0xD121,
  PTPPropertyCodeNikonExternalFlashSort = 0xD122,
  PTPPropertyCodeNikonExternalFlashMode = 0xD123,
  PTPPropertyCodeNikonExternalFlashCompensation = 0xD124,
  PTPPropertyCodeNikonNewExternalFlashMode = 0xD125,
  PTPPropertyCodeNikonFlashExposureCompensation = 0xD126,
  PTPPropertyCodeNikonHDRMode = 0xD130,
  PTPPropertyCodeNikonHDRHighDynamic = 0xD131,
  PTPPropertyCodeNikonHDRSmoothing = 0xD132,
  PTPPropertyCodeNikonOptimizeImage = 0xD140,
  PTPPropertyCodeNikonSaturation = 0xD142,
  PTPPropertyCodeNikonBWFillerEffect = 0xD143,
  PTPPropertyCodeNikonBWSharpness = 0xD144,
  PTPPropertyCodeNikonBWContrast = 0xD145,
  PTPPropertyCodeNikonBWSettingType = 0xD146,
  PTPPropertyCodeNikonSlot2SaveMode = 0xD148,
  PTPPropertyCodeNikonRawBitMode = 0xD149,
  PTPPropertyCodeNikonActiveDLighting = 0xD14E,
  PTPPropertyCodeNikonFlourescentType = 0xD14F,
  PTPPropertyCodeNikonTuneColourTemperature = 0xD150,
  PTPPropertyCodeNikonTunePreset0 = 0xD151,
  PTPPropertyCodeNikonTunePreset1 = 0xD152,
  PTPPropertyCodeNikonTunePreset2 = 0xD153,
  PTPPropertyCodeNikonTunePreset3 = 0xD154,
  PTPPropertyCodeNikonTunePreset4 = 0xD155,
  PTPPropertyCodeNikonBeepOff = 0xD160,
  PTPPropertyCodeNikonAutofocusMode = 0xD161,
  PTPPropertyCodeNikonAFAssist = 0xD163,
  PTPPropertyCodeNikonPADVPMode = 0xD164,
  PTPPropertyCodeNikonImageReview = 0xD165,
  PTPPropertyCodeNikonAFAreaIllumination = 0xD166,
  PTPPropertyCodeNikonFlashMode = 0xD167,
  PTPPropertyCodeNikonFlashCommanderMode = 0xD168,
  PTPPropertyCodeNikonFlashSign = 0xD169,
  PTPPropertyCodeNikonISOAuto = 0xD16A,
  PTPPropertyCodeNikonRemoteTimeout = 0xD16B,
  PTPPropertyCodeNikonGridDisplay = 0xD16C,
  PTPPropertyCodeNikonFlashModeManualPower = 0xD16D,
  PTPPropertyCodeNikonFlashModeCommanderPower = 0xD16E,
  PTPPropertyCodeNikonAutoFP = 0xD16F,
  PTPPropertyCodeNikonDateImprintSetting = 0xD170,
  PTPPropertyCodeNikonDateCounterSelect = 0xD171,
  PTPPropertyCodeNikonDateCountData = 0xD172,
  PTPPropertyCodeNikonDateCountDisplaySetting = 0xD173,
  PTPPropertyCodeNikonRangeFinderSetting = 0xD174,
  PTPPropertyCodeNikonCSMMenu = 0xD180,
  PTPPropertyCodeNikonWarningDisplay = 0xD181,
  PTPPropertyCodeNikonBatteryCellKind = 0xD182,
  PTPPropertyCodeNikonISOAutoHiLimit = 0xD183,
  PTPPropertyCodeNikonDynamicAFArea = 0xD184,
  PTPPropertyCodeNikonContinuousSpeedHigh = 0xD186,
  PTPPropertyCodeNikonInfoDispSetting = 0xD187,
  PTPPropertyCodeNikonPreviewButton = 0xD189,
  PTPPropertyCodeNikonPreviewButton2 = 0xD18A,
  PTPPropertyCodeNikonAEAFLockButton2 = 0xD18B,
  PTPPropertyCodeNikonIndicatorDisp = 0xD18D,
  PTPPropertyCodeNikonCellKindPriority = 0xD18E,
  PTPPropertyCodeNikonBracketingFramesAndSteps = 0xD190,
  PTPPropertyCodeNikonLiveViewMode = 0xD1A0,
  PTPPropertyCodeNikonLiveViewDriveMode = 0xD1A1,
  PTPPropertyCodeNikonLiveViewStatus = 0xD1A2,
  PTPPropertyCodeNikonLiveViewImageZoomRatio = 0xD1A3,
  PTPPropertyCodeNikonLiveViewProhibitCondition = 0xD1A4,
  PTPPropertyCodeNikonMovieShutterSpeed = 0xD1A8,
  PTPPropertyCodeNikonMovieFNumber = 0xD1A9,
  PTPPropertyCodeNikonMovieISO = 0xD1AA,
  PTPPropertyCodeNikonLiveViewImageSize = 0xD1AC,
  PTPPropertyCodeNikonBlinkingStatus = 0xD1B0,
  PTPPropertyCodeNikonExposureIndicateStatus = 0xD1B1,
  PTPPropertyCodeNikonInfoDispErrStatus = 0xD1B2,
  PTPPropertyCodeNikonExposureIndicateLightup = 0xD1B3,
  PTPPropertyCodeNikonFlashOpen = 0xD1C0,
  PTPPropertyCodeNikonFlashCharged = 0xD1C1,
  PTPPropertyCodeNikonFlashMRepeatValue = 0xD1D0,
  PTPPropertyCodeNikonFlashMRepeatCount = 0xD1D1,
  PTPPropertyCodeNikonFlashMRepeatInterval = 0xD1D2,
  PTPPropertyCodeNikonFlashCommandChannel = 0xD1D3,
  PTPPropertyCodeNikonFlashCommandSelfMode = 0xD1D4,
  PTPPropertyCodeNikonFlashCommandSelfCompensation = 0xD1D5,
  PTPPropertyCodeNikonFlashCommandSelfValue = 0xD1D6,
  PTPPropertyCodeNikonFlashCommandAMode = 0xD1D7,
  PTPPropertyCodeNikonFlashCommandACompensation = 0xD1D8,
  PTPPropertyCodeNikonFlashCommandAValue = 0xD1D9,
  PTPPropertyCodeNikonFlashCommandBMode = 0xD1DA,
  PTPPropertyCodeNikonFlashCommandBCompensation = 0xD1DB,
  PTPPropertyCodeNikonFlashCommandBValue = 0xD1DC,
  PTPPropertyCodeNikonApplicationMode = 0xD1F0,
  PTPPropertyCodeNikonActiveSlot = 0xD1F2,
  PTPPropertyCodeNikonActivePicCtrlItem = 0xD200,
  PTPPropertyCodeNikonChangePicCtrlItem = 0xD201,
  PTPPropertyCodeNikonMovieNrHighISO = 0xD236,
};

@interface PTPNikonRequest : PTPRequest
+(NSString *)operationCodeName:(PTPRequestCode)operationCode;
@end

@interface PTPNikonResponse : PTPResponse
+(NSString *)responseCodeName:(PTPResponseCode)responseCode;
@end

@interface PTPNikonEvent : PTPEvent
+(NSString *)eventCodeName:(PTPEventCode)eventCode;
@end

@interface PTPNikonProperty : PTPProperty
+(NSString *)propertyCodeName:(PTPPropertyCode)propertyCode;
@end

@interface PTPNikonDeviceInfo : PTPDeviceInfo
@end

@interface PTPNikonCamera : PTPCamera
@end
