// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// Hardware test implemented by OpenAI Codex.

#include <pthread.h>
#include <stdlib.h>
#include <dirent.h>
#include <unistd.h>
#include <time.h>
#ifdef ASI_DYNAMIC_DRIVER
#include <dlfcn.h>
#endif
#include <indigo/indigo_driver.h>
#include <indigo_drivers/ccd_asi/indigo_ccd_asi.h>
#include <indigo_drivers/agent_imager/indigo_agent_imager.h>
#include "../test_runner.h"

#define ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))
#define TEST_SUFFIX "INDIGOT1"
_Static_assert(sizeof(TEST_SUFFIX) - 1 == 8, "Hardware suffix fixture must contain exactly eight bytes");
#define MAX_DEVICES 16
#define MAX_PROPERTIES 128
#define CHECK(condition)                                              \
	do {                                                                \
		if (!(condition)) {                                               \
			fprintf(stderr, "%s:%d: %s\n", __FILE__, __LINE__, #condition); \
			indigo_test_failures++;                                         \
			goto cleanup;                                                   \
		}                                                                 \
	} while (0)

typedef struct {
	char name[INDIGO_NAME_SIZE];
	indigo_device *device, *master;
	unsigned interface;
	bool present;
	indigo_property *properties[MAX_PROPERTIES];
	unsigned revisions[MAX_PROPERTIES];
	unsigned frames, invalid_frames, width, height, bytes;
} observed_device;

static observed_device devices[MAX_DEVICES];
static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
static int camera = -1, guider = -1, imager = -1;
static bool hotplug, acceptance, suffix_only, abort_latency_only, abort_agent_only, abort_previews_only;

typedef struct {
	bool enabled;
	double sent, busy, done, agent_done;
	unsigned frames_sent, frames_busy, frames_done, frames_agent_done;
	indigo_property_state state;
} abort_measurement;

static abort_measurement abort_probe;
static char config_folder[] = "/tmp/indigo_asi_hw_XXXXXX";

const char *asi_test_config_folder(void) {
	return config_folder;
}
#ifdef ASI_DYNAMIC_DRIVER
static indigo_result (*driver_entry)(indigo_driver_action, indigo_driver_info *);
static void *driver_library;

static bool load_driver_library(void) {
	driver_library = dlopen(ASI_DRIVER_PATH, RTLD_NOW | RTLD_LOCAL);
	if (!driver_library) {
		fprintf(stderr, "dlopen: %s\n", dlerror());
		return false;
	}
	driver_entry = dlsym(driver_library, "indigo_ccd_asi");
	return driver_entry != NULL;
}
#else
static indigo_result (*driver_entry)(indigo_driver_action, indigo_driver_info *) = indigo_ccd_asi;
#endif
static indigo_client client;

static int slot(int d, const char *name) {
	for (int p = 0; p < MAX_PROPERTIES; p++) {
		if (devices[d].properties[p] && !strcmp(devices[d].properties[p]->name, name)) {
			return p;
		}
	}
	return -1;
}

static indigo_result observe(indigo_device *device, indigo_property *property, const char *message, bool image_update) {
	pthread_mutex_lock(&mutex);
	int d;
	for (d = 0; d < MAX_DEVICES; d++) {
		if (!*devices[d].name || !strcmp(devices[d].name, property->device)) {
			break;
		}
	}
	if (d < MAX_DEVICES) {
		snprintf(devices[d].name, INDIGO_NAME_SIZE, "%s", property->device);
		devices[d].device = device;
		devices[d].master = device->master_device;
		if (!image_update && !strcmp(property->name, "INFO")) {
			devices[d].present = true;
			for (int i = 0; i < property->count; i++) {
				if (!strcmp(property->items[i].name, "DEVICE_INTERFACE")) {
					devices[d].interface = strtoul(property->items[i].text.value, NULL, 10);
				}
			}
		}
		int p = slot(d, property->name);
		if (p < 0) {
			for (p = 0; p < MAX_PROPERTIES && devices[d].properties[p]; p++) {
			}
		}
		if (p < MAX_PROPERTIES) {
			indigo_release_property(devices[d].properties[p]);
			devices[d].properties[p] = indigo_copy_property(NULL, property);
			devices[d].revisions[p]++;
		}
		if (abort_probe.enabled && d == imager && image_update && !strcmp(property->name, "AGENT_ABORT_PROCESS") && property->state != INDIGO_BUSY_STATE && abort_probe.agent_done == 0) {
			abort_probe.agent_done = indigo_monotonic_time();
			abort_probe.frames_agent_done = devices[camera].frames;
		}
		if (abort_probe.enabled && d == camera && image_update && !strcmp(property->name, "CCD_ABORT_EXPOSURE")) {
			if (property->state == INDIGO_BUSY_STATE && abort_probe.busy == 0) {
				abort_probe.busy = indigo_monotonic_time();
				abort_probe.frames_busy = devices[d].frames;
			} else if (property->state != INDIGO_BUSY_STATE && abort_probe.done == 0) {
				abort_probe.done = indigo_monotonic_time();
				abort_probe.frames_done = devices[d].frames;
				abort_probe.state = property->state;
			}
		}
		if (image_update && !strcmp(property->name, "CCD_IMAGE") && property->state == INDIGO_OK_STATE && property->count && property->items[0].blob.value) {
			indigo_item *item = property->items;
			indigo_raw_header header = { 0 };
			if (item->blob.size >= sizeof(header)) {
				memcpy(&header, item->blob.value, sizeof(header));
			}
			unsigned bytes = header.signature == INDIGO_RAW_MONO8 ? 1 : (header.signature == INDIGO_RAW_MONO16 ? 2 : (header.signature == INDIGO_RAW_RGB24 ? 3 : (header.signature == INDIGO_RAW_RGB48 ? 6 : 0)));
			if (strcmp(item->blob.format, ".raw") || !bytes || !header.width || !header.height || (uint64_t)header.width * header.height * bytes + sizeof(header) > item->blob.size) {
				devices[d].invalid_frames++;
			}
			devices[d].width = header.width;
			devices[d].height = header.height;
			devices[d].bytes = bytes;
			devices[d].frames++;
			if (devices[d].frames <= 12 || devices[d].frames % 100 == 0) {
				printf("    frame %u: %u x %u, %ld bytes\n", devices[d].frames, header.width, header.height, item->blob.size);
			}
		}
	}
	pthread_mutex_unlock(&mutex);
	if (message && *message) {
		fprintf(stderr, "    %s %s: %s\n", property->device, property->name, message);
	}
	return INDIGO_OK;
}

static indigo_result define_property(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	return observe(device, property, message, false);
}

static indigo_result update_property(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	return observe(device, property, message, true);
}

static indigo_result report_message(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	fprintf(stderr, "    message: %s\n", message ? message : "");
	return INDIGO_OK;
}

static indigo_result delete_property(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	if (!*property->name) {
		pthread_mutex_lock(&mutex);
		for (int d = 0; d < MAX_DEVICES; d++) {
			if (!strcmp(devices[d].name, property->device)) {
				devices[d].present = false;
				for (int p = 0; p < MAX_PROPERTIES; p++) {
					indigo_release_property(devices[d].properties[p]);
					devices[d].properties[p] = NULL;
				}
			}
		}
		pthread_mutex_unlock(&mutex);
	}
	return INDIGO_OK;
}

static bool same_camera_model(const char *name, const char *selected) {
	const char *suffix = strstr(selected, " #");
	size_t length = suffix ? (size_t)(suffix - selected) : strlen(selected);
	return !strncmp(name, selected, length) && (name[length] == 0 || !strncmp(name + length, " #", 2));
}

static bool wait_presence(bool present) {
	double deadline = indigo_monotonic_time() + 600;
	while (indigo_monotonic_time() < deadline) {
		pthread_mutex_lock(&mutex);
		if (present && !devices[camera].present) {
			for (int d = 0; d < MAX_DEVICES; d++) {
				if (devices[d].present && (devices[d].interface & INDIGO_INTERFACE_CCD) && same_camera_model(devices[d].name, getenv("INDIGO_TEST_DEVICE") ? getenv("INDIGO_TEST_DEVICE") : devices[camera].name)) {
					camera = d;
					guider = -1;
					for (int g = 0; g < MAX_DEVICES; g++) {
						if (devices[g].present && devices[g].master == devices[d].device && (devices[g].interface & INDIGO_INTERFACE_GUIDER)) {
							guider = g;
						}
					}
					break;
				}
			}
		}
		bool ready = devices[camera].present == present && (guider < 0 || devices[guider].present == present);
		if (present) {
			ready = ready && slot(camera, "CONNECTION") >= 0 && (guider < 0 || slot(guider, "CONNECTION") >= 0);
		}
		pthread_mutex_unlock(&mutex);
		if (ready) {
			return true;
		}
		indigo_usleep(10000);
	}
	fprintf(stderr, "Timed out waiting for physical %s\n", present ? "replug" : "unplug");
	return false;
}

static bool disconnect_device(int d) {
	if (d < 0) {
		return true;
	}
	pthread_mutex_lock(&mutex);
	bool present = devices[d].present;
	pthread_mutex_unlock(&mutex);
	if (!present) {
		return true;
	}
	indigo_change_switch_property_1(&client, devices[d].name, "CONNECTION", "DISCONNECTED", true);
	for (int i = 0; i < 3000; i++) {
		pthread_mutex_lock(&mutex);
		int p = slot(d, "CONNECTION");
		bool disconnected = false;
		if (p >= 0 && devices[d].properties[p]->state == INDIGO_OK_STATE) {
			indigo_property *property = devices[d].properties[p];
			for (int j = 0; j < property->count; j++) {
				if (!strcmp(property->items[j].name, "DISCONNECTED")) {
					disconnected = property->items[j].sw.value;
				}
			}
		}
		pthread_mutex_unlock(&mutex);
		if (disconnected) {
			return true;
		}
		indigo_usleep(10000);
	}
	fprintf(stderr, "Disconnect timeout: %s\n", devices[d].name);
	return false;
}

static unsigned revision(int d, const char *name) {
	pthread_mutex_lock(&mutex);
	int p = slot(d, name);
	unsigned result = p < 0 ? 0 : devices[d].revisions[p];
	pthread_mutex_unlock(&mutex);
	return result;
}

static bool wait_state(int d, const char *name, unsigned after, indigo_property_state state) {
	for (int i = 0; i < 3000; i++) {
		pthread_mutex_lock(&mutex);
		int p = slot(d, name);
		bool ready = p >= 0 && devices[d].revisions[p] > after && devices[d].properties[p]->state == state;
		bool failed = p >= 0 && devices[d].revisions[p] > after && devices[d].properties[p]->state == INDIGO_ALERT_STATE && state != INDIGO_ALERT_STATE;
		pthread_mutex_unlock(&mutex);
		if (failed) {
			fprintf(stderr, "Failed: %s %s expected state %d\n", devices[d].name, name, state);
			return false;
		}
		if (ready) {
			return true;
		}
		indigo_usleep(10000);
	}
	fprintf(stderr, "Timeout: %s %s expected state %d\n", devices[d].name, name, state);
	return false;
}

static bool switch_value(int d, const char *name, const char *item, indigo_property_state state) {
	if (d < 0) {
		return true;
	}
	unsigned before = revision(d, name);
	indigo_change_switch_property_1(&client, devices[d].name, name, item, true);
	return wait_state(d, name, before, state);
}

static bool number_value(int d, const char *name, const char *item, double value, indigo_property_state state) {
	if (d < 0) {
		return true;
	}
	unsigned before = revision(d, name);
	double sent = indigo_monotonic_time();
	if (getenv("INDIGO_ASI_DIAGNOSE_RETRY")) {
		printf("    request %s %s.%s = %.6f, expected %d\n", devices[d].name, name, item, value, state);
	}
	indigo_change_number_property_1(&client, devices[d].name, name, item, value);
	bool ok = wait_state(d, name, before, state);
	if (getenv("INDIGO_ASI_DIAGNOSE_RETRY")) {
		printf("    result %s %s: %s after %.3f s\n", devices[d].name, name, ok ? "PASS" : "FAIL", indigo_monotonic_time() - sent);
	}
	return ok;
}

static unsigned frames(void) {
	pthread_mutex_lock(&mutex);
	unsigned result = devices[camera].frames;
	pthread_mutex_unlock(&mutex);
	return result;
}

static indigo_property *snapshot(int d, const char *name) {
	pthread_mutex_lock(&mutex);
	int p = slot(d, name);
	indigo_property *copy = p < 0 ? NULL : indigo_copy_property(NULL, devices[d].properties[p]);
	pthread_mutex_unlock(&mutex);
	return copy;
}

static bool restore_property(indigo_property *p) {
	if (!p) {
		return true;
	}
	int target = -1;
	pthread_mutex_lock(&mutex);
	for (int d = 0; d < MAX_DEVICES; d++) {
		if (devices[d].present && !strcmp(devices[d].name, p->device)) {
			target = d;
			break;
		}
	}
	pthread_mutex_unlock(&mutex);
	if (target < 0) {
		return false;
	}
	unsigned before = revision(target, p->name);
	return indigo_change_property(&client, p) == INDIGO_OK && wait_state(target, p->name, before, INDIGO_OK_STATE);
}

static bool set_local_directory(void) {
	unsigned before = revision(camera, "CCD_LOCAL_MODE");
	indigo_change_text_property_1(&client, devices[camera].name, "CCD_LOCAL_MODE", "DIR", config_folder);
	return wait_state(camera, "CCD_LOCAL_MODE", before, INDIGO_OK_STATE);
}

static bool all_frame_types(void) {
	indigo_property *type = snapshot(camera, "CCD_FRAME_TYPE");
	bool ok = type != NULL;
	for (int i = 0; ok && i < type->count; i++) {
		unsigned before = frames();
		ok = switch_value(camera, "CCD_FRAME_TYPE", type->items[i].name, INDIGO_OK_STATE) && number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE) && frames() == before + 1;
		printf("    frame type %s: %s\n", type->items[i].name, ok ? "PASS" : "FAIL");
	}
	ok = restore_property(type) && ok;
	indigo_release_property(type);
	return ok;
}

static bool format_geometry_and_controls(void) {
	indigo_property *pixel = snapshot(camera, "X_PIXEL_FORMAT");
	indigo_property *frame = snapshot(camera, "CCD_FRAME");
	indigo_property *bin = snapshot(camera, "CCD_BIN");
	indigo_property *gain = snapshot(camera, "CCD_GAIN");
	indigo_property *offset = snapshot(camera, "CCD_OFFSET");
	indigo_property *type = snapshot(camera, "CCD_FRAME_TYPE");
	bool ok = pixel && frame && bin;
	for (int i = 0; ok && i < pixel->count; i++) {
		printf("    hardware pixel format: %s\n", pixel->items[i].name);
		unsigned before = frames();
		ok = switch_value(camera, "X_PIXEL_FORMAT", pixel->items[i].name, INDIGO_OK_STATE) && number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE) && frames() == before + 1;
	}
	if (ok) {
		ok = switch_value(camera, "X_PIXEL_FORMAT", pixel->items[0].name, INDIGO_OK_STATE);
	}
	for (int factor = 1; ok && factor <= 2 && factor <= bin->items[0].number.max; factor++) {
		unsigned before = revision(camera, "CCD_BIN");
		indigo_change_number_property(&client, devices[camera].name, "CCD_BIN", 2, (const char *[]){ "HORIZONTAL", "VERTICAL" }, (double[]){ factor, factor });
		ok = wait_state(camera, "CCD_BIN", before, INDIGO_OK_STATE);
		before = revision(camera, "CCD_FRAME");
		indigo_change_number_property(&client, devices[camera].name, "CCD_FRAME", 4, (const char *[]){ "LEFT", "TOP", "WIDTH", "HEIGHT" }, (double[]){ 16, 24, 256, 256 });
		ok = ok && wait_state(camera, "CCD_FRAME", before, INDIGO_OK_STATE) && number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE);
		pthread_mutex_lock(&mutex);
		ok = ok && devices[camera].width == 256 / factor && devices[camera].height == 256 / factor;
		pthread_mutex_unlock(&mutex);
		printf("    hardware ROI 256x256 at 16,24, bin %d: %s\n", factor, ok ? "PASS" : "FAIL");
	}
#ifndef ASI_DYNAMIC_DRIVER
	if (ok && gain && gain->perm == INDIGO_RW_PERM) {
		double value = gain->items[0].number.value;
		double changed = value < gain->items[0].number.max ? value + 1 : value - 1;
		ok = number_value(camera, "CCD_GAIN", "GAIN", changed, INDIGO_OK_STATE) && switch_value(camera, "CONFIG", "SAVE", INDIGO_OK_STATE) && restore_property(gain) && switch_value(camera, "CONFIG", "LOAD", INDIGO_OK_STATE);
		indigo_property *loaded = snapshot(camera, "CCD_GAIN");
		ok = ok && loaded && loaded->items[0].number.value == changed;
		indigo_release_property(loaded);
		printf("    hardware gain/config roundtrip in temporary directory: %s\n", ok ? "PASS" : "FAIL");
	}
#endif
	if (ok && offset && offset->perm == INDIGO_RW_PERM) {
		ok = number_value(camera, "CCD_OFFSET", "OFFSET", offset->items[0].number.value < offset->items[0].number.max ? offset->items[0].number.value + 1 : offset->items[0].number.value - 1, INDIGO_OK_STATE);
	}
	if (ok) {
		ok = all_frame_types() && switch_value(camera, "CCD_FRAME_TYPE", "LIGHT", INDIGO_OK_STATE);
	}
	if (ok) {
		printf("    completed long exposure with concurrent guider commands\n");
		unsigned before = revision(camera, "CCD_EXPOSURE");
		indigo_change_number_property_1(&client, devices[camera].name, "CCD_EXPOSURE", "EXPOSURE", 5);
		ok = wait_state(camera, "CCD_EXPOSURE", before, INDIGO_BUSY_STATE) && number_value(guider, "GUIDER_GUIDE_RA", "EAST", 100, INDIGO_OK_STATE) && number_value(guider, "GUIDER_GUIDE_DEC", "NORTH", 100, INDIGO_OK_STATE) && wait_state(camera, "CCD_EXPOSURE", before, INDIGO_OK_STATE);
	}
	indigo_property *restore[] = { bin, frame, pixel, gain, offset, type };
	for (int i = 0; i < ARRAY_SIZE(restore); i++) {
		if (!restore_property(restore[i])) {
			ok = false;
		}
		indigo_release_property(restore[i]);
	}
	return ok;
}

static bool additional_controls_and_cooling(void) {
	indigo_property *advanced = snapshot(camera, "X_ADVANCED");
	indigo_property *gain = snapshot(camera, "CCD_GAIN");
	indigo_property *gamma = snapshot(camera, "CCD_GAMMA");
	indigo_property *offset = snapshot(camera, "CCD_OFFSET");
	indigo_property *presets = snapshot(camera, "X_PRESETS");
	indigo_property *temperature = snapshot(camera, "CCD_TEMPERATURE");
	indigo_property *cooler = snapshot(camera, "CCD_COOLER");
	bool ok = true;
	if (advanced && advanced->perm == INDIGO_RW_PERM) {
		for (int i = 0; ok && i < advanced->count; i++) {
			indigo_item *item = advanced->items + i;
			double changed = item->number.value < item->number.max ? item->number.value + item->number.step : item->number.value - item->number.step;
			if (changed >= item->number.min && changed <= item->number.max) {
				unsigned before = revision(camera, "X_ADVANCED");
				indigo_change_number_property_1(&client, devices[camera].name, "X_ADVANCED", item->name, changed);
				bool ready = false;
				for (int attempt = 0; attempt < 1000; attempt++) {
					indigo_property *p = snapshot(camera, "X_ADVANCED");
					ready = p && revision(camera, "X_ADVANCED") > before && p->state != INDIGO_BUSY_STATE;
					if (ready) {
						if (p->state == INDIGO_ALERT_STATE) {
							ok = p->items[i].number.value == item->number.value;
							printf("    SDK limitation: %s write rejected, original value %.0f retained: %s\n", item->name, item->number.value, ok ? "PASS error handling" : "FAIL");
						} else {
							ok = p->state == INDIGO_OK_STATE && p->items[i].number.value == changed;
							printf("    advanced %s write/readback: %s\n", item->name, ok ? "PASS" : "FAIL");
						}
					}
					indigo_release_property(p);
					if (ready) {
						break;
					}
					indigo_usleep(10000);
				}
				ok = ok && ready;
			}
		}
	}
	if (ok && gamma && gamma->perm == INDIGO_RW_PERM) {
		ok = number_value(camera, "CCD_GAMMA", "GAMMA", gamma->items->number.value < gamma->items->number.max ? gamma->items->number.value + 1 : gamma->items->number.value - 1, INDIGO_OK_STATE);
	}
	if (ok && presets) {
		for (int i = 0; ok && i < presets->count; i++) {
			ok = switch_value(camera, "X_PRESETS", presets->items[i].name, INDIGO_OK_STATE);
			printf("    preset %s: %s\n", presets->items[i].name, ok ? "PASS" : "FAIL");
		}
	}
	if (ok && temperature && cooler && temperature->perm == INDIGO_RW_PERM && cooler->perm == INDIGO_RW_PERM) {
		ok = switch_value(camera, "CCD_COOLER", "OFF", INDIGO_OK_STATE);
		// OFF lets the normal poll settle the measured-temperature property before a new target.
		ok = ok && wait_state(camera, "CCD_TEMPERATURE", 0, INDIGO_OK_STATE);
		double target = fmax(temperature->items->number.min, fmin(temperature->items->number.max, floor(temperature->items->number.value) - 1));
		ok = ok && number_value(camera, "CCD_TEMPERATURE", "TEMPERATURE", target, INDIGO_BUSY_STATE) && switch_value(camera, "CCD_COOLER", "ON", INDIGO_OK_STATE);
		double deadline = indigo_monotonic_time() + 60;
		bool cooled = false;
		while (ok && indigo_monotonic_time() < deadline) {
			indigo_property *t = snapshot(camera, "CCD_TEMPERATURE");
			indigo_property *power = snapshot(camera, "CCD_COOLER_POWER");
			if (t && power) {
				printf("    cooling target %.1f measured %.1f power %.1f%% state %d\n", t->items->number.target, t->items->number.value, power->items->number.value, t->state);
				cooled = t->state == INDIGO_OK_STATE && fabs(t->items->number.value - target) <= 0.5;
				ok = t->state != INDIGO_ALERT_STATE && power->state != INDIGO_ALERT_STATE;
			}
			indigo_release_property(t);
			indigo_release_property(power);
			if (cooled || !ok) {
				break;
			}
			indigo_usleep(1000000);
		}
		ok = ok && cooled;
		// Restore target with cooler off; then restore the original cooler selection.
		bool restored = switch_value(camera, "CCD_COOLER", "OFF", INDIGO_OK_STATE) && wait_state(camera, "CCD_TEMPERATURE", 0, INDIGO_OK_STATE);
		if (restored) {
			restored = number_value(camera, "CCD_TEMPERATURE", "TEMPERATURE", temperature->items->number.target, INDIGO_BUSY_STATE);
		}
		if (restored) {
			restored = switch_value(camera, "CCD_COOLER", "ON", INDIGO_OK_STATE);
			// Target is applied on the next normal poll after ON.
			double deadline = indigo_monotonic_time() + 6;
			while (indigo_monotonic_time() < deadline) {
				indigo_usleep(10000);
			}
		}
		restored = restore_property(cooler) && restored;
		printf("    cooler/target restoration: %s\n", restored ? "PASS" : "FAIL");
		ok = ok && restored;
	} else {
		printf("    cooling: sensor-only or unavailable\n");
	}
	indigo_property *saved[] = { advanced, gain, gamma, offset };
	for (int i = 0; i < ARRAY_SIZE(saved); i++) {
		ok = restore_property(saved[i]) && ok;
		indigo_release_property(saved[i]);
	}
	indigo_release_property(presets);
	indigo_release_property(temperature);
	indigo_release_property(cooler);
	return ok;
}

static bool fractional_and_long_streams(void) {
	bool ok = number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 1.5, INDIGO_OK_STATE) && number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 2.5, INDIGO_OK_STATE);
	unsigned before = frames(), changed = revision(camera, "CCD_STREAMING");
	indigo_change_number_property(&client, devices[camera].name, "CCD_STREAMING", 2, (const char *[]){ "EXPOSURE", "COUNT" }, (double[]){ 2.5, -1 });
	ok = ok && wait_state(camera, "CCD_STREAMING", changed, INDIGO_BUSY_STATE);
	double deadline = indigo_monotonic_time() + 20;
	while (ok && frames() < before + 3 && indigo_monotonic_time() < deadline) {
		indigo_usleep(10000);
	}
	ok = ok && frames() >= before + 3;
	double sent = indigo_monotonic_time();
	ok = switch_value(camera, "CCD_ABORT_EXPOSURE", "ABORT_EXPOSURE", INDIGO_OK_STATE) && ok;
	printf("    long indefinite video: frames %u, terminal abort %.3f s, %s\n", frames() - before, indigo_monotonic_time() - sent, ok ? "PASS" : "FAIL");
	before = frames();
	ok = ok && number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE) && frames() == before + 1;
	if (!ok && getenv("INDIGO_ASI_DIAGNOSE_RETRY")) {
		for (int attempt = 1; attempt <= 3; attempt++) {
			bool recovered = number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE);
			printf("    diagnostic fresh request %d: %s\n", attempt, recovered ? "PASS" : "FAIL");
			if (recovered) {
				break;
			}
		}
	}
	return ok;
}

static bool guide_overlap_and_disconnect(void) {
	if (guider < 0) {
		return true;
	}
	bool ok = number_value(guider, "GUIDER_GUIDE_RA", "EAST", 1000, INDIGO_BUSY_STATE) && number_value(guider, "GUIDER_GUIDE_DEC", "NORTH", 1500, INDIGO_BUSY_STATE);
	// The framework silently ignores same-axis requests while BUSY; no new revision is expected.
	ok = ok && indigo_change_number_property_1(&client, devices[guider].name, "GUIDER_GUIDE_RA", "WEST", 100) == INDIGO_OK;
	indigo_property *ra = snapshot(guider, "GUIDER_GUIDE_RA");
	bool east = false, west = false;
	for (int i = 0; ra && i < ra->count; i++) {
		if (!strcmp(ra->items[i].name, "EAST")) {
			east = ra->items[i].number.value == 1000;
		}
		if (!strcmp(ra->items[i].name, "WEST")) {
			west = ra->items[i].number.value == 0;
		}
	}
	indigo_release_property(ra);
	ok = ok && east && west && wait_state(guider, "GUIDER_GUIDE_RA", 0, INDIGO_OK_STATE) && wait_state(guider, "GUIDER_GUIDE_DEC", 0, INDIGO_OK_STATE);
	ok = ok && number_value(guider, "GUIDER_GUIDE_RA", "EAST", 0, INDIGO_OK_STATE) && number_value(guider, "GUIDER_GUIDE_DEC", "NORTH", 0, INDIGO_OK_STATE);
	ok = ok && number_value(guider, "GUIDER_GUIDE_RA", "WEST", 1000, INDIGO_BUSY_STATE) && disconnect_device(guider);
	ok = ok && number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE) && switch_value(guider, "CONNECTION", "CONNECTED", INDIGO_OK_STATE) && number_value(guider, "GUIDER_GUIDE_RA", "WEST", 100, INDIGO_OK_STATE);
	printf("    simultaneous guide axes, BUSY reversal rejection, zero requests and guider disconnect with surviving CCD: %s\n", ok ? "PASS" : "FAIL");
	return ok;
}

static bool physical_cycle(const char *phase) {
	int other = -1;
	pthread_mutex_lock(&mutex);
	for (int d = 0; d < MAX_DEVICES; d++) {
		if (d != camera && devices[d].present && (devices[d].interface & INDIGO_INTERFACE_CCD)) {
			other = d;
			break;
		}
	}
	pthread_mutex_unlock(&mutex);
	indigo_property *other_format = NULL, *other_upload = NULL;
	bool ok = true;
	if (other >= 0) {
		ok = switch_value(other, "CONNECTION", "CONNECTED", INDIGO_OK_STATE);
		other_format = snapshot(other, "CCD_IMAGE_FORMAT");
		other_upload = snapshot(other, "CCD_UPLOAD_MODE");
		ok = ok && switch_value(other, "CCD_UPLOAD_MODE", "CLIENT", INDIGO_OK_STATE) && switch_value(other, "CCD_IMAGE_FORMAT", "RAW", INDIGO_OK_STATE) && number_value(other, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE);
	}
	if (ok) {
		printf("HOTPLUG_READY [%s]: unplug USB camera now: %s\n", phase, devices[camera].name);
		ok = wait_presence(false);
	}
	if (ok && other >= 0) {
		ok = number_value(other, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE);
		printf("    second camera survives removal: %s, %s\n", devices[other].name, ok ? "PASS" : "FAIL");
	}
	if (ok) {
		printf("HOTPLUG_REMOVED [%s]: reconnect the same USB camera now\n", phase);
		ok = wait_presence(true) && switch_value(camera, "CONNECTION", "CONNECTED", INDIGO_OK_STATE) && switch_value(guider, "CONNECTION", "CONNECTED", INDIGO_OK_STATE) && switch_value(camera, "CCD_UPLOAD_MODE", "CLIENT", INDIGO_OK_STATE) && switch_value(camera, "CCD_IMAGE_FORMAT", "RAW", INDIGO_OK_STATE);
	}
	unsigned before = frames();
	ok = ok && number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE) && frames() == before + 1 && number_value(guider, "GUIDER_GUIDE_RA", "EAST", 100, INDIGO_OK_STATE);
	if (other >= 0) {
		ok = restore_property(other_format) && ok;
		ok = restore_property(other_upload) && ok;
		ok = disconnect_device(other) && ok;
	}
	indigo_release_property(other_format);
	indigo_release_property(other_upload);
	printf("HOTPLUG_RECOVERED [%s]: %s, camera name: %s\n", phase, ok ? "PASS" : "FAIL", devices[camera].name);
	return ok;
}

static bool set_suffix(const char *value) {
	unsigned before = revision(camera, "X_CUSTOM_SUFFIX");
	printf("    Request suffix %s, revision %u\n", value, before);
	indigo_change_text_property_1(&client, devices[camera].name, "X_CUSTOM_SUFFIX", "SUFFIX", value);
	bool ok = wait_state(camera, "X_CUSTOM_SUFFIX", before, INDIGO_OK_STATE);
	indigo_property *p = snapshot(camera, "X_CUSTOM_SUFFIX");
	printf("    Suffix result: state %d, revision %u, value %s\n", p ? p->state : -1, revision(camera, "X_CUSTOM_SUFFIX"), p ? p->items[0].text.value : "missing");
	indigo_release_property(p);
	return ok;
}

static bool suffix_acceptance(void) {
	indigo_property *suffix = snapshot(camera, "X_CUSTOM_SUFFIX");
	if (!suffix || !suffix->count) {
		indigo_release_property(suffix);
		return false;
	}
	char original[17];
	snprintf(original, sizeof(original), "%s", suffix->items[0].text.value);
	indigo_release_property(suffix);
	printf("    original suffix: '%s'\n", original);
	bool ok = set_suffix(TEST_SUFFIX) && physical_cycle("8-byte suffix") && strstr(devices[camera].name, "#INDIGOT1") != NULL;
	if (ok) {
		ok = set_suffix("") && physical_cycle("cleared suffix") && strstr(devices[camera].name, "#INDIGOT1") == NULL;
	}
	// Always restore after the first flash write, including failed assertions.
	bool restored = set_suffix(original);
	if (restored && *original) {
		restored = physical_cycle("restored suffix") && strstr(devices[camera].name, original) != NULL;
	}
	printf("    original suffix restoration: %s\n", restored ? "PASS" : "FAIL");
	return ok && restored;
}

static bool complete_physical_acceptance(void) {
	if (!physical_cycle("idle")) {
		return false;
	}
	unsigned before = revision(camera, "CCD_EXPOSURE");
	indigo_change_number_property_1(&client, devices[camera].name, "CCD_EXPOSURE", "EXPOSURE", 120);
	if (!wait_state(camera, "CCD_EXPOSURE", before, INDIGO_BUSY_STATE) || !physical_cycle("long exposure")) {
		return false;
	}
	if (guider >= 0) {
		before = revision(guider, "GUIDER_GUIDE_RA");
		indigo_change_number_property_1(&client, devices[guider].name, "GUIDER_GUIDE_RA", "EAST", 60000);
		if (!wait_state(guider, "GUIDER_GUIDE_RA", before, INDIGO_BUSY_STATE) || !physical_cycle("guiding")) {
			return false;
		}
	}
	return suffix_acceptance();
}

static indigo_property_state cached_state(const char *name) {
	pthread_mutex_lock(&mutex);
	int p = slot(camera, name);
	indigo_property_state state = p < 0 ? INDIGO_ALERT_STATE : devices[camera].properties[p]->state;
	pthread_mutex_unlock(&mutex);
	return state;
}

static bool abort_latency_trials(void) {
	indigo_property *saved_format = snapshot(camera, "CCD_IMAGE_FORMAT");
	indigo_property *saved_upload = snapshot(camera, "CCD_UPLOAD_MODE");
	bool ok = switch_value(camera, "CCD_UPLOAD_MODE", "CLIENT", INDIGO_OK_STATE) && switch_value(camera, "CCD_IMAGE_FORMAT", "RAW", INDIGO_OK_STATE);
	ok = ok && switch_value(camera, "CCD_ABORT_EXPOSURE", "ABORT_EXPOSURE", INDIGO_ALERT_STATE);
	unsigned max_sent = 0, max_busy = 0, max_done = 0;
	double max_latency = 0;
	for (int mode = abort_previews_only ? 3 : (abort_agent_only ? 2 : 0); ok && mode < (abort_previews_only ? 5 : (abort_agent_only ? 3 : 2)); mode++) {
		for (int trial = 0; ok && trial < 20; trial++) {
			unsigned before = frames();
			int phase_ms = (trial % 10) * (mode >= 2 ? 30 : 10);
			if (mode >= 2) {
				indigo_change_number_property(&client, devices[imager].name, "AGENT_IMAGER_BATCH", 3, (const char *[]){ "EXPOSURE", "COUNT", "DELAY" }, (double[]){ 0.1, mode == 4 ? -1 : 100, 0 });
				indigo_change_switch_property_1(&client, devices[imager].name, "AGENT_START_PROCESS", mode == 3 ? "PREVIEW" : (mode == 4 ? "STREAMING" : "EXPOSURE"), true);
			} else if (mode == 0) {
				indigo_change_number_property(&client, devices[camera].name, "CCD_STREAMING", 2, (const char *[]){ "EXPOSURE", "COUNT" }, (double[]){ 0.1, -1 });
			} else {
				indigo_change_number_property_1(&client, devices[camera].name, "CCD_EXPOSURE", "EXPOSURE", 0.1);
			}
			double deadline = indigo_monotonic_time() + 10, abort_at = 0;
			while (indigo_monotonic_time() < deadline) {
				double now = indigo_monotonic_time();
				if (abort_at == 0 && frames() >= before + 3 && (mode != 1 || cached_state("CCD_EXPOSURE") == INDIGO_OK_STATE)) {
					if (mode == 1) {
						indigo_change_number_property_1(&client, devices[camera].name, "CCD_EXPOSURE", "EXPOSURE", 0.1);
					}
					abort_at = now + phase_ms / 1000.0;
				}
				if (abort_at != 0 && now >= abort_at) {
					break;
				}
				if (mode == 1 && cached_state("CCD_EXPOSURE") == INDIGO_OK_STATE) {
					indigo_change_number_property_1(&client, devices[camera].name, "CCD_EXPOSURE", "EXPOSURE", 0.1);
				}
				indigo_usleep(500);
			}
			if (abort_at == 0) {
				fprintf(stderr, "No three-frame warmup in mode %d trial %d\n", mode, trial);
				ok = false;
				break;
			}
			pthread_mutex_lock(&mutex);
			abort_probe = (abort_measurement){ .enabled = true, .sent = indigo_monotonic_time(), .frames_sent = devices[camera].frames };
			pthread_mutex_unlock(&mutex);
			indigo_change_switch_property_1(&client, devices[mode >= 2 ? imager : camera].name, mode >= 2 ? "AGENT_ABORT_PROCESS" : "CCD_ABORT_EXPOSURE", mode >= 2 ? "ABORT" : "ABORT_EXPOSURE", true);
			deadline = indigo_monotonic_time() + 5;
			for (;;) {
				pthread_mutex_lock(&mutex);
				double done = mode >= 2 ? abort_probe.agent_done : abort_probe.done;
				pthread_mutex_unlock(&mutex);
				if (done != 0 || indigo_monotonic_time() >= deadline) {
					break;
				}
				indigo_usleep(500);
			}
			indigo_usleep(600000);
			pthread_mutex_lock(&mutex);
			abort_measurement result = abort_probe;
			unsigned end = devices[camera].frames;
			abort_probe.enabled = false;
			pthread_mutex_unlock(&mutex);
			unsigned after_sent = end - result.frames_sent, after_busy = result.busy ? end - result.frames_busy : 0, after_done = result.done ? end - result.frames_done : 0;
			double latency = result.done ? (result.done - result.sent) * 1000 : -1;
			printf("ABORT_LATENCY mode=%s trial=%d phase_ms=%d frames_before=%u after_send=%u after_busy=%u after_done=%u busy_ms=%.3f done_ms=%.3f state=%d\n", mode == 0 ? "stream" : (mode == 1 ? "client_series" : (mode == 2 ? "imager_batch" : (mode == 3 ? "imager_preview" : "imager_streaming"))), trial + 1, phase_ms, result.frames_sent - before, after_sent, after_busy, after_done, result.busy ? (result.busy - result.sent) * 1000 : -1, latency, result.state);
			if (mode >= 2) {
				printf("AGENT_LATENCY trial=%d done_ms=%.3f after_done=%u\n", trial + 1, result.agent_done ? (result.agent_done - result.sent) * 1000 : -1, result.agent_done ? end - result.frames_agent_done : 0);
			}
			if (after_sent > max_sent) {
				max_sent = after_sent;
			}
			if (after_busy > max_busy) {
				max_busy = after_busy;
			}
			if (after_done > max_done) {
				max_done = after_done;
			}
			if (latency > max_latency) {
				max_latency = latency;
			}
			ok = (mode >= 2 ? result.agent_done != 0 && end == result.frames_agent_done : result.busy != 0 && result.done != 0) && after_done == 0 && cached_state(mode == 0 || mode == 4 ? "CCD_STREAMING" : "CCD_EXPOSURE") != INDIGO_BUSY_STATE;
		}
	}
	pthread_mutex_lock(&mutex);
	abort_probe.enabled = false;
	pthread_mutex_unlock(&mutex);
	if (ok) {
		ok = number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE);
	}
	if (ok) {
		ok = switch_value(camera, "CCD_ABORT_EXPOSURE", "ABORT_EXPOSURE", INDIGO_ALERT_STATE);
	}
	printf("ABORT_SUMMARY max_after_send=%u max_after_busy=%u max_after_done=%u max_done_ms=%.3f success=%d\n", max_sent, max_busy, max_done, max_latency, ok);
	bool format_restored = restore_property(saved_format);
	bool upload_restored = restore_property(saved_upload);
	indigo_release_property(saved_format);
	indigo_release_property(saved_upload);
	return ok && format_restored && upload_restored;
}

static void hardware_workflows(void) {
	bool initialized = false, agent_initialized = false;
	CHECK(indigo_start() == INDIGO_OK);
	CHECK(indigo_attach_client(&client) == INDIGO_OK);
	CHECK(driver_entry(INDIGO_DRIVER_INIT, NULL) == INDIGO_OK);
	initialized = true;
	// Let initial USB enumeration settle before selecting a unique camera.
	for (int i = 0; i < 500; i++) {
		indigo_usleep(10000);
	}
	const char *requested = getenv("INDIGO_TEST_DEVICE");
	int matches = 0;
	pthread_mutex_lock(&mutex);
	for (int d = 0; d < MAX_DEVICES; d++) {
		if (devices[d].interface & INDIGO_INTERFACE_CCD) {
			printf("    discovered camera: %s\n", devices[d].name);
			if (!requested || !strcmp(requested, devices[d].name)) {
				camera = d;
				matches++;
			}
		}
	}
	if (matches == 1) {
		for (int d = 0; d < MAX_DEVICES; d++) {
			if ((devices[d].interface & INDIGO_INTERFACE_GUIDER) && devices[d].master == devices[camera].device) {
				guider = d;
			}
		}
	}
	pthread_mutex_unlock(&mutex);
	if (matches != 1) {
		fprintf(stderr, "Expected one camera; found %d matches. Set INDIGO_TEST_DEVICE to an exact discovered name when needed.\n", matches);
		camera = -1;
	}
	CHECK(camera >= 0);
	printf("    selected: %s, guider: %s\n", devices[camera].name, guider < 0 ? "not available (SKIP guider workflows)" : devices[guider].name);
	if (abort_latency_only) {
		if (!abort_agent_only) {
			CHECK(switch_value(camera, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
		}
		if (abort_agent_only) {
			CHECK(indigo_agent_imager(INDIGO_DRIVER_INIT, NULL) == INDIGO_OK);
			agent_initialized = true;
			for (int d = 0; d < MAX_DEVICES; d++) {
				if (!strcmp(devices[d].name, "Imager Agent")) {
					imager = d;
				}
			}
			CHECK(imager >= 0);
			CHECK(switch_value(imager, "FILTER_CCD_LIST", devices[camera].name, INDIGO_OK_STATE));
			unsigned features_revision = revision(imager, "AGENT_PROCESS_FEATURES");
			indigo_change_switch_property_1(&client, devices[imager].name, "AGENT_PROCESS_FEATURES", "ENABLE_DITHERING", false);
			CHECK(wait_state(imager, "AGENT_PROCESS_FEATURES", features_revision, INDIGO_OK_STATE));
		}
		CHECK(abort_latency_trials());
		goto cleanup;
	}
	CHECK(switch_value(guider, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
	CHECK(switch_value(camera, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
	CHECK(set_local_directory());
	CHECK(switch_value(camera, "CCD_UPLOAD_MODE", "CLIENT", INDIGO_OK_STATE));
	CHECK(switch_value(camera, "CCD_IMAGE_FORMAT", "RAW", INDIGO_OK_STATE));
	const char *phase = getenv("INDIGO_TEST_PHASE");
	if (phase && !strcmp(phase, "frame-types")) {
		CHECK(all_frame_types());
		goto cleanup;
	}
	if (phase && !strcmp(phase, "guider")) {
		CHECK(guide_overlap_and_disconnect());
		goto cleanup;
	}
	if (phase && !strcmp(phase, "acceptance")) {
		CHECK(complete_physical_acceptance());
		goto cleanup;
	}
	if (phase && !strncmp(phase, "hotplug", 7)) {
		if (!strcmp(phase, "hotplug-exposure")) {
			CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 120, INDIGO_BUSY_STATE));
		} else if (!strcmp(phase, "hotplug-guide")) {
			CHECK(guider >= 0);
			CHECK(number_value(guider, "GUIDER_GUIDE_RA", "EAST", 60000, INDIGO_BUSY_STATE));
			CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 120, INDIGO_BUSY_STATE));
		} else if (!strcmp(phase, "hotplug-stream")) {
			unsigned before = frames(), changed = revision(camera, "CCD_STREAMING");
			indigo_change_number_property(&client, devices[camera].name, "CCD_STREAMING", 2, (const char *[]){ "EXPOSURE", "COUNT" }, (double[]){ 0.1, -1 });
			CHECK(wait_state(camera, "CCD_STREAMING", changed, INDIGO_BUSY_STATE));
			double deadline = indigo_monotonic_time() + 20;
			while (frames() < before + 3 && indigo_monotonic_time() < deadline) {
				indigo_usleep(10000);
			}
			CHECK(frames() >= before + 3);
		}
		CHECK(physical_cycle(phase));
		goto cleanup;
	}
	if (phase && !strcmp(phase, "reload")) {
		CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE));
		goto reload_driver;
	}
	if (phase && (!strcmp(phase, "fractional") || !strcmp(phase, "controls"))) {
		if (!strcmp(phase, "controls")) {
			CHECK(additional_controls_and_cooling());
		}
		CHECK(fractional_and_long_streams());
		goto cleanup;
	}
	if (suffix_only) {
		CHECK(suffix_acceptance());
		goto cleanup;
	}
	CHECK(format_geometry_and_controls());
	CHECK(additional_controls_and_cooling());
	CHECK(fractional_and_long_streams());
	for (int i = 0; i < 3; i++) {
		unsigned before = frames();
		CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE));
		CHECK(frames() == before + 1);
	}
	CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 5, INDIGO_BUSY_STATE));
	// Allow delayed SDK setup to start the physical exposure before aborting it.
	indigo_usleep(500000);
	CHECK(switch_value(camera, "CCD_ABORT_EXPOSURE", "ABORT_EXPOSURE", INDIGO_OK_STATE));
	CHECK(wait_state(camera, "CCD_EXPOSURE", 0, INDIGO_ALERT_STATE));
	unsigned before = frames(), stream_revision = revision(camera, "CCD_STREAMING");
	indigo_change_number_property(&client, devices[camera].name, "CCD_STREAMING", 2, (const char *[]){ "EXPOSURE", "COUNT" }, (double[]){ 0.1, 5 });
	CHECK(wait_state(camera, "CCD_STREAMING", stream_revision, INDIGO_OK_STATE));
	CHECK(frames() == before + 5);
	stream_revision = revision(camera, "CCD_STREAMING");
	before = frames();
	indigo_change_number_property(&client, devices[camera].name, "CCD_STREAMING", 2, (const char *[]){ "EXPOSURE", "COUNT" }, (double[]){ 0.1, -1 });
	CHECK(wait_state(camera, "CCD_STREAMING", stream_revision, INDIGO_BUSY_STATE));
	for (int i = 0; i < 1000; i++) {
		indigo_usleep(10000);
	}
	CHECK(frames() >= before + 3);
	printf("    sustained stream: %u frames in approximately 10 seconds\n", frames() - before);
	CHECK(switch_value(camera, "CCD_ABORT_EXPOSURE", "ABORT_EXPOSURE", INDIGO_OK_STATE));
	CHECK(wait_state(camera, "CCD_STREAMING", stream_revision, INDIGO_OK_STATE));
	const char *axes[] = { "GUIDER_GUIDE_RA", "GUIDER_GUIDE_RA", "GUIDER_GUIDE_DEC", "GUIDER_GUIDE_DEC" };
	const char *directions[] = { "EAST", "WEST", "NORTH", "SOUTH" };
	for (int i = 0; i < 4; i++) {
		CHECK(number_value(guider, axes[i], directions[i], 100, INDIGO_OK_STATE));
	}
	CHECK(guide_overlap_and_disconnect());
	CHECK(switch_value(camera, "CONNECTION", "DISCONNECTED", INDIGO_OK_STATE));
	CHECK(number_value(guider, "GUIDER_GUIDE_RA", "EAST", 100, INDIGO_OK_STATE));
	CHECK(switch_value(guider, "CONNECTION", "DISCONNECTED", INDIGO_OK_STATE));
	CHECK(switch_value(camera, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
	CHECK(switch_value(guider, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
	before = frames();
	CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE));
	CHECK(frames() == before + 1);
	if (hotplug) {
		before = frames();
		stream_revision = revision(camera, "CCD_STREAMING");
		indigo_change_number_property(&client, devices[camera].name, "CCD_STREAMING", 2, (const char *[]){ "EXPOSURE", "COUNT" }, (double[]){ 0.1, -1 });
		CHECK(wait_state(camera, "CCD_STREAMING", stream_revision, INDIGO_BUSY_STATE));
		for (int i = 0; i < 3000 && frames() < before + 3; i++) {
			indigo_usleep(10000);
		}
		CHECK(frames() >= before + 3);
		printf("HOTPLUG_READY: unplug USB camera now: %s\n", devices[camera].name);
		CHECK(wait_presence(false));
		printf("HOTPLUG_REMOVED: reconnect the same USB camera now\n");
		CHECK(wait_presence(true));
		CHECK(switch_value(camera, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
		CHECK(switch_value(guider, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
		CHECK(set_local_directory());
		CHECK(switch_value(camera, "CCD_UPLOAD_MODE", "CLIENT", INDIGO_OK_STATE));
		CHECK(switch_value(camera, "CCD_IMAGE_FORMAT", "RAW", INDIGO_OK_STATE));
		before = frames();
		CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE));
		CHECK(frames() == before + 1);
		CHECK(number_value(guider, "GUIDER_GUIDE_RA", "EAST", 100, INDIGO_OK_STATE));
		printf("HOTPLUG_RECOVERED: exposure and guide pulse succeeded after replug\n");
	}
	if (acceptance) {
		CHECK(complete_physical_acceptance());
	}
reload_driver:
	CHECK(disconnect_device(camera));
	CHECK(disconnect_device(guider));
	CHECK(driver_entry(INDIGO_DRIVER_SHUTDOWN, NULL) == INDIGO_OK);
	initialized = false;
#ifdef ASI_DYNAMIC_DRIVER
	CHECK(dlclose(driver_library) == 0);
	driver_library = NULL;
	driver_entry = NULL;
	CHECK(load_driver_library());
	printf("    Dynamic driver dlclose/dlopen completed\n");
#endif
	CHECK(driver_entry(INDIGO_DRIVER_INIT, NULL) == INDIGO_OK);
	initialized = true;
	CHECK(wait_presence(true));
	CHECK(switch_value(camera, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
	CHECK(switch_value(guider, "CONNECTION", "CONNECTED", INDIGO_OK_STATE));
	CHECK(set_local_directory());
	CHECK(switch_value(camera, "CCD_UPLOAD_MODE", "CLIENT", INDIGO_OK_STATE));
	CHECK(switch_value(camera, "CCD_IMAGE_FORMAT", "RAW", INDIGO_OK_STATE));
	before = frames();
	CHECK(number_value(camera, "CCD_EXPOSURE", "EXPOSURE", 0.1, INDIGO_OK_STATE));
	CHECK(frames() == before + 1);
#ifdef ASI_DYNAMIC_DRIVER
	printf("    Fresh exposure after dynamic driver reload: PASS\n");
#else
	printf("    Driver shutdown/reinitialization: fresh queue and exposure succeeded (SDK library remains loaded)\n");
#endif
	pthread_mutex_lock(&mutex);
	unsigned invalid = devices[camera].invalid_frames;
	pthread_mutex_unlock(&mutex);
	CHECK(invalid == 0);
cleanup:
	if (agent_initialized) {
		indigo_change_switch_property_1(&client, devices[imager].name, "AGENT_ABORT_PROCESS", "ABORT", true);
		if (indigo_agent_imager(INDIGO_DRIVER_SHUTDOWN, NULL) != INDIGO_OK) {
			indigo_test_failures++;
		}
	}
	if (camera >= 0) {
		// Abort any unfinished acquisition before disconnecting; disconnected properties may be unchanged.
		indigo_change_switch_property_1(&client, devices[camera].name, "CCD_ABORT_EXPOSURE", "ABORT_EXPOSURE", true);
		if (!disconnect_device(camera)) {
			indigo_test_failures++;
		}
	}
	if (guider >= 0) {
		if (!disconnect_device(guider)) {
			indigo_test_failures++;
		}
	}
	if (initialized && driver_entry(INDIGO_DRIVER_SHUTDOWN, NULL) != INDIGO_OK) {
		indigo_test_failures++;
	}
	indigo_detach_client(&client);
	indigo_stop();
}

int main(int argc, char **argv) {
	if ((argc != 2 && argc != 3) || strcmp(argv[1], "--run") || (argc == 3 && strcmp(argv[2], "--hotplug") && strcmp(argv[2], "--acceptance") && strcmp(argv[2], "--suffix") && strcmp(argv[2], "--abort-latency") && strcmp(argv[2], "--abort-agent") && strcmp(argv[2], "--abort-previews"))) {
		fprintf(stderr, "Physical camera test: --run [--hotplug|--acceptance|--suffix|--abort-latency|--abort-agent|--abort-previews].\n");
		return 2;
	}
	suffix_only = argc == 3 && !strcmp(argv[2], "--suffix");
	abort_previews_only = argc == 3 && !strcmp(argv[2], "--abort-previews");
	abort_agent_only = abort_previews_only || (argc == 3 && !strcmp(argv[2], "--abort-agent"));
	abort_latency_only = abort_agent_only || (argc == 3 && !strcmp(argv[2], "--abort-latency"));
	hotplug = argc == 3 && !suffix_only && !abort_latency_only;

	acceptance = argc == 3 && !strcmp(argv[2], "--acceptance");
	setvbuf(stdout, NULL, _IONBF, 0);
	client = (indigo_client){ .name = "ASI hardware test", .version = INDIGO_VERSION_CURRENT, .define_property = define_property, .update_property = update_property, .delete_property = delete_property, .send_message = report_message };
	if (!mkdtemp(config_folder)) {
		return 1;
	}
#ifdef ASI_DYNAMIC_DRIVER
	if (!load_driver_library()) {
		return 1;
	}
#endif
	const indigo_test_case tests[] = { { abort_latency_only ? "Physical camera abort latency" : "Physical camera exposure, streaming, guider and reconnect", hardware_workflows } };
	int result = indigo_run_tests("ASI hardware", tests, 1);
	for (int d = 0; d < MAX_DEVICES; d++) {
		for (int p = 0; p < MAX_PROPERTIES; p++) {
			indigo_release_property(devices[d].properties[p]);
		}
	}
	DIR *dir = opendir(config_folder);
	if (dir) {
		struct dirent *entry;
		while ((entry = readdir(dir))) {
			if (entry->d_name[0] != '.') {
				char path[1024];
				snprintf(path, sizeof(path), "%s/%s", config_folder, entry->d_name);
				unlink(path);
			}
		}
		closedir(dir);
	}
	rmdir(config_folder);
#ifdef ASI_DYNAMIC_DRIVER
	if (driver_library && dlclose(driver_library) != 0) {
		result = 1;
	}
#endif
	return result;
}
