// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// AUX powerbox coverage for indigo_aux_svbpowerbox against the standalone SVBONY simulator over a
// real PTY. The box exposes six switched outlets, two USB ports, two PWM heaters, a variable
// voltage rail and two independent environment sensors. Either sensor can be absent, and the
// driver has to publish the documented "no reading" sentinels instead of plausible-looking zeroes,
// so the sensor-absence combinations are the most valuable part of this suite.

#include <indigo_drivers/aux_svbpowerbox/indigo_aux_svbpowerbox.h>

#include "serial_simulator_test_common.h"

#ifndef AUX_SVBPOWERBOX_SIMULATOR_EXECUTABLE
#define AUX_SVBPOWERBOX_SIMULATOR_EXECUTABLE "build/integration/aux_svbpowerbox_simulator"
#endif

#define NO_TEMPERATURE (-273.15)
#define NO_HUMIDITY    (-1.0)

static const simulator_driver_case svbpowerbox_aux = {
	"SVBONY PowerBox",
	"indigo_aux_svbpowerbox",
	"SVBONY PowerBox",
	indigo_aux_svbpowerbox,
	false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static bool start_powerbox(external_serial_simulator *simulator, const char **arguments) {
	if (arguments == NULL) {
		return start_external_serial_simulator(simulator, AUX_SVBPOWERBOX_SIMULATOR_EXECUTABLE);
	}
	return start_external_serial_simulator_with_args(simulator, AUX_SVBPOWERBOX_SIMULATOR_EXECUTABLE, arguments);
}

static bool set_switch(const char *property, const char *item, bool value) {
	return indigo_change_switch_property_1(&simulator_test_client, svbpowerbox_aux.device_name, property, item, value) == INDIGO_OK;
}

static bool set_number(const char *property, const char *item, double value) {
	return indigo_change_number_property_1(&simulator_test_client, svbpowerbox_aux.device_name, property, item, value) == INDIGO_OK;
}

static double number_of(const char *property, const char *item) {
	return cached_number_value(property, item);
}

// The sensor properties are defined OK at attach with zeroed items, so waiting for a state tells
// nothing about whether a reading has arrived. The supply voltage is only ever written by a
// completed poll, so it is the reliable signal that the first status frame has been parsed.
static bool wait_for_first_poll(void) {
	for (int i = 0; i < 500; i++) {
		if (cached_number_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME) > 0) {
			return true;
		}
		indigo_usleep(10000);
	}
	return false;
}

// -------------------------------------------------------------------------------- metadata

static void metadata_and_property_completeness(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(context.connected && context.last_connection_state == INDIGO_OK_STATE);
	assert_device_interface(INDIGO_INTERFACE_AUX_POWERBOX | INDIGO_INTERFACE_AUX_WEATHER);
	static const char *properties[] = {
		AUX_OUTLET_NAMES_PROPERTY_NAME,
		AUX_POWER_OUTLET_PROPERTY_NAME,
		AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME,
		AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME,
		AUX_USB_PORT_PROPERTY_NAME,
		AUX_HEATER_OUTLET_PROPERTY_NAME,
		AUX_DEW_CONTROL_PROPERTY_NAME,
		AUX_WEATHER_PROPERTY_NAME,
		AUX_TEMPERATURE_SENSORS_PROPERTY_NAME,
		AUX_DEW_WARNING_PROPERTY_NAME,
		AUX_INFO_PROPERTY_NAME
	};
	assert_defined_properties(properties, ARRAY_SIZE(properties));
	static const char *outlets[] = {
		AUX_POWER_OUTLET_1_ITEM_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, AUX_POWER_OUTLET_3_ITEM_NAME,
		AUX_POWER_OUTLET_4_ITEM_NAME, AUX_POWER_OUTLET_5_ITEM_NAME, AUX_POWER_OUTLET_6_ITEM_NAME
	};
	assert_property_has_items(AUX_POWER_OUTLET_PROPERTY_NAME, outlets, ARRAY_SIZE(outlets));
	static const char *usb[] = { AUX_USB_PORT_1_ITEM_NAME, AUX_USB_PORT_2_ITEM_NAME };
	assert_property_has_items(AUX_USB_PORT_PROPERTY_NAME, usb, ARRAY_SIZE(usb));
	static const char *heaters[] = { AUX_HEATER_OUTLET_1_ITEM_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME };
	assert_property_has_items(AUX_HEATER_OUTLET_PROPERTY_NAME, heaters, ARRAY_SIZE(heaters));
	static const char *weather[] = { AUX_WEATHER_TEMPERATURE_ITEM_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME, AUX_WEATHER_DEWPOINT_ITEM_NAME };
	assert_property_has_items(AUX_WEATHER_PROPERTY_NAME, weather, ARRAY_SIZE(weather));
	static const char *sensors[] = { AUX_TEMPERATURE_SENSORS_SENSOR_1_ITEM_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME };
	assert_property_has_items(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, sensors, ARRAY_SIZE(sensors));
	assert_property_has_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME);
	assert_property_has_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME);
	assert_property_has_item(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME);
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- outlets

// Each of the six outlets has its own bit in the protocol frame, so all of them are switched
// individually in both directions rather than only the first.
static void every_power_outlet_switches(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	static const char *outlets[] = {
		AUX_POWER_OUTLET_1_ITEM_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, AUX_POWER_OUTLET_3_ITEM_NAME,
		AUX_POWER_OUTLET_4_ITEM_NAME, AUX_POWER_OUTLET_5_ITEM_NAME, AUX_POWER_OUTLET_6_ITEM_NAME
	};
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	for (int i = 0; i < ARRAY_SIZE(outlets); i++) {
		SERIAL_CHECK_TRUE(set_switch(AUX_POWER_OUTLET_PROPERTY_NAME, outlets[i], true));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
		assert_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, outlets[i], true);
	}
	for (int i = 0; i < ARRAY_SIZE(outlets); i++) {
		SERIAL_CHECK_TRUE(set_switch(AUX_POWER_OUTLET_PROPERTY_NAME, outlets[i], false));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
		assert_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, outlets[i], false);
	}
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

static void both_usb_ports_switch(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	static const char *ports[] = { AUX_USB_PORT_1_ITEM_NAME, AUX_USB_PORT_2_ITEM_NAME };
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	for (int i = 0; i < ARRAY_SIZE(ports); i++) {
		SERIAL_CHECK_TRUE(set_switch(AUX_USB_PORT_PROPERTY_NAME, ports[i], false));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		assert_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, ports[i], false);
		SERIAL_CHECK_TRUE(set_switch(AUX_USB_PORT_PROPERTY_NAME, ports[i], true));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		assert_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, ports[i], true);
	}
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

// Both PWM heaters across the whole duty range, including both ends.
static void heater_outlets_accept_the_full_range(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	static const char *heaters[] = { AUX_HEATER_OUTLET_1_ITEM_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME };
	const double duties[] = { 0, 1, 50, 99, 100 };
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	for (int h = 0; h < ARRAY_SIZE(heaters); h++) {
		for (int i = 0; i < ARRAY_SIZE(duties); i++) {
			SERIAL_CHECK_TRUE(set_number(AUX_HEATER_OUTLET_PROPERTY_NAME, heaters[h], duties[i]));
			SERIAL_CHECK_TRUE(wait_for_property_state(AUX_HEATER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
			SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_HEATER_OUTLET_PROPERTY_NAME, heaters[h], duties[i], 0.001));
		}
	}
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

static void variable_voltage_rail_is_settable(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	indigo_property *voltage = find_cached_property(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(voltage != NULL && voltage->count > 0);
	const double target = voltage->items[0].number.min + (voltage->items[0].number.max - voltage->items[0].number.min) / 2;
	printf("Variable rail range %g..%g, setting %g\n", voltage->items[0].number.min, voltage->items[0].number.max, target);
	SERIAL_CHECK_TRUE(set_number(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME, target));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

static void dew_control_switches_between_manual_and_automatic(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(set_switch(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_DEW_CONTROL_PROPERTY_NAME, INDIGO_OK_STATE));
	assert_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true);
	SERIAL_CHECK_TRUE(set_switch(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_DEW_CONTROL_PROPERTY_NAME, INDIGO_OK_STATE));
	assert_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true);
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- sensors

static void both_sensors_present_report_readings(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	printf("SHT40 %g C / %g %%RH, DS18B20 %g C, supply %g V\n", number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME), number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME), number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME), number_of(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME));
	SERIAL_CHECK_TRUE(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME) > NO_TEMPERATURE + 1);
	SERIAL_CHECK_TRUE(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME) >= 0);
	SERIAL_CHECK_TRUE(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_1_ITEM_NAME) > NO_TEMPERATURE + 1);
	SERIAL_CHECK_TRUE(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME) > NO_TEMPERATURE + 1);
	SERIAL_CHECK_TRUE(number_of(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME) > 0);
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

// Without the SHT40 there is no ambient temperature or humidity, so the driver must publish the
// sentinels rather than a plausible looking zero, and the DS18B20 probe must still be reported.
static void missing_sht40_reports_sentinels(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	const char *arguments[] = { "--no-sht40", NULL };
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	printf("No SHT40: weather %g C / %g %%RH, probe %g C\n", number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME), number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME), number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME));
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME) - NO_TEMPERATURE) < .01);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME) - NO_HUMIDITY) < .01);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_1_ITEM_NAME) - NO_TEMPERATURE) < .01);
	SERIAL_CHECK_TRUE(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME) > NO_TEMPERATURE + 1);
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

static void missing_ds18b20_keeps_the_ambient_sensor(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	const char *arguments[] = { "--no-ds18b20", NULL };
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	printf("No DS18B20: weather %g C, probe %g C\n", number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME), number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME));
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME) - NO_TEMPERATURE) < .01);
	SERIAL_CHECK_TRUE(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME) > NO_TEMPERATURE + 1);
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

// With no sensor at all the temperature property has nothing to report and must say so rather than
// claiming a valid reading.
static void both_sensors_missing_reports_no_readings(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	const char *arguments[] = { "--no-sht40", "--no-ds18b20", NULL };
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	printf("No sensors: weather %g C / %g %%RH, probes %g / %g C\n", number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME), number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME), number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_1_ITEM_NAME), number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME));
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_1_ITEM_NAME) - NO_TEMPERATURE) < .01);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME) - NO_TEMPERATURE) < .01);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME) - NO_HUMIDITY) < .01);
	// The box itself is still healthy, so its supply voltage has to keep being reported.
	SERIAL_CHECK_TRUE(number_of(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME) > 0);
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- lifecycle

static void reconnect_restores_the_controls(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(set_switch(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
	disconnect_serial_device(&svbpowerbox_aux);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connect_serial_device(&svbpowerbox_aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(set_switch(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

static void repeated_disconnect_is_tolerated(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&svbpowerbox_aux, simulator.port));
	online = true;
	disconnect_serial_device(&svbpowerbox_aux);
	SERIAL_CHECK_TRUE(!context.connected);
	disconnect_serial_device(&svbpowerbox_aux);
	SERIAL_CHECK_TRUE(!context.connected);
	online = false;
	tear_down_serial_driver(&svbpowerbox_aux);
cleanup:
	if (online) { stop_serial_driver(&svbpowerbox_aux); }
	stop_external_serial_simulator(&simulator);
}

static void silent_port_is_refused(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_powerbox(&simulator, NULL));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&svbpowerbox_aux));
	stop_external_serial_simulator(&simulator);
	SERIAL_CHECK_TRUE(!connect_serial_device(&svbpowerbox_aux, simulator.port));
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&svbpowerbox_aux);
}

int main(void) {
	const indigo_test_case tests[] = {
		{ "metadata_and_property_completeness", metadata_and_property_completeness },
		{ "every_power_outlet_switches", every_power_outlet_switches },
		{ "both_usb_ports_switch", both_usb_ports_switch },
		{ "heater_outlets_accept_the_full_range", heater_outlets_accept_the_full_range },
		{ "variable_voltage_rail_is_settable", variable_voltage_rail_is_settable },
		{ "dew_control_switches_between_manual_and_automatic", dew_control_switches_between_manual_and_automatic },
		{ "both_sensors_present_report_readings", both_sensors_present_report_readings },
		{ "missing_sht40_reports_sentinels", missing_sht40_reports_sentinels },
		{ "missing_ds18b20_keeps_the_ambient_sensor", missing_ds18b20_keeps_the_ambient_sensor },
		{ "both_sensors_missing_reports_no_readings", both_sensors_missing_reports_no_readings },
		{ "reconnect_restores_the_controls", reconnect_restores_the_controls },
		{ "repeated_disconnect_is_tolerated", repeated_disconnect_is_tolerated },
		{ "silent_port_is_refused", silent_port_is_refused }
	};
	return indigo_run_tests("SVBONY PowerBox serial simulator integration tests", tests, ARRAY_SIZE(tests));
}
