// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

#include <errno.h>
#include <fcntl.h>
#include <stdatomic.h>

#include <indigo/indigo_uni_io.h>
#include <indigo_drivers/focuser_optec/indigo_focuser_optec.h>

#include "serial_simulator_test_common.h"

#ifndef FOCUSER_OPTEC_SIMULATOR_EXECUTABLE
#define FOCUSER_OPTEC_SIMULATOR_EXECUTABLE "build/integration/focuser_optec_simulator"
#endif

static const simulator_driver_case optec_focuser = {
	"Optec TCF-S Focuser", "indigo_focuser_optec", "Optec TCF-S", indigo_focuser_optec, false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static external_serial_simulator fixture, second_fixture;
static char fixture_dir[] = "/tmp/indigo-optec.XXXXXX";
static char event_path[256], fault_path[256];
static const char *current_profile;

static bool fault(const char *command, const char *action) {
	char temporary[280];
	snprintf(temporary, sizeof(temporary), "%s.tmp", fault_path);
	FILE *file = fopen(temporary, "w");
	if (!file) {
		return false;
	}
	fprintf(file, "%s %s\n", command, action);
	fclose(file);
	return rename(temporary, fault_path) == 0;
}

static int commands(const char *prefix) {
	FILE *file = fopen(event_path, "r");
	if (!file) {
		return -1;
	}
	char line[512], kind[16], value[256];
	double timestamp;
	int count = 0;
	while (fgets(line, sizeof(line), file)) {
		if (sscanf(line, "%lf %15s %255s", &timestamp, kind, value) == 3 && !strcmp(kind, "RX") && !strncmp(value, prefix, strlen(prefix))) {
			count++;
		}
	}
	fclose(file);
	return count;
}

static int open_descriptors(void) {
	int count = 0;
	for (int fd = 0; fd < 1024; fd++) {
		if (fcntl(fd, F_GETFD) >= 0) {
			count++;
		}
	}
	return count;
}

static void driver_stop(void) {
	disconnect_serial_device(&optec_focuser);
	bool disconnected = !context.connected;
	indigo_result result = indigo_focuser_optec(INDIGO_DRIVER_SHUTDOWN, NULL);
	indigo_detach_client(&simulator_test_client);
	indigo_stop();
	release_cached_properties();
	ASSERT_TRUE(disconnected);
	ASSERT_EQ_INT(INDIGO_OK, result);
}

static bool driver_start(void) {
	return bring_up_serial_driver(&optec_focuser) && connect_serial_device(&optec_focuser, fixture.port);
}

static const char *observed_names[] = {
	CONNECTION_PROPERTY_NAME, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_STEPS_PROPERTY_NAME,
	FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_MODE_PROPERTY_NAME,
	FOCUSER_REVERSE_MOTION_PROPERTY_NAME
};
static atomic_uint revisions[ARRAY_SIZE(observed_names)], motion_busy;

static int observed_index(const char *name) {
	for (int index = 0; index < ARRAY_SIZE(observed_names); index++) {
		if (!strcmp(name, observed_names[index])) {
			return index;
		}
	}
	return -1;
}

static indigo_result observe_update(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	indigo_result result = simulator_client_update_property(client, device, property, message);
	int index = observed_index(property->name);
	if (index >= 0) {
		atomic_fetch_add(&revisions[index], 1);
	}
	if ((index == 1 || index == 2) && property->state == INDIGO_BUSY_STATE) {
		atomic_fetch_add(&motion_busy, 1);
	}
	return result;
}

static bool new_state(const char *name, unsigned before, indigo_property_state state) {
	int index = observed_index(name);
	for (int retry = 0; retry < 500; retry++) {
		indigo_property *property = find_cached_property(name);
		if (index >= 0 && atomic_load(&revisions[index]) > before && property && property->state == state) {
			return true;
		}
		indigo_usleep(25000);
	}
	fprintf(stderr, "No fresh %s state %d\n", name, state);
	return false;
}

static bool number_change(const char *property, const char *item, double value, indigo_property_state state) {
	int index = observed_index(property);
	unsigned before = index >= 0 ? atomic_load(&revisions[index]) : 0;
	if (indigo_change_number_property_1(&simulator_test_client, optec_focuser.device_name, property, item, value) != INDIGO_OK) {
		return false;
	}
	return index >= 0 ? new_state(property, before, state) : wait_for_property_state(property, state);
}

static bool switch_change(const char *property, const char *item, bool value, indigo_property_state state) {
	int index = observed_index(property);
	unsigned before = index >= 0 ? atomic_load(&revisions[index]) : 0;
	if (indigo_change_switch_property_1(&simulator_test_client, optec_focuser.device_name, property, item, value) != INDIGO_OK) {
		return false;
	}
	return index >= 0 ? new_state(property, before, state) : wait_for_property_state(property, state);
}

static bool at_position(int position) {
	return wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, position, 1) && wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE) && wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE);
}

static bool simulator_write(indigo_uni_handle *handle, const char *command) {
	size_t length = strlen(command);
	if (!strcmp(current_profile, "split") && length > 2) {
		size_t half = length / 2;
		if (indigo_uni_write(handle, command, half) != (long)half) {
			return false;
		}
		indigo_usleep(10000);
		return indigo_uni_write(handle, command + half, length - half) == (long)(length - half);
	}
	return indigo_uni_write(handle, command, length) == (long)length;
}

static bool simulator_exchange(indigo_uni_handle *handle, const char *command, const char *expected) {
	char response[128];
	if (indigo_uni_discard(handle) < 0 || !simulator_write(handle, command)) {
		return false;
	}
	if (!expected) {
		return true;
	}
	long count = indigo_uni_read_section2(handle, response, sizeof(response) - 1, "\r", "\n", INDIGO_DELAY(2), INDIGO_DELAY(0.1));
	if (count != (long)strlen(expected) + 1 || response[count - 1] != '\r') {
		return false;
	}
	response[count - 1] = 0;
	if (strcmp(response, expected)) {
		fprintf(stderr, "%s expected '%s', got '%s'\n", command, expected, response);
		return false;
	}
	return true;
}

static bool simulator_read(indigo_uni_handle *handle, const char *expected) {
	char response[128];
	long count = indigo_uni_read_section2(handle, response, sizeof(response) - 1, "\r", "\n", INDIGO_DELAY(2), INDIGO_DELAY(0.1));
	if (count != (long)strlen(expected) + 1 || response[count - 1] != '\r') {
		return false;
	}
	response[count - 1] = 0;
	return !strcmp(response, expected);
}

static bool simulator_silent(indigo_uni_handle *handle, const char *command) {
	return indigo_uni_discard(handle) >= 0 && simulator_write(handle, command) && indigo_uni_wait_for_data(handle, INDIGO_DELAY(0.1)) == 0;
}

static void simulator_protocol(void) {
	indigo_uni_handle *handle = indigo_uni_open_serial_with_speed(fixture.port, 19200, INDIGO_LOG_DEBUG);
	SERIAL_CHECK_TRUE(handle != NULL);
	const char *commands[][2] = {
		{ "FMMODE", "!" }, { "FPOSRO", "P=5000" }, { "FTMPRO", "T=+24.5" },
		{ "FREADA", "A=0086" }, { "FREADB", "B=0042" }, { "FTxxxA", "A=0" }, { "FTxxxB", "B=0" },
		{ "FLA012", "DONE" }, { "FLB345", "DONE" }, { "FZAxx1", "DONE" }, { "FZBxx1", "DONE" },
		{ "FDA123", "DONE" }, { "FDB456", "DONE" }, { "FI0010", "*" }, { "FO0010", "*" },
		{ "FCENTR", "CENTER" }, { "FQUIT1", "DONE" }, { "FAMODE", NULL }, { "FMMODE", "!" },
		{ "FBMODE", NULL }, { "FMMODE", "!" }, { "FSLEEP", "ZZZ" }, { "FWAKUP", "WAKE" },
		{ "FHOME", "DONE" }, { "FFMODE", "END" }
	};
	for (int index = 0; index < ARRAY_SIZE(commands); index++) {
		SERIAL_CHECK_TRUE(simulator_exchange(handle, commands[index][0], commands[index][1]));
	}
cleanup:
	if (handle) {
		indigo_uni_close(&handle);
	}
}

static void simulator_automatic_compensation(void) {
	indigo_uni_handle *handle = indigo_uni_open_serial_with_speed(fixture.port, 19200, INDIGO_LOG_DEBUG);
	SERIAL_CHECK_TRUE(handle != NULL);
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FMMODE", "!"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FQUIT1", "DONE"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FAMODE", NULL));
	SERIAL_CHECK_TRUE(fault("temperature", "25.5"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FQUIT0", "DONE"));
	SERIAL_CHECK_TRUE(simulator_read(handle, "P=5086"));
	SERIAL_CHECK_TRUE(simulator_read(handle, "T=+25.5"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FQUIT1", "DONE"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FMMODE", "!"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FFMODE", "END"));
cleanup:
	if (handle) {
		indigo_uni_close(&handle);
	}
}

static void simulator_rejections(void) {
	indigo_uni_handle *handle = indigo_uni_open_serial_with_speed(fixture.port, 19200, INDIGO_LOG_DEBUG);
	SERIAL_CHECK_TRUE(handle != NULL);
	SERIAL_CHECK_TRUE(simulator_silent(handle, "FPOSRO"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FMMODE", "!"));
	SERIAL_CHECK_TRUE(simulator_silent(handle, "FO7001"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FO7000", "*"));
	SERIAL_CHECK_TRUE(simulator_silent(handle, "FLA12X"));
	SERIAL_CHECK_TRUE(simulator_silent(handle, "FZAxx2"));
	SERIAL_CHECK_TRUE(simulator_silent(handle, "FDAA00"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FQUIT1", "DONE"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FAMODE", NULL));
	SERIAL_CHECK_TRUE(simulator_silent(handle, "FPOSRO"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FMMODE", "!"));
	SERIAL_CHECK_TRUE(simulator_exchange(handle, "FFMODE", "END"));
cleanup:
	if (handle) {
		indigo_uni_close(&handle);
	}
}

static void capabilities(void) {
	SERIAL_CHECK_TRUE(driver_start());
	assert_device_interface(INDIGO_INTERFACE_FOCUSER);
	assert_property_has_item(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME);
	assert_property_has_item(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME);
	assert_property_has_item(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME);
	assert_property_has_item(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	assert_property_has_item(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME);
	assert_property_has_item(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME);
	assert_property_has_item(FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_MANUAL_ITEM_NAME);
	assert_property_has_item(FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_AUTOMATIC_ITEM_NAME);
	SERIAL_CHECK_TRUE(!has_defined_property(FOCUSER_SPEED_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(FOCUSER_ABORT_MOTION_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(FOCUSER_ON_POSITION_SET_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(FOCUSER_LIMITS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_REVERSE_MOTION_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(find_cached_property(FOCUSER_POSITION_PROPERTY_NAME)->perm == INDIGO_RO_PERM);
	SERIAL_CHECK_TRUE(find_cached_item(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME)->number.max == 9999);
	SERIAL_CHECK_TRUE(find_cached_item(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME)->number.max == 9999);
	double position = !strcmp(current_profile, "alternate") ? 1234 : 5000;
	double coefficient = !strcmp(current_profile, "alternate") ? -12 : 86;
	double temperature = !strcmp(current_profile, "alternate") ? -5.5 : 24.5;
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, position, .01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, coefficient, .01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, temperature, .01));
cleanup:
	driver_stop();
}

static void relative_motion(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, true, INDIGO_OK_STATE));
	unsigned busy = atomic_load(&motion_busy);
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 40, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(at_position(5040) && atomic_load(&motion_busy) > busy && commands("FO0040") == 1);
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_ENABLED_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 20, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(at_position(5020) && commands("FI0020") == 1);
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 10, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(at_position(5030) && commands("FO0010") == 1);
	int before = commands("FO0000") + commands("FI0000");
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 0, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(commands("FO0000") + commands("FI0000") == before);
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_DISABLED_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(fault("external", "2"));
	SERIAL_CHECK_TRUE(at_position(2));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(at_position(0));
	SERIAL_CHECK_TRUE(fault("external", "9997"));
	SERIAL_CHECK_TRUE(at_position(9997));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(at_position(9999));
cleanup:
	driver_stop();
}

static void controls(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, -12, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(commands("FLA012") == 1 && commands("FZAxx1") == 1);
	SERIAL_CHECK_TRUE(number_change(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, 0, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(commands("FLA000") == 1 && commands("FZAxx0") == 1);
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_AUTOMATIC_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(commands("FQUIT1") == 1 && commands("FAMODE") == 1);
	SERIAL_CHECK_TRUE(find_cached_property(FOCUSER_POSITION_PROPERTY_NAME) == NULL && find_cached_property(FOCUSER_STEPS_PROPERTY_NAME) == NULL);
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_MANUAL_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(commands("FMMODE") >= 2 && has_defined_property(FOCUSER_POSITION_PROPERTY_NAME) && has_defined_property(FOCUSER_STEPS_PROPERTY_NAME));
cleanup:
	driver_stop();
}

static void rejected_connection(void) {
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&optec_focuser));
	int descriptors = open_descriptors();
	const char *key = !strncmp(current_profile, "position", 8) ? "FPOSRO" : !strncmp(current_profile, "temperature", 11) ? "FTMPRO" : !strncmp(current_profile, "slope", 5) ? "FREADA" : !strncmp(current_profile, "sign", 4) ? "FTxxxA" : "FMMODE";
	const char *action = strstr(current_profile, "partial") ? "partial" : strstr(current_profile, "overlong") ? "overlong" : strstr(current_profile, "error") ? "error1" : strstr(current_profile, "silent") ? (!strcmp(key, "FMMODE") ? "always_silent" : "silent") : "malformed";
	SERIAL_CHECK_TRUE(fault(key, action));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_text_property_1_raw(&simulator_test_client, optec_focuser.device_name, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, fixture.port));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_switch_property_1(&simulator_test_client, optec_focuser.device_name, CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(CONNECTION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(!context.connected && descriptors == open_descriptors());
	unlink(fault_path);
	SERIAL_CHECK_TRUE(connect_serial_device(&optec_focuser, fixture.port));
cleanup:
	driver_stop();
}

static void poll_failure(void) {
	SERIAL_CHECK_TRUE(driver_start());
	const char *command = strstr(current_profile, "temperature") ? "FTMPRO" : "FPOSRO";
	const char *property = strstr(current_profile, "temperature") ? FOCUSER_TEMPERATURE_PROPERTY_NAME : FOCUSER_POSITION_PROPERTY_NAME;
	unsigned before = atomic_load(&revisions[observed_index(property)]);
	SERIAL_CHECK_TRUE(fault(command, strstr(current_profile, "partial") ? "partial" : strstr(current_profile, "overlong") ? "overlong" : "malformed"));
	SERIAL_CHECK_TRUE(new_state(property, before, INDIGO_ALERT_STATE));
	before = atomic_load(&revisions[observed_index(property)]);
	SERIAL_CHECK_TRUE(new_state(property, before, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

static void compensation_failure(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(fault("FZAxx1", "malformed"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, -12, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, -12, .01));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, 15, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

static void mode_failure(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(fault("FQUIT1", "malformed"));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_AUTOMATIC_ITEM_NAME, true, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(find_cached_item(FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_MANUAL_ITEM_NAME)->sw.value);
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_POSITION_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_AUTOMATIC_ITEM_NAME, true, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

static void motion_failure(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, true, INDIGO_OK_STATE));
	if (!strcmp(current_profile, "start_failure")) {
		SERIAL_CHECK_TRUE(fault("FO0500", "malformed"));
	} else if (!strcmp(current_profile, "stall")) {
		SERIAL_CHECK_TRUE(fault("FO0500", "stall"));
	} else {
		SERIAL_CHECK_TRUE(fault("FPOSRO", !strcmp(current_profile, "transport_close") ? "close" : "malformed"));
	}
	unsigned before = atomic_load(&revisions[observed_index(FOCUSER_STEPS_PROPERTY_NAME)]);
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 500, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(new_state(FOCUSER_STEPS_PROPERTY_NAME, before, INDIGO_ALERT_STATE));
	if (strcmp(current_profile, "transport_close")) {
		SERIAL_CHECK_TRUE(at_position(!strcmp(current_profile, "start_failure") || !strcmp(current_profile, "stall") ? 5000 : 5500));
		SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 10, INDIGO_BUSY_STATE));
		SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	}
cleanup:
	driver_stop();
}

static void overlap(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 1000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, optec_focuser.device_name, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 10));
	SERIAL_CHECK_TRUE(at_position(6000));
	SERIAL_CHECK_TRUE(commands("FO") == 1);
cleanup:
	driver_stop();
}

static void disconnect_motion(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, true, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 1000, INDIGO_BUSY_STATE));
	disconnect_serial_device(&optec_focuser);
	SERIAL_CHECK_TRUE(!context.connected);
	int before = commands("FPOSRO");
	indigo_usleep(300000);
	SERIAL_CHECK_TRUE(commands("FPOSRO") == before && commands("FFMODE") == 1);
	SERIAL_CHECK_TRUE(connect_serial_device(&optec_focuser, fixture.port));
cleanup:
	driver_stop();
}

static void reconnect(void) {
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&optec_focuser));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_text_property_1_raw(&simulator_test_client, optec_focuser.device_name, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, "/dev/indigo-optec-missing"));
	SERIAL_CHECK_TRUE(switch_change(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME, true, INDIGO_ALERT_STATE));
	for (int index = 0; index < 3; index++) {
		SERIAL_CHECK_TRUE(connect_serial_device(&optec_focuser, fixture.port));
		disconnect_serial_device(&optec_focuser);
	}
cleanup:
	driver_stop();
}

static void instances(void) {
	static const simulator_driver_case second = { "Optec TCF-S Focuser", "indigo_focuser_optec", "Optec TCF-S #2", indigo_focuser_optec, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0 };
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, optec_focuser.device_name, ADDITIONAL_INSTANCES_PROPERTY_NAME, ADDITIONAL_INSTANCES_COUNT_ITEM_NAME, 1));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(ADDITIONAL_INSTANCES_PROPERTY_NAME, ADDITIONAL_INSTANCES_COUNT_ITEM_NAME, 1, .01));
	SERIAL_CHECK_TRUE(connect_serial_device(&second, second_fixture.port));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1234, .01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, -12, .01));
	disconnect_serial_device(&second);
cleanup:
	disconnect_serial_device(&optec_focuser);
	indigo_change_number_property_1(&simulator_test_client, optec_focuser.device_name, ADDITIONAL_INSTANCES_PROPERTY_NAME, ADDITIONAL_INSTANCES_COUNT_ITEM_NAME, 0);
	driver_stop();
}

static void descriptor_cleanup(void) {
	int before = open_descriptors();
	SERIAL_CHECK_TRUE(driver_start());
	driver_stop();
	SERIAL_CHECK_TRUE(open_descriptors() == before);
cleanup:
	if (context.connected) {
		driver_stop();
	}
}

typedef struct { const char *name; void (*run)(void); const char *profile; } optec_test;

static int run_cases(const optec_test *cases, int count) {
	int failures = 0;
	setvbuf(stdout, NULL, _IOLBF, 0);
	const char *filter = getenv("OPTEC_TEST_FILTER");
	if (!mkdtemp(fixture_dir)) {
		return 1;
	}
	snprintf(event_path, sizeof(event_path), "%s/events", fixture_dir);
	snprintf(fault_path, sizeof(fault_path), "%s/fault", fixture_dir);
	setenv("INDIGO_OPTEC_EVENTS", event_path, 1);
	setenv("INDIGO_OPTEC_FAULT", fault_path, 1);
	for (int index = 0; index < count; index++) {
		if (filter && !strstr(cases[index].name, filter)) {
			continue;
		}
		current_profile = cases[index].profile;
		unlink(fault_path);
		const char *simulator_profile = !strcmp(current_profile, "split") || !strcmp(current_profile, "alternate") || !strcmp(current_profile, "tcf-s") ? current_profile : "normal";
		const char *args[] = { "--profile", simulator_profile, NULL };
		if (!start_external_serial_simulator_with_args(&fixture, FOCUSER_OPTEC_SIMULATOR_EXECUTABLE, args)) {
			failures++;
			break;
		}
		if (!strcmp(cases[index].name, "instances")) {
			unsetenv("INDIGO_OPTEC_EVENTS");
			unsetenv("INDIGO_OPTEC_FAULT");
			const char *second_args[] = { "--profile", "alternate", NULL };
			bool ready = start_external_serial_simulator_with_args(&second_fixture, FOCUSER_OPTEC_SIMULATOR_EXECUTABLE, second_args);
			setenv("INDIGO_OPTEC_EVENTS", event_path, 1);
			setenv("INDIGO_OPTEC_FAULT", fault_path, 1);
			if (!ready) {
				stop_external_serial_simulator(&fixture);
				failures++;
				break;
			}
		}
		fflush(NULL);
		pid_t child = fork();
		if (child == 0) {
			alarm(30);
			indigo_test_case test = { cases[index].name, cases[index].run };
			_exit(indigo_run_tests("Optec", &test, 1));
		}
		int status = 0;
		if (child > 0) {
			while (waitpid(child, &status, 0) < 0 && errno == EINTR) {
			}
		}
		stop_external_serial_simulator(&fixture);
		stop_external_serial_simulator(&second_fixture);
		if (child < 0 || !WIFEXITED(status) || WEXITSTATUS(status)) {
			fprintf(stderr, "FAIL %s (status %d)\n", cases[index].name, status);
			failures++;
		}
	}
	unlink(fault_path);
	unlink(event_path);
	rmdir(fixture_dir);
	unsetenv("INDIGO_OPTEC_EVENTS");
	unsetenv("INDIGO_OPTEC_FAULT");
	printf("Optec: %d failing scenarios\n", failures);
	return failures ? 1 : 0;
}

int main(void) {
	simulator_test_client.update_property = observe_update;
	const optec_test tests[] = {
		{ "simulator_protocol", simulator_protocol, "normal" }, { "simulator_split", simulator_protocol, "split" },
		{ "simulator_automatic_compensation", simulator_automatic_compensation, "normal" },
		{ "simulator_rejections", simulator_rejections, "tcf-s" },
		{ "capabilities", capabilities, "normal" }, { "capabilities_split", capabilities, "split" }, { "capabilities_alternate", capabilities, "alternate" },
		{ "relative_motion", relative_motion, "normal" }, { "controls", controls, "normal" },
		{ "init_handshake_silent", rejected_connection, "handshake_silent" }, { "init_position_malformed", rejected_connection, "position_malformed" },
		{ "init_position_partial", rejected_connection, "position_partial" }, { "init_position_overlong", rejected_connection, "position_overlong" },
		{ "init_position_error", rejected_connection, "position_error" }, { "init_temperature_malformed", rejected_connection, "temperature_malformed" },
		{ "init_slope_malformed", rejected_connection, "slope_malformed" }, { "init_sign_malformed", rejected_connection, "sign_malformed" },
		{ "poll_position_malformed", poll_failure, "position_poll" }, { "poll_position_partial", poll_failure, "position_partial_poll" },
		{ "poll_position_overlong", poll_failure, "position_overlong_poll" }, { "poll_temperature_malformed", poll_failure, "temperature_poll" },
		{ "compensation_partial_failure", compensation_failure, "normal" }, { "mode_failure", mode_failure, "normal" },
		{ "motion_start_failure", motion_failure, "start_failure" }, { "motion_poll_failure", motion_failure, "poll_failure" },
		{ "motion_stall", motion_failure, "stall" }, { "motion_transport_close", motion_failure, "transport_close" },
		{ "overlap", overlap, "normal" }, { "disconnect_motion", disconnect_motion, "normal" },
		{ "reconnect", reconnect, "normal" }, { "instances", instances, "normal" }, { "descriptor_cleanup", descriptor_cleanup, "normal" }
	};
	return run_cases(tests, ARRAY_SIZE(tests));
}
