// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// AUX powerbox coverage for indigo_aux_uch against the standalone Pegasus USB Control Hub simulator
// over a real PTY. The hub switches six USB ports and reports supply voltage and uptime from a
// periodic "PA" status frame. Port state is owned by the device: the poll mirrors it back into
// AUX_USB_PORT, so a switch request has to be confirmed by the following status frame rather than
// by the driver echoing the request.

#include <indigo_drivers/aux_uch/indigo_aux_uch.h>

#include "serial_simulator_test_common.h"

#ifndef AUX_UCH_SIMULATOR_EXECUTABLE
#define AUX_UCH_SIMULATOR_EXECUTABLE "build/integration/aux_uch_simulator"
#endif

static const simulator_driver_case uch_case = {
	"PegasusAstro USB Control Hub",
	"indigo_aux_uch",
	"USB Control Hub",
	indigo_aux_uch,
	false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static const char *const usb_items[] = {
	AUX_USB_PORT_1_ITEM_NAME, AUX_USB_PORT_2_ITEM_NAME, AUX_USB_PORT_3_ITEM_NAME,
	AUX_USB_PORT_4_ITEM_NAME, AUX_USB_PORT_5_ITEM_NAME, AUX_USB_PORT_6_ITEM_NAME
};

static const char *info_text(const char *item_name) {
	indigo_item *item = find_cached_item(INFO_PROPERTY_NAME, item_name);
	return item == NULL ? "" : item->text.value;
}

static bool set_port(const char *item, bool value) {
	return indigo_change_switch_property_1(&simulator_test_client, uch_case.device_name, AUX_USB_PORT_PROPERTY_NAME, item, value) == INDIGO_OK;
}

// AUX_INFO is defined with zeroed items at attach, so its state says nothing about whether a status
// frame has arrived. The supply voltage is only ever written by a completed poll.
static bool wait_for_first_poll(void) {
	for (int i = 0; i < 500; i++) {
		if (cached_number_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME) > 0) {
			return true;
		}
		indigo_usleep(10000);
	}
	return false;
}

// The poll mirrors the device's own port state back, so a request is only confirmed once the status
// frame agrees with it. The property must also have left BUSY: INDIGO_COPY_VALUES_PROCESS_CHANGE
// drops a change that arrives while the previous one is still running, so a test that issues the
// next request as soon as the item value looks right would silently lose it.
static bool wait_for_port(const char *item, bool value) {
	for (int i = 0; i < 500; i++) {
		indigo_property *property = find_cached_property(AUX_USB_PORT_PROPERTY_NAME);
		indigo_item *port = find_cached_item(AUX_USB_PORT_PROPERTY_NAME, item);
		if (property != NULL && property->state != INDIGO_BUSY_STATE && port != NULL && port->sw.value == value) {
			return true;
		}
		indigo_usleep(10000);
	}
	return false;
}

// -------------------------------------------------------------------------------- metadata

static void metadata_identity_and_property_completeness(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(context.connected && context.last_connection_state == INDIGO_OK_STATE);
	assert_device_interface(INDIGO_INTERFACE_AUX_POWERBOX);
	static const char *properties[] = {
		AUX_OUTLET_NAMES_PROPERTY_NAME,
		AUX_USB_PORT_PROPERTY_NAME,
		AUX_INFO_PROPERTY_NAME,
		"X_AUX_REBOOT",
		AUX_SAVE_OUTLET_STATES_AS_DEFAULT_PROPERTY_NAME
	};
	assert_defined_properties(properties, ARRAY_SIZE(properties));
	assert_property_has_items(AUX_USB_PORT_PROPERTY_NAME, usb_items, ARRAY_SIZE(usb_items));
	assert_property_has_item(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME);
	assert_property_has_item(AUX_INFO_PROPERTY_NAME, "UPTIME");
	// A USB hub has no switched mains outlets, no heaters and no environment sensors.
	assert_not_defined_property(AUX_POWER_OUTLET_PROPERTY_NAME);
	assert_not_defined_property(AUX_HEATER_OUTLET_PROPERTY_NAME);
	assert_not_defined_property(AUX_WEATHER_PROPERTY_NAME);
	printf("Model '%s' firmware '%s'\n", info_text(INFO_DEVICE_MODEL_ITEM_NAME), info_text(INFO_DEVICE_FW_REVISION_ITEM_NAME));
	SERIAL_CHECK_TRUE(strcmp(info_text(INFO_DEVICE_MODEL_ITEM_NAME), "Unknown") != 0);
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- telemetry

static void status_frame_reports_voltage_and_uptime(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	printf("Supply %g V, uptime %g\n", cached_number_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME), cached_number_value(AUX_INFO_PROPERTY_NAME, "UPTIME"));
	SERIAL_CHECK_TRUE(cached_number_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME) > 0);
	SERIAL_CHECK_TRUE(cached_number_value(AUX_INFO_PROPERTY_NAME, "UPTIME") >= 0);
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- ports

// Each of the six ports occupies its own character in the status frame, so all of them are switched
// individually in both directions and confirmed from the device's own report.
static void every_usb_port_switches(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	for (int i = 0; i < ARRAY_SIZE(usb_items); i++) {
		SERIAL_CHECK_TRUE(set_port(usb_items[i], false));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(wait_for_port(usb_items[i], false));
	}
	for (int i = 0; i < ARRAY_SIZE(usb_items); i++) {
		SERIAL_CHECK_TRUE(set_port(usb_items[i], true));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(wait_for_port(usb_items[i], true));
	}
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

// Switching several ports in one request must not disturb the ports it does not name.
static void switching_one_port_leaves_the_others_alone(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(set_port(AUX_USB_PORT_3_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_port(AUX_USB_PORT_3_ITEM_NAME, false));
	for (int i = 0; i < ARRAY_SIZE(usb_items); i++) {
		if (i == 2) {
			continue;
		}
		SERIAL_CHECK_TRUE(wait_for_port(usb_items[i], true));
	}
	SERIAL_CHECK_TRUE(set_port(AUX_USB_PORT_3_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_port(AUX_USB_PORT_3_ITEM_NAME, true));
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- driver actions

// A status frame that was already in flight when a change was accepted must not
// overwrite the requested port state: the queued handler would then send the stale
// state back to the hub and the port would silently revert. The simulator holds its
// status reply so the request lands inside that window every time.
static void a_change_survives_a_status_frame_in_flight(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	const char *arguments[] = { "--slow-status", "700", NULL };
	SERIAL_CHECK_TRUE(start_external_serial_simulator_with_args(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	for (int attempt = 0; attempt < 4; attempt++) {
		bool target = attempt % 2 == 0 ? false : true;
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(set_port(usb_items[0], target));
		SERIAL_CHECK_TRUE(wait_for_port(usb_items[0], target));
		// Give the poll that was in flight time to publish before the value is trusted.
		indigo_usleep(1500000);
		SERIAL_CHECK_TRUE(wait_for_port(usb_items[0], target));
	}
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

static void saving_the_defaults_is_accepted(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_switch_property_1(&simulator_test_client, uch_case.device_name, AUX_SAVE_OUTLET_STATES_AS_DEFAULT_PROPERTY_NAME, AUX_SAVE_OUTLET_STATES_AS_DEFAULT_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_SAVE_OUTLET_STATES_AS_DEFAULT_PROPERTY_NAME, INDIGO_OK_STATE));
	// The hub has to stay usable afterwards.
	SERIAL_CHECK_TRUE(set_port(AUX_USB_PORT_1_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_port(AUX_USB_PORT_1_ITEM_NAME, false));
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

// The reboot switch is momentary: it has to settle back rather than stay latched.
static void reboot_request_is_accepted_and_resets(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_switch_property_1(&simulator_test_client, uch_case.device_name, "X_AUX_REBOOT", "REBOOT", true));
	SERIAL_CHECK_TRUE(wait_for_property_state("X_AUX_REBOOT", INDIGO_OK_STATE));
	assert_switch_item_value("X_AUX_REBOOT", "REBOOT", false);
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

static void outlet_names_are_writable(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	indigo_property *names = find_cached_property(AUX_OUTLET_NAMES_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(names != NULL && names->count > 0);
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_text_property_1_raw(&simulator_test_client, uch_case.device_name, AUX_OUTLET_NAMES_PROPERTY_NAME, names->items[0].name, "Mount"));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_OUTLET_NAMES_PROPERTY_NAME, INDIGO_OK_STATE));
	indigo_item *renamed = find_cached_item(AUX_OUTLET_NAMES_PROPERTY_NAME, names->items[0].name);
	SERIAL_CHECK_TRUE(renamed != NULL && !strcmp(renamed->text.value, "Mount"));
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- lifecycle

static void reconnect_resumes_polling(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	disconnect_serial_device(&uch_case);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connect_serial_device(&uch_case, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(set_port(AUX_USB_PORT_2_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_port(AUX_USB_PORT_2_ITEM_NAME, false));
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

static void repeated_disconnect_is_tolerated(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(start_serial_driver(&uch_case, simulator.port));
	online = true;
	disconnect_serial_device(&uch_case);
	SERIAL_CHECK_TRUE(!context.connected);
	disconnect_serial_device(&uch_case);
	SERIAL_CHECK_TRUE(!context.connected);
	online = false;
	tear_down_serial_driver(&uch_case);
cleanup:
	if (online) { stop_serial_driver(&uch_case); }
	stop_external_serial_simulator(&simulator);
}

// "P#" must answer UCH_OK; without any reply the open has to roll back.
static void silent_port_is_refused(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_external_serial_simulator(&simulator, AUX_UCH_SIMULATOR_EXECUTABLE));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&uch_case));
	stop_external_serial_simulator(&simulator);
	SERIAL_CHECK_TRUE(!connect_serial_device(&uch_case, simulator.port));
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&uch_case);
}

int main(void) {
	const indigo_test_case tests[] = {
		{ "metadata_identity_and_property_completeness", metadata_identity_and_property_completeness },
		{ "status_frame_reports_voltage_and_uptime", status_frame_reports_voltage_and_uptime },
		{ "every_usb_port_switches", every_usb_port_switches },
		{ "switching_one_port_leaves_the_others_alone", switching_one_port_leaves_the_others_alone },
		{ "a_change_survives_a_status_frame_in_flight", a_change_survives_a_status_frame_in_flight },
		{ "saving_the_defaults_is_accepted", saving_the_defaults_is_accepted },
		{ "reboot_request_is_accepted_and_resets", reboot_request_is_accepted_and_resets },
		{ "outlet_names_are_writable", outlet_names_are_writable },
		{ "reconnect_resumes_polling", reconnect_resumes_polling },
		{ "repeated_disconnect_is_tolerated", repeated_disconnect_is_tolerated },
		{ "silent_port_is_refused", silent_port_is_refused }
	};
	return indigo_run_tests("USB Control Hub serial simulator integration tests", tests, ARRAY_SIZE(tests));
}
