// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// AUX powerbox coverage for indigo_aux_wbprov3 against the standalone WandererBox Pro V3 simulator
// over a real PTY. Like the Plus V3 the box never acknowledges a command, it only broadcasts an
// "A"-separated status frame once a second, so every command is verified through the next frame.
// The Pro V3 is the wide variant: three switched outlet groups, five USB groups, three heaters and
// four temperature sensors, all of which are driven from a single handler per property. That makes
// crosstalk between channels the failure worth hunting, so most scenarios move one channel and
// assert that its neighbours stayed put.

#include <indigo/indigo_aux_driver.h>

#include <indigo_drivers/aux_wbprov3/indigo_aux_wbprov3.h>

#include "serial_simulator_test_common.h"

#ifndef AUX_WBPROV3_SIMULATOR_EXECUTABLE
#define AUX_WBPROV3_SIMULATOR_EXECUTABLE "build/integration/aux_wbprov3_simulator"
#endif

#define X_AUX_CALIBRATE_PROPERTY_NAME "X_AUX_CALIBRATE"
#define X_AUX_CALIBRATE_ITEM_NAME     "CALIBRATE"

// The simulator's compiled-in sensor readings. The status frame carries the three probes before the
// humidity, and the DHT22 temperature only after it, so the five temperatures are easy to mix up.
#define SIMULATED_PROBE_1_TEMPERATURE  23.94
#define SIMULATED_PROBE_2_TEMPERATURE  24.70
#define SIMULATED_PROBE_3_TEMPERATURE  25.70
#define SIMULATED_DHT22_HUMIDITY       36.90
#define SIMULATED_DHT22_TEMPERATURE    26.70
#define SIMULATED_INPUT_CURRENT        12.32
#define SIMULATED_19V_CURRENT          4.08
#define SIMULATED_5V_12V_CURRENT       3.91
#define SIMULATED_VOLTAGE              12.11

static const simulator_driver_case wbprov3_aux = {
	"WandererBox Pro V3 Powerbox",
	"indigo_aux_wbprov3",
	"WandererBox Pro V3",
	indigo_aux_wbprov3,
	false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static bool start_wbprov3(external_serial_simulator *simulator, const char * const *arguments) {
	if (arguments == NULL) {
		return start_external_serial_simulator(simulator, AUX_WBPROV3_SIMULATOR_EXECUTABLE);
	}
	return start_external_serial_simulator_with_args(simulator, AUX_WBPROV3_SIMULATOR_EXECUTABLE, arguments);
}

static double number_of(const char *property_name, const char *item_name) {
	return cached_number_value(property_name, item_name);
}

static const char *info_text(const char *item_name) {
	indigo_item *item = find_cached_item(INFO_PROPERTY_NAME, item_name);
	return item == NULL ? "" : item->text.value;
}

static const char *item_label(const char *property_name, const char *item_name) {
	indigo_item *item = find_cached_item(property_name, item_name);
	return item == NULL ? "" : item->label;
}

// AUX_INFO is defined with zeroed items at attach, so its state says nothing about whether a status
// frame has arrived. The supply voltage is only ever written by a completed poll.
static bool wait_for_first_poll(void) {
	for (int i = 0; i < 500; i++) {
		if (number_of(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME) > 0) {
			return true;
		}
		indigo_usleep(10000);
	}
	return false;
}

// A command is only visible once the device has echoed it back in a status frame, and the poll
// refuses to touch a property that is still BUSY, so both conditions have to hold.
static bool wait_for_switch(const char *property_name, const char *item_name, bool value) {
	for (int i = 0; i < 500; i++) {
		indigo_property *property = find_cached_property(property_name);
		indigo_item *item = find_cached_item(property_name, item_name);
		if (property != NULL && property->state != INDIGO_BUSY_STATE && item != NULL && item->sw.value == value) {
			return true;
		}
		indigo_usleep(10000);
	}
	return false;
}

static bool wait_for_number(const char *property_name, const char *item_name, double value, double tolerance) {
	for (int i = 0; i < 500; i++) {
		indigo_property *property = find_cached_property(property_name);
		if (property != NULL && property->state != INDIGO_BUSY_STATE && fabs(number_of(property_name, item_name) - value) <= tolerance) {
			return true;
		}
		indigo_usleep(10000);
	}
	return false;
}

static bool set_switch(const char *property_name, const char *item_name, bool value) {
	return indigo_change_switch_property_1(&simulator_test_client, wbprov3_aux.device_name, property_name, item_name, value) == INDIGO_OK;
}

static bool set_number(const char *property_name, const char *item_name, double value) {
	return indigo_change_number_property_1(&simulator_test_client, wbprov3_aux.device_name, property_name, item_name, value) == INDIGO_OK;
}

static const char *power_outlet_items[] = { AUX_POWER_OUTLET_1_ITEM_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, AUX_POWER_OUTLET_3_ITEM_NAME };
static const char *usb_port_items[] = { AUX_USB_PORT_1_ITEM_NAME, AUX_USB_PORT_2_ITEM_NAME, AUX_USB_PORT_3_ITEM_NAME, AUX_USB_PORT_4_ITEM_NAME, AUX_USB_PORT_5_ITEM_NAME };
static const char *heater_items[] = { AUX_HEATER_OUTLET_1_ITEM_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME, AUX_HEATER_OUTLET_3_ITEM_NAME };

// -------------------------------------------------------------------------------- metadata

static void metadata_and_property_completeness(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(context.connected && context.last_connection_state == INDIGO_OK_STATE);

	assert_device_interface(INDIGO_INTERFACE_AUX_POWERBOX | INDIGO_INTERFACE_AUX_WEATHER);
	assert_serial_aux_class_property_completeness();

	// The Pro V3 exposes every channel group the wide protocol defines; a missing item here means a
	// channel the user cannot reach at all.
	assert_property_has_items(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items, ARRAY_SIZE(power_outlet_items));
	assert_property_has_items(AUX_USB_PORT_PROPERTY_NAME, usb_port_items, ARRAY_SIZE(usb_port_items));
	assert_property_has_items(AUX_HEATER_OUTLET_PROPERTY_NAME, heater_items, ARRAY_SIZE(heater_items));
	static const char *outlet_name_items[] = {
		AUX_POWER_OUTLET_NAME_1_ITEM_NAME, AUX_POWER_OUTLET_NAME_2_ITEM_NAME, AUX_POWER_OUTLET_NAME_3_ITEM_NAME,
		AUX_HEATER_OUTLET_NAME_1_ITEM_NAME, AUX_HEATER_OUTLET_NAME_2_ITEM_NAME, AUX_HEATER_OUTLET_NAME_3_ITEM_NAME
	};
	assert_property_has_items(AUX_OUTLET_NAMES_PROPERTY_NAME, outlet_name_items, ARRAY_SIZE(outlet_name_items));
	static const char *temperature_items[] = {
		AUX_TEMPERATURE_SENSORS_SENSOR_1_ITEM_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME,
		AUX_TEMPERATURE_SENSORS_SENSOR_3_ITEM_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_4_ITEM_NAME
	};
	assert_property_has_items(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, temperature_items, ARRAY_SIZE(temperature_items));
	assert_property_has_item(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME);
	assert_property_has_item(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME, AUX_POWER_OUTLET_CURRENT_1_ITEM_NAME);
	assert_property_has_item(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME, AUX_POWER_OUTLET_CURRENT_2_ITEM_NAME);
	assert_property_has_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME);
	assert_property_has_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME);
	assert_property_has_item(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME);
	assert_property_has_item(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME);
	assert_property_has_item(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_DEWPOINT_ITEM_NAME);
	assert_property_has_item(AUX_DEW_WARNING_PROPERTY_NAME, AUX_DEW_WARNING_SENSOR_1_ITEM_NAME);
	assert_property_has_item(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME);
	assert_property_has_item(AUX_INFO_PROPERTY_NAME, AUX_INFO_CURRENT_ITEM_NAME);
	assert_property_has_item(X_AUX_CALIBRATE_PROPERTY_NAME, X_AUX_CALIBRATE_ITEM_NAME);

	// Read-only sensor properties must not be presented as settable.
	indigo_property *property = find_cached_property(AUX_WEATHER_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(property != NULL && property->perm == INDIGO_RO_PERM);
	property = find_cached_property(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(property != NULL && property->perm == INDIGO_RO_PERM);
	property = find_cached_property(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(property != NULL && property->perm == INDIGO_RO_PERM);
	property = find_cached_property(AUX_INFO_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(property != NULL && property->perm == INDIGO_RO_PERM);

	property = find_cached_property(AUX_POWER_OUTLET_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(property != NULL && property->rule == INDIGO_ANY_OF_MANY_RULE && property->count == 3);
	property = find_cached_property(AUX_USB_PORT_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(property != NULL && property->rule == INDIGO_ANY_OF_MANY_RULE && property->count == 5);
	// Only DC3-DC4 is regulated, so there is exactly one voltage control.
	property = find_cached_property(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(property != NULL && property->count == 1);
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

static void identity_and_firmware_reach_info(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	const char *arguments[] = { "--firmware", "20240607", NULL };
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	indigo_property *info = find_cached_property(INFO_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(info != NULL && info->count >= 6);
	printf("INFO model='%s' firmware='%s'\n", info_text(INFO_DEVICE_MODEL_ITEM_NAME), info_text(INFO_DEVICE_FW_REVISION_ITEM_NAME));
	SERIAL_CHECK_TRUE(!strcmp(info_text(INFO_DEVICE_MODEL_ITEM_NAME), "ZXWBProV3"));
	SERIAL_CHECK_TRUE(!strcmp(info_text(INFO_DEVICE_FW_REVISION_ITEM_NAME), "20240607"));
	disconnect_serial_device(&wbprov3_aux);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(!strcmp(info_text(INFO_DEVICE_MODEL_ITEM_NAME), "Unknown"));
	SERIAL_CHECK_TRUE(!strcmp(info_text(INFO_DEVICE_FW_REVISION_ITEM_NAME), "Unknown"));
	online = false;
	tear_down_serial_driver(&wbprov3_aux);
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- sensors

// Five distinct temperatures arrive in one frame and are fanned out to two properties, so every
// value is checked against the one sensor it belongs to.
static void status_frame_populates_every_sensor(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	printf("DHT22 %g C / %g %%RH, probes %g / %g / %g C\n",
		number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME),
		number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME),
		number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME),
		number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_3_ITEM_NAME),
		number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_4_ITEM_NAME));
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME) - SIMULATED_DHT22_TEMPERATURE) < .005);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME) - SIMULATED_DHT22_HUMIDITY) < .005);
	// Sensor 1 is the DHT22, sensors 2-4 the three separate probes, in frame order.
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_1_ITEM_NAME) - SIMULATED_DHT22_TEMPERATURE) < .005);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_2_ITEM_NAME) - SIMULATED_PROBE_1_TEMPERATURE) < .005);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_3_ITEM_NAME) - SIMULATED_PROBE_2_TEMPERATURE) < .005);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, AUX_TEMPERATURE_SENSORS_SENSOR_4_ITEM_NAME) - SIMULATED_PROBE_3_TEMPERATURE) < .005);
	// Three currents arrive in the same frame; the input current must not be reported as an outlet
	// current, which is the mistake the near-identical field names invite.
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME) - SIMULATED_VOLTAGE) < .005);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_INFO_PROPERTY_NAME, AUX_INFO_CURRENT_ITEM_NAME) - SIMULATED_INPUT_CURRENT) < .005);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME, AUX_POWER_OUTLET_CURRENT_1_ITEM_NAME) - SIMULATED_19V_CURRENT) < .005);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME, AUX_POWER_OUTLET_CURRENT_2_ITEM_NAME) - SIMULATED_5V_12V_CURRENT) < .005);
	double expected_dewpoint = indigo_aux_dewpoint(SIMULATED_DHT22_TEMPERATURE, SIMULATED_DHT22_HUMIDITY);
	printf("Dewpoint %g C (expected %g C)\n", number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_DEWPOINT_ITEM_NAME), expected_dewpoint);
	SERIAL_CHECK_TRUE(fabs(number_of(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_DEWPOINT_ITEM_NAME) - expected_dewpoint) < .01);
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_WEATHER_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_TEMPERATURE_SENSORS_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

static void dew_warning_is_clear_in_dry_air(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_DEW_WARNING_PROPERTY_NAME, INDIGO_OK_STATE));
	indigo_item *warning = find_cached_item(AUX_DEW_WARNING_PROPERTY_NAME, AUX_DEW_WARNING_SENSOR_1_ITEM_NAME);
	SERIAL_CHECK_TRUE(warning != NULL);
	printf("Dew warning light state %d\n", warning->light.value);
	SERIAL_CHECK_EQ_INT(INDIGO_OK_STATE, warning->light.value);
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- outlets

// Every switch item is seeded true at attach while the device boots with everything off, so the
// first status frame has to overwrite all eight seeds rather than the driver trusting its defaults.
static void first_status_frame_overrides_the_seeded_outlet_state(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	for (int i = 0; i < ARRAY_SIZE(power_outlet_items); i++) {
		SERIAL_CHECK_TRUE(wait_for_switch(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items[i], false));
	}
	for (int i = 0; i < ARRAY_SIZE(usb_port_items); i++) {
		SERIAL_CHECK_TRUE(wait_for_switch(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], false));
	}
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// One change writes all three outlet commands, so a swapped or duplicated command shows up as a
// neighbour moving with the channel under test.
static void each_power_outlet_switches_on_its_own(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, false));
	for (int i = 0; i < ARRAY_SIZE(power_outlet_items); i++) {
		SERIAL_CHECK_TRUE(set_switch(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items[i], true));
		SERIAL_CHECK_TRUE(wait_for_switch(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items[i], true));
		for (int j = 0; j < ARRAY_SIZE(power_outlet_items); j++) {
			assert_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items[j], j <= i);
		}
	}
	// And back down again, one at a time, from the other end.
	for (int i = ARRAY_SIZE(power_outlet_items) - 1; i >= 0; i--) {
		SERIAL_CHECK_TRUE(set_switch(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items[i], false));
		SERIAL_CHECK_TRUE(wait_for_switch(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items[i], false));
		for (int j = 0; j < ARRAY_SIZE(power_outlet_items); j++) {
			assert_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, power_outlet_items[j], j < i);
		}
	}
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// The five USB groups share one handler that writes five commands; each has its own command pair.
static void each_usb_group_switches_on_its_own(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_USB_PORT_PROPERTY_NAME, AUX_USB_PORT_1_ITEM_NAME, false));
	for (int i = 0; i < ARRAY_SIZE(usb_port_items); i++) {
		SERIAL_CHECK_TRUE(set_switch(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], true));
		SERIAL_CHECK_TRUE(wait_for_switch(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], true));
		for (int j = 0; j < ARRAY_SIZE(usb_port_items); j++) {
			assert_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[j], j <= i);
		}
	}
	SERIAL_CHECK_TRUE(set_switch(AUX_USB_PORT_PROPERTY_NAME, AUX_USB_PORT_3_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_USB_PORT_PROPERTY_NAME, AUX_USB_PORT_3_ITEM_NAME, false));
	assert_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, AUX_USB_PORT_2_ITEM_NAME, true);
	assert_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, AUX_USB_PORT_4_ITEM_NAME, true);
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

static void regulated_outlet_voltage_round_trips(void) {
	static const double requests[] = { 0.0, 3.5, 12.0, 13.2 };
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	for (int i = 0; i < ARRAY_SIZE(requests); i++) {
		SERIAL_CHECK_TRUE(set_number(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME, requests[i]));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(wait_for_number(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME, requests[i], .001));
		printf("Requested %.2f V, device reports %.2f V\n", requests[i], number_of(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME));
	}
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// Each heater has its own command range, and one change writes all three, so setting them to three
// different duty cycles at once is the scenario that catches a channel writing another's value.
static void heaters_hold_independent_duty_cycles(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	// The percentage is quantised to an 8 bit PWM, so each duty cycle read back is the nearest
	// representable step. Asserting the nearest step rather than a one-step tolerance is what keeps
	// the conversion honest: truncating instead of rounding (DRV-205) lands a step low for every
	// request that does not fall exactly on a step. 60 and 100 land exactly on steps 153 and 255,
	// so 25 is the one carrying that part of the check: it falls between steps 63 and 64.
	static const char *items[] = { AUX_HEATER_OUTLET_1_ITEM_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME, AUX_HEATER_OUTLET_3_ITEM_NAME };
	static const double values[] = { 25, 60, 100 };
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property(&simulator_test_client, wbprov3_aux.device_name, AUX_HEATER_OUTLET_PROPERTY_NAME, 3, items, values));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_HEATER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
	for (int i = 0; i < ARRAY_SIZE(items); i++) {
		double expected = round(values[i] * 255.0 / 100.0) / 255.0 * 100.0;
		SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, items[i], expected, .01));
		printf("Heater %d requested %.0f %%, device reports %.2f %% (nearest step %.2f %%)\n", i + 1, values[i], number_of(AUX_HEATER_OUTLET_PROPERTY_NAME, items[i]), expected);
	}
	// Moving one heater must leave the other two where they were.
	SERIAL_CHECK_TRUE(set_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME, 0));
	SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME, 0, .001));
	SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME, round(25 * 255.0 / 100.0) / 255.0 * 100.0, .01));
	SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_3_ITEM_NAME, 100, .001));
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- dew control

static void manual_heater_change_leaves_automatic_mode(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(set_switch(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(set_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_3_ITEM_NAME, 40));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_HEATER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true));
	assert_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, false);
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// The simulated air is dry, so automatic mode has to shut every running heater down, not just the
// first one.
static void automatic_dew_control_stops_all_heaters_in_dry_air(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	static const char *items[] = { AUX_HEATER_OUTLET_1_ITEM_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME, AUX_HEATER_OUTLET_3_ITEM_NAME };
	static const double values[] = { 100, 100, 100 };
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property(&simulator_test_client, wbprov3_aux.device_name, AUX_HEATER_OUTLET_PROPERTY_NAME, 3, items, values));
	for (int i = 0; i < ARRAY_SIZE(items); i++) {
		SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, items[i], 100, .001));
	}
	SERIAL_CHECK_TRUE(set_switch(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	for (int i = 0; i < ARRAY_SIZE(items); i++) {
		SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, items[i], 0, .001));
	}
	// Shutting the heaters down is the regulator's own decision and must not flip the mode back.
	assert_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true);
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- misc

static void outlet_names_relabel_the_controls(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	static const char *items[] = {
		AUX_POWER_OUTLET_NAME_1_ITEM_NAME, AUX_POWER_OUTLET_NAME_2_ITEM_NAME, AUX_POWER_OUTLET_NAME_3_ITEM_NAME,
		AUX_HEATER_OUTLET_NAME_1_ITEM_NAME, AUX_HEATER_OUTLET_NAME_2_ITEM_NAME, AUX_HEATER_OUTLET_NAME_3_ITEM_NAME
	};
	static const char *values[] = { "Mount", "Cameras", "Dome", "Corrector", "Guider", "Finder" };
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_text_property(&simulator_test_client, wbprov3_aux.device_name, AUX_OUTLET_NAMES_PROPERTY_NAME, ARRAY_SIZE(items), items, values));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_OUTLET_NAMES_PROPERTY_NAME, INDIGO_OK_STATE));
	for (int i = 0; i < 500; i++) {
		if (strstr(item_label(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME), "Mount") != NULL) {
			break;
		}
		indigo_usleep(10000);
	}
	SERIAL_CHECK_TRUE(strstr(item_label(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME), "Mount") != NULL);
	SERIAL_CHECK_TRUE(strstr(item_label(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME), "Cameras") != NULL);
	SERIAL_CHECK_TRUE(strstr(item_label(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME), "Dome") != NULL);
	// The regulated outlet's voltage control carries the same user name as the outlet itself.
	SERIAL_CHECK_TRUE(strstr(item_label(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME), "Mount") != NULL);
	SERIAL_CHECK_TRUE(strstr(item_label(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME), "Corrector") != NULL);
	SERIAL_CHECK_TRUE(strstr(item_label(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME), "Guider") != NULL);
	SERIAL_CHECK_TRUE(strstr(item_label(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_3_ITEM_NAME), "Finder") != NULL);
	printf("Labels: '%s' / '%s' / '%s' / '%s' / '%s' / '%s'\n",
		item_label(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME),
		item_label(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME),
		item_label(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME),
		item_label(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME),
		item_label(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME),
		item_label(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_3_ITEM_NAME));
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

static void calibration_switch_is_momentary(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(set_switch(X_AUX_CALIBRATE_PROPERTY_NAME, X_AUX_CALIBRATE_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(X_AUX_CALIBRATE_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch(X_AUX_CALIBRATE_PROPERTY_NAME, X_AUX_CALIBRATE_ITEM_NAME, false));
	// The device keeps running afterwards.
	SERIAL_CHECK_TRUE(set_switch(AUX_USB_PORT_PROPERTY_NAME, AUX_USB_PORT_1_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_USB_PORT_PROPERTY_NAME, AUX_USB_PORT_1_ITEM_NAME, true));
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

static void out_of_range_requests_are_clamped_before_they_reach_the_device(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	// The bus clamps a number change to the item range before the driver ever sees it, so an
	// over-range request has to arrive at the device as the limit, not as an out-of-range command.
	SERIAL_CHECK_TRUE(set_number(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME, 15.0));
	SERIAL_CHECK_TRUE(wait_for_number(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME, 13.2, .001));
	SERIAL_CHECK_TRUE(set_number(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME, -1.0));
	SERIAL_CHECK_TRUE(wait_for_number(AUX_POWER_OUTLET_VOLTAGE_PROPERTY_NAME, AUX_POWER_OUTLET_VOLTAGE_1_ITEM_NAME, 0, .001));
	SERIAL_CHECK_TRUE(set_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME, 120.0));
	SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME, 100, .001));
	SERIAL_CHECK_TRUE(set_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME, -5.0));
	SERIAL_CHECK_TRUE(wait_for_number(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME, 0, .001));
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// -------------------------------------------------------------------------------- lifecycle

static void reconnect_resumes_polling(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	SERIAL_CHECK_TRUE(set_switch(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, true));
	disconnect_serial_device(&wbprov3_aux);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connect_serial_device(&wbprov3_aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_first_poll());
	// The device kept the outlet on across the reconnect, and the driver has to report what it finds
	// rather than the seeded defaults.
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, true));
	assert_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, false);
	SERIAL_CHECK_TRUE(!strcmp(info_text(INFO_DEVICE_MODEL_ITEM_NAME), "ZXWBProV3"));
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

static void repeated_disconnect_is_tolerated(void) {
	external_serial_simulator simulator = { 0 };
	bool online = false;
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&wbprov3_aux, simulator.port));
	online = true;
	disconnect_serial_device(&wbprov3_aux);
	SERIAL_CHECK_TRUE(!context.connected);
	disconnect_serial_device(&wbprov3_aux);
	SERIAL_CHECK_TRUE(!context.connected);
	online = false;
	tear_down_serial_driver(&wbprov3_aux);
cleanup:
	if (online) { stop_serial_driver(&wbprov3_aux); }
	stop_external_serial_simulator(&simulator);
}

// The open only succeeds once a status frame identifies the box, so a port with nothing behind it
// has to be refused rather than reported as a connected powerbox.
static void vanished_port_is_refused(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_wbprov3(&simulator, NULL));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&wbprov3_aux));
	stop_external_serial_simulator(&simulator);
	SERIAL_CHECK_TRUE(!connect_serial_device(&wbprov3_aux, simulator.port));
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&wbprov3_aux);
}

int main(void) {
	const indigo_test_case tests[] = {
		{ "metadata_and_property_completeness", metadata_and_property_completeness },
		{ "identity_and_firmware_reach_info", identity_and_firmware_reach_info },
		{ "status_frame_populates_every_sensor", status_frame_populates_every_sensor },
		{ "dew_warning_is_clear_in_dry_air", dew_warning_is_clear_in_dry_air },
		{ "first_status_frame_overrides_the_seeded_outlet_state", first_status_frame_overrides_the_seeded_outlet_state },
		{ "each_power_outlet_switches_on_its_own", each_power_outlet_switches_on_its_own },
		{ "each_usb_group_switches_on_its_own", each_usb_group_switches_on_its_own },
		{ "regulated_outlet_voltage_round_trips", regulated_outlet_voltage_round_trips },
		{ "heaters_hold_independent_duty_cycles", heaters_hold_independent_duty_cycles },
		{ "manual_heater_change_leaves_automatic_mode", manual_heater_change_leaves_automatic_mode },
		{ "automatic_dew_control_stops_all_heaters_in_dry_air", automatic_dew_control_stops_all_heaters_in_dry_air },
		{ "outlet_names_relabel_the_controls", outlet_names_relabel_the_controls },
		{ "calibration_switch_is_momentary", calibration_switch_is_momentary },
		{ "out_of_range_requests_are_clamped_before_they_reach_the_device", out_of_range_requests_are_clamped_before_they_reach_the_device },
		{ "reconnect_resumes_polling", reconnect_resumes_polling },
		{ "repeated_disconnect_is_tolerated", repeated_disconnect_is_tolerated },
		{ "vanished_port_is_refused", vanished_port_is_refused }
	};
	return indigo_run_tests("WandererBox Pro V3 serial simulator integration tests", tests, ARRAY_SIZE(tests));
}
