// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

#include <indigo/indigo_wheel_driver.h>
#include <indigo_drivers/wheel_fli/indigo_wheel_fli.h>

#include "fli_fake_sdk.h"
#include "fli_sdk_test_common.h"

static const char *observed_names[] = {
	CONNECTION_PROPERTY_NAME,
	WHEEL_SLOT_PROPERTY_NAME,
	WHEEL_SLOT_NAME_PROPERTY_NAME,
	INFO_PROPERTY_NAME
};

// ----------------------------------------------------------------- scenarios

static void driver_metadata(void) {
	indigo_driver_info info;
	memset(&info, 0, sizeof(info));
	ASSERT_EQ_INT(INDIGO_OK, indigo_wheel_fli(INDIGO_DRIVER_INFO, &info));
	ASSERT_STREQ("FLI Filter Wheel", info.description);
	ASSERT_STREQ("indigo_wheel_fli", info.name);
	ASSERT_TRUE(info.multi_device_support);
	ASSERT_EQ_INT(INDIGO_DRIVER_SHUTDOWN, info.status);
}

// One wheel arrives, is identified from the SDK and exposes the wheel class
// contract with the slot count the SDK reports.
static void attach_and_identify(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_assert_interface(0, INDIGO_INTERFACE_WHEEL));
	FLI_CHECK_TRUE(fli_number_max(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 7));
	FLI_CHECK_TRUE(fli_number_is(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 1));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "CFW-1-7"));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_SERIAL_NUM_ITEM_NAME, "SN1000"));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME, "256"));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_HW_REVISION_ITEM_NAME, "16"));
	FLI_CHECK_TRUE(fli_property_count(0, WHEEL_SLOT_NAME_PROPERTY_NAME, 7));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// Every slot is selectable and the SDK receives the zero based position.
static void select_slots(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	for (int slot = 1; slot <= 7; slot++) {
		FLI_CHECK_TRUE(fli_set_number(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, slot, INDIGO_OK_STATE));
		FLI_CHECK_TRUE(fli_number_is(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, slot));
	}
	FLI_CHECK_EQ_INT(6, (int)atomic_load(&fli_fake.last_filter));
	// Selecting the slot the wheel already holds is accepted without a command.
	int before = atomic_load(&fli_fake.set_filter_calls);
	FLI_CHECK_TRUE(fli_set_number(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 7, INDIGO_OK_STATE));
	FLI_CHECK_EQ_INT(before, atomic_load(&fli_fake.set_filter_calls));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// A failed FLISetFilterPos must be reported and must not fake the new slot.
static void select_failure(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	atomic_store(&fli_fake.fail_set_filter, 1);
	FLI_CHECK_TRUE(fli_set_number(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 4, INDIGO_ALERT_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 1));
	// The wheel stays usable afterwards.
	FLI_CHECK_TRUE(fli_set_number(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 4, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 4));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// A failed position readback must be reported rather than assumed successful.
static void readback_failure(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	atomic_store(&fli_fake.fail_get_filter, 1);
	FLI_CHECK_TRUE(fli_set_number(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 3, INDIGO_ALERT_STATE));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// An uninitialised wheel reports a negative position and has to be homed.
static void uninitialised_wheel_is_homed(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	fli_fake_devices[0].filter_position = -1;
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_number_is(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 1));
	FLI_CHECK_EQ_INT(0, (int)atomic_load(&fli_fake.last_filter));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// A failed open must leave no SDK handle behind and must report an alert.
static void open_failure(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	atomic_store(&fli_fake.fail_open, 1);
	FLI_CHECK_TRUE(fli_connect_expect(0, false));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	// A second attempt has to work.
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.open_handles));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// A wheel whose slot count cannot be read is not usable, and the failed
// attempt has to close the handle it opened.
static void filter_count_failure(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	atomic_store(&fli_fake.fail_filter_count, 1);
	FLI_CHECK_TRUE(fli_connect_expect(0, false));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_connect(0));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// Two wheels are attached independently and each keeps its own SDK handle.
static void two_wheels(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 2);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(2));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_connect(1));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_set_number(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 2, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_set_number(1, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 5, INDIGO_OK_STATE));
	FLI_CHECK_EQ_INT(2, (int)fli_fake_devices[0].filter_position + 1);
	FLI_CHECK_EQ_INT(5, (int)fli_fake_devices[1].filter_position + 1);
	FLI_CHECK_TRUE(fli_disconnect(0));
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.open_handles));
	// The sibling is untouched by the first wheel's disconnect.
	FLI_CHECK_TRUE(fli_set_number(1, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 6, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// A removal detaches exactly the wheel the SDK no longer enumerates.
static void hot_unplug(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 2);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(2));
	fli_fake_devices[0].present = false;
	fli_usb_event(0, false);
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_find_device("CFW-2-7") >= 0);
	// The surviving wheel still works.
	int index = fli_find_device("CFW-2-7");
	FLI_CHECK_TRUE(fli_connect(index));
	FLI_CHECK_TRUE(fli_set_number(index, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 3, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// A duplicate arrival event must not attach the same wheel twice.
static void duplicate_arrival(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	fli_usb_event(0, true);
	fli_usb_event(0, true);
	indigo_usleep(500000);
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_attached));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// An arrival that the SDK does not enumerate must not attach anything.
static void arrival_without_device(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 0);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	indigo_usleep(500000);
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_attached));
	// The wheel appears later and the next arrival event attaches it.
	fli_fake_devices[0].present = true;
	fli_usb_event(0, true);
	FLI_CHECK_TRUE(fli_wait_attached(1));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// Reconnecting must re-read the wheel and leave no handle behind.
static void reconnect(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 5, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_disconnect(0));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_connect(0));
	// The wheel is where it was left, read back from the SDK.
	FLI_CHECK_TRUE(fli_number_is(0, WHEEL_SLOT_PROPERTY_NAME, WHEEL_SLOT_ITEM_NAME, 5));
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.open_handles));
cleanup:
	fli_driver_down(indigo_wheel_fli);
}

// Shutdown with a wheel still attached but disconnected releases everything.
static void shutdown_releases_devices(void) {
	fli_fake_reset(FLIDEVICE_FILTERWHEEL, 2);
	FLI_CHECK_TRUE(fli_driver_up(indigo_wheel_fli));
	FLI_CHECK_TRUE(fli_wait_attached(2));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_disconnect(0));
cleanup:
	fli_driver_down(indigo_wheel_fli);
	ASSERT_EQ_INT(0, atomic_load(&fli_attached));
	ASSERT_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	ASSERT_EQ_INT(0, atomic_load(&fli_fake.invalid_handle_uses));
}

int main(void) {
	const indigo_test_case tests[] = {
		{ "driver_metadata", driver_metadata },
		{ "attach_and_identify", attach_and_identify },
		{ "select_slots", select_slots },
		{ "select_failure", select_failure },
		{ "readback_failure", readback_failure },
		{ "uninitialised_wheel_is_homed", uninitialised_wheel_is_homed },
		{ "open_failure", open_failure },
		{ "filter_count_failure", filter_count_failure },
		{ "two_wheels", two_wheels },
		{ "hot_unplug", hot_unplug },
		{ "duplicate_arrival", duplicate_arrival },
		{ "arrival_without_device", arrival_without_device },
		{ "reconnect", reconnect },
		{ "shutdown_releases_devices", shutdown_releases_devices }
	};
	setvbuf(stdout, NULL, _IOLBF, 0);
	fli_observe(observed_names, ARRAY_SIZE(observed_names));
	return indigo_run_tests("FLI filter wheel fake SDK tests", tests, ARRAY_SIZE(tests));
}
