// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

#include <indigo/indigo_focuser_driver.h>
#include <indigo_drivers/focuser_fli/indigo_focuser_fli.h>

#include "fli_fake_sdk.h"
#include "fli_sdk_test_common.h"

static const char *observed_names[] = {
	CONNECTION_PROPERTY_NAME,
	FOCUSER_POSITION_PROPERTY_NAME,
	FOCUSER_STEPS_PROPERTY_NAME,
	FOCUSER_DIRECTION_PROPERTY_NAME,
	FOCUSER_ABORT_MOTION_PROPERTY_NAME,
	FOCUSER_SPEED_PROPERTY_NAME,
	FOCUSER_ON_POSITION_SET_PROPERTY_NAME,
	FOCUSER_LIMITS_PROPERTY_NAME,
	FOCUSER_TEMPERATURE_PROPERTY_NAME,
	FOCUSER_COMPENSATION_PROPERTY_NAME,
	FOCUSER_MODE_PROPERTY_NAME,
	FOCUSER_BACKLASH_PROPERTY_NAME,
	FOCUSER_REVERSE_MOTION_PROPERTY_NAME,
	INFO_PROPERTY_NAME
};

static bool position_is(int index, double value, double target) {
	indigo_property *property = fli_snapshot(index, FOCUSER_POSITION_PROPERTY_NAME);
	indigo_item *item = fli_snapshot_item(property, FOCUSER_POSITION_ITEM_NAME);
	bool result = item != NULL && item->number.value == value && item->number.target == target;
	if (!result) {
		fprintf(stderr, "FOCUSER_POSITION expected %g / %g, got %g / %g\n", value, target, item ? item->number.value : NAN, item ? item->number.target : NAN);
	}
	indigo_release_property(property);
	return result;
}

static bool target_is(int index, double target) {
	indigo_property *property = fli_snapshot(index, FOCUSER_POSITION_PROPERTY_NAME);
	indigo_item *item = fli_snapshot_item(property, FOCUSER_POSITION_ITEM_NAME);
	bool result = item != NULL && item->number.target == target;
	if (!result) {
		fprintf(stderr, "FOCUSER_POSITION target expected %g, got %g\n", target, item ? item->number.target : NAN);
	}
	indigo_release_property(property);
	return result;
}

static bool message_contains(int index, const char *property_name, const char *text) {
	char buffer[INDIGO_VALUE_SIZE];
	fli_message(index, property_name, buffer);
	if (strstr(buffer, text) == NULL) {
		fprintf(stderr, "%s message '%s' does not contain '%s'\n", property_name, buffer, text);
		return false;
	}
	return true;
}

static bool wait_steps(int expected) {
	for (int i = 0; i < 300; i++) {
		if (atomic_load(&fli_fake.step_motor_calls) >= expected) {
			return true;
		}
		indigo_usleep(10000);
	}
	fprintf(stderr, "step commands expected %d, got %d\n", expected, atomic_load(&fli_fake.step_motor_calls));
	return false;
}

static bool set_direction(int index, const char *item_name) {
	return fli_set_switch(index, FOCUSER_DIRECTION_PROPERTY_NAME, item_name, true);
}

// ----------------------------------------------------------------- scenarios

static void driver_metadata(void) {
	indigo_driver_info info;
	memset(&info, 0, sizeof(info));
	ASSERT_EQ_INT(INDIGO_OK, indigo_focuser_fli(INDIGO_DRIVER_INFO, &info));
	ASSERT_STREQ("FLI Focuser", info.description);
	ASSERT_STREQ("indigo_focuser_fli", info.name);
	ASSERT_TRUE(info.multi_device_support);
	ASSERT_EQ_INT(INDIGO_DRIVER_SHUTDOWN, info.status);
}

// The focuser is homed on connect, its extent becomes the position range and
// the identification comes from the SDK.
static void attach_and_identify(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.home_calls));
	FLI_CHECK_TRUE(fli_assert_interface(0, INDIGO_INTERFACE_FOCUSER));
	FLI_CHECK_TRUE(fli_number_max(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 7000));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "Atlas-1"));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_SERIAL_NUM_ITEM_NAME, "SN1000"));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME, "256"));
	// The controller has no speed setting, so the property stays hidden.
	FLI_CHECK_TRUE(fli_snapshot(0, FOCUSER_SPEED_PROPERTY_NAME) == NULL);
	// Neither sync, limits, a temperature probe, compensation, backlash nor reversal exists.
	const char *absent[] = { FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_MODE_PROPERTY_NAME, FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_PROPERTY_NAME };
	for (int i = 0; i < ARRAY_SIZE(absent); i++) {
		indigo_property *property = fli_snapshot(0, absent[i]);
		if (property != NULL) {
			fprintf(stderr, "%s is defined\n", absent[i]);
			indigo_release_property(property);
			FLI_CHECK_TRUE(false);
		}
	}
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// Homing takes a few status polls before the moving bit clears.
static void homing_waits_for_status(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].moving_polls = 3;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_EQ_INT(0, fli_fake_devices[0].moving_polls);
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A focuser that cannot be homed is not usable and releases its handle.
static void homing_failure(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	atomic_store(&fli_fake.fail_home, 1);
	FLI_CHECK_TRUE(fli_connect_expect(0, false));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_connect(0));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A focuser whose extent cannot be read is not usable either.
static void extent_failure(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	atomic_store(&fli_fake.fail_focuser_extent, 1);
	FLI_CHECK_TRUE(fli_connect_expect(0, false));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_snapshot(0, FOCUSER_POSITION_PROPERTY_NAME) == NULL);
	// a failed position read at connect is refused the same way
	atomic_store(&fli_fake.fail_stepper_position, 1);
	FLI_CHECK_TRUE(fli_connect_expect(0, false));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_snapshot(0, FOCUSER_POSITION_PROPERTY_NAME) == NULL);
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 300, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// Absolute moves are relative steps at SDK level, measured from the position
// that homing established as zero.
static void absolute_moves(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1500, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1500));
	FLI_CHECK_EQ_INT(INDIGO_OK_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_EQ_INT(1500, (int)atomic_load(&fli_fake.last_steps));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 900, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 900));
	FLI_CHECK_EQ_INT(-600, (int)atomic_load(&fli_fake.last_steps));
	// Requesting the position the focuser already holds moves nothing.
	int before = atomic_load(&fli_fake.step_motor_calls);
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 900, INDIGO_OK_STATE));
	FLI_CHECK_EQ_INT(before, atomic_load(&fli_fake.step_motor_calls));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

static void relative_moves(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(set_direction(0, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 300, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2300));
	FLI_CHECK_TRUE(set_direction(0, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 500, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1800));
	// A zero step request settles without a command.
	int before = atomic_load(&fli_fake.step_motor_calls);
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 0, INDIGO_OK_STATE));
	FLI_CHECK_EQ_INT(before, atomic_load(&fli_fake.step_motor_calls));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A move longer than one SDK command is issued in chunks.
static void long_move_is_chunked(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	int before = atomic_load(&fli_fake.step_motor_calls);
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 6500, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 6500));
	// 6500 steps do not fit into one 4000 step command.
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls) - before);
	FLI_CHECK_EQ_INT(2500, (int)atomic_load(&fli_fake.last_steps));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// Both travel limits are respected.
static void limits_are_respected(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 200, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(set_direction(0, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 1000, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0));
	FLI_CHECK_TRUE(set_direction(0, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 7000, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 7000));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A move that the SDK rejects is reported and does not leave a phantom target.
static void move_failure(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	atomic_store(&fli_fake.fail_step, 1);
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1200, INDIGO_ALERT_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_TRUE(message_contains(0, FOCUSER_POSITION_PROPERTY_NAME, "refused"));
	// a failed position read before the move sends no step command
	int steps = atomic_load(&fli_fake.step_motor_calls);
	atomic_store(&fli_fake.fail_stepper_position, 1);
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1300, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(steps, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0));
	// a refused second chunk of a long move ends ALERT and sends nothing more
	steps = atomic_load(&fli_fake.step_motor_calls);
	FLI_CHECK_TRUE(indigo_change_number_property_1(&fli_test_client, fli_observed[0].name, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 6500) == INDIGO_OK);
	FLI_CHECK_TRUE(wait_steps(steps + 1));
	atomic_store(&fli_fake.fail_step, 1);
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	indigo_usleep(1000000);
	FLI_CHECK_EQ_INT(steps + 2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 4000));
	// The focuser stays usable.
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1200, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A failed progress readback is reported rather than treated as completion.
static void progress_failure(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].step_hold = 500;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	atomic_store(&fli_fake.fail_steps_remaining, 1);
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1000, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	// the stop is sent and the move is never counted as arrival
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(0, (int)atomic_load(&fli_fake.last_steps));
	FLI_CHECK_EQ_INT(0, (int)fli_fake_devices[0].steps_remaining);
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 500));
	FLI_CHECK_TRUE(message_contains(0, FOCUSER_POSITION_PROPERTY_NAME, "could not be read"));
	fli_fake_devices[0].step_hold = 0;
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 900, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 900));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A running move is stopped mid-way and ends ALERT where the focuser actually
// stopped, never at the requested target.
static void abort_during_motion(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].step_hold = 800;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000, INDIGO_BUSY_STATE));
	FLI_CHECK_TRUE(wait_steps(1));
	FLI_CHECK_TRUE(fli_set_switch(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_TRUE(fli_switch_is(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, false));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(0, (int)atomic_load(&fli_fake.last_steps));
	FLI_CHECK_TRUE(position_is(0, 1000, 1000));
	// two readbacks a poll period apart prove the focuser stopped short of the target
	FLI_CHECK_EQ_INT(1000, (int)fli_fake_devices[0].stepper_position);
	FLI_CHECK_EQ_INT(0, (int)fli_fake_devices[0].steps_remaining);
	indigo_usleep(1000000);
	FLI_CHECK_EQ_INT(1000, (int)fli_fake_devices[0].stepper_position);
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_POSITION_PROPERTY_NAME));
	// The focuser accepts a fresh move afterwards.
	fli_fake_devices[0].step_hold = 0;
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1100, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1100));
	FLI_CHECK_EQ_INT(INDIGO_OK_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// Aborting while nothing is moving sends no command and disturbs nothing; a
// request with the item OFF is answered without a command.
static void abort_while_idle(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 400, INDIGO_OK_STATE));
	int steps = atomic_load(&fli_fake.step_motor_calls);
	int updates = fli_updates(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME);
	FLI_CHECK_TRUE(fli_set_switch(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	for (int i = 0; i < 100 && fli_updates(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME) < updates + 2; i++) {
		indigo_usleep(10000);
	}
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, INDIGO_OK_STATE));
	FLI_CHECK_EQ_INT(steps, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(INDIGO_OK_STATE, fli_property_state(0, FOCUSER_POSITION_PROPERTY_NAME));
	FLI_CHECK_TRUE(position_is(0, 400, 400));
	updates = fli_updates(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME);
	FLI_CHECK_TRUE(fli_set_switch(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, false));
	for (int i = 0; i < 100 && fli_updates(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME) < updates + 2; i++) {
		indigo_usleep(10000);
	}
	FLI_CHECK_TRUE(fli_updates(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME) >= updates + 2);
	FLI_CHECK_EQ_INT(INDIGO_OK_STATE, fli_property_state(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME));
	FLI_CHECK_EQ_INT(steps, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 700, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A refused stop leaves the move reported while the focuser keeps moving, and
// a retried abort stops it.
static void abort_refused_stop_keeps_move(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].step_hold = 800;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000, INDIGO_BUSY_STATE));
	FLI_CHECK_TRUE(wait_steps(1));
	atomic_store(&fli_fake.fail_step, 1);
	FLI_CHECK_TRUE(fli_set_switch(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	FLI_CHECK_TRUE(fli_switch_is(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, false));
	FLI_CHECK_EQ_INT(800, (int)fli_fake_devices[0].steps_remaining);
	indigo_usleep(1000000);
	FLI_CHECK_EQ_INT(INDIGO_BUSY_STATE, fli_property_state(0, FOCUSER_POSITION_PROPERTY_NAME));
	FLI_CHECK_EQ_INT(INDIGO_BUSY_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_TRUE(fli_set_switch(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_EQ_INT(3, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(0, (int)fli_fake_devices[0].steps_remaining);
	FLI_CHECK_TRUE(position_is(0, 1000, 1000));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// An abort that arrives while the move handler is still talking to the SDK
// waits for it and still ends the move, not BUSY.
static void abort_queued_behind_start(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].step_hold = 800;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	atomic_store(&fli_fake.stepper_position_waiting, false);
	atomic_store(&fli_fake.hold_stepper_position, true);
	FLI_CHECK_TRUE(indigo_change_number_property_1(&fli_test_client, fli_observed[0].name, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000) == INDIGO_OK);
	for (int i = 0; i < 300 && !atomic_load(&fli_fake.stepper_position_waiting); i++) {
		indigo_usleep(10000);
	}
	FLI_CHECK_TRUE(atomic_load(&fli_fake.stepper_position_waiting));
	FLI_CHECK_TRUE(fli_set_switch(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	indigo_usleep(100000);
	atomic_store(&fli_fake.hold_stepper_position, false);
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_ABORT_MOTION_PROPERTY_NAME, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(0, (int)atomic_load(&fli_fake.last_steps));
	FLI_CHECK_TRUE(position_is(0, 1000, 1000));
	indigo_usleep(1000000);
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_POSITION_PROPERTY_NAME));
cleanup:
	atomic_store(&fli_fake.hold_stepper_position, false);
	fli_driver_down(indigo_focuser_fli);
}

// A second move request while one is running is refused without a command and
// the running move ends at its own target.
static void move_refused_while_moving(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].step_hold = 800;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000, INDIGO_BUSY_STATE));
	FLI_CHECK_TRUE(wait_steps(1));
	FLI_CHECK_TRUE(fli_refused_while_busy(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 3000));
	FLI_CHECK_TRUE(target_is(0, 2000));
	FLI_CHECK_TRUE(set_direction(0, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME));
	FLI_CHECK_TRUE(fli_refused_while_busy(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100));
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.step_motor_calls));
	// the focuser completes the running move
	fli_fake_devices[0].stepper_position = 2000;
	fli_fake_devices[0].steps_remaining = 0;
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(position_is(0, 2000, 2000));
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.step_motor_calls));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A move that stops progressing, or that ends away from its target, is stopped
// and reported ALERT within bounded time.
static void stalled_move_ends_alert(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].step_hold = 800;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000, INDIGO_BUSY_STATE));
	FLI_CHECK_TRUE(wait_steps(1));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_TRUE(message_contains(0, FOCUSER_POSITION_PROPERTY_NAME, "does not move"));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(0, (int)atomic_load(&fli_fake.last_steps));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1000));
	// the focuser reports the move finished away from the target
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 3000, INDIGO_BUSY_STATE));
	FLI_CHECK_TRUE(wait_steps(3));
	fli_fake_devices[0].steps_remaining = 0;
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	FLI_CHECK_EQ_INT(INDIGO_ALERT_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_TRUE(message_contains(0, FOCUSER_POSITION_PROPERTY_NAME, "short of the target"));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000));
	fli_fake_devices[0].step_hold = 0;
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2500, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2500));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// Disconnecting during a move stops the focuser once before the handle closes;
// nothing is sent afterwards and the next session starts settled.
static void disconnect_during_motion_stops(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].step_hold = 800;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000, INDIGO_BUSY_STATE));
	FLI_CHECK_TRUE(wait_steps(1));
	int closes = atomic_load(&fli_fake.close_calls);
	FLI_CHECK_TRUE(fli_disconnect(0));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(0, (int)atomic_load(&fli_fake.last_steps));
	FLI_CHECK_EQ_INT(0, (int)fli_fake_devices[0].steps_remaining);
	FLI_CHECK_EQ_INT(closes + 1, atomic_load(&fli_fake.close_calls));
	int reads = atomic_load(&fli_fake.stepper_position_calls);
	indigo_usleep(1500000);
	FLI_CHECK_EQ_INT(reads, atomic_load(&fli_fake.stepper_position_calls));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.step_motor_calls));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.invalid_handle_uses));
	fli_fake_devices[0].step_hold = 0;
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_EQ_INT(INDIGO_OK_STATE, fli_property_state(0, FOCUSER_POSITION_PROPERTY_NAME));
	FLI_CHECK_EQ_INT(INDIGO_OK_STATE, fli_property_state(0, FOCUSER_STEPS_PROPERTY_NAME));
	FLI_CHECK_TRUE(position_is(0, 0, 0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 300, INDIGO_OK_STATE));
	// an idle disconnect sends no stop
	int steps = atomic_load(&fli_fake.step_motor_calls);
	FLI_CHECK_TRUE(fli_disconnect(0));
	FLI_CHECK_EQ_INT(steps, atomic_load(&fli_fake.step_motor_calls));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// Connect publishes the travel the focuser reports; failed optional identity
// queries keep their placeholders, and a reconnect follows a changed device.
static void connect_publishes_device_state(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	fli_fake_devices[0].focuser_extent = 12000;
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	atomic_store(&fli_fake.fail_model, 1);
	atomic_store(&fli_fake.fail_serial, 1);
	atomic_store(&fli_fake.fail_firmware, 1);
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_number_max(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 12000));
	FLI_CHECK_TRUE(fli_number_max(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 12000));
	FLI_CHECK_TRUE(position_is(0, 0, 0));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "Atlas-1"));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_SERIAL_NUM_ITEM_NAME, ""));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME, ""));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 11000, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_disconnect(0));
	fli_fake_devices[0].focuser_extent = 9000;
	snprintf(fli_fake_devices[0].model, sizeof(fli_fake_devices[0].model), "Atlas-Pro");
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_number_max(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 9000));
	FLI_CHECK_TRUE(position_is(0, 0, 0));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "Atlas-Pro"));
	FLI_CHECK_TRUE(fli_text_is(0, INFO_PROPERTY_NAME, INFO_DEVICE_SERIAL_NUM_ITEM_NAME, "SN1000"));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// A refusal turns FOCUSER_POSITION ALERT while the accepted move is still being started; the next
// request must still be refused instead of queuing a second move.
static void refusal_keeps_pending_move(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	atomic_store(&fli_fake.stepper_position_waiting, false);
	atomic_store(&fli_fake.hold_stepper_position, true);
	FLI_CHECK_TRUE(indigo_change_number_property_1(&fli_test_client, fli_observed[0].name, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000) == INDIGO_OK);
	for (int i = 0; i < 300 && !atomic_load(&fli_fake.stepper_position_waiting); i++) {
		indigo_usleep(10000);
	}
	FLI_CHECK_TRUE(atomic_load(&fli_fake.stepper_position_waiting));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 3000, INDIGO_ALERT_STATE));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100, INDIGO_ALERT_STATE));
	atomic_store(&fli_fake.hold_stepper_position, false);
	FLI_CHECK_TRUE(wait_steps(1));
	FLI_CHECK_TRUE(fli_wait_state(0, FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000));
	indigo_usleep(1000000);
	FLI_CHECK_EQ_INT(1, atomic_load(&fli_fake.step_motor_calls));
cleanup:
	atomic_store(&fli_fake.hold_stepper_position, false);
	fli_driver_down(indigo_focuser_fli);
}

// Two focusers are independent and each keeps its own SDK handle.
static void two_focusers(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 2);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(2));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_connect(1));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 400, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_set_number(1, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 900, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 400));
	FLI_CHECK_TRUE(fli_number_is(1, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 900));
	FLI_CHECK_TRUE(fli_disconnect(0));
	FLI_CHECK_TRUE(fli_set_number(1, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 950, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

static void hot_unplug(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 2);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(2));
	fli_fake_devices[1].present = false;
	fli_usb_event(1, false);
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_find_device("Atlas-1") >= 0);
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

// Reconnecting homes the focuser again and restarts from zero.
static void reconnect(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 1);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(1));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1700, INDIGO_OK_STATE));
	FLI_CHECK_TRUE(fli_disconnect(0));
	FLI_CHECK_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	FLI_CHECK_TRUE(fli_connect(0));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_fake.home_calls));
	FLI_CHECK_TRUE(fli_number_is(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 600, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_focuser_fli);
}

static void shutdown_releases_devices(void) {
	fli_fake_reset(FLIDEVICE_FOCUSER, 2);
	FLI_CHECK_TRUE(fli_driver_up(indigo_focuser_fli));
	FLI_CHECK_TRUE(fli_wait_attached(2));
	FLI_CHECK_TRUE(fli_connect(0));
	// SHUTDOWN is refused while a focuser is connected, and the focuser keeps working
	FLI_CHECK_EQ_INT(INDIGO_BUSY, indigo_focuser_fli(INDIGO_DRIVER_SHUTDOWN, NULL));
	FLI_CHECK_EQ_INT(2, atomic_load(&fli_attached));
	FLI_CHECK_TRUE(fli_set_number(0, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 250, INDIGO_OK_STATE));
cleanup:
	fli_driver_down(indigo_focuser_fli);
	ASSERT_EQ_INT(0, atomic_load(&fli_attached));
	ASSERT_EQ_INT(0, atomic_load(&fli_fake.open_handles));
	ASSERT_EQ_INT(0, atomic_load(&fli_fake.invalid_handle_uses));
}

int main(void) {
	const indigo_test_case tests[] = {
		{ "driver_metadata", driver_metadata },
		{ "attach_and_identify", attach_and_identify },
		{ "homing_waits_for_status", homing_waits_for_status },
		{ "homing_failure", homing_failure },
		{ "extent_failure", extent_failure },
		{ "absolute_moves", absolute_moves },
		{ "relative_moves", relative_moves },
		{ "long_move_is_chunked", long_move_is_chunked },
		{ "limits_are_respected", limits_are_respected },
		{ "move_failure", move_failure },
		{ "progress_failure", progress_failure },
		{ "abort_during_motion", abort_during_motion },
		{ "abort_while_idle", abort_while_idle },
		{ "abort_refused_stop_keeps_move", abort_refused_stop_keeps_move },
		{ "abort_queued_behind_start", abort_queued_behind_start },
		{ "move_refused_while_moving", move_refused_while_moving },
		{ "stalled_move_ends_alert", stalled_move_ends_alert },
		{ "disconnect_during_motion_stops", disconnect_during_motion_stops },
		{ "connect_publishes_device_state", connect_publishes_device_state },
		{ "refusal_keeps_pending_move", refusal_keeps_pending_move },
		{ "two_focusers", two_focusers },
		{ "hot_unplug", hot_unplug },
		{ "reconnect", reconnect },
		{ "shutdown_releases_devices", shutdown_releases_devices }
	};
	setvbuf(stdout, NULL, _IOLBF, 0);
	fli_observe(observed_names, ARRAY_SIZE(observed_names));
	return indigo_run_tests("FLI focuser fake SDK tests", tests, ARRAY_SIZE(tests));
}
