// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// Pegasus Ultimate Powerbox v1 and v2 protocol coverage. The driver exposes two
// logical devices over one serial connection - the powerbox itself and the
// focuser that shares the port through its master - so both are exercised, each
// in its own driver lifecycle over a fresh simulator.

#include <pthread.h>

#include <indigo/indigo_usb_utils.h>
#include <indigo_drivers/aux_upb/indigo_aux_upb.h>

#include "serial_simulator_test_common.h"

#ifndef AUX_UPB_SIMULATOR_EXECUTABLE
#define AUX_UPB_SIMULATOR_EXECUTABLE "build/integration/aux_upb_simulator"
#endif

static const simulator_driver_case aux = {
	"Ultimate Powerbox", "indigo_aux_upb", "Ultimate Powerbox", indigo_aux_upb, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0
};
static const simulator_driver_case focuser = {
	"Ultimate Powerbox focuser", "indigo_aux_upb", "Ultimate Powerbox (focuser)", indigo_aux_upb, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

// ---------------------------------------------------------------- smart hub

// The v1 box switches its six USB ports through an internal Microchip USB2517 hub
// that the driver finds and drives over libusb rather than over the serial link.
// The driver object linked here is compiled with its libusb calls renamed to the
// functions below (see the Makefile), so the v1 cases see this fake hub instead of
// whatever hub happens to be on the host's USB bus.
//
// Port status words are the ones a real UPB v1.7 returned to GET_STATUS: 0x0100 for
// a powered port with nothing attached, 0x0103 for the internal port that carries
// the box's own serial bridge. Clearing PORT_POWER drops the port to 0x0000.

#define HUB_PORTS 7
#define HUB_PORT_POWER 0x0100
#define HUB_PORT_ATTACHED 0x0003
#define HUB_PORT_OVERCURRENT 0x0008

static struct {
	pthread_mutex_t mutex;
	pthread_cond_t cond;
	bool present;
	uint16_t status[HUB_PORTS + 1];
	int set_power[HUB_PORTS + 1];
	int clear_power[HUB_PORTS + 1];
	int status_reads;
	bool hold_armed;
	bool holding;
	bool fail_power;
	unsigned int ok_revision_at_power_change;
} smart_hub = { .mutex = PTHREAD_MUTEX_INITIALIZER, .cond = PTHREAD_COND_INITIALIZER };

static char smart_hub_token;

static void smart_hub_reset(bool present) {
	pthread_mutex_lock(&smart_hub.mutex);
	smart_hub.present = present;
	for (int i = 1; i <= HUB_PORTS; i++) {
		smart_hub.status[i] = HUB_PORT_POWER;
		smart_hub.set_power[i] = smart_hub.clear_power[i] = 0;
	}
	smart_hub.status[HUB_PORTS] = HUB_PORT_POWER | HUB_PORT_ATTACHED;
	smart_hub.status_reads = 0;
	smart_hub.hold_armed = smart_hub.holding = false;
	smart_hub.fail_power = false;
	smart_hub.ok_revision_at_power_change = 0;
	pthread_mutex_unlock(&smart_hub.mutex);
}

ssize_t LIBUSB_CALL upb_test_get_device_list(libusb_context *ctx, libusb_device ***list) {
	(void)ctx;
	libusb_device **devices = calloc(2, sizeof(libusb_device *));
	pthread_mutex_lock(&smart_hub.mutex);
	bool present = smart_hub.present;
	pthread_mutex_unlock(&smart_hub.mutex);
	if (present) {
		devices[0] = (libusb_device *)&smart_hub_token;
	}
	*list = devices;
	return present ? 1 : 0;
}

void LIBUSB_CALL upb_test_free_device_list(libusb_device **list, int unref_devices) {
	(void)unref_devices;
	free(list);
}

int LIBUSB_CALL upb_test_get_device_descriptor(libusb_device *dev, struct libusb_device_descriptor *descriptor) {
	memset(descriptor, 0, sizeof(*descriptor));
	if (dev != (libusb_device *)&smart_hub_token) {
		return LIBUSB_ERROR_NO_DEVICE;
	}
	descriptor->bDeviceClass = LIBUSB_CLASS_HUB;
	descriptor->idVendor = 0x0424;
	descriptor->idProduct = 0x2517;
	return LIBUSB_SUCCESS;
}

int LIBUSB_CALL upb_test_open(libusb_device *dev, libusb_device_handle **handle) {
	*handle = (libusb_device_handle *)dev;
	return LIBUSB_SUCCESS;
}

void LIBUSB_CALL upb_test_close(libusb_device_handle *handle) {
	(void)handle;
}

int LIBUSB_CALL upb_test_control_transfer(libusb_device_handle *handle, uint8_t request_type, uint8_t request, uint16_t value, uint16_t index, unsigned char *data, uint16_t length, unsigned int timeout) {
	(void)handle;
	(void)timeout;
	if (index < 1 || index > HUB_PORTS) {
		return LIBUSB_ERROR_PIPE;
	}
	int result = LIBUSB_ERROR_PIPE;
	pthread_mutex_lock(&smart_hub.mutex);
	if (request_type == (LIBUSB_ENDPOINT_IN | LIBUSB_REQUEST_TYPE_CLASS | LIBUSB_RECIPIENT_OTHER) && request == LIBUSB_REQUEST_GET_STATUS && length == 4) {
		// A held read parks the poll inside the hub loop until the test lets it go,
		// which is exactly where a real poll is while its serial exchange runs.
		if (smart_hub.hold_armed) {
			smart_hub.hold_armed = false;
			smart_hub.holding = true;
			pthread_cond_broadcast(&smart_hub.cond);
			while (smart_hub.holding) {
				pthread_cond_wait(&smart_hub.cond, &smart_hub.mutex);
			}
		}
		uint32_t status = smart_hub.status[index];
		memcpy(data, &status, sizeof(status));
		smart_hub.status_reads++;
		pthread_cond_broadcast(&smart_hub.cond);
		result = 4;
	} else if (request_type == (LIBUSB_REQUEST_TYPE_CLASS | LIBUSB_RECIPIENT_OTHER) && value == 8 && length == 0) {
		// A hub that stops answering port power requests leaves the port as it was.
		if (smart_hub.fail_power) {
			result = LIBUSB_ERROR_IO;
		} else if (request == LIBUSB_REQUEST_SET_FEATURE) {
			smart_hub.status[index] |= HUB_PORT_POWER;
			smart_hub.set_power[index]++;
			result = 0;
		} else if (request == LIBUSB_REQUEST_CLEAR_FEATURE) {
			smart_hub.status[index] = 0;
			smart_hub.clear_power[index]++;
			result = 0;
		}
		smart_hub.ok_revision_at_power_change = property_state_revision(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE);
	}
	pthread_mutex_unlock(&smart_hub.mutex);
	return result;
}

static bool smart_hub_wait(bool (*done)(void *), void *context) {
	struct timespec deadline;
	clock_gettime(CLOCK_REALTIME, &deadline);
	deadline.tv_sec += 10;
	pthread_mutex_lock(&smart_hub.mutex);
	bool result = done(context);
	while (!result && pthread_cond_timedwait(&smart_hub.cond, &smart_hub.mutex, &deadline) == 0) {
		result = done(context);
	}
	result = done(context);
	pthread_mutex_unlock(&smart_hub.mutex);
	return result;
}

static bool smart_hub_is_holding(void *context) {
	(void)context;
	return smart_hub.holding;
}

static bool smart_hub_read_past(void *context) {
	return smart_hub.status_reads >= *(int *)context;
}

// Park the next port status read, which is the poll's once nothing else is pending.
static bool smart_hub_hold_poll(void) {
	pthread_mutex_lock(&smart_hub.mutex);
	smart_hub.hold_armed = true;
	pthread_mutex_unlock(&smart_hub.mutex);
	if (!smart_hub_wait(smart_hub_is_holding, NULL)) {
		fprintf(stderr, "The poll never read the smart hub\n");
		return false;
	}
	return true;
}

static void smart_hub_release_poll(void) {
	pthread_mutex_lock(&smart_hub.mutex);
	smart_hub.hold_armed = smart_hub.holding = false;
	pthread_cond_broadcast(&smart_hub.cond);
	pthread_mutex_unlock(&smart_hub.mutex);
}

// Wait until the hub has answered this many more status reads, which covers at
// least one complete poll of all its ports.
static bool smart_hub_wait_for_reads(int more) {
	pthread_mutex_lock(&smart_hub.mutex);
	int target = smart_hub.status_reads + more;
	pthread_mutex_unlock(&smart_hub.mutex);
	if (!smart_hub_wait(smart_hub_read_past, &target)) {
		fprintf(stderr, "The smart hub was not polled again\n");
		return false;
	}
	return true;
}

static void smart_hub_set_status(int port, uint16_t status) {
	pthread_mutex_lock(&smart_hub.mutex);
	smart_hub.status[port] = status;
	pthread_mutex_unlock(&smart_hub.mutex);
}

static void smart_hub_fail_power(bool fail) {
	pthread_mutex_lock(&smart_hub.mutex);
	smart_hub.fail_power = fail;
	pthread_mutex_unlock(&smart_hub.mutex);
}

static void smart_hub_counts(int port, uint16_t *status, int *set_power, int *clear_power) {
	pthread_mutex_lock(&smart_hub.mutex);
	*status = smart_hub.status[port];
	*set_power = smart_hub.set_power[port];
	*clear_power = smart_hub.clear_power[port];
	pthread_mutex_unlock(&smart_hub.mutex);
}

// ---------------------------------------------------------------- utilities

static bool start_upb(external_serial_simulator *simulator, const char * const *arguments) {
	if (arguments == NULL) {
		return start_external_serial_simulator(simulator, AUX_UPB_SIMULATOR_EXECUTABLE);
	}
	return start_external_serial_simulator_with_args(simulator, AUX_UPB_SIMULATOR_EXECUTABLE, arguments);
}

static bool wait_for_switch_item_value(const char *property_name, const char *item_name, bool expected) {
	for (int i = 0; i < 100; i++) {
		indigo_item *item = find_cached_item(property_name, item_name);
		if (item != NULL && item->sw.value == expected) {
			return true;
		}
		indigo_usleep(100000);
	}
	indigo_item *item = find_cached_item(property_name, item_name);
	fprintf(stderr, "Switch %s.%s is %s, expected %s\n", property_name, item_name, item == NULL ? "missing" : item->sw.value ? "on" : "off", expected ? "on" : "off");
	return false;
}

static bool wait_for_light_item_value(const char *property_name, const char *item_name, indigo_property_state expected) {
	for (int i = 0; i < 100; i++) {
		indigo_item *item = find_cached_item(property_name, item_name);
		if (item != NULL && item->light.value == expected) {
			return true;
		}
		indigo_usleep(100000);
	}
	indigo_item *item = find_cached_item(property_name, item_name);
	fprintf(stderr, "Light %s.%s is %d, expected %d\n", property_name, item_name, item == NULL ? -1 : item->light.value, expected);
	return false;
}

// Switch one item of an ANY_OF_MANY property without disturbing the others, which
// is what a client does when it toggles a single outlet.
static bool set_switch(const simulator_driver_case *driver_case, const char *property_name, const char *item_name, bool value) {
	return indigo_change_switch_property_1(&simulator_test_client, driver_case->device_name, property_name, item_name, value) == INDIGO_OK;
}

static bool set_number(const simulator_driver_case *driver_case, const char *property_name, const char *item_name, double value) {
	return indigo_change_number_property_1(&simulator_test_client, driver_case->device_name, property_name, item_name, value) == INDIGO_OK;
}

// find_cached_property() returns NULL for a property the driver never defined, so
// the count is reported through a helper rather than through a raw dereference.
static int property_count(const char *property_name) {
	indigo_property *property = find_cached_property(property_name);
	if (property == NULL) {
		fprintf(stderr, "Property %s is not defined\n", property_name);
		return -1;
	}
	return property->count;
}

// The refusal is a transition, not a resting state: the driver publishes the
// property in ALERT and the very next status poll publishes the running motion
// again, so the check is whether ALERT was published at all after the request.
// A refused motion request: a BUSY message while the running move owns the property, ALERT with the values restored otherwise.
static bool assert_refused_motion_request(const char *property_name, const char *item_name, double value) {
	return assert_rejected_number_change_on(focuser.device_name, property_name, item_name, value);
}

static void outlet_item(char *buffer, size_t size, int index) {
	snprintf(buffer, size, "OUTLET_%d", index);
}

// ---------------------------------------------------------------- powerbox

static void metadata_and_property_completeness(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	assert_device_interface(INDIGO_INTERFACE_AUX_POWERBOX | INDIGO_INTERFACE_AUX_WEATHER);
	assert_serial_aux_class_property_completeness();
	SERIAL_CHECK_EQ_INT(4, property_count(AUX_POWER_OUTLET_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(4, property_count(AUX_POWER_OUTLET_STATE_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(4, property_count(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(3, property_count(AUX_HEATER_OUTLET_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(3, property_count(AUX_HEATER_OUTLET_STATE_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(3, property_count(AUX_HEATER_OUTLET_CURRENT_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(6, property_count(AUX_USB_PORT_PROPERTY_NAME));
	assert_property_has_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME);
	assert_property_has_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME);
	assert_property_has_item(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME);
	assert_property_has_item(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME);
	assert_property_has_item(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_DEWPOINT_ITEM_NAME);
	assert_property_has_item(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME);
	assert_property_has_item(AUX_INFO_PROPERTY_NAME, "X_AUX_AVERAGE");
	assert_property_has_item("X_AUX_VARIABLE_POWER_OUTLET", "OUTLET_1");
	assert_property_has_item("X_AUX_REBOOT", "REBOOT");
	assert_property_has_item(AUX_SAVE_OUTLET_STATES_AS_DEFAULT_PROPERTY_NAME, AUX_SAVE_OUTLET_STATES_AS_DEFAULT_ITEM_NAME);
	assert_property_has_item(AUX_OUTLET_NAMES_PROPERTY_NAME, AUX_POWER_OUTLET_NAME_1_ITEM_NAME);
	// PU:b is documented for both models, so the hub switch is available on the v2
	// box as well, next to its per port controls.
	assert_property_has_item("X_AUX_HUB", "ENABLED");
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// The v1 box has two heater outlets, no variable voltage outlet and switches USB
// through an external hub rather than through the protocol.
static void upb1_model_reduces_the_outlet_inventory(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_EQ_INT(4, property_count(AUX_POWER_OUTLET_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(2, property_count(AUX_HEATER_OUTLET_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(2, property_count(AUX_HEATER_OUTLET_STATE_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(2, property_count(AUX_HEATER_OUTLET_CURRENT_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property("X_AUX_VARIABLE_POWER_OUTLET"));
	assert_property_has_item("X_AUX_HUB", "ENABLED");
	assert_property_has_item("X_AUX_HUB", "DISABLED");
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void connect_seeds_every_sensor_from_the_status_frame(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--power", "13.4", "2.5", "33", "--weather", "-3.5", "82", "-6.1", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME, 13.4, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_CURRENT_ITEM_NAME, 2.5, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_POWER_ITEM_NAME, 33, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME, -3.5, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME, 82, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_DEWPOINT_ITEM_NAME, -6.1, 0.01));
	// The running counters come from the separate PC frame.
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, "X_AUX_AVERAGE", 2.1, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, "X_AUX_AMP_HOUR", 12, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, "X_AUX_WATT_HOUR", 46, 0.01));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// A bare box has no environmental probe, so the whole weather group reads zero.
// This is what the hardware run against a Pegasus UPB v1 actually reported, and the
// driver has to publish it rather than treat it as a failed parse.
static void a_box_without_a_probe_reports_zero_weather(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--no-probe", "--outlet-current", "6", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME, 0, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME, 0, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_DEWPOINT_ITEM_NAME, 0, 0.01));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_WEATHER_PROPERTY_NAME, INDIGO_OK_STATE));
	// A lightly loaded outlet reads a small current rather than the fixed sample value.
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME, AUX_POWER_OUTLET_CURRENT_1_ITEM_NAME, 6 / 300.0, 0.01));
	// The box stays fully controllable without a probe.
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, false));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void each_power_outlet_switches_on_its_own(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	static const char * const items[] = { AUX_POWER_OUTLET_1_ITEM_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, AUX_POWER_OUTLET_3_ITEM_NAME, AUX_POWER_OUTLET_4_ITEM_NAME };
	for (int i = 0; i < 4; i++) {
		SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, items[i], false));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
		// The status poll reads the outlet mask back, so the value has to survive it.
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, items[i], false));
		for (int j = 0; j < 4; j++) {
			SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, items[j], j > i ? true : false));
		}
	}
	for (int i = 0; i < 4; i++) {
		// The change dispatch ignores a request that arrives while the property is still
		// BUSY, so each outlet has to settle before the next one is switched.
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, items[i], true));
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, items[i], true));
	}
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// A healthy outlet reports OK while it is on and IDLE once it is switched off.
static void power_outlet_state_follows_the_switch(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_1_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_1_ITEM_NAME, INDIGO_IDLE_STATE));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_1_ITEM_NAME, INDIGO_OK_STATE));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// The overcurrent field of the status frame outranks the switch state.
static void overcurrent_raises_the_outlet_state(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--overcurrent", "0010100", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_3_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_1_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_2_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_4_ITEM_NAME, INDIGO_OK_STATE));
	// The fifth flag belongs to the first heater outlet.
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_HEATER_OUTLET_STATE_PROPERTY_NAME, AUX_HEATER_OUTLET_STATE_1_ITEM_NAME, INDIGO_ALERT_STATE));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void power_outlet_current_is_published(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	// The v2 box reports the raw reading in units of 1/300 A.
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME, AUX_POWER_OUTLET_CURRENT_1_ITEM_NAME, 200 / 300.0, 0.01));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_POWER_OUTLET_CURRENT_PROPERTY_NAME, AUX_POWER_OUTLET_CURRENT_1_ITEM_NAME, 0, 0.01));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void heaters_hold_independent_duty_cycles(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	for (int i = 1; i <= 3; i++) {
		char item[32];
		outlet_item(item, sizeof(item), i);
		SERIAL_CHECK_TRUE(set_number(&aux, AUX_HEATER_OUTLET_PROPERTY_NAME, item, 25.0 * i));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_HEATER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
		// The device stores the duty cycle as 0..255, so the readback is rounded.
		SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_HEATER_OUTLET_PROPERTY_NAME, item, 25.0 * i, 1));
	}
	for (int i = 1; i <= 3; i++) {
		char item[32];
		outlet_item(item, sizeof(item), i);
		SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_HEATER_OUTLET_PROPERTY_NAME, item, 25.0 * i, 1));
	}
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void heater_state_and_current_follow_the_duty_cycle(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_HEATER_OUTLET_STATE_PROPERTY_NAME, AUX_HEATER_OUTLET_STATE_2_ITEM_NAME, INDIGO_IDLE_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_HEATER_OUTLET_CURRENT_PROPERTY_NAME, AUX_HEATER_OUTLET_CURRENT_2_ITEM_NAME, 0, 0.01));
	SERIAL_CHECK_TRUE(set_number(&aux, AUX_HEATER_OUTLET_PROPERTY_NAME, "OUTLET_2", 60));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_HEATER_OUTLET_STATE_PROPERTY_NAME, AUX_HEATER_OUTLET_STATE_2_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_HEATER_OUTLET_CURRENT_PROPERTY_NAME, AUX_HEATER_OUTLET_CURRENT_2_ITEM_NAME, 200 / 300.0, 0.01));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void automatic_dew_control_round_trips(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_DEW_CONTROL_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// A box that was left in automatic dew mode has to come up in that mode.
static void autodew_state_is_adopted_from_the_device(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--autodew", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// TGT-D22: when the status frame of the connect goes unanswered the connect still succeeds without reading the dew
// control mode, so the one-of-many dew control is defined with its initial items; exactly one of them has to be on,
// and the poll then adopts the automatic mode the box reports.
static void dew_control_has_one_mode_when_the_connect_status_fails(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--autodew", "--fault-once", "PA", "silent", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(context.connected);
	indigo_item *manual = find_cached_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME);
	indigo_item *automatic = find_cached_item(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME);
	SERIAL_CHECK_TRUE(manual != NULL && automatic != NULL);
	fprintf(stderr, "Dew control after a failed PA: manual %s, automatic %s\n", manual->sw.value ? "on" : "off", automatic->sw.value ? "on" : "off");
	SERIAL_CHECK_EQ_INT(1, (manual->sw.value ? 1 : 0) + (automatic->sw.value ? 1 : 0));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_DEW_CONTROL_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void each_usb_port_switches_on_its_own(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	static const char * const items[] = {
		AUX_USB_PORT_1_ITEM_NAME, AUX_USB_PORT_2_ITEM_NAME, AUX_USB_PORT_3_ITEM_NAME,
		AUX_USB_PORT_4_ITEM_NAME, AUX_USB_PORT_5_ITEM_NAME, AUX_USB_PORT_6_ITEM_NAME
	};
	for (int i = 0; i < 6; i++) {
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, items[i], false));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, items[i], false));
	}
	for (int i = 0; i < 6; i++) {
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, items[i], false));
	}
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, items[2], true));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, items[2], true));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void usb_hub_switches_on_the_v1_box(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(set_switch(&aux, "X_AUX_HUB", "DISABLED", true));
	SERIAL_CHECK_TRUE(wait_for_property_state("X_AUX_HUB", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value("X_AUX_HUB", "DISABLED", true));
	SERIAL_CHECK_TRUE(set_switch(&aux, "X_AUX_HUB", "ENABLED", true));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value("X_AUX_HUB", "ENABLED", true));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static const char * const usb_port_items[] = {
	AUX_USB_PORT_1_ITEM_NAME, AUX_USB_PORT_2_ITEM_NAME, AUX_USB_PORT_3_ITEM_NAME,
	AUX_USB_PORT_4_ITEM_NAME, AUX_USB_PORT_5_ITEM_NAME, AUX_USB_PORT_6_ITEM_NAME
};
static const char * const usb_port_state_items[] = {
	AUX_USB_PORT_STATE_1_ITEM_NAME, AUX_USB_PORT_STATE_2_ITEM_NAME, AUX_USB_PORT_STATE_3_ITEM_NAME,
	AUX_USB_PORT_STATE_4_ITEM_NAME, AUX_USB_PORT_STATE_5_ITEM_NAME, AUX_USB_PORT_STATE_6_ITEM_NAME
};

// Without a smart hub on the bus the v1 box has no per port USB control at all.
static void v1_without_a_smart_hub_hides_the_usb_ports(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", NULL };
	smart_hub_reset(false);
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(!has_defined_property(AUX_USB_PORT_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(AUX_USB_PORT_STATE_PROPERTY_NAME));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// Each port is switched with its own PORT_POWER request and the others are left
// alone; the status lights follow the hub's port status word.
static void v1_usb_ports_switch_through_the_smart_hub(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", NULL };
	smart_hub_reset(true);
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_EQ_INT(6, property_count(AUX_USB_PORT_PROPERTY_NAME));
	SERIAL_CHECK_EQ_INT(6, property_count(AUX_USB_PORT_STATE_PROPERTY_NAME));
	for (int i = 0; i < 6; i++) {
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], true));
		SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_USB_PORT_STATE_PROPERTY_NAME, usb_port_state_items[i], INDIGO_IDLE_STATE));
	}
	smart_hub_set_status(3, HUB_PORT_POWER | HUB_PORT_ATTACHED);
	smart_hub_set_status(4, HUB_PORT_POWER | HUB_PORT_OVERCURRENT);
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_USB_PORT_STATE_PROPERTY_NAME, usb_port_state_items[2], INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_USB_PORT_STATE_PROPERTY_NAME, usb_port_state_items[3], INDIGO_ALERT_STATE));
	for (int i = 0; i < 6; i++) {
		uint16_t status;
		int set_power, clear_power;
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], false));
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], false));
		SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
		smart_hub_counts(i + 1, &status, &set_power, &clear_power);
		SERIAL_CHECK_EQ_INT(0, status);
		SERIAL_CHECK_EQ_INT(0, set_power);
		SERIAL_CHECK_EQ_INT(1, clear_power);
		SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_USB_PORT_STATE_PROPERTY_NAME, usb_port_state_items[i], INDIGO_IDLE_STATE));
	}
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, usb_port_items[2], true));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[2], true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
	for (int i = 0; i < 6; i++) {
		uint16_t status;
		int set_power, clear_power;
		smart_hub_counts(i + 1, &status, &set_power, &clear_power);
		SERIAL_CHECK_EQ_INT(i == 2 ? HUB_PORT_POWER : 0, status);
		SERIAL_CHECK_EQ_INT(i == 2 ? 1 : 0, set_power);
		SERIAL_CHECK_EQ_INT(1, clear_power);
	}
	// A poll after the last change still reports what was requested.
	SERIAL_CHECK_TRUE(smart_hub_wait_for_reads(2 * 6));
	for (int i = 0; i < 6; i++) {
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], i == 2));
	}
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
	smart_hub_reset(false);
}

// A request that arrives while the poll is reading the hub must survive it. The
// hardware lost 4 of 11 such requests: the poll overwrote the requested value with
// the old hub state, the handler found nothing to switch and published OK with the
// old value. The status light is read-only and keeps following the hub meanwhile,
// but it must not publish the pending switch as OK before its handler has run.
static void v1_usb_port_change_survives_a_concurrent_poll(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", NULL };
	bool held = false;
	uint16_t status;
	int set_power, clear_power;
	smart_hub_reset(true);
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[1], true));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_USB_PORT_STATE_PROPERTY_NAME, usb_port_state_items[0], INDIGO_IDLE_STATE));
	unsigned int ok_revision = property_state_revision(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE);
	SERIAL_CHECK_TRUE(held = smart_hub_hold_poll());
	smart_hub_set_status(1, HUB_PORT_POWER | HUB_PORT_ATTACHED);
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, usb_port_items[1], false));
	smart_hub_release_poll();
	held = false;
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[1], false));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
	smart_hub_counts(2, &status, &set_power, &clear_power);
	SERIAL_CHECK_EQ_INT(1, clear_power);
	SERIAL_CHECK_EQ_INT(0, status);
	pthread_mutex_lock(&smart_hub.mutex);
	unsigned int ok_revision_at_power_change = smart_hub.ok_revision_at_power_change;
	pthread_mutex_unlock(&smart_hub.mutex);
	SERIAL_CHECK_EQ_INT(ok_revision, ok_revision_at_power_change);
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_USB_PORT_STATE_PROPERTY_NAME, usb_port_state_items[0], INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(smart_hub_wait_for_reads(2 * 6));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[1], false));
	smart_hub_counts(2, &status, &set_power, &clear_power);
	SERIAL_CHECK_EQ_INT(1, clear_power);
	SERIAL_CHECK_EQ_INT(0, set_power);
cleanup:
	if (held) {
		smart_hub_release_poll();
	}
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
	smart_hub_reset(false);
}

// TGT-040: a port the hub refuses to switch is shown in the state the hub reported, with ALERT, instead of
// the request. The ALERT itself carries that state, the following polls find nothing to correct and publish nothing.
static void v1_usb_port_failure_shows_the_hub_state(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", NULL };
	uint16_t status;
	int set_power, clear_power;
	smart_hub_reset(true);
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[1], true));
	smart_hub_fail_power(true);
	unsigned int revision = property_state_revision(AUX_USB_PORT_PROPERTY_NAME, INDIGO_ALERT_STATE);
	unsigned int ok_revision = property_state_revision(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE);
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, usb_port_items[1], false));
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after(AUX_USB_PORT_PROPERTY_NAME, INDIGO_ALERT_STATE, revision));
	SERIAL_CHECK_TRUE(smart_hub_wait_for_reads(2 * 6));
	for (int i = 0; i < 6; i++) {
		SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[i], true));
	}
	SERIAL_CHECK_EQ_INT(ok_revision, property_state_revision(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
	smart_hub_counts(2, &status, &set_power, &clear_power);
	SERIAL_CHECK_EQ_INT(HUB_PORT_POWER, status);
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
	smart_hub_reset(false);
}

// TGT-039: a port the box does not answer for is shown in the state the box reported, with ALERT, and a later
// request for another port does not send the refused request again.
static void usb_port_failure_shows_the_box_state(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--fault-once", "U3:0", "silent", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE));
	unsigned int revision = property_state_revision(AUX_USB_PORT_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, usb_port_items[2], false));
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after(AUX_USB_PORT_PROPERTY_NAME, INDIGO_ALERT_STATE, revision));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[2], true));
	revision = property_state_revision(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE);
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_USB_PORT_PROPERTY_NAME, usb_port_items[3], false));
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after(AUX_USB_PORT_PROPERTY_NAME, INDIGO_OK_STATE, revision));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[3], false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_USB_PORT_PROPERTY_NAME, usb_port_items[2], true));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// TGT-038: an outlet the box does not answer for is shown in the state the box reported, with ALERT. The poll writes
// only the values, so a later request for another outlet must not send the refused request from a stale target.
static void power_outlet_failure_shows_the_box_state(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--fault-once", "P2:0", "silent", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
	unsigned int revision = property_state_revision(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_ALERT_STATE, revision));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, true));
	revision = property_state_revision(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE);
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE, revision));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, true));
	// The state lights follow the box on every poll, so outlet 2 is still powered.
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_3_ITEM_NAME, INDIGO_IDLE_STATE));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_2_ITEM_NAME, INDIGO_OK_STATE));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// TGT-D15: an outlet the box reports switched without a request from the driver is published in AUX_POWER_OUTLET,
// not only in AUX_POWER_OUTLET_STATE. The simulator switches outlet 2 off from the third status frame on, after the
// connect and the first poll.
static void power_outlet_change_reported_by_the_box_is_published(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--outlet-after", "2", "2", "0", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_light_item_value(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_2_ITEM_NAME, INDIGO_IDLE_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_POWER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// TGT-041: a dew control request the box does not answer is shown as the mode the box reported, with ALERT.
static void dew_control_failure_shows_the_box_state(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--fault-once", "PD:1", "silent", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true));
	unsigned int revision = property_state_revision(AUX_DEW_CONTROL_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_AUTOMATIC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after(AUX_DEW_CONTROL_PROPERTY_NAME, INDIGO_ALERT_STATE, revision));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_DEW_CONTROL_PROPERTY_NAME, AUX_DEW_CONTROL_MANUAL_ITEM_NAME, true));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// TGT-042: a hub request the box does not answer is shown as the hub state the box reported, with ALERT.
static void v1_hub_failure_shows_the_box_state(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", "--fault-once", "PU:0", "silent", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value("X_AUX_HUB", "ENABLED", true));
	unsigned int revision = property_state_revision("X_AUX_HUB", INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(set_switch(&aux, "X_AUX_HUB", "DISABLED", true));
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after("X_AUX_HUB", INDIGO_ALERT_STATE, revision));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value("X_AUX_HUB", "ENABLED", true));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// TGT-D02: a hub state the v1 box reports differently from what the driver shows is published as X_AUX_HUB, and
// AUX_DEW_CONTROL, which did not change, is not published for it. The PU:1 of the connect is lost, so the box keeps
// the hub it was left with.
static void v1_hub_change_reported_by_the_box_is_published(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--model", "upb", "--hub-off", "--fault-once", "PU:1", "silent", NULL };
	smart_hub_reset(false);
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	unsigned int dew_revision = property_revision(AUX_DEW_CONTROL_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(wait_for_switch_item_value("X_AUX_HUB", "DISABLED", true));
	SERIAL_CHECK_TRUE(wait_for_property_state("X_AUX_HUB", INDIGO_OK_STATE));
	SERIAL_CHECK_EQ_INT(dew_revision, property_revision(AUX_DEW_CONTROL_PROPERTY_NAME));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void variable_power_outlet_round_trips(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_number_item_value("X_AUX_VARIABLE_POWER_OUTLET", "OUTLET_1", 12, 0.01));
	SERIAL_CHECK_TRUE(set_number(&aux, "X_AUX_VARIABLE_POWER_OUTLET", "OUTLET_1", 5));
	SERIAL_CHECK_TRUE(wait_for_property_state("X_AUX_VARIABLE_POWER_OUTLET", INDIGO_OK_STATE));
	// The value is read back from the separate PS frame on the next poll.
	SERIAL_CHECK_TRUE(wait_for_number_item_value("X_AUX_VARIABLE_POWER_OUTLET", "OUTLET_1", 5, 0.01));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// The variable voltage the box reports is published by the poll, not only read at connect. The simulator sets it to
// 9 V from the third status frame on, without a command from the driver.
static void variable_power_outlet_change_reported_by_the_box_is_published(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--outlet-after", "2", "8", "9", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_number_item_value("X_AUX_VARIABLE_POWER_OUTLET", "OUTLET_1", 9, 0.01));
	SERIAL_CHECK_TRUE(wait_for_property_state("X_AUX_VARIABLE_POWER_OUTLET", INDIGO_OK_STATE));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static char heater_command_log[PATH_MAX];
static atomic_int heater_ok_updates, heater_ok_before_command;

static bool command_logged(const char *path, const char *command) {
	FILE *file = fopen(path, "r");
	bool found = false;
	if (file != NULL) {
		char line[128];
		while (!found && fgets(line, sizeof(line), file) != NULL) {
			line[strcspn(line, "\r\n")] = '\0';
			found = !strcmp(line, command);
		}
		fclose(file);
	}
	return found;
}

// The first OK after the heater request has to come after the box got the request; an OK the poll published before
// that is suppressed when the handler publishes the same values, so only its timing shows it.
static indigo_result check_heater_ok_updates(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	if (!strcmp(property->name, AUX_HEATER_OUTLET_PROPERTY_NAME) && property->state == INDIGO_OK_STATE) {
		if (atomic_fetch_add(&heater_ok_updates, 1) == 0 && !command_logged(heater_command_log, "P6:127")) {
			atomic_store(&heater_ok_before_command, 1);
		}
	}
	return simulator_client_update_property(client, device, property, message);
}

// A heater request copied after the poll adopted a changed heater from the status frame is not published OK by that
// poll before its handler sends it. The simulator changes heater 1 in the frame of the poll whose PC it answers 0.5 s
// late; heater 2 is requested meanwhile, so AUX_HEATER_OUTLET may turn OK only after the box got P6.
static void heater_request_survives_the_poll_publish(void) {
	external_serial_simulator simulator = { 0 };
	char slow_file[] = "/tmp/indigo-upb-slow.XXXXXX";
	int fd = mkstemp(slow_file);
	SERIAL_CHECK_TRUE(fd >= 0);
	close(fd);
	unlink(slow_file);
	snprintf(heater_command_log, sizeof(heater_command_log), "%s.log", slow_file);
	unlink(heater_command_log);
	const char *arguments[] = { "--slow-file", slow_file, "5", "128", "--command-log", heater_command_log, NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_HEATER_OUTLET_PROPERTY_NAME, INDIGO_OK_STATE));
	FILE *file = fopen(slow_file, "w");
	SERIAL_CHECK_TRUE(file != NULL);
	fclose(file);
	// the simulator removes the file at the PC of the poll that read the changed heater, then holds the reply back
	for (int i = 0; i < 400 && access(slow_file, F_OK) == 0; i++) {
		indigo_usleep(10000);
	}
	SERIAL_CHECK_TRUE(access(slow_file, F_OK) != 0);
	atomic_store(&heater_ok_updates, 0);
	atomic_store(&heater_ok_before_command, 0);
	simulator_test_client.update_property = check_heater_ok_updates;
	SERIAL_CHECK_TRUE(set_number(&aux, AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME, 50));
	indigo_usleep(2500000);
	printf("    AUX_HEATER_OUTLET published OK %s the box got P6:127\n", atomic_load(&heater_ok_before_command) ? "before" : "after");
	SERIAL_CHECK_TRUE(atomic_load(&heater_ok_updates) > 0);
	SERIAL_CHECK_EQ_INT(0, atomic_load(&heater_ok_before_command));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_2_ITEM_NAME, 50, 1));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_HEATER_OUTLET_PROPERTY_NAME, AUX_HEATER_OUTLET_1_ITEM_NAME, 50, 1));
cleanup:
	simulator_test_client.update_property = simulator_client_update_property;
	unlink(heater_command_log);
	unlink(slow_file);
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void outlet_names_relabel_the_controls(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_text_property_1_raw(&simulator_test_client, aux.device_name, AUX_OUTLET_NAMES_PROPERTY_NAME, AUX_POWER_OUTLET_NAME_1_ITEM_NAME, "Mount"));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_OUTLET_NAMES_PROPERTY_NAME, INDIGO_OK_STATE));
	indigo_item *item = find_cached_item(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME);
	SERIAL_CHECK_TRUE(item != NULL && !strcmp(item->label, "Mount"));
	item = find_cached_item(AUX_POWER_OUTLET_STATE_PROPERTY_NAME, AUX_POWER_OUTLET_STATE_1_ITEM_NAME);
	SERIAL_CHECK_TRUE(item != NULL && !strcmp(item->label, "Mount state"));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// Reboot and save-as-default are momentary: the driver clears the item again so a
// client never sees a latched request.
static void reboot_is_momentary(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(set_switch(&aux, "X_AUX_REBOOT", "REBOOT", true));
	SERIAL_CHECK_TRUE(wait_for_property_state("X_AUX_REBOOT", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value("X_AUX_REBOOT", "REBOOT", false));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void saving_outlet_states_is_momentary(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_SAVE_OUTLET_STATES_AS_DEFAULT_PROPERTY_NAME, AUX_SAVE_OUTLET_STATES_AS_DEFAULT_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_SAVE_OUTLET_STATES_AS_DEFAULT_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_SAVE_OUTLET_STATES_AS_DEFAULT_PROPERTY_NAME, AUX_SAVE_OUTLET_STATES_AS_DEFAULT_ITEM_NAME, false));
	// The saved mask is what the outlets currently are, so the second outlet stays off.
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_2_ITEM_NAME, false));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void reconnect_resumes_polling(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME, false));
	disconnect_serial_device(&aux);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connect_serial_device(&aux, NULL));
	// The device kept the outlet off, so the fresh status frame has to report it.
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_3_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME, 12.2, 0.01));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void repeated_disconnect_is_tolerated(void) {
	external_serial_simulator simulator = { 0 };
	bool online = true;
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	disconnect_serial_device(&aux);
	SERIAL_CHECK_TRUE(!context.connected);
	disconnect_serial_device(&aux);
	SERIAL_CHECK_TRUE(!context.connected);
	online = false;
	tear_down_serial_driver(&aux);
cleanup:
	if (online) {
		stop_serial_driver(&aux);
	}
	stop_external_serial_simulator(&simulator);
}

static void shutdown_is_refused_while_connected(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_EQ_INT(INDIGO_BUSY, indigo_aux_upb(INDIGO_DRIVER_SHUTDOWN, NULL));
	SERIAL_CHECK_TRUE(context.connected);
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// P# identifies the box and picks the v1 or v2 behaviour, so an answer that names
// neither model has to be refused rather than guessed.
static void unknown_identity_is_refused(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--fault", "P#", "invalid", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&aux));
	SERIAL_CHECK_TRUE(!connect_serial_device(&aux, simulator.port));
	SERIAL_CHECK_EQ_INT(INDIGO_ALERT_STATE, context.last_connection_state);
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// The firmware version is read as part of the same open, so losing it refuses the
// connection as well and leaves no half opened port behind.
static void firmware_read_failure_is_refused(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--fault", "PV", "silent", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&aux));
	SERIAL_CHECK_TRUE(!connect_serial_device(&aux, simulator.port));
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

static void vanished_port_is_refused(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&aux));
	stop_external_serial_simulator(&simulator);
	SERIAL_CHECK_TRUE(!connect_serial_device(&aux, simulator.port));
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&aux);
}

// The connect parses the whole status frame, so a truncated one leaves the driver
// without the outlet inventory and has to refuse the connection instead of
// publishing a half populated powerbox.
static void truncated_status_frame_refuses_the_connection(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--fault", "PA", "short", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&aux));
	SERIAL_CHECK_TRUE(!connect_serial_device(&aux, simulator.port));
	SERIAL_CHECK_EQ_INT(INDIGO_ALERT_STATE, context.last_connection_state);
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// A status frame lost while polling is a transient fault: the connection stays up
// and the next poll has to publish the real readings rather than a partial parse.
static void status_fault_while_polling_is_survived(void) {
	external_serial_simulator simulator = { 0 };
	// The connect consumes the first PA, so the fault is aimed at the first poll.
	const char *arguments[] = { "--fault-after", "1", "PA", "short", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(context.connected);
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME, 12.2, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_TEMPERATURE_ITEM_NAME, 23.2, 0.01));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_WEATHER_PROPERTY_NAME, AUX_WEATHER_HUMIDITY_ITEM_NAME, 59, 0.01));
	// The outlet mask survives the truncated frame rather than being cleared by it.
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, true));
	// The device is still usable afterwards.
	SERIAL_CHECK_TRUE(set_switch(&aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_4_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_4_ITEM_NAME, false));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

// ----------------------------------------------------------------- focuser

static void focuser_metadata_and_property_completeness(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	assert_device_interface(INDIGO_INTERFACE_FOCUSER);
	assert_serial_focuser_class_property_completeness();
	assert_property_has_item(FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MIN_POSITION_ITEM_NAME);
	assert_property_has_item(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME);
	assert_property_has_item(FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_ENABLED_ITEM_NAME);
	assert_property_has_item(FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_SYNC_ITEM_NAME);
	// The connect handler seeds the settings from the SA and SS frames.
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 50, 0));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 100, 0));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 400, 0));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_DISABLED_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, 22.4, 0.01));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

static void focuser_absolute_goto_reaches_the_target(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 500));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME) < 500);
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 500, 0));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	// A goto to the position the focuser already holds must still settle.
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 500));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 500, 0));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

static void focuser_relative_steps_move_both_directions(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 150));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 200, 0));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 100, 0));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

// The driver clamps a relative move against FOCUSER_LIMITS before it reaches the
// device, so the focuser stops at the limit rather than beyond it.
static void focuser_steps_are_clamped_by_the_limits(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MAX_POSITION_ITEM_NAME, 300));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 5000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 300, 0));
	// An absolute goto beyond the limit is clamped the same way.
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 9000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 300, 0));
cleanup:
	// FOCUSER_LIMITS is persistent, so the narrowed range would be restored on the next
	// attach and silently shorten a later case's move.
	set_number(&focuser, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MAX_POSITION_ITEM_NAME, 9999999);
	wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_OK_STATE);
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

static void focuser_abort_stops_the_motion(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 20000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_ABORT_MOTION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_property_not_busy(FOCUSER_POSITION_PROPERTY_NAME));
	double stopped = cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	SERIAL_CHECK_TRUE(stopped < 20000);
	// A fresh move has to be accepted right after the abort.
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, stopped + 40));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, stopped + 40, 0));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

// An abort while the focuser is idle is harmless and leaves the motion properties
// usable.
static void focuser_abort_while_idle_is_harmless(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_ABORT_MOTION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 120));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 120, 0));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

// SYNC updates the coordinate without moving the motor.
static void focuser_sync_relabels_the_position(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_SYNC_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_ON_POSITION_SET_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 4200));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 4200, 0));
	// The motor never ran, so the position property never went BUSY for a move.
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_GOTO_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 4260));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 4260, 0));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

static void focuser_settings_round_trip(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 800));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_SPEED_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 250));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_BACKLASH_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_ENABLED_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_REVERSE_MOTION_PROPERTY_NAME, INDIGO_OK_STATE));
	// Reconnecting re-reads all three from the device, which proves they were stored.
	disconnect_serial_device(&focuser);
	SERIAL_CHECK_TRUE(connect_serial_device(&focuser, NULL));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 800, 0));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 250, 0));
	SERIAL_CHECK_TRUE(wait_for_switch_item_value(FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_ENABLED_ITEM_NAME, true));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

// A second motion request while one is running is refused rather than queued.
static void focuser_overlapping_request_is_rejected(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_shared_serial_device(&focuser, aux.device_name, simulator.port));
	// FOCUSER_LIMITS and FOCUSER_ON_POSITION_SET are persistent and shared with the other
	// cases through the configuration, so the long move this case needs is set up
	// explicitly instead of relying on what ran before it.
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_GOTO_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_ON_POSITION_SET_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MAX_POSITION_ITEM_NAME, 9999999));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 400));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_SPEED_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_number(&focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 20000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(assert_refused_motion_request(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100));
	SERIAL_CHECK_TRUE(set_switch(&focuser, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_not_busy(FOCUSER_POSITION_PROPERTY_NAME));
cleanup:
	stop_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

// The focuser initialization parses the SA frame; a malformed one has to roll the
// connection back instead of leaving a half configured device.
static void focuser_initialization_failure_rolls_back(void) {
	external_serial_simulator simulator = { 0 };
	const char *arguments[] = { "--fault", "SA", "invalid", NULL };
	SERIAL_CHECK_TRUE(start_upb(&simulator, arguments));
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&focuser));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_text_property_1_raw(&simulator_test_client, aux.device_name, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, simulator.port));
	SERIAL_CHECK_TRUE(!connect_serial_device(&focuser, NULL));
	SERIAL_CHECK_EQ_INT(INDIGO_ALERT_STATE, context.last_connection_state);
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	tear_down_serial_driver(&focuser);
	stop_external_serial_simulator(&simulator);
}

// The focuser shares the powerbox connection, so it has to survive the powerbox
// being connected first and the port staying open for it.
static void focuser_shares_the_powerbox_connection(void) {
	external_serial_simulator simulator = { 0 };
	SERIAL_CHECK_TRUE(start_upb(&simulator, NULL));
	SERIAL_CHECK_TRUE(start_serial_driver(&aux, simulator.port));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME, 12.2, 0.01));
	reset_simulator_context(&focuser);
	enumerate_simulator_device();
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_switch_property_1(&simulator_test_client, focuser.device_name, CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(CONNECTION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 50, 0));
	// Closing the focuser must not take the powerbox connection down with it.
	disconnect_serial_device(&focuser);
	reset_simulator_context(&aux);
	enumerate_simulator_device();
	SERIAL_CHECK_TRUE(wait_for_property_state(CONNECTION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_INFO_PROPERTY_NAME, AUX_INFO_VOLTAGE_ITEM_NAME, 12.2, 0.01));
cleanup:
	stop_serial_driver(&aux);
	stop_external_serial_simulator(&simulator);
}

int main(void) {
	setvbuf(stdout, NULL, _IONBF, 0);
	// The driver saves persistent properties below HOME, so the run gets a private one
	// instead of writing into the user's configuration.
	char home[] = "/tmp/indigo-aux-upb.XXXXXX";
	if (mkdtemp(home) == NULL) {
		perror("mkdtemp");
		return 1;
	}
	setenv("HOME", home, 1);
	const indigo_test_case tests[] = {
		{ "metadata_and_property_completeness", metadata_and_property_completeness },
		{ "upb1_model_reduces_the_outlet_inventory", upb1_model_reduces_the_outlet_inventory },
		{ "connect_seeds_every_sensor_from_the_status_frame", connect_seeds_every_sensor_from_the_status_frame },
		{ "a_box_without_a_probe_reports_zero_weather", a_box_without_a_probe_reports_zero_weather },
		{ "each_power_outlet_switches_on_its_own", each_power_outlet_switches_on_its_own },
		{ "power_outlet_state_follows_the_switch", power_outlet_state_follows_the_switch },
		{ "overcurrent_raises_the_outlet_state", overcurrent_raises_the_outlet_state },
		{ "power_outlet_current_is_published", power_outlet_current_is_published },
		{ "heaters_hold_independent_duty_cycles", heaters_hold_independent_duty_cycles },
		{ "heater_state_and_current_follow_the_duty_cycle", heater_state_and_current_follow_the_duty_cycle },
		{ "automatic_dew_control_round_trips", automatic_dew_control_round_trips },
		{ "autodew_state_is_adopted_from_the_device", autodew_state_is_adopted_from_the_device },
		{ "dew_control_has_one_mode_when_the_connect_status_fails", dew_control_has_one_mode_when_the_connect_status_fails },
		{ "each_usb_port_switches_on_its_own", each_usb_port_switches_on_its_own },
		{ "usb_hub_switches_on_the_v1_box", usb_hub_switches_on_the_v1_box },
		{ "v1_without_a_smart_hub_hides_the_usb_ports", v1_without_a_smart_hub_hides_the_usb_ports },
		{ "v1_usb_ports_switch_through_the_smart_hub", v1_usb_ports_switch_through_the_smart_hub },
		{ "v1_usb_port_change_survives_a_concurrent_poll", v1_usb_port_change_survives_a_concurrent_poll },
		{ "v1_usb_port_failure_shows_the_hub_state", v1_usb_port_failure_shows_the_hub_state },
		{ "usb_port_failure_shows_the_box_state", usb_port_failure_shows_the_box_state },
		{ "power_outlet_failure_shows_the_box_state", power_outlet_failure_shows_the_box_state },
		{ "power_outlet_change_reported_by_the_box_is_published", power_outlet_change_reported_by_the_box_is_published },
		{ "dew_control_failure_shows_the_box_state", dew_control_failure_shows_the_box_state },
		{ "v1_hub_failure_shows_the_box_state", v1_hub_failure_shows_the_box_state },
		{ "v1_hub_change_reported_by_the_box_is_published", v1_hub_change_reported_by_the_box_is_published },
		{ "variable_power_outlet_round_trips", variable_power_outlet_round_trips },
		{ "variable_power_outlet_change_reported_by_the_box_is_published", variable_power_outlet_change_reported_by_the_box_is_published },
		{ "heater_request_survives_the_poll_publish", heater_request_survives_the_poll_publish },
		{ "outlet_names_relabel_the_controls", outlet_names_relabel_the_controls },
		{ "reboot_is_momentary", reboot_is_momentary },
		{ "saving_outlet_states_is_momentary", saving_outlet_states_is_momentary },
		{ "reconnect_resumes_polling", reconnect_resumes_polling },
		{ "repeated_disconnect_is_tolerated", repeated_disconnect_is_tolerated },
		{ "shutdown_is_refused_while_connected", shutdown_is_refused_while_connected },
		{ "unknown_identity_is_refused", unknown_identity_is_refused },
		{ "firmware_read_failure_is_refused", firmware_read_failure_is_refused },
		{ "vanished_port_is_refused", vanished_port_is_refused },
		{ "truncated_status_frame_refuses_the_connection", truncated_status_frame_refuses_the_connection },
		{ "status_fault_while_polling_is_survived", status_fault_while_polling_is_survived },
		{ "focuser_metadata_and_property_completeness", focuser_metadata_and_property_completeness },
		{ "focuser_absolute_goto_reaches_the_target", focuser_absolute_goto_reaches_the_target },
		{ "focuser_relative_steps_move_both_directions", focuser_relative_steps_move_both_directions },
		{ "focuser_steps_are_clamped_by_the_limits", focuser_steps_are_clamped_by_the_limits },
		{ "focuser_abort_stops_the_motion", focuser_abort_stops_the_motion },
		{ "focuser_abort_while_idle_is_harmless", focuser_abort_while_idle_is_harmless },
		{ "focuser_sync_relabels_the_position", focuser_sync_relabels_the_position },
		{ "focuser_settings_round_trip", focuser_settings_round_trip },
		{ "focuser_overlapping_request_is_rejected", focuser_overlapping_request_is_rejected },
		{ "focuser_initialization_failure_rolls_back", focuser_initialization_failure_rolls_back },
		{ "focuser_shares_the_powerbox_connection", focuser_shares_the_powerbox_connection }
	};
	int result = indigo_run_tests("Ultimate Powerbox serial simulator integration tests", tests, ARRAY_SIZE(tests));
	char command[PATH_MAX];
	snprintf(command, sizeof(command), "rm -rf '%s'", home);
	if (system(command) != 0) {
		fprintf(stderr, "Cannot remove %s\n", home);
	}
	return result;
}
