// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// Talon6 ROR driver tests against dome_talon6ror_simulator.
// Every case runs in its own child process with a fresh simulator, a
// temporary HOME and an alarm; the parent terminates the child's process
// group afterwards. Options:
//   --known-defects        run the defect reproducers only
//   --capture-trace PATH   write the normalized reference trace to PATH
// Environment: TALON6ROR_TEST_FILTER selects cases by substring,
// TALON6ROR_DEBUG enables driver debug logging and update tracing.

#include <errno.h>
#include <fcntl.h>
#include <ftw.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdatomic.h>
#include <sys/stat.h>

#include <indigo_drivers/dome_talon6ror/indigo_dome_talon6ror.h>

#include "serial_simulator_test_common.h"

#ifndef DOME_TALON6ROR_SIMULATOR_EXECUTABLE
#define DOME_TALON6ROR_SIMULATOR_EXECUTABLE "build/integration/dome_talon6ror_simulator"
#endif

#ifndef TALON6ROR_REFERENCE_TRACE_PATH
#define TALON6ROR_REFERENCE_TRACE_PATH "fixtures/dome_talon6ror/generated_reference_trace.txt"
#endif

#ifndef EXPECTED_API_GENERATION
#define EXPECTED_API_GENERATION INDIGO_DRIVER_API_3
#endif

#define DEVICE_NAME "Talon6 ROR"
#define SECOND_DEVICE_NAME "Talon6 ROR #2"
#define EXPECTED_LABEL "Talon6 ROR"

#define X_SENSORS_PROPERTY_NAME "X_SENSORS"
#define X_SENSORS_POWER_CONDITION_ITEM_NAME "POWER_CONDITION"
#define X_SENSORS_WEATHER_CONDITION_ITEM_NAME "WEATHER_CONDITION"
#define X_SENSORS_PARKED_SENSOR_ITEM_NAME "PARKED_SENSOR"
#define X_SENSORS_OPEN_SENSOR_ITEM_NAME "OPEN_SENSOR"
#define X_SENSORS_CLOSE_SENSOR_ITEM_NAME "CLOSE_SENSOR"
#define X_SENSORS_OPEN_BUTTON_ITEM_NAME "OPEN_BUTTON"
#define X_SENSORS_CLOSE_BUTTON_ITEM_NAME "CLOSE_BUTTON"
#define X_SENSORS_STOP_BUTTON_ITEM_NAME "STOP_BUTTON"

#define X_MOTOR_CONF_PROPERTY_NAME "X_MOTOR_CONF"
#define X_MOTOR_CONF_KP_ITEM_NAME "KP"
#define X_MOTOR_CONF_KI_ITEM_NAME "KI"
#define X_MOTOR_CONF_KD_ITEM_NAME "KD"
#define X_MOTOR_CONF_MAX_SPEED_ITEM_NAME "MAX_SPEED"
#define X_MOTOR_CONF_MIN_SPEED_ITEM_NAME "MIN_SPEED"
#define X_MOTOR_CONF_ACCELERATION_ITEM_NAME "ACCELERATION"
#define X_MOTOR_CONF_RAMP_ITEM_NAME "RAMP"
#define X_MOTOR_CONF_FULL_ENC_ITEM_NAME "FULL_ENC"
#define X_MOTOR_CONF_ENC_FACTOR_ITEM_NAME "ENC_FACTOR"
#define X_MOTOR_CONF_REVERSE_ITEM_NAME "REVERSE"

#define X_DELAY_CONF_PROPERTY_NAME "X_DELAY_CONF"
#define X_DELAY_CONF_PARK_ITEM_NAME "PARK"
#define X_DELAY_CONF_WEATHER_ITEM_NAME "WEATHER"
#define X_DELAY_CONF_POWER_ITEM_NAME "POWER"
#define X_DELAY_CONF_TIMEOUT_ITEM_NAME "TIMEOUT"

#define X_CLOSE_COND_PROPERTY_NAME "X_CLOSE_COND"
#define X_CLOSE_COND_WEATHER_ITEM_NAME "WEATHER"
#define X_CLOSE_COND_POWER_ITEM_NAME "POWER"
#define X_CLOSE_COND_TIMEOUT_ITEM_NAME "TIMEOUT"

#define X_CLOSE_TIMER_PROPERTY_NAME "X_TIMER_COND"
#define X_CLOSE_TIMER_WEATHER_ITEM_NAME "WEATHER"
#define X_CLOSE_TIMER_POWER_ITEM_NAME "POWER"
#define X_CLOSE_TIMER_TIMEOUT_ITEM_NAME "TIMEOUT"

#define X_POSITION_PROPERTY_NAME "X_POSITION_PROPERTY"
#define X_POSITION_ITEM_NAME "POSITION"

#define X_STATUS_PROPERTY_NAME "X_STATUS_PROPERTY"
#define X_STATUS_VOLTAGE_ITEM_NAME "VOLTAGE"

#define IDLE_MESSAGE_PROPERTY "IDLE"
#define ALERT_MESSAGE_PROPERTY "ALERT"

#define FULL_TRAVEL 50000
#define DEFAULT_SIMULATOR_ARGS "--travel-time 2"
#define STATUS_REQUEST "&G%#"

#define OBSERVED_MAX 96
#define MESSAGES_MAX 512
#define EVENTS_MAX 32768
#define TRACE_SIZE 262144

#define CHECK(condition) do { \
	if (!(condition)) { \
		fprintf(stderr, "%s:%d: check failed: %s\n", __FILE__, __LINE__, #condition); \
		indigo_test_failures++; \
		goto cleanup; \
	} \
} while (0)

#define CHECK_EQ(expected, actual) do { \
	long long expected_value = (long long)(expected); \
	long long actual_value = (long long)(actual); \
	if (expected_value != actual_value) { \
		fprintf(stderr, "%s:%d: expected %lld, got %lld: %s\n", __FILE__, __LINE__, expected_value, actual_value, #actual); \
		indigo_test_failures++; \
		goto cleanup; \
	} \
} while (0)

#define CHECK_NEAR(expected, actual, tolerance) do { \
	double expected_value = (expected); \
	double actual_value = (actual); \
	if (!(fabs(expected_value - actual_value) <= (tolerance))) { \
		fprintf(stderr, "%s:%d: expected %g, got %g: %s\n", __FILE__, __LINE__, expected_value, actual_value, #actual); \
		indigo_test_failures++; \
		goto cleanup; \
	} \
} while (0)

#define CHECK_STR(expected, actual) do { \
	const char *expected_value = (expected); \
	const char *actual_value = (actual); \
	if (actual_value == NULL || strcmp(expected_value, actual_value)) { \
		fprintf(stderr, "%s:%d: expected \"%s\", got \"%s\": %s\n", __FILE__, __LINE__, expected_value, actual_value ? actual_value : "(null)", #actual); \
		indigo_test_failures++; \
		goto cleanup; \
	} \
} while (0)

#define DEFECT_EXIT() do { \
	if (known_defects_mode && indigo_test_failures) { \
		fflush(NULL); \
		_exit(1); \
	} \
} while (0)

typedef struct {
	const char *name;
	void (*run)(void);
	const char *args;
	bool defect;
} talon6ror_case;

typedef struct {
	char name[INDIGO_NAME_SIZE];
	unsigned revision, busy, alert, defines, deletes;
	char last_trace[512];
} observed_property;

typedef struct {
	char property[INDIGO_NAME_SIZE];
	char text[INDIGO_VALUE_SIZE];
} observed_message;

typedef struct {
	char kind[12];
	char text[400];
} sim_event;

static const simulator_driver_case talon6ror_dome = {
	EXPECTED_LABEL, "indigo_dome_talon6ror", DEVICE_NAME, indigo_dome_talon6ror, false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static const simulator_driver_case talon6ror_second_dome = {
	EXPECTED_LABEL, "indigo_dome_talon6ror", SECOND_DEVICE_NAME, indigo_dome_talon6ror, false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static bool known_defects_mode;
static const char *capture_path;
static external_serial_simulator simulator, second_simulator;
static char fixture_dir[PATH_MAX], event_path[PATH_MAX], fault_path[PATH_MAX], control_path[PATH_MAX], home_path[PATH_MAX];
static pthread_mutex_t observe_mutex = PTHREAD_MUTEX_INITIALIZER;
static observed_property observed[OBSERVED_MAX];
static int observed_count;
static observed_message messages[MESSAGES_MAX];
static int message_count;
static sim_event events[EVENTS_MAX];
static char trace_text[TRACE_SIZE], trace_pending[TRACE_SIZE / 4];
static size_t trace_length, trace_pending_length;
static atomic_bool trace_active;
static int trace_mark;

// ---------------------------------------------------------------------------- utilities

static double now(void) {
	struct timespec time;
	clock_gettime(CLOCK_MONOTONIC, &time);
	return time.tv_sec + time.tv_nsec / 1e9;
}

static bool atomic_file(const char *path, const char *format, ...) __attribute__((format(printf, 2, 3)));

static bool atomic_file(const char *path, const char *format, ...) {
	char temporary[PATH_MAX + 8];
	snprintf(temporary, sizeof(temporary), "%s.tmp", path);
	FILE *file = fopen(temporary, "w");
	if (!file) {
		return false;
	}
	va_list args;
	va_start(args, format);
	vfprintf(file, format, args);
	va_end(args);
	fputc('\n', file);
	fclose(file);
	return rename(temporary, path) == 0;
}

static bool inject(const char *command, const char *action, int count) {
	return atomic_file(fault_path, "%s %s %d", command, action, count);
}

static bool inject_argument(const char *command, const char *action, int count, const char *argument) {
	return atomic_file(fault_path, "%s %s %d %s", command, action, count, argument);
}

static bool control(const char *key, const char *value) {
	if (!atomic_file(control_path, "%s %s", key, value)) {
		return false;
	}
	for (int i = 0; i < 200; i++) {
		if (access(control_path, F_OK) != 0) {
			return true;
		}
		indigo_usleep(10000);
	}
	return false;
}

static int open_descriptors(void) {
	int count = 0;
	for (int fd = 0; fd < 1024; fd++) {
		if (fcntl(fd, F_GETFD) >= 0) {
			count++;
		}
	}
	return count;
}

static bool start_simulator_with(external_serial_simulator *fixture, const char *extra) {
	static char buffer[512];
	const char *args[32];
	int count = 0;
	snprintf(buffer, sizeof(buffer), "%s %s", DEFAULT_SIMULATOR_ARGS, extra ? extra : "");
	for (char *token = strtok(buffer, " "); token && count < 31; token = strtok(NULL, " ")) {
		args[count++] = token;
	}
	args[count] = NULL;
	return start_external_serial_simulator_with_args(fixture, DOME_TALON6ROR_SIMULATOR_EXECUTABLE, args);
}

// ---------------------------------------------------------------------------- simulator event log

static int load_events(void) {
	FILE *file = fopen(event_path, "r");
	if (!file) {
		return 0;
	}
	char line[512];
	int count = 0;
	while (count < EVENTS_MAX && fgets(line, sizeof(line), file)) {
		size_t length = strlen(line);
		if (length == 0 || line[length - 1] != '\n') {
			break;
		}
		line[length - 1] = 0;
		double timestamp;
		int consumed = 0;
		if (sscanf(line, "%lf %11s %n", &timestamp, events[count].kind, &consumed) >= 2) {
			snprintf(events[count].text, sizeof(events[count].text), "%s", line + consumed);
			count++;
		}
	}
	fclose(file);
	return count;
}

static int rx_count(const char *request) {
	int count = load_events(), result = 0;
	for (int i = 0; i < count; i++) {
		if (!strcmp(events[i].kind, "RX") && !strcmp(events[i].text, request)) {
			result++;
		}
	}
	return result;
}

static int rx_prefix_count(const char *prefix) {
	int count = load_events(), result = 0;
	for (int i = 0; i < count; i++) {
		if (!strcmp(events[i].kind, "RX") && !strncmp(events[i].text, prefix, strlen(prefix))) {
			result++;
		}
	}
	return result;
}

static int rx_total(void) {
	int count = load_events(), result = 0;
	for (int i = 0; i < count; i++) {
		if (!strcmp(events[i].kind, "RX")) {
			result++;
		}
	}
	return result;
}

// commands other than the status request
static int command_count(void) {
	int count = load_events(), result = 0;
	for (int i = 0; i < count; i++) {
		if (!strcmp(events[i].kind, "RX") && strcmp(events[i].text, STATUS_REQUEST)) {
			result++;
		}
	}
	return result;
}

static bool wait_rx(const char *request, int expected, double timeout) {
	double end = now() + timeout;
	do {
		if (rx_count(request) >= expected) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "No %d x %s\n", expected, request);
	return false;
}

static bool wait_rx_prefix(const char *prefix, int expected, double timeout) {
	double end = now() + timeout;
	do {
		if (rx_prefix_count(prefix) >= expected) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "No %d x %s...\n", expected, prefix);
	return false;
}

static const char *last_request_with_prefix(const char *prefix) {
	static char request[400];
	int count = load_events();
	*request = 0;
	for (int i = 0; i < count; i++) {
		if (!strcmp(events[i].kind, "RX") && !strncmp(events[i].text, prefix, strlen(prefix))) {
			snprintf(request, sizeof(request), "%s", events[i].text);
		}
	}
	return request;
}

// index of the event following the reply of the n-th status request, or -1
static int poll_end_index(int count, int poll) {
	int seen = 0;
	for (int i = 0; i < count; i++) {
		if (!strcmp(events[i].kind, "RX") && !strcmp(events[i].text, STATUS_REQUEST) && ++seen == poll) {
			for (int j = i + 1; j < count && strcmp(events[j].kind, "RX"); j++) {
				if (!strcmp(events[j].kind, "TX")) {
					return j + 1;
				}
			}
			return -1;
		}
	}
	return -1;
}

static bool wait_polls(int polls, double timeout) {
	int target = rx_count(STATUS_REQUEST) + polls;
	double end = now() + timeout;
	do {
		int count = load_events();
		if (poll_end_index(count, target) >= 0) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "No %d status polls\n", polls);
	return false;
}

static bool rx_sequence(int mark, const char * const *expected, int expected_count, bool skip_polls, double timeout) {
	double end = now() + timeout;
	do {
		int count = load_events(), found = 0;
		bool matches = true;
		for (int i = mark; i < count && found < expected_count; i++) {
			if (strcmp(events[i].kind, "RX") || (skip_polls && !strcmp(events[i].text, STATUS_REQUEST) && strcmp(events[i].text, expected[found]))) {
				continue;
			}
			if (strcmp(events[i].text, expected[found])) {
				fprintf(stderr, "RX #%d: expected %s, got %s\n", found, expected[found], events[i].text);
				matches = false;
				break;
			}
			found++;
		}
		if (!matches) {
			return false;
		}
		if (found == expected_count) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "RX sequence incomplete\n");
	return false;
}

// decodes a logged frame ("&a 80 81 ...%#") back into bytes; returns the byte count
static int frame_bytes(const char *text, uint8_t *bytes, int max) {
	int count = 0;
	for (const char *pointer = text; *pointer && count < max; ) {
		if (*pointer == ' ') {
			unsigned value = 0;
			if (sscanf(pointer + 1, "%2x", &value) != 1) {
				return -1;
			}
			bytes[count++] = (uint8_t)value;
			pointer += 3;
		} else {
			bytes[count++] = (uint8_t)*pointer++;
		}
	}
	return count;
}

static int status_state(const char *reply) {
	uint8_t bytes[64];
	int count = frame_bytes(reply, bytes, sizeof(bytes));
	return count > 3 && bytes[1] == 'G' ? (bytes[2] & 0x70) >> 4 : -1;
}

static int status_action(const char *reply) {
	uint8_t bytes[64];
	int count = frame_bytes(reply, bytes, sizeof(bytes));
	return count > 3 && bytes[1] == 'G' ? bytes[2] & 0x0F : -1;
}

// ---------------------------------------------------------------------------- property observation

static observed_property *observed_entry(const char *name, bool add) {
	for (int i = 0; i < observed_count; i++) {
		if (!strcmp(observed[i].name, name)) {
			return observed + i;
		}
	}
	if (!add || observed_count == OBSERVED_MAX) {
		return NULL;
	}
	observed_property *entry = observed + observed_count++;
	memset(entry, 0, sizeof(*entry));
	snprintf(entry->name, sizeof(entry->name), "%s", name);
	return entry;
}

static void reset_observations(void) {
	pthread_mutex_lock(&observe_mutex);
	observed_count = 0;
	message_count = 0;
	pthread_mutex_unlock(&observe_mutex);
}

static bool is_current_device(indigo_property *property) {
	return context.driver_case != NULL && !strcmp(property->device, context.driver_case->device_name);
}

static const char *state_name(indigo_property_state state) {
	switch (state) {
		case INDIGO_IDLE_STATE:
			return "IDLE";
		case INDIGO_OK_STATE:
			return "OK";
		case INDIGO_BUSY_STATE:
			return "BUSY";
		default:
			return "ALERT";
	}
}

static bool traced_property(const char *name) {
	return strcmp(name, DEVICE_PORTS_PROPERTY_NAME) && strcmp(name, CONFIG_PROPERTY_NAME) && strcmp(name, PROFILE_PROPERTY_NAME) && strcmp(name, PROFILE_NAME_PROPERTY_NAME) && strcmp(name, GEOGRAPHIC_COORDINATES_PROPERTY_NAME) && strcmp(name, DOME_DIMENSION_PROPERTY_NAME);
}

// values that depend on elapsed time are masked in the trace
static bool masked_property(const char *name) {
	return !strcmp(name, X_POSITION_PROPERTY_NAME) || !strcmp(name, X_CLOSE_TIMER_PROPERTY_NAME) || !strcmp(name, X_STATUS_PROPERTY_NAME);
}

static void trace_pending_line(const char *line) {
	int written = snprintf(trace_pending + trace_pending_length, sizeof(trace_pending) - trace_pending_length, "%s\n", line);
	if (written > 0 && trace_pending_length + written < sizeof(trace_pending)) {
		trace_pending_length += written;
	}
}

static void trace_property(observed_property *entry, const char *kind, indigo_property *property) {
	if (!atomic_load(&trace_active) || !traced_property(property->name)) {
		return;
	}
	char line[512];
	size_t length = (size_t)snprintf(line, sizeof(line), "%s %s", kind, property->name);
	if (*kind != 'X') {
		length += (size_t)snprintf(line + length, sizeof(line) - length, " %s", state_name(property->state));
		if (*kind == 'D') {
			length += (size_t)snprintf(line + length, sizeof(line) - length, " %s count=%d", property->perm == INDIGO_RO_PERM ? "RO" : "RW", property->count);
		}
		bool masked = masked_property(property->name);
		for (int i = 0; i < property->count && length < sizeof(line); i++) {
			indigo_item *item = property->items + i;
			switch (property->type) {
				case INDIGO_NUMBER_VECTOR:
					if (masked) {
						length += (size_t)snprintf(line + length, sizeof(line) - length, " %s=*", item->name);
					} else {
						length += (size_t)snprintf(line + length, sizeof(line) - length, " %s=%g/%g", item->name, item->number.value, item->number.target);
					}
					break;
				case INDIGO_SWITCH_VECTOR:
					if (item->sw.value) {
						length += (size_t)snprintf(line + length, sizeof(line) - length, " %s", item->name);
					}
					break;
				case INDIGO_LIGHT_VECTOR:
					length += (size_t)snprintf(line + length, sizeof(line) - length, " %s=%s", item->name, state_name(item->light.value));
					break;
				case INDIGO_TEXT_VECTOR:
					if (!strcmp(property->name, DEVICE_PORT_PROPERTY_NAME)) {
						length += (size_t)snprintf(line + length, sizeof(line) - length, " %s=PORT", item->name);
					} else {
						length += (size_t)snprintf(line + length, sizeof(line) - length, " %s=%s", item->name, indigo_get_text_item_value(item));
					}
					break;
				default:
					break;
			}
		}
	}
	if (entry && *kind == 'U' && !strcmp(entry->last_trace, line)) {
		return;
	}
	if (entry) {
		snprintf(entry->last_trace, sizeof(entry->last_trace), "%s", line);
	}
	trace_pending_line(line);
}

static void note_state(observed_property *entry, indigo_property *property) {
	entry->revision++;
	if (property->state == INDIGO_BUSY_STATE) {
		entry->busy++;
	} else if (property->state == INDIGO_ALERT_STATE) {
		entry->alert++;
	}
}

static indigo_result observe_define(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	pthread_mutex_lock(&observe_mutex);
	indigo_result result = simulator_client_define_property(client, device, property, message);
	if (is_current_device(property)) {
		observed_property *entry = observed_entry(property->name, true);
		if (entry) {
			entry->defines++;
			note_state(entry, property);
			*entry->last_trace = 0;
		}
		trace_property(entry, "D", property);
	}
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static indigo_result observe_update(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	pthread_mutex_lock(&observe_mutex);
	indigo_result result = simulator_client_update_property(client, device, property, message);
	if (is_current_device(property)) {
		observed_property *entry = observed_entry(property->name, true);
		if (entry) {
			note_state(entry, property);
		}
		trace_property(entry, "U", property);
		if (getenv("TALON6ROR_DEBUG")) {
			fprintf(stderr, "%.3f U %s %s\n", now(), property->name, state_name(property->state));
		}
	}
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static indigo_result observe_delete(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	pthread_mutex_lock(&observe_mutex);
	indigo_result result = simulator_client_delete_property(client, device, property, message);
	if (is_current_device(property) && !*property->name) {
		release_cached_properties();
	} else if (is_current_device(property)) {
		observed_property *entry = observed_entry(property->name, true);
		if (entry) {
			entry->deletes++;
			*entry->last_trace = 0;
		}
		trace_property(entry, "X", property);
	}
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static indigo_result observe_message(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	pthread_mutex_lock(&observe_mutex);
	if (device != NULL && context.driver_case != NULL && !strcmp(device->name, context.driver_case->device_name) && message != NULL) {
		const char *name = property ? property->name : "";
		if (message_count < MESSAGES_MAX) {
			snprintf(messages[message_count].property, sizeof(messages[message_count].property), "%s", name);
			snprintf(messages[message_count].text, sizeof(messages[message_count].text), "%s", message);
			message_count++;
		}
		if (atomic_load(&trace_active)) {
			char line[512], text[INDIGO_VALUE_SIZE];
			snprintf(text, sizeof(text), "%s", message);
			char *port = strstr(text, " on /dev/");
			if (port) {
				strcpy(port, " on PORT");
			}
			snprintf(line, sizeof(line), "M %s \"%s\"", name, text);
			trace_pending_line(line);
		}
		if (getenv("TALON6ROR_DEBUG")) {
			fprintf(stderr, "%.3f M %s %s\n", now(), name, message);
		}
	}
	pthread_mutex_unlock(&observe_mutex);
	return INDIGO_OK;
}

static unsigned revision_of(const char *name) {
	pthread_mutex_lock(&observe_mutex);
	observed_property *entry = observed_entry(name, false);
	unsigned result = entry ? entry->revision : 0;
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static unsigned deletes_of(const char *name) {
	pthread_mutex_lock(&observe_mutex);
	observed_property *entry = observed_entry(name, false);
	unsigned result = entry ? entry->deletes : 0;
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static bool message_seen(const char *name, const char *text) {
	bool result = false;
	// a message follows its property update through a separate send_message callback
	for (int attempt = 0; attempt < 100 && !result; attempt++) {
		pthread_mutex_lock(&observe_mutex);
		for (int i = 0; i < message_count && !result; i++) {
			result = !strcmp(messages[i].property, name) && !strcmp(messages[i].text, text);
		}
		pthread_mutex_unlock(&observe_mutex);
		if (!result) {
			indigo_usleep(20000);
		}
	}
	if (!result) {
		fprintf(stderr, "No message \"%s\" for %s\n", text, name);
	}
	return result;
}

static int message_count_of(const char *text) {
	int result = 0;
	pthread_mutex_lock(&observe_mutex);
	for (int i = 0; i < message_count; i++) {
		result += !strcmp(messages[i].text, text);
	}
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static bool present(const char *name) {
	pthread_mutex_lock(&observe_mutex);
	bool result = find_cached_property(name) != NULL;
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static int state_of(const char *name) {
	pthread_mutex_lock(&observe_mutex);
	indigo_property *property = find_cached_property(name);
	int result = property ? (int)property->state : -1;
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static int count_of(const char *name) {
	pthread_mutex_lock(&observe_mutex);
	indigo_property *property = find_cached_property(name);
	int result = property ? property->count : -1;
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static int perm_of(const char *name) {
	pthread_mutex_lock(&observe_mutex);
	indigo_property *property = find_cached_property(name);
	int result = property ? (int)property->perm : -1;
	pthread_mutex_unlock(&observe_mutex);
	return result;
}

static bool item_of(const char *name, const char *item_name, indigo_item *copy) {
	pthread_mutex_lock(&observe_mutex);
	indigo_item *item = find_cached_item(name, item_name);
	if (item) {
		*copy = *item;
	}
	pthread_mutex_unlock(&observe_mutex);
	return item != NULL;
}

static double value_of(const char *name, const char *item_name) {
	indigo_item item;
	return item_of(name, item_name, &item) ? item.number.value : NAN;
}

static bool switch_of(const char *name, const char *item_name) {
	indigo_item item;
	return item_of(name, item_name, &item) && item.sw.value;
}

static int light_of(const char *name, const char *item_name) {
	indigo_item item;
	return item_of(name, item_name, &item) ? (int)item.light.value : -1;
}

static const char *text_of(const char *name, const char *item_name) {
	static char text[INDIGO_VALUE_SIZE];
	pthread_mutex_lock(&observe_mutex);
	indigo_item *item = find_cached_item(name, item_name);
	snprintf(text, sizeof(text), "%s", item ? indigo_get_text_item_value(item) : "");
	pthread_mutex_unlock(&observe_mutex);
	return text;
}

static bool wait_settled(const char *name, unsigned before, indigo_property_state expected, double timeout) {
	double end = now() + timeout;
	do {
		int state = state_of(name);
		if (revision_of(name) > before && state >= 0 && state != INDIGO_BUSY_STATE) {
			if (state == (int)expected) {
				return true;
			}
			fprintf(stderr, "%s settled in %s instead of %s\n", name, state_name(state), state_name(expected));
			return false;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "%s did not settle in %s\n", name, state_name(expected));
	return false;
}

static bool wait_state(const char *name, indigo_property_state expected, double timeout) {
	double end = now() + timeout;
	do {
		if (state_of(name) == (int)expected) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "%s is %s instead of %s\n", name, state_name(state_of(name)), state_name(expected));
	return false;
}

static bool wait_present(const char *name, bool expected, double timeout) {
	double end = now() + timeout;
	do {
		if (present(name) == expected) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "%s presence is not %d\n", name, expected);
	return false;
}

static bool wait_value(const char *name, const char *item_name, double expected, double tolerance, double timeout) {
	double end = now() + timeout;
	do {
		if (fabs(value_of(name, item_name) - expected) <= tolerance) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "%s.%s is %g instead of %g\n", name, item_name, value_of(name, item_name), expected);
	return false;
}

static bool wait_light(const char *name, const char *item_name, indigo_property_state expected, double timeout) {
	double end = now() + timeout;
	do {
		if (light_of(name, item_name) == (int)expected) {
			return true;
		}
		indigo_usleep(20000);
	} while (now() < end);
	fprintf(stderr, "%s.%s light is %s instead of %s\n", name, item_name, state_name(light_of(name, item_name)), state_name(expected));
	return false;
}

static indigo_result request_number(const char *name, const char *item, double value) {
	return indigo_change_number_property_1(&simulator_test_client, context.driver_case->device_name, name, item, value);
}

static indigo_result request_switch(const char *name, const char *item) {
	return indigo_change_switch_property_1(&simulator_test_client, context.driver_case->device_name, name, item, true);
}

static bool change_number(const char *name, const char *item, double value, indigo_property_state expected, double timeout) {
	unsigned before = revision_of(name);
	return request_number(name, item, value) == INDIGO_OK && wait_settled(name, before, expected, timeout);
}

static bool change_switch(const char *name, const char *item, indigo_property_state expected, double timeout) {
	unsigned before = revision_of(name);
	return request_switch(name, item) == INDIGO_OK && wait_settled(name, before, expected, timeout);
}

static bool open_roof(indigo_property_state expected, double timeout) {
	return change_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME, expected, timeout);
}

static bool close_roof(indigo_property_state expected, double timeout) {
	return change_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME, expected, timeout);
}

static bool abort_motion(indigo_property_state expected) {
	return change_switch(DOME_ABORT_MOTION_PROPERTY_NAME, DOME_ABORT_MOTION_ITEM_NAME, expected, 8);
}

// ---------------------------------------------------------------------------- driver lifecycle

static bool driver_up(void) {
	reset_observations();
	return bring_up_serial_driver(&talon6ror_dome);
}

static bool set_port(const char *port) {
	unsigned before = revision_of(DEVICE_PORT_PROPERTY_NAME);
	return indigo_change_text_property_1_raw(&simulator_test_client, context.driver_case->device_name, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, port) == INDIGO_OK && wait_settled(DEVICE_PORT_PROPERTY_NAME, before, strncmp(port, "/dev/indigo-", 12) ? INDIGO_OK_STATE : INDIGO_ALERT_STATE, 5);
}

static bool connect_to(const char *port, indigo_property_state expected, bool wait_first_poll) {
	if (!set_port(port)) {
		return false;
	}
	unsigned before = revision_of(CONNECTION_PROPERTY_NAME);
	// the connection flushes the controller banner for up to 5 s before the handshake
	if (request_switch(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME) != INDIGO_OK || !wait_settled(CONNECTION_PROPERTY_NAME, before, expected, 30)) {
		return false;
	}
	if (expected != INDIGO_OK_STATE) {
		return !switch_of(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME);
	}
	if (!switch_of(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME)) {
		return false;
	}
	return !wait_first_poll || (wait_polls(1, 5) && wait_present(X_SENSORS_PROPERTY_NAME, true, 2));
}

static bool disconnect(void) {
	unsigned before = revision_of(CONNECTION_PROPERTY_NAME);
	return request_switch(CONNECTION_PROPERTY_NAME, CONNECTION_DISCONNECTED_ITEM_NAME) == INDIGO_OK && wait_settled(CONNECTION_PROPERTY_NAME, before, INDIGO_OK_STATE, 15) && switch_of(CONNECTION_PROPERTY_NAME, CONNECTION_DISCONNECTED_ITEM_NAME);
}

static bool start_connected(void) {
	return driver_up() && connect_to(simulator.port, INDIGO_OK_STATE, true);
}

static void driver_down(void) {
	DEFECT_EXIT();
	if (switch_of(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME)) {
		disconnect();
	}
	indigo_result result = indigo_dome_talon6ror(INDIGO_DRIVER_SHUTDOWN, NULL);
	indigo_detach_client(&simulator_test_client);
	indigo_stop();
	pthread_mutex_lock(&observe_mutex);
	release_cached_properties();
	pthread_mutex_unlock(&observe_mutex);
	ASSERT_EQ_INT(INDIGO_OK, result);
}

// ---------------------------------------------------------------------------- simulator protocol

static bool exchange(indigo_uni_handle *handle, const char *request, uint8_t *reply, size_t size, long *length) {
	long written = indigo_uni_write(handle, request, (long)strlen(request));
	if (written != (long)strlen(request)) {
		return false;
	}
	long count = indigo_uni_read_section2(handle, (char *)reply, (long)size - 1, "#", "", INDIGO_DELAY(2), INDIGO_DELAY(1));
	if (count < 0) {
		return false;
	}
	reply[count] = 0;
	if (length) {
		*length = count;
	}
	return count > 0;
}

static int reply_position(const uint8_t *reply) {
	return ((reply[3] & 0x7F) << 14) | ((reply[4] & 0x7F) << 7) | (reply[5] & 0x7F);
}

static bool reply_checksum_valid(const uint8_t *reply, int payload) {
	int sum = 0;
	for (int i = 2; i < 2 + payload; i++) {
		sum += reply[i];
	}
	return reply[2 + payload] == (uint8_t)(0x80 | (-(sum % 128) & 0x7F));
}

static void simulator_protocol(void) {
	uint8_t reply[256];
	long length = 0;
	indigo_uni_handle *handle = indigo_uni_open_serial(simulator.port, INDIGO_LOG_DEBUG);
	CHECK(handle != NULL);
	CHECK(exchange(handle, "&V%#", reply, sizeof(reply), &length));
	CHECK_STR("&V3.20N--#", (const char *)reply);
	CHECK(exchange(handle, "&p%#", reply, sizeof(reply), &length));
	CHECK_EQ(58, length);
	CHECK(reply[1] == 'p' && reply_checksum_valid(reply, 54));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(24, length);
	CHECK(reply[1] == 'G' && reply_checksum_valid(reply, 20));
	CHECK_EQ(1, (reply[2] & 0x70) >> 4);
	CHECK_EQ(0, reply_position(reply));
	CHECK_EQ(836, ((reply[6] & 0x7F) << 7) | (reply[7] & 0x7F));
	// closed sensor and mount at park
	CHECK_EQ(0x14, reply[16] & 0x7F);
	CHECK(exchange(handle, "&X%#", reply, sizeof(reply), &length));
	CHECK_STR("&ERROR#", (const char *)reply);
	// elapsed-time travel over the configured encoder ticks
	double started = now();
	CHECK(exchange(handle, "&O%#", reply, sizeof(reply), &length));
	CHECK_STR("&#", (const char *)reply);
	indigo_usleep(500000);
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(2, (reply[2] & 0x70) >> 4);
	CHECK_EQ(1, reply[2] & 0x0F);
	CHECK(reply_position(reply) > 1000 && reply_position(reply) < FULL_TRAVEL);
	for (int i = 0; i < 200 && (reply[2] & 0x70) != 0; i++) {
		indigo_usleep(20000);
		CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	}
	CHECK_EQ(0, (reply[2] & 0x70) >> 4);
	CHECK_EQ(FULL_TRAVEL, reply_position(reply));
	CHECK(now() - started >= 1.8);
	// open sensor
	CHECK_EQ(0x0C, reply[16] & 0x7F);
	// stop between the end positions reports the error state
	CHECK(exchange(handle, "&P%#", reply, sizeof(reply), &length));
	indigo_usleep(600000);
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(3, (reply[2] & 0x70) >> 4);
	CHECK_EQ(2, reply[2] & 0x0F);
	CHECK(exchange(handle, "&S%#", reply, sizeof(reply), &length));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(4, (reply[2] & 0x70) >> 4);
	CHECK_EQ(14, reply[2] & 0x0F);
	int stopped = reply_position(reply);
	indigo_usleep(300000);
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(stopped, reply_position(reply));
	// close without mount park
	CHECK(exchange(handle, "&C%#", reply, sizeof(reply), &length));
	for (int i = 0; i < 200 && (reply[2] & 0x70) != 0x10; i++) {
		indigo_usleep(20000);
		CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	}
	CHECK_EQ(1, (reply[2] & 0x70) >> 4);
	CHECK_EQ(0, reply_position(reply));
	// close with mount park waits for the park sensor
	CHECK(control("parked", "0"));
	CHECK(exchange(handle, "&O%#", reply, sizeof(reply), &length));
	indigo_usleep(2100000);
	CHECK(exchange(handle, "&P%#", reply, sizeof(reply), &length));
	indigo_usleep(300000);
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(0, (reply[2] & 0x70) >> 4);
	CHECK_EQ(15, reply[2] & 0x0F);
	CHECK(control("parked", "1"));
	indigo_usleep(300000);
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(3, (reply[2] & 0x70) >> 4);
	CHECK_EQ(2, reply[2] & 0x0F);
	CHECK(exchange(handle, "&S%#", reply, sizeof(reply), &length));
	// safety conditions refuse opening
	CHECK(control("weather", "1"));
	CHECK(exchange(handle, "&O%#", reply, sizeof(reply), &length));
	CHECK_STR("&#", (const char *)reply);
	indigo_usleep(300000);
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(4, (reply[2] & 0x70) >> 4);
	CHECK_EQ(0x02, reply[16] & 0x02);
	CHECK(control("weather", "0"));
	// buttons and external control
	CHECK(control("position", "0"));
	CHECK(control("button", "open"));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(2, (reply[2] & 0x70) >> 4);
	CHECK_EQ(0x20, reply[16] & 0x20);
	CHECK(control("stall", "1"));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(4, (reply[2] & 0x70) >> 4);
	CHECK_EQ(13, reply[2] & 0x0F);
	CHECK(control("voltage", "700"));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_EQ(700, ((reply[6] & 0x7F) << 7) | (reply[7] & 0x7F));
	// fault injection
	CHECK(inject("G", "error", 1));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_STR("&ERROR#", (const char *)reply);
	CHECK(inject("G", "checksum", 1));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK(!reply_checksum_valid(reply, 20));
	CHECK(inject("G", "short", 1));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK(length < 24);
	CHECK(inject("G", "garbage", 1));
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK_STR("x#", (const char *)reply);
	CHECK(exchange(handle, "", reply, sizeof(reply), &length));
	CHECK(inject("G", "silent", 1));
	CHECK(!exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK(inject_argument("G", "slow", 1, "300"));
	started = now();
	CHECK(exchange(handle, "&G%#", reply, sizeof(reply), &length));
	CHECK(now() - started >= 0.25);
	// configuration write validation
	CHECK(exchange(handle, "&p%#", reply, sizeof(reply), &length));
	uint8_t frame[64];
	frame[0] = '&';
	frame[1] = 'a';
	memcpy(frame + 2, reply + 2, 55);
	frame[3] = 0x81;
	frame[4] = 0xC8;
	int sum = 0;
	for (int i = 2; i < 56; i++) {
		sum += frame[i];
	}
	frame[56] = (uint8_t)(0x80 | (-(sum % 128) & 0x7F));
	frame[57] = '%';
	frame[58] = '#';
	CHECK(indigo_uni_write(handle, (const char *)frame, 59) == 59);
	CHECK(indigo_uni_read_section2(handle, (char *)reply, sizeof(reply) - 1, "#", "", INDIGO_DELAY(2), INDIGO_DELAY(1)) == 2);
	frame[56] ^= 0x01;
	CHECK(indigo_uni_write(handle, (const char *)frame, 59) == 59);
	length = indigo_uni_read_section2(handle, (char *)reply, sizeof(reply) - 1, "#", "", INDIGO_DELAY(2), INDIGO_DELAY(1));
	reply[length] = 0;
	CHECK_STR("&ERROR#", (const char *)reply);
	CHECK(exchange(handle, "&p%#", reply, sizeof(reply), &length));
	CHECK_EQ(200, ((reply[2] & 0x7F) << 14) | ((reply[3] & 0x7F) << 7) | (reply[4] & 0x7F));
cleanup:
	indigo_uni_close(&handle);
}

// ---------------------------------------------------------------------------- characterization cases

static void metadata_before_connection(void) {
	indigo_driver_info info = { 0 };
	CHECK_EQ(INDIGO_OK, indigo_dome_talon6ror(INDIGO_DRIVER_INFO, &info));
	CHECK_STR(EXPECTED_LABEL, info.description);
	CHECK_STR("indigo_dome_talon6ror", info.name);
	CHECK_EQ(EXPECTED_API_GENERATION, INDIGO_DRIVER_API_GENERATION(info.version));
	CHECK(!info.multi_device_support);
	CHECK(driver_up());
	assert_device_interface(INDIGO_INTERFACE_DOME);
	CHECK(present(DEVICE_PORT_PROPERTY_NAME) && present(DEVICE_PORTS_PROPERTY_NAME));
	CHECK(present(ADDITIONAL_INSTANCES_PROPERTY_NAME) && present(CONNECTION_PROPERTY_NAME) && present(INFO_PROPERTY_NAME) && present(CONFIG_PROPERTY_NAME));
	CHECK(!present(X_SENSORS_PROPERTY_NAME) && !present(X_MOTOR_CONF_PROPERTY_NAME) && !present(X_POSITION_PROPERTY_NAME));
	CHECK(!present(DOME_SHUTTER_PROPERTY_NAME) && !present(DOME_ABORT_MOTION_PROPERTY_NAME));
	CHECK_EQ(0, rx_total());
cleanup:
	driver_down();
}

static void connect_sequence(void) {
	static const char * const sequence[] = { "&V%#", "&p%#", STATUS_REQUEST };
	indigo_item item;
	double started = now();
	CHECK(start_connected());
	// the connection drains the controller banner for 5 s before the handshake
	CHECK(now() - started >= 4.5);
	CHECK(rx_sequence(0, sequence, ARRAY_SIZE(sequence), false, 3));
	CHECK_STR("3.20N--", text_of(INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME));
	CHECK_STR("Talon6 ROR", text_of(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME));
	CHECK_EQ(6, count_of(INFO_PROPERTY_NAME));
	assert_device_interface(INDIGO_INTERFACE_DOME);
	CHECK(present(DOME_SHUTTER_PROPERTY_NAME) && present(DOME_ABORT_MOTION_PROPERTY_NAME));
	CHECK(!present(DOME_SPEED_PROPERTY_NAME) && !present(DOME_DIRECTION_PROPERTY_NAME) && !present(DOME_STEPS_PROPERTY_NAME));
	CHECK(!present(DOME_HORIZONTAL_COORDINATES_PROPERTY_NAME) && !present(DOME_PARK_PROPERTY_NAME) && !present(DOME_DIMENSION_PROPERTY_NAME));
	CHECK(!present(DOME_SLAVING_PARAMETERS_PROPERTY_NAME) && !present(DOME_FLAP_PROPERTY_NAME));
	CHECK(present(X_SENSORS_PROPERTY_NAME) && present(X_MOTOR_CONF_PROPERTY_NAME) && present(X_DELAY_CONF_PROPERTY_NAME));
	CHECK(present(X_CLOSE_COND_PROPERTY_NAME) && present(X_CLOSE_TIMER_PROPERTY_NAME) && present(X_POSITION_PROPERTY_NAME) && present(X_STATUS_PROPERTY_NAME));
	CHECK_EQ(8, count_of(X_SENSORS_PROPERTY_NAME));
	CHECK_EQ(10, count_of(X_MOTOR_CONF_PROPERTY_NAME));
	CHECK_EQ(4, count_of(X_DELAY_CONF_PROPERTY_NAME));
	CHECK_EQ(3, count_of(X_CLOSE_COND_PROPERTY_NAME));
	CHECK_EQ(INDIGO_RO_PERM, perm_of(X_CLOSE_TIMER_PROPERTY_NAME));
	CHECK_EQ(INDIGO_RO_PERM, perm_of(X_POSITION_PROPERTY_NAME));
	CHECK_EQ(INDIGO_RW_PERM, perm_of(X_MOTOR_CONF_PROPERTY_NAME));
	// configuration values of the simulator
	CHECK_EQ(180, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME));
	CHECK_EQ(140, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KI_ITEM_NAME));
	CHECK_EQ(2, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KD_ITEM_NAME));
	CHECK_EQ(100, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_MAX_SPEED_ITEM_NAME));
	CHECK_EQ(14, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_MIN_SPEED_ITEM_NAME));
	CHECK_EQ(20, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_ACCELERATION_ITEM_NAME));
	CHECK_EQ(5, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_RAMP_ITEM_NAME));
	CHECK_EQ(FULL_TRAVEL, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_FULL_ENC_ITEM_NAME));
	CHECK_EQ(4, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_ENC_FACTOR_ITEM_NAME));
	CHECK_EQ(0, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_REVERSE_ITEM_NAME));
	CHECK_EQ(120, value_of(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_PARK_ITEM_NAME));
	CHECK_EQ(60, value_of(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_WEATHER_ITEM_NAME));
	CHECK_EQ(54, value_of(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_POWER_ITEM_NAME));
	CHECK(!switch_of(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_WEATHER_ITEM_NAME));
	CHECK(!switch_of(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_POWER_ITEM_NAME));
	CHECK(!switch_of(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_TIMEOUT_ITEM_NAME));
	// status values of the first poll
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK_EQ(INDIGO_OK_STATE, state_of(DOME_SHUTTER_PROPERTY_NAME));
	// the closed roof matches the initial switch, so no shutter update is published
	CHECK_EQ(0, message_count_of("Roof closed"));
	CHECK(wait_value(X_STATUS_PROPERTY_NAME, X_STATUS_VOLTAGE_ITEM_NAME, 12.2, 0.01, 3));
	CHECK_EQ(0, value_of(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_CLOSE_SENSOR_ITEM_NAME, INDIGO_OK_STATE, 3));
	CHECK_EQ(INDIGO_OK_STATE, light_of(X_SENSORS_PROPERTY_NAME, X_SENSORS_PARKED_SENSOR_ITEM_NAME));
	CHECK_EQ(INDIGO_IDLE_STATE, light_of(X_SENSORS_PROPERTY_NAME, X_SENSORS_OPEN_SENSOR_ITEM_NAME));
	CHECK_EQ(INDIGO_IDLE_STATE, light_of(X_SENSORS_PROPERTY_NAME, X_SENSORS_POWER_CONDITION_ITEM_NAME));
	CHECK_EQ(INDIGO_IDLE_STATE, light_of(X_SENSORS_PROPERTY_NAME, X_SENSORS_WEATHER_CONDITION_ITEM_NAME));
	CHECK(item_of(X_SENSORS_PROPERTY_NAME, X_SENSORS_STOP_BUTTON_ITEM_NAME, &item));
	CHECK(wait_polls(2, 3));
	CHECK_EQ(2, command_count());
cleanup:
	driver_down();
}

static void connect_with_open_roof(void) {
	CHECK(start_connected());
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK_EQ(INDIGO_OK_STATE, state_of(DOME_SHUTTER_PROPERTY_NAME));
	CHECK(message_seen(DOME_SHUTTER_PROPERTY_NAME, "Roof opened"));
	CHECK(wait_value(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME, FULL_TRAVEL, 0, 3));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_OPEN_SENSOR_ITEM_NAME, INDIGO_OK_STATE, 3));
	CHECK_EQ(INDIGO_IDLE_STATE, light_of(X_SENSORS_PROPERTY_NAME, X_SENSORS_CLOSE_SENSOR_ITEM_NAME));
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Open requested by user"));
cleanup:
	driver_down();
}

static void connection_failures_and_recovery(void) {
	CHECK(driver_up());
	CHECK(connect_to("/dev/indigo-talon6ror-nonexistent", INDIGO_ALERT_STATE, false));
	int descriptors = open_descriptors();
	CHECK(inject("V", "silent", 1));
	CHECK(connect_to(simulator.port, INDIGO_ALERT_STATE, false));
	CHECK(message_seen(ALERT_MESSAGE_PROPERTY, "Handshake failed"));
	CHECK_EQ(descriptors, open_descriptors());
	CHECK(!present(X_SENSORS_PROPERTY_NAME) && !present(X_MOTOR_CONF_PROPERTY_NAME));
	CHECK(inject("V", "error", 1));
	CHECK(connect_to(simulator.port, INDIGO_ALERT_STATE, false));
	CHECK_EQ(0, rx_count("&p%#"));
	CHECK_EQ(descriptors, open_descriptors());
	CHECK(inject("p", "checksum", 1));
	CHECK(connect_to(simulator.port, INDIGO_ALERT_STATE, false));
	CHECK(message_seen(ALERT_MESSAGE_PROPERTY, "Checksum error, handshake failed"));
	CHECK_EQ(descriptors, open_descriptors());
	CHECK(inject("p", "silent", 1));
	CHECK(connect_to(simulator.port, INDIGO_ALERT_STATE, false));
	CHECK_EQ(descriptors, open_descriptors());
	CHECK_EQ(0, rx_count(STATUS_REQUEST));
	CHECK(connect_to(simulator.port, INDIGO_OK_STATE, true));
	CHECK_STR("3.20N--", text_of(INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME));
	CHECK(disconnect());
	CHECK_EQ(descriptors, open_descriptors());
cleanup:
	driver_down();
}

static void open_and_close_roof(void) {
	CHECK(start_connected());
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 3));
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Open requested by user"));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_OK_STATE, 15));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(message_seen(DOME_SHUTTER_PROPERTY_NAME, "Roof opened"));
	CHECK(wait_value(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME, FULL_TRAVEL, 0, 3));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_OPEN_SENSOR_ITEM_NAME, INDIGO_OK_STATE, 3));
	before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(wait_rx("&P%#", 1, 5));
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Close requested by user"));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_OK_STATE, 15));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(message_seen(DOME_SHUTTER_PROPERTY_NAME, "Roof closed"));
	CHECK(wait_value(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME, 0, 0, 3));
	CHECK_EQ(1, rx_count("&O%#"));
	CHECK_EQ(1, rx_count("&P%#"));
cleanup:
	driver_down();
}

static void open_when_already_open(void) {
	CHECK(start_connected());
	CHECK(open_roof(INDIGO_OK_STATE, 10));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK_EQ(1, rx_count("&O%#"));
	CHECK(wait_polls(2, 5));
	CHECK_EQ(INDIGO_OK_STATE, state_of(DOME_SHUTTER_PROPERTY_NAME));
cleanup:
	driver_down();
}

static void abort_while_opening(void) {
	CHECK(start_connected());
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 3));
	CHECK(wait_polls(1, 5));
	CHECK(abort_motion(INDIGO_OK_STATE));
	CHECK_EQ(1, rx_count("&S%#"));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_ALERT_STATE, 5));
	CHECK(!switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(!switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(wait_polls(2, 5));
	double position = value_of(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME);
	CHECK(position > 0 && position < FULL_TRAVEL);
	CHECK(wait_polls(2, 5));
	CHECK_EQ(position, value_of(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME));
	// the roof can be closed after the abort
	CHECK(close_roof(INDIGO_OK_STATE, 15));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
cleanup:
	driver_down();
}

static void abort_when_idle_alerts(void) {
	CHECK(start_connected());
	CHECK(abort_motion(INDIGO_ALERT_STATE));
	CHECK_EQ(0, rx_count("&S%#"));
	CHECK_EQ(INDIGO_OK_STATE, state_of(DOME_SHUTTER_PROPERTY_NAME));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
cleanup:
	driver_down();
}

static void status_checksum_error_and_recovery(void) {
	CHECK(start_connected());
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK(inject("G", "checksum", 1));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_ALERT_STATE, 5));
	CHECK(message_seen(DOME_SHUTTER_PROPERTY_NAME, "Checksum error"));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_OK_STATE, 5));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
cleanup:
	driver_down();
}

static void status_read_failures(void) {
	CHECK(start_connected());
	unsigned revision = revision_of(X_POSITION_PROPERTY_NAME);
	CHECK(inject("G", "silent", 2));
	indigo_usleep(1000000);
	CHECK_EQ(revision, revision_of(X_POSITION_PROPERTY_NAME));
	CHECK_EQ(INDIGO_OK_STATE, state_of(DOME_SHUTTER_PROPERTY_NAME));
	CHECK(inject("G", "short", 1));
	indigo_usleep(1000000);
	CHECK(inject("G", "garbage", 1));
	// a reply preceded by noise is still parsed
	CHECK(wait_polls(3, 20));
	CHECK(open_roof(INDIGO_OK_STATE, 15));
	CHECK(wait_value(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME, FULL_TRAVEL, 0, 5));
cleanup:
	driver_down();
}

static void sensors_and_buttons(void) {
	CHECK(start_connected());
	unsigned revision = revision_of(X_SENSORS_PROPERTY_NAME);
	CHECK(wait_polls(2, 5));
	CHECK_EQ(revision, revision_of(X_SENSORS_PROPERTY_NAME));
	CHECK(control("weather", "1"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_WEATHER_CONDITION_ITEM_NAME, INDIGO_ALERT_STATE, 5));
	CHECK(control("power", "1"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_POWER_CONDITION_ITEM_NAME, INDIGO_ALERT_STATE, 5));
	CHECK(control("parked", "0"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_PARKED_SENSOR_ITEM_NAME, INDIGO_IDLE_STATE, 5));
	CHECK(control("button", "stop"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_STOP_BUTTON_ITEM_NAME, INDIGO_BUSY_STATE, 5));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_STOP_BUTTON_ITEM_NAME, INDIGO_IDLE_STATE, 5));
	CHECK(control("weather", "0"));
	CHECK(control("power", "0"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_WEATHER_CONDITION_ITEM_NAME, INDIGO_IDLE_STATE, 5));
	CHECK_EQ(INDIGO_IDLE_STATE, light_of(X_SENSORS_PROPERTY_NAME, X_SENSORS_POWER_CONDITION_ITEM_NAME));
cleanup:
	driver_down();
}

static void manual_open_by_button(void) {
	CHECK(start_connected());
	CHECK(control("button", "open"));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 5));
	CHECK(message_seen(DOME_SHUTTER_PROPERTY_NAME, "Roof opening"));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_OK_STATE, 15));
	CHECK(message_seen(DOME_SHUTTER_PROPERTY_NAME, "Roof opened"));
	CHECK_EQ(0, rx_count("&O%#"));
	// an abort stops a roof moved by the keypad
	CHECK(control("button", "close"));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 5));
	CHECK(abort_motion(INDIGO_OK_STATE));
	CHECK_EQ(1, rx_count("&S%#"));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_ALERT_STATE, 5));
cleanup:
	driver_down();
}

static void condition_close(void) {
	CHECK(start_connected());
	CHECK(open_roof(INDIGO_OK_STATE, 15));
	CHECK(change_number(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_WEATHER_ITEM_NAME, 2, INDIGO_OK_STATE, 5));
	CHECK(change_switch(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_WEATHER_ITEM_NAME, INDIGO_OK_STATE, 5));
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK(control("weather", "1"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_WEATHER_CONDITION_ITEM_NAME, INDIGO_ALERT_STATE, 5));
	CHECK(wait_value(X_CLOSE_TIMER_PROPERTY_NAME, X_CLOSE_TIMER_WEATHER_ITEM_NAME, 2, 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 8));
	CHECK(message_seen(DOME_SHUTTER_PROPERTY_NAME, "Roof closing"));
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Close due to weather"));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_OK_STATE, 15));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK_EQ(0, rx_count("&P%#"));
cleanup:
	driver_down();
}

static void configuration_writes(void) {
	uint8_t bytes[64];
	CHECK(start_connected());
	CHECK(change_number(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME, 200, INDIGO_OK_STATE, 5));
	CHECK(wait_rx_prefix("&a", 1, 3));
	CHECK_EQ(59, frame_bytes(last_request_with_prefix("&a"), bytes, sizeof(bytes)));
	CHECK_EQ(200, ((bytes[2] & 0x7F) << 14) | ((bytes[3] & 0x7F) << 7) | (bytes[4] & 0x7F));
	// unrelated configuration bytes are preserved: communication delay 60, IP switch 120, TW time 120
	CHECK_EQ(60, ((bytes[29] & 0x7F) << 14) | ((bytes[30] & 0x7F) << 7) | (bytes[31] & 0x7F));
	CHECK_EQ(120, ((bytes[35] & 0x7F) << 14) | ((bytes[36] & 0x7F) << 7) | (bytes[37] & 0x7F));
	CHECK_EQ(120, ((bytes[53] & 0x7F) << 14) | ((bytes[54] & 0x7F) << 7) | (bytes[55] & 0x7F));
	int sum = 0;
	for (int i = 2; i < 56; i++) {
		sum += bytes[i];
	}
	CHECK_EQ((uint8_t)(0x80 | (-(sum % 128) & 0x7F)), bytes[56]);
	CHECK(change_number(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_WEATHER_ITEM_NAME, 90, INDIGO_OK_STATE, 5));
	CHECK(wait_rx_prefix("&a", 2, 3));
	CHECK_EQ(59, frame_bytes(last_request_with_prefix("&a"), bytes, sizeof(bytes)));
	CHECK_EQ(90, ((bytes[23] & 0x7F) << 14) | ((bytes[24] & 0x7F) << 7) | (bytes[25] & 0x7F));
	CHECK_EQ(200, ((bytes[2] & 0x7F) << 14) | ((bytes[3] & 0x7F) << 7) | (bytes[4] & 0x7F));
	CHECK(change_switch(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_POWER_ITEM_NAME, INDIGO_OK_STATE, 5));
	CHECK(wait_rx_prefix("&a", 3, 3));
	CHECK_EQ(59, frame_bytes(last_request_with_prefix("&a"), bytes, sizeof(bytes)));
	CHECK_EQ(0x01, bytes[49] & 0x07);
	CHECK(change_number(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_ENC_FACTOR_ITEM_NAME, 2, INDIGO_OK_STATE, 5));
	CHECK(wait_rx_prefix("&a", 4, 3));
	CHECK_EQ(59, frame_bytes(last_request_with_prefix("&a"), bytes, sizeof(bytes)));
	CHECK_EQ(2, bytes[47] & 0x7F);
	CHECK_EQ(0x01, bytes[49] & 0x07);
	// the controller keeps the written values: they are read back after a reconnection
	CHECK(disconnect());
	CHECK(connect_to(simulator.port, INDIGO_OK_STATE, true));
	CHECK_EQ(200, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME));
	CHECK_EQ(90, value_of(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_WEATHER_ITEM_NAME));
	CHECK_EQ(2, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_ENC_FACTOR_ITEM_NAME));
	CHECK(switch_of(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_POWER_ITEM_NAME));
	CHECK(!switch_of(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_WEATHER_ITEM_NAME));
cleanup:
	driver_down();
}

static void busy_requests_rejected(void) {
	CHECK(start_connected());
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 3));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_OK_STATE, 15));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK_EQ(0, rx_count("&P%#"));
	CHECK_EQ(1, rx_count("&O%#"));
cleanup:
	driver_down();
}

static void busy_guard_holds_while_command_runs(void) {
	CHECK(start_connected());
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK(inject_argument("O", "slow", 1, "800"));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_OK_STATE, 20));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK_EQ(0, rx_count("&P%#"));
cleanup:
	driver_down();
}

static void disconnect_during_motion(void) {
	CHECK(start_connected());
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 3));
	CHECK(disconnect());
	// the roof is not stopped on disconnect and no further requests are sent
	CHECK_EQ(0, rx_count("&S%#"));
	int total = rx_total();
	indigo_usleep(2000000);
	CHECK_EQ(total, rx_total());
	CHECK(!present(X_SENSORS_PROPERTY_NAME) && !present(X_POSITION_PROPERTY_NAME) && !present(DOME_SHUTTER_PROPERTY_NAME));
	CHECK(connect_to(simulator.port, INDIGO_OK_STATE, true));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_value(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME, FULL_TRAVEL, 0, 5));
	CHECK(close_roof(INDIGO_OK_STATE, 15));
cleanup:
	driver_down();
}

static void lifecycle_and_shutdown(void) {
	CHECK(start_connected());
	CHECK_EQ(INDIGO_BUSY, indigo_dome_talon6ror(INDIGO_DRIVER_SHUTDOWN, NULL));
	CHECK(switch_of(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME));
	CHECK(open_roof(INDIGO_OK_STATE, 15));
	CHECK(disconnect());
	CHECK_EQ(INDIGO_OK, request_switch(CONNECTION_PROPERTY_NAME, CONNECTION_DISCONNECTED_ITEM_NAME));
	indigo_usleep(500000);
	CHECK(switch_of(CONNECTION_PROPERTY_NAME, CONNECTION_DISCONNECTED_ITEM_NAME));
	CHECK_EQ(INDIGO_OK_STATE, state_of(CONNECTION_PROPERTY_NAME));
	CHECK_EQ(INDIGO_OK, indigo_dome_talon6ror(INDIGO_DRIVER_SHUTDOWN, NULL));
	CHECK_EQ(INDIGO_OK, indigo_dome_talon6ror(INDIGO_DRIVER_SHUTDOWN, NULL));
	CHECK(wait_present(CONNECTION_PROPERTY_NAME, false, 2));
	reset_observations();
	CHECK_EQ(INDIGO_OK, indigo_dome_talon6ror(INDIGO_DRIVER_INIT, NULL));
	CHECK_EQ(INDIGO_OK, indigo_dome_talon6ror(INDIGO_DRIVER_INIT, NULL));
	CHECK(wait_present(CONNECTION_PROPERTY_NAME, true, 2));
	for (int i = 0; i < 2; i++) {
		CHECK(connect_to(simulator.port, INDIGO_OK_STATE, true));
		CHECK_STR("3.20N--", text_of(INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME));
		CHECK(disconnect());
	}
cleanup:
	driver_down();
}

static bool switch_to_device(const simulator_driver_case *device_case) {
	pthread_mutex_lock(&observe_mutex);
	reset_simulator_context(device_case);
	observed_count = 0;
	message_count = 0;
	pthread_mutex_unlock(&observe_mutex);
	enumerate_simulator_device();
	return wait_present(CONNECTION_PROPERTY_NAME, true, 5);
}

static void additional_instance(void) {
	CHECK(start_simulator_with(&second_simulator, "--position 50000"));
	CHECK(driver_up());
	CHECK_EQ(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, DEVICE_NAME, ADDITIONAL_INSTANCES_PROPERTY_NAME, ADDITIONAL_INSTANCES_COUNT_ITEM_NAME, 1));
	CHECK(wait_value(ADDITIONAL_INSTANCES_PROPERTY_NAME, ADDITIONAL_INSTANCES_COUNT_ITEM_NAME, 1, 0, 5));
	CHECK(switch_to_device(&talon6ror_second_dome));
	CHECK(!present(ADDITIONAL_INSTANCES_PROPERTY_NAME));
	CHECK(connect_to(second_simulator.port, INDIGO_OK_STATE, true));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_value(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME, FULL_TRAVEL, 0, 5));
	CHECK(close_roof(INDIGO_OK_STATE, 15));
	CHECK(disconnect());
cleanup:
	if (switch_of(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME)) {
		disconnect();
	}
	switch_to_device(&talon6ror_dome);
	indigo_change_number_property_1(&simulator_test_client, DEVICE_NAME, ADDITIONAL_INSTANCES_PROPERTY_NAME, ADDITIONAL_INSTANCES_COUNT_ITEM_NAME, 0);
	indigo_usleep(300000);
	driver_down();
	stop_external_serial_simulator(&second_simulator);
}

static void overlong_reply_is_bounded(void) {
	CHECK(start_connected());
	CHECK(inject("G", "long", 1));
	// the unterminated reply is discarded and the next poll recovers
	CHECK(wait_polls(3, 20));
	CHECK_EQ(INDIGO_OK_STATE, state_of(DOME_SHUTTER_PROPERTY_NAME));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(open_roof(INDIGO_OK_STATE, 15));
cleanup:
	driver_down();
}

// ---------------------------------------------------------------------------- generated behaviour

static void urgent_abort_cancels_queued_open(void) {
	CHECK(start_connected());
	// the open request is queued behind a status poll delayed by 1.2 s
	CHECK(inject_argument("G", "slow", 1, "1200"));
	CHECK(wait_rx(STATUS_REQUEST, rx_count(STATUS_REQUEST) + 1, 5));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_ABORT_MOTION_PROPERTY_NAME, DOME_ABORT_MOTION_ITEM_NAME));
	CHECK(wait_state(DOME_ABORT_MOTION_PROPERTY_NAME, INDIGO_OK_STATE, 10));
	CHECK(wait_polls(2, 10));
	// the cancelled request never reaches the controller and the roof keeps its state
	CHECK_EQ(0, rx_count("&O%#"));
	CHECK_EQ(1, rx_count("&S%#"));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_OK_STATE, 5));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
cleanup:
	driver_down();
}

// ---------------------------------------------------------------------------- defect reproducers

static void t6r01_rejected_commands_alert(void) {
	CHECK(start_connected());
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK(inject("O", "error", 1));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_ALERT_STATE, 10));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	// a rejected abort must not report success
	CHECK(open_roof(INDIGO_OK_STATE, 25));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(wait_rx("&P%#", 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 5));
	CHECK(inject("S", "error", 1));
	CHECK(abort_motion(INDIGO_ALERT_STATE));
cleanup:
	driver_down();
}

static void t6r02_queued_request_survives_status_poll(void) {
	CHECK(start_connected());
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK(inject_argument("G", "slow", 1, "1000"));
	CHECK(wait_rx(STATUS_REQUEST, rx_count(STATUS_REQUEST) + 1, 5));
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	// the status reply captured before the command must not complete the request
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_OK_STATE, 20));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK_EQ(0, message_count_of("Roof closed"));
cleanup:
	driver_down();
}

static void t6r03_refused_open_alerts(void) {
	CHECK(start_connected());
	CHECK(change_switch(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_WEATHER_ITEM_NAME, INDIGO_OK_STATE, 5));
	CHECK(control("weather", "1"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_WEATHER_CONDITION_ITEM_NAME, INDIGO_ALERT_STATE, 5));
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	// the controller accepted the command but the safety condition prevents the motion
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_ALERT_STATE, 20));
	CHECK_EQ(0, message_count_of("Roof closed"));
cleanup:
	driver_down();
}

static void t6r03_close_waits_for_mount_park(void) {
	CHECK(start_connected());
	CHECK(open_roof(INDIGO_OK_STATE, 15));
	CHECK(control("parked", "0"));
	CHECK(wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_PARKED_SENSOR_ITEM_NAME, INDIGO_IDLE_STATE, 5));
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	int opened = message_count_of("Roof opened");
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
	CHECK(wait_rx("&P%#", 1, 5));
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Mount park requested"));
	// the roof stays open until the mount is parked; the request must stay BUSY
	indigo_usleep(8000000);
	CHECK_EQ(INDIGO_BUSY_STATE, state_of(DOME_SHUTTER_PROPERTY_NAME));
	CHECK_EQ(opened, message_count_of("Roof opened"));
	CHECK(control("parked", "1"));
	CHECK(wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_OK_STATE, 20));
	CHECK(switch_of(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_CLOSED_ITEM_NAME));
cleanup:
	driver_down();
}

static void t6r04_configuration_checksum_not_truncated(void) {
	uint8_t bytes[64];
	CHECK(start_connected());
	// KP 210 makes the payload sum a multiple of 128 with the simulator configuration
	CHECK(change_number(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME, 210, INDIGO_OK_STATE, 5));
	CHECK(wait_rx_prefix("&a", 1, 3));
	CHECK_EQ(59, frame_bytes(last_request_with_prefix("&a"), bytes, sizeof(bytes)));
	int sum = 0;
	for (int i = 2; i < 56; i++) {
		sum += bytes[i];
	}
	CHECK_EQ(0, sum % 128);
	CHECK_EQ(0x80, bytes[56]);
	CHECK(disconnect());
	CHECK(connect_to(simulator.port, INDIGO_OK_STATE, true));
	CHECK_EQ(210, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME));
cleanup:
	driver_down();
}

static void t6r05_failed_configuration_write_restores_values(void) {
	uint8_t bytes[64];
	CHECK(start_connected());
	unsigned before = revision_of(X_MOTOR_CONF_PROPERTY_NAME);
	CHECK(inject("a", "error", 1));
	CHECK_EQ(INDIGO_OK, request_number(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME, 300));
	CHECK(wait_settled(X_MOTOR_CONF_PROPERTY_NAME, before, INDIGO_ALERT_STATE, 10));
	CHECK_EQ(180, value_of(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME));
	// the rejected value must not reappear in the next configuration write
	CHECK(change_number(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_POWER_ITEM_NAME, 80, INDIGO_OK_STATE, 10));
	CHECK(wait_rx_prefix("&a", 2, 3));
	CHECK_EQ(59, frame_bytes(last_request_with_prefix("&a"), bytes, sizeof(bytes)));
	CHECK_EQ(180, ((bytes[2] & 0x7F) << 14) | ((bytes[3] & 0x7F) << 7) | (bytes[4] & 0x7F));
	CHECK_EQ(80, ((bytes[26] & 0x7F) << 14) | ((bytes[27] & 0x7F) << 7) | (bytes[28] & 0x7F));
cleanup:
	driver_down();
}

static void t6r07_no_updates_after_disconnect(void) {
	CHECK(start_connected());
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 3));
	unsigned deletes = deletes_of(DOME_SHUTTER_PROPERTY_NAME);
	CHECK(disconnect());
	CHECK_EQ(deletes + 1, deletes_of(DOME_SHUTTER_PROPERTY_NAME));
	unsigned revision = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	indigo_usleep(2000000);
	// the open handler must not publish the deleted property after the disconnect
	CHECK_EQ(revision, revision_of(DOME_SHUTTER_PROPERTY_NAME));
cleanup:
	driver_down();
}

static void t6r08_last_action_announced_after_reconnect(void) {
	CHECK(start_connected());
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Open requested by user"));
	CHECK(disconnect());
	reset_observations();
	CHECK(connect_to(simulator.port, INDIGO_OK_STATE, true));
	CHECK(wait_polls(2, 5));
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Open requested by user"));
cleanup:
	driver_down();
}

static void t6r09_motor_stall_message(void) {
	CHECK(start_connected());
	CHECK_EQ(INDIGO_OK, request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME));
	CHECK(wait_rx("&O%#", 1, 5));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_BUSY_STATE, 3));
	CHECK(control("stall", "1"));
	CHECK(wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_ALERT_STATE, 10));
	CHECK(message_seen(IDLE_MESSAGE_PROPERTY, "Motor stalled"));
cleanup:
	driver_down();
}

static void t6r10_ranges_cover_protocol(void) {
	uint8_t bytes[64];
	indigo_item item;
	CHECK(start_connected());
	CHECK(item_of(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_TIMEOUT_ITEM_NAME, &item));
	CHECK(item.number.min == 0 && item.number.max >= 2097151);
	CHECK(item_of(X_CLOSE_TIMER_PROPERTY_NAME, X_CLOSE_TIMER_TIMEOUT_ITEM_NAME, &item));
	CHECK(item.number.max >= 2097151);
	CHECK(item_of(X_POSITION_PROPERTY_NAME, X_POSITION_ITEM_NAME, &item));
	CHECK(item.number.max >= 2097151);
	// a timeout closing after four hours must reach the controller unclamped
	CHECK(change_number(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_TIMEOUT_ITEM_NAME, 14400, INDIGO_OK_STATE, 5));
	CHECK(wait_rx_prefix("&a", 1, 3));
	CHECK_EQ(59, frame_bytes(last_request_with_prefix("&a"), bytes, sizeof(bytes)));
	CHECK_EQ(14400, ((bytes[44] & 0x7F) << 14) | ((bytes[45] & 0x7F) << 7) | (bytes[46] & 0x7F));
	CHECK_EQ(14400, value_of(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_TIMEOUT_ITEM_NAME));
cleanup:
	driver_down();
}

// ---------------------------------------------------------------------------- reference trace

static void trace_append(const char *line) {
	int written = snprintf(trace_text + trace_length, sizeof(trace_text) - trace_length, "%s\n", line);
	if (written > 0 && trace_length + written < sizeof(trace_text)) {
		trace_length += written;
	}
}

static bool wait_poll_boundary(void) {
	if (!wait_polls(1, 6)) {
		return false;
	}
	int count = load_events(), polls = 0;
	for (int i = 0; i < count; i++) {
		polls += !strcmp(events[i].kind, "RX") && !strcmp(events[i].text, STATUS_REQUEST);
	}
	trace_mark = poll_end_index(count, polls);
	return trace_mark >= 0;
}

static void trace_begin(bool polling) {
	if (polling) {
		wait_poll_boundary();
	} else {
		trace_mark = load_events();
	}
	pthread_mutex_lock(&observe_mutex);
	trace_pending_length = 0;
	*trace_pending = 0;
	for (int i = 0; i < observed_count; i++) {
		*observed[i].last_trace = 0;
	}
	pthread_mutex_unlock(&observe_mutex);
	atomic_store(&trace_active, true);
}

// a status poll is a request and its reply; the reply is reduced to the roof state and last action
static bool poll_at(int count, int index, char *line, size_t size) {
	if (index + 2 > count) {
		return false;
	}
	sim_event *request = events + index, *reply = request + 1;
	if (strcmp(request->kind, "RX") || strcmp(request->text, STATUS_REQUEST) || strcmp(reply->kind, "TX") || status_state(reply->text) < 0) {
		return false;
	}
	snprintf(line, size, "S POLL state=%d action=%d", status_state(reply->text), status_action(reply->text));
	return true;
}

static bool trace_end(const char *step, bool polling) {
	char line[512], previous_poll[256] = "";
	bool ok = polling ? wait_polls(1, 8) : (indigo_usleep(1500000), true);
	int count = load_events();
	if (polling) {
		int polls = 0;
		for (int i = 0; i < count; i++) {
			polls += !strcmp(events[i].kind, "RX") && !strcmp(events[i].text, STATUS_REQUEST);
		}
		int end = poll_end_index(count, polls);
		count = end >= 0 ? end : count;
	}
	snprintf(line, sizeof(line), "## %s", step);
	trace_append(line);
	for (int i = trace_mark; i < count; i++) {
		if (poll_at(count, i, line, sizeof(line))) {
			if (strcmp(line, previous_poll)) {
				trace_append(line);
				snprintf(previous_poll, sizeof(previous_poll), "%s", line);
			}
			i++;
			continue;
		}
		if (strcmp(events[i].kind, "RX") && strcmp(events[i].kind, "TX")) {
			continue;
		}
		*previous_poll = 0;
		snprintf(line, sizeof(line), "S %s %s", events[i].kind, events[i].text);
		trace_append(line);
	}
	atomic_store(&trace_active, false);
	pthread_mutex_lock(&observe_mutex);
	if (trace_length + trace_pending_length < sizeof(trace_text)) {
		memcpy(trace_text + trace_length, trace_pending, trace_pending_length);
		trace_length += trace_pending_length;
		trace_text[trace_length] = 0;
	}
	trace_pending_length = 0;
	pthread_mutex_unlock(&observe_mutex);
	if (!ok) {
		fprintf(stderr, "Trace step %s did not end with a status poll\n", step);
	}
	return ok;
}

#define TRACE_STEP(step, begin_polling, end_polling, action) do { \
	trace_begin(begin_polling); \
	CHECK(action); \
	CHECK(trace_end(step, end_polling)); \
} while (0)

static bool trace_connect(void) {
	unsigned before = revision_of(CONNECTION_PROPERTY_NAME);
	return request_switch(CONNECTION_PROPERTY_NAME, CONNECTION_CONNECTED_ITEM_NAME) == INDIGO_OK && wait_settled(CONNECTION_PROPERTY_NAME, before, INDIGO_OK_STATE, 30) && wait_polls(1, 5);
}

static bool trace_abort_in_motion(void) {
	unsigned before = revision_of(DOME_SHUTTER_PROPERTY_NAME);
	return request_switch(DOME_SHUTTER_PROPERTY_NAME, DOME_SHUTTER_OPENED_ITEM_NAME) == INDIGO_OK && wait_rx("&O%#", 1, 5) && wait_polls(3, 5) && abort_motion(INDIGO_OK_STATE) && wait_settled(DOME_SHUTTER_PROPERTY_NAME, before, INDIGO_ALERT_STATE, 5) && wait_polls(1, 5);
}

static void reference_trace(void) {
	char *reference = NULL;
	trace_length = 0;
	*trace_text = 0;
	CHECK(driver_up());
	CHECK(set_port(simulator.port));
	TRACE_STEP("connect", false, true, trace_connect());
	TRACE_STEP("open", true, true, open_roof(INDIGO_OK_STATE, 20));
	TRACE_STEP("open again", true, true, open_roof(INDIGO_OK_STATE, 10));
	TRACE_STEP("close", true, true, close_roof(INDIGO_OK_STATE, 20));
	TRACE_STEP("abort idle", true, true, abort_motion(INDIGO_ALERT_STATE));
	TRACE_STEP("abort in motion", true, true, trace_abort_in_motion());
	TRACE_STEP("close after abort", true, true, close_roof(INDIGO_OK_STATE, 20));
	TRACE_STEP("motor configuration", true, true, change_number(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KP_ITEM_NAME, 190, INDIGO_OK_STATE, 10));
	TRACE_STEP("delay configuration", true, true, change_number(X_DELAY_CONF_PROPERTY_NAME, X_DELAY_CONF_WEATHER_ITEM_NAME, 90, INDIGO_OK_STATE, 10));
	TRACE_STEP("close conditions", true, true, change_switch(X_CLOSE_COND_PROPERTY_NAME, X_CLOSE_COND_POWER_ITEM_NAME, INDIGO_OK_STATE, 10));
	TRACE_STEP("unanswered configuration", true, true, inject("a", "silent", 1) && change_number(X_MOTOR_CONF_PROPERTY_NAME, X_MOTOR_CONF_KD_ITEM_NAME, 3, INDIGO_ALERT_STATE, 15));
	TRACE_STEP("checksum error", true, true, inject("G", "checksum", 1) && wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_ALERT_STATE, 5) && wait_state(DOME_SHUTTER_PROPERTY_NAME, INDIGO_OK_STATE, 5));
	TRACE_STEP("weather condition", true, true, control("weather", "1") && wait_light(X_SENSORS_PROPERTY_NAME, X_SENSORS_WEATHER_CONDITION_ITEM_NAME, INDIGO_ALERT_STATE, 5));
	TRACE_STEP("disconnect", true, false, disconnect());
	if (capture_path) {
		FILE *file = fopen(capture_path, "w");
		CHECK(file != NULL);
		fwrite(trace_text, 1, trace_length, file);
		fclose(file);
		printf("Reference trace written to %s\n", capture_path);
	} else {
		FILE *file = fopen(TALON6ROR_REFERENCE_TRACE_PATH, "r");
		CHECK(file != NULL);
		reference = calloc(1, TRACE_SIZE);
		size_t length = fread(reference, 1, TRACE_SIZE - 1, file);
		fclose(file);
		reference[length] = 0;
		if (strcmp(reference, trace_text)) {
			char path[PATH_MAX];
			snprintf(path, sizeof(path), "%s/actual_trace.txt", fixture_dir);
			file = fopen(path, "w");
			if (file) {
				fwrite(trace_text, 1, trace_length, file);
				fclose(file);
			}
			fprintf(stderr, "Reference trace mismatch; actual trace kept in %s (diff it against %s)\n", path, TALON6ROR_REFERENCE_TRACE_PATH);
			indigo_test_failures++;
		}
	}
cleanup:
	atomic_store(&trace_active, false);
	free(reference);
	driver_down();
}

// ---------------------------------------------------------------------------- runner

static int remove_entry(const char *path, const struct stat *status, int flag, struct FTW *ftw) {
	(void)status;
	(void)flag;
	(void)ftw;
	return remove(path);
}

static const talon6ror_case cases[] = {
	{ "simulator_protocol", simulator_protocol, "--conditions 2", false },
	{ "metadata_before_connection", metadata_before_connection, NULL, false },
	{ "connect_sequence", connect_sequence, NULL, false },
	{ "connect_with_open_roof", connect_with_open_roof, "--position 50000 --last-action 1", false },
	{ "connection_failures_and_recovery", connection_failures_and_recovery, NULL, false },
	{ "open_and_close_roof", open_and_close_roof, NULL, false },
	{ "open_when_already_open", open_when_already_open, "--position 50000", false },
	{ "abort_while_opening", abort_while_opening, "--travel-time 6", false },
	{ "abort_when_idle_alerts", abort_when_idle_alerts, NULL, false },
	{ "status_checksum_error_and_recovery", status_checksum_error_and_recovery, NULL, false },
	{ "status_read_failures", status_read_failures, NULL, false },
	{ "sensors_and_buttons", sensors_and_buttons, NULL, false },
	{ "manual_open_by_button", manual_open_by_button, "--travel-time 3", false },
	{ "condition_close", condition_close, NULL, false },
	{ "configuration_writes", configuration_writes, NULL, false },
	{ "busy_requests_rejected", busy_requests_rejected, "--travel-time 4", false },
	{ "busy_guard_holds_while_command_runs", busy_guard_holds_while_command_runs, "--travel-time 4", false },
	{ "disconnect_during_motion", disconnect_during_motion, "--travel-time 4", false },
	{ "lifecycle_and_shutdown", lifecycle_and_shutdown, NULL, false },
	{ "additional_instance", additional_instance, NULL, false },
	{ "overlong_reply_is_bounded", overlong_reply_is_bounded, NULL, false },
	{ "urgent_abort_cancels_queued_open", urgent_abort_cancels_queued_open, NULL, false },
	{ "reference_trace", reference_trace, "--travel-time 4", false },
	{ "T6R-01 rejected_commands_alert", t6r01_rejected_commands_alert, "--travel-time 6", false },
	{ "T6R-02 queued_request_survives_status_poll", t6r02_queued_request_survives_status_poll, NULL, false },
	{ "T6R-03 refused_open_alerts", t6r03_refused_open_alerts, NULL, false },
	{ "T6R-03 close_waits_for_mount_park", t6r03_close_waits_for_mount_park, NULL, false },
	{ "T6R-04 configuration_checksum_not_truncated", t6r04_configuration_checksum_not_truncated, NULL, false },
	{ "T6R-05 failed_configuration_write_restores_values", t6r05_failed_configuration_write_restores_values, NULL, false },
	{ "T6R-07 no_updates_after_disconnect", t6r07_no_updates_after_disconnect, "--travel-time 6", false },
	{ "T6R-08 last_action_announced_after_reconnect", t6r08_last_action_announced_after_reconnect, "--last-action 1", false },
	{ "T6R-09 motor_stall_message", t6r09_motor_stall_message, "--travel-time 6", false },
	{ "T6R-10 ranges_cover_protocol", t6r10_ranges_cover_protocol, NULL, false },
};

static void run_child(const talon6ror_case *test) {
	setpgid(0, 0);
	setenv("HOME", home_path, 1);
	alarm(test->defect ? 120 : 240);
	if (!start_simulator_with(&simulator, test->args)) {
		_exit(2);
	}
	if (getenv("TALON6ROR_DEBUG")) {
		indigo_set_log_level(INDIGO_LOG_DEBUG);
	}
	indigo_test_case runner = { test->name, test->run };
	int result = indigo_run_tests("Talon6 ROR", &runner, 1);
	stop_external_serial_simulator(&simulator);
	fflush(NULL);
	_exit(result);
}

int main(int argc, char **argv) {
	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "--known-defects")) {
			known_defects_mode = true;
		} else if (i + 1 < argc && !strcmp(argv[i], "--capture-trace")) {
			capture_path = argv[++i];
		} else {
			fprintf(stderr, "Usage: %s [--known-defects] [--capture-trace PATH]\n", argv[0]);
			return 2;
		}
	}
	setvbuf(stdout, NULL, _IOLBF, 0);
	simulator_test_client.define_property = observe_define;
	simulator_test_client.update_property = observe_update;
	simulator_test_client.delete_property = observe_delete;
	simulator_test_client.send_message = observe_message;
	simulator_test_client.force_property_updates = true;
	snprintf(fixture_dir, sizeof(fixture_dir), "/tmp/indigo-talon6ror.XXXXXX");
	if (!mkdtemp(fixture_dir)) {
		perror("mkdtemp");
		return 1;
	}
	snprintf(event_path, sizeof(event_path), "%s/events", fixture_dir);
	snprintf(fault_path, sizeof(fault_path), "%s/fault", fixture_dir);
	snprintf(control_path, sizeof(control_path), "%s/control", fixture_dir);
	snprintf(home_path, sizeof(home_path), "%s/home", fixture_dir);
	mkdir(home_path, 0700);
	setenv("INDIGO_TALON6ROR_EVENTS", event_path, 1);
	setenv("INDIGO_TALON6ROR_FAULT", fault_path, 1);
	setenv("INDIGO_TALON6ROR_CONTROL", control_path, 1);
	const char *filter = getenv("TALON6ROR_TEST_FILTER");
	int run = 0, passed = 0, failed = 0;
	for (int i = 0; i < ARRAY_SIZE(cases); i++) {
		const talon6ror_case *test = cases + i;
		if (test->defect != known_defects_mode || (filter && !strstr(test->name, filter)) || (capture_path && test->run != reference_trace)) {
			continue;
		}
		unlink(event_path);
		unlink(fault_path);
		unlink(control_path);
		fflush(NULL);
		pid_t child = fork();
		if (child == 0) {
			run_child(test);
		}
		int status = 0;
		if (child > 0) {
			while (waitpid(child, &status, 0) < 0 && errno == EINTR) {
			}
			kill(-child, SIGTERM);
		}
		run++;
		bool ok = child > 0 && WIFEXITED(status) && WEXITSTATUS(status) == 0;
		if (known_defects_mode) {
			printf("%s %s (status %d)\n", ok ? "UNEXPECTED PASS" : "EXPECTED FAIL", test->name, status);
		} else if (!ok) {
			printf("FAIL %s (status %d)\n", test->name, status);
		}
		if (ok) {
			passed++;
		} else {
			failed++;
		}
	}
	if (!getenv("TALON6ROR_KEEP_FIXTURE")) {
		nftw(fixture_dir, remove_entry, 16, FTW_DEPTH | FTW_PHYS);
	}
	if (known_defects_mode) {
		printf("Talon6 ROR defect reproducers: %d run, %d failed as expected, %d passed\n", run, failed, passed);
		return 0;
	}
	printf("Talon6 ROR: %d run, %d passed, %d failed\n", run, passed, failed);
	return failed ? 1 : 0;
}
