// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

#include <indigo_drivers/focuser_primaluce/indigo_focuser_primaluce.h>

#include "serial_simulator_test_common.h"
#include <errno.h>
#include <sys/wait.h>
#include <pthread.h>
#include <stdatomic.h>

#ifndef FOCUSER_PRIMALUCE_SIMULATOR_EXECUTABLE
#define FOCUSER_PRIMALUCE_SIMULATOR_EXECUTABLE "build/integration/focuser_primaluce_simulator"
#endif

#define PRIMALUCE_FOCUSER_NAME             "PrimaluceLab Focuser"
#define PRIMALUCE_ROTATOR_NAME             "PrimaluceLab Rotator"
#define X_CONFIG_PROPERTY_NAME             "X_CONFIG"
#define X_CONFIG_M1ACC_ITEM_NAME           "M1ACC"
#define X_CONFIG_M1SPD_ITEM_NAME           "M1SPD"
#define X_CONFIG_M1HOLD_ITEM_NAME          "M1HOLD"
#define X_STATE_PROPERTY_NAME              "X_STATE"
#define X_STATE_MOTOR_TEMP_ITEM_NAME       "MOTOR_TEMP"
#define X_STATE_VIN_12V_ITEM_NAME          "VIN_12V"
#define X_STATE_VIN_USB_ITEM_NAME          "VIN_USB"
#define X_WIFI_PROPERTY_NAME               "X_WIFI"
#define X_WIFI_OFF_ITEM_NAME               "OFF"
#define X_WIFI_AP_ITEM_NAME                "AP"
#define X_WIFI_STA_ITEM_NAME               "STA"
#define X_WIFI_AP_PROPERTY_NAME            "X_WIFI_AP"
#define X_WIFI_AP_SSID_ITEM_NAME           "AP_SSID"
#define X_WIFI_AP_PASSWORD_ITEM_NAME       "AP_PASSWORD"
#define X_WIFI_STA_PROPERTY_NAME           "X_WIFI_STA"
#define X_WIFI_STA_SSID_ITEM_NAME          "STA_SSID"
#define X_WIFI_STA_PASSWORD_ITEM_NAME      "STA_PASSWORD"
#define X_LEDS_PROPERTY_NAME               "X_LEDS"
#define X_LEDS_OFF_ITEM_NAME               "OFF"
#define X_LEDS_DIM_ITEM_NAME               "DIM"
#define X_LEDS_MIDDLE_ITEM_NAME            "MIDDLE"
#define X_PRESETS_PROPERTY_NAME            "X_PRESETS"
#define X_PRESET_NAMES_PROPERTY_NAME       "X_PRESET_NAMES"
#define X_PRESET_GOTO_PROPERTY_NAME        "X_PRESET_GOTO"
#define X_LEDS_ON_ITEM_NAME                "ON"
#define X_RUNPRESET_PROPERTY_NAME          "X_RUNPRESET"
#define X_RUNPRESET_L_ITEM_NAME            "L"
#define X_RUNPRESET_M_ITEM_NAME            "M"
#define X_RUNPRESET_L_PROPERTY_NAME        "X_RUNPRESET_L"
#define X_RUNPRESET_M_PROPERTY_NAME        "X_RUNPRESET_M"
#define X_RUNPRESET_S_PROPERTY_NAME        "X_RUNPRESET_S"
#define X_RUNPRESET_1_PROPERTY_NAME        "X_RUNPRESET_1"
#define X_RUNPRESET_2_PROPERTY_NAME        "X_RUNPRESET_2"
#define X_RUNPRESET_3_PROPERTY_NAME        "X_RUNPRESET_3"
#define X_HOLD_CURR_PROPERTY_NAME          "X_HOLD_CURR"
#define X_HOLD_CURR_OFF_ITEM_NAME          "OFF"
#define X_HOLD_CURR_ON_ITEM_NAME           "ON"
#define X_CALIBRATE_F_PROPERTY_NAME        "X_CALIBRATE"
#define X_CALIBRATE_F_START_ITEM_NAME      "START"
#define X_CALIBRATE_F_END_ITEM_NAME        "END"
#define X_CALIBRATE_R_PROPERTY_NAME        "X_CALIBRATE_A"
#define X_CALIBRATE_R_START_ITEM_NAME      "START"

static const simulator_driver_case primaluce_focuser = {
	"PrimaluceLab Focuser/Rotator",
	"indigo_focuser_primaluce",
	PRIMALUCE_FOCUSER_NAME,
	indigo_focuser_primaluce,
	false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static const simulator_driver_case primaluce_rotator = {
	"PrimaluceLab Focuser/Rotator",
	"indigo_focuser_primaluce",
	PRIMALUCE_ROTATOR_NAME,
	indigo_focuser_primaluce,
	false,
	NULL, 0, NULL, 0, NULL, 0, NULL, 0
};

static external_serial_simulator fixture;
static char fixture_directory[] = "/tmp/indigo-primaluce.XXXXXX";
static char event_path[PATH_MAX], fault_path[PATH_MAX];

// ----------------------------------------------------------------- fixtures

// Arm a one-shot controller fault. The simulator applies it to the next request
// containing key and then removes the control file.
static bool fault(const char *key, const char *action) {
	char temporary[PATH_MAX + 8];
	snprintf(temporary, sizeof(temporary), "%s.tmp", fault_path);
	FILE *file = fopen(temporary, "w");
	if (file == NULL) {
		return false;
	}
	fprintf(file, "%s %s\n", key, action);
	fclose(file);
	return rename(temporary, fault_path) == 0;
}

static int requests(const char *fragment) {
	FILE *file = fopen(event_path, "r");
	if (file == NULL) {
		return -1;
	}
	char line[4096];
	int count = 0;
	while (fgets(line, sizeof(line), file) != NULL) {
		if (strstr(line, fragment) != NULL) {
			count++;
		}
	}
	fclose(file);
	return count;
}

static void print_journal(const char *reason) {
	fprintf(stderr, "%s, journal holds:\n", reason);
	FILE *file = fopen(event_path, "r");
	if (file == NULL) {
		fprintf(stderr, "  (no journal at %s)\n", event_path);
		return;
	}
	char line[4096];
	while (fgets(line, sizeof(line), file) != NULL) {
		fprintf(stderr, "  %s", line);
	}
	fclose(file);
}

// The driver publishes a property state as soon as its transaction returns, so
// the controller may not have logged the request yet.
static bool wait_for_requests(const char *fragment, int expected) {
	for (int i = 0; i < 200; i++) {
		if (requests(fragment) >= expected) {
			return true;
		}
		indigo_usleep(25000);
	}
	char reason[128];
	snprintf(reason, sizeof(reason), "Fewer than %d requests containing '%s'", expected, fragment);
	print_journal(reason);
	return false;
}

// The n-th request of the journal (0 based) contains fragment.
static bool journal_line_has(int index, const char *fragment) {
	FILE *file = fopen(event_path, "r");
	if (file == NULL) {
		return false;
	}
	char line[4096];
	bool found = false;
	for (int i = 0; fgets(line, sizeof(line), file) != NULL; i++) {
		if (i == index) {
			found = strstr(line, fragment) != NULL;
			break;
		}
	}
	fclose(file);
	if (!found) {
		print_journal("Unexpected request order");
	}
	return found;
}

static bool remove_fault(void) {
	return unlink(fault_path) == 0 || errno == ENOENT;
}

// ----------------------------------------------------------------- helpers

// Every FOCUSER_POSITION state the focuser published, in order.
static atomic_uint position_log_count;
static indigo_property_state position_log[256];

static indigo_result observe_update(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	if (!strcmp(property->device, PRIMALUCE_FOCUSER_NAME) && !strcmp(property->name, FOCUSER_POSITION_PROPERTY_NAME)) {
		unsigned slot = atomic_fetch_add(&position_log_count, 1);
		if (slot < ARRAY_SIZE(position_log)) {
			position_log[slot] = property->state;
		}
	}
	return simulator_client_update_property(client, device, property, message);
}

static const char *device_name(void) {
	return context.driver_case == NULL ? PRIMALUCE_FOCUSER_NAME : context.driver_case->device_name;
}

// The bus delivers the message of an update through send_message, which the common test
// client does not set, so the messages of this driver are recorded here.
static pthread_mutex_t message_mutex = PTHREAD_MUTEX_INITIALIZER;
static char messages[4096];

static indigo_result record_message(indigo_client *client, indigo_device *device, indigo_property *property, const char *message) {
	// the shared harness counts BUSY refusal messages
	simulator_client_send_message(client, device, property, message);
	if (message != NULL && *message) {
		pthread_mutex_lock(&message_mutex);
		if (strlen(messages) + strlen(message) + 2 < sizeof(messages)) {
			strcat(messages, message);
			strcat(messages, "\n");
		}
		pthread_mutex_unlock(&message_mutex);
	}
	return INDIGO_OK;
}

static void clear_messages(void) {
	pthread_mutex_lock(&message_mutex);
	messages[0] = 0;
	pthread_mutex_unlock(&message_mutex);
}

static bool message_seen(const char *fragment) {
	for (int i = 0; i < 200; i++) {
		pthread_mutex_lock(&message_mutex);
		bool found = strstr(messages, fragment) != NULL;
		pthread_mutex_unlock(&message_mutex);
		if (found) {
			return true;
		}
		indigo_usleep(25000);
	}
	fprintf(stderr, "No message containing '%s'\n", fragment);
	return false;
}

static double number_max(const char *property, const char *item) {
	indigo_item *cached = find_cached_item(property, item);
	return cached == NULL ? -1 : cached->number.max;
}

static bool state_seen(const char *property, indigo_property_state state, unsigned int revision) {
	if (wait_for_property_state_seen_after(property, state, revision)) {
		return true;
	}
	indigo_property *cached = find_cached_property(property);
	fprintf(stderr, "%s never published state %d (current %d)\n", property, state, cached == NULL ? -1 : cached->state);
	return false;
}

static bool number_change(const char *property, const char *item, double value, indigo_property_state state) {
	unsigned int revision = property_state_revision(property, state);
	return indigo_change_number_property_1(&simulator_test_client, device_name(), property, item, value) == INDIGO_OK && state_seen(property, state, revision);
}

static bool switch_change(const char *property, const char *item, indigo_property_state state) {
	unsigned int revision = property_state_revision(property, state);
	return indigo_change_switch_property_1(&simulator_test_client, device_name(), property, item, true) == INDIGO_OK && state_seen(property, state, revision);
}

static bool text_change(const char *property, const char *item, const char *value, indigo_property_state state) {
	unsigned int revision = property_state_revision(property, state);
	return indigo_change_text_property_1_raw(&simulator_test_client, device_name(), property, item, value) == INDIGO_OK && state_seen(property, state, revision);
}

static bool rejected_number_change(const char *property, const char *item, double value) {
	indigo_item *cached = find_cached_item(property, item);
	if (cached == NULL) {
		fprintf(stderr, "Missing number item %s.%s\n", property, item);
		return false;
	}
	double target = cached->number.target;
	// a BUSY property is refused with a BUSY message, any other one with ALERT (indigo_reject_change())
	if (!assert_rejected_number_change_on(device_name(), property, item, value)) {
		return false;
	}
	cached = find_cached_item(property, item);
	if (cached == NULL || cached->number.target != target) {
		fprintf(stderr, "Refused %s.%s target %g was replaced by %g\n", property, item, target, cached == NULL ? NAN : cached->number.target);
		return false;
	}
	return true;
}

static bool number_is(const char *property_name, const char *item_name, double expected, double tolerance) {
	indigo_item *item = find_cached_item(property_name, item_name);
	if (item == NULL || fabs(item->number.value - expected) > tolerance) {
		fprintf(stderr, "%s.%s: expected %g, received %g\n", property_name, item_name, expected, item == NULL ? NAN : item->number.value);
		return false;
	}
	return true;
}

static bool switch_is(const char *property_name, const char *item_name, bool expected) {
	indigo_item *item = find_cached_item(property_name, item_name);
	if (item == NULL || item->sw.value != expected) {
		fprintf(stderr, "%s.%s: expected %s\n", property_name, item_name, expected ? "on" : "off");
		return false;
	}
	return true;
}

static bool text_is(const char *property_name, const char *item_name, const char *expected) {
	indigo_item *item = find_cached_item(property_name, item_name);
	if (item == NULL || strcmp(item->text.value, expected)) {
		fprintf(stderr, "%s.%s: expected \"%s\", received \"%s\"\n", property_name, item_name, expected, item == NULL ? "(none)" : item->text.value);
		return false;
	}
	return true;
}

// A settled focuser: the controller reported the coordinate and stopped.
static bool position_is(double expected) {
	for (int i = 0; i < 400; i++) {
		indigo_property *property = find_cached_property(FOCUSER_POSITION_PROPERTY_NAME);
		indigo_item *item = find_cached_item(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
		if (property != NULL && item != NULL && property->state == INDIGO_OK_STATE && fabs(item->number.value - expected) <= 1) {
			return true;
		}
		indigo_usleep(25000);
	}
	indigo_property *property = find_cached_property(FOCUSER_POSITION_PROPERTY_NAME);
	indigo_item *item = find_cached_item(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	fprintf(stderr, "Focuser did not settle at %g (value %g, state %d)\n", expected, item == NULL ? NAN : item->number.value, property == NULL ? -1 : property->state);
	return false;
}

static bool rotator_position_is(double expected) {
	for (int i = 0; i < 400; i++) {
		indigo_property *property = find_cached_property(ROTATOR_POSITION_PROPERTY_NAME);
		indigo_item *item = find_cached_item(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME);
		if (property != NULL && item != NULL && property->state == INDIGO_OK_STATE && fabs(item->number.value - expected) <= 1) {
			return true;
		}
		indigo_usleep(25000);
	}
	indigo_property *property = find_cached_property(ROTATOR_POSITION_PROPERTY_NAME);
	indigo_item *item = find_cached_item(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME);
	fprintf(stderr, "Rotator did not settle at %g (value %g, state %d)\n", expected, item == NULL ? NAN : item->number.value, property == NULL ? -1 : property->state);
	return false;
}

static double number_target(const char *property_name, const char *item_name) {
	indigo_item *item = find_cached_item(property_name, item_name);
	return item == NULL ? NAN : item->number.target;
}

static indigo_property_state property_state(const char *property_name) {
	indigo_property *property = find_cached_property(property_name);
	return property == NULL ? -1 : property->state;
}

// Wait until a fresh publication carries the state, also when it was only transient.
static bool state_seen_within(const char *property, indigo_property_state state, unsigned int revision, int seconds) {
	for (int i = 0; i < seconds * 40; i++) {
		if (property_state_revision(property, state) > revision) {
			return true;
		}
		indigo_usleep(25000);
	}
	fprintf(stderr, "%s never published state %d within %d s\n", property, state, seconds);
	return false;
}

// Both motion properties ended the move in state at the stopped position: value equals target.
static bool motion_ended(indigo_property_state state) {
	for (int i = 0; i < 400; i++) {
		if (property_state(FOCUSER_POSITION_PROPERTY_NAME) == state && property_state(FOCUSER_STEPS_PROPERTY_NAME) == state) {
			break;
		}
		indigo_usleep(25000);
	}
	double value = cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	double target = number_target(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	if (property_state(FOCUSER_POSITION_PROPERTY_NAME) != state || property_state(FOCUSER_STEPS_PROPERTY_NAME) != state || value != target) {
		fprintf(stderr, "Motion ended with position %d, steps %d, value %g, target %g\n", property_state(FOCUSER_POSITION_PROPERTY_NAME), property_state(FOCUSER_STEPS_PROPERTY_NAME), value, target);
		return false;
	}
	return true;
}

// Wait until the controller reports a position between origin and target, so an
// abort really interrupts a running motion.
static bool position_in_motion(double origin, double target) {
	for (int i = 0; i < 400; i++) {
		indigo_item *item = find_cached_item(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
		if (item != NULL && ((item->number.value > origin && item->number.value < target) || (item->number.value < origin && item->number.value > target))) {
			return true;
		}
		indigo_usleep(25000);
	}
	fprintf(stderr, "Position never moved between %g and %g\n", origin, target);
	return false;
}

static bool driver_up(void) {
	return bring_up_serial_driver(&primaluce_focuser);
}

static bool connect_focuser(void) {
	return connect_serial_device(&primaluce_focuser, fixture.port);
}

// The rotator shares the focuser's port, which only the focuser publishes.
static bool connect_rotator(void) {
	if (indigo_change_text_property_1_raw(&simulator_test_client, PRIMALUCE_FOCUSER_NAME, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, fixture.port) != INDIGO_OK) {
		return false;
	}
	indigo_usleep(100000);
	return connect_serial_device(&primaluce_rotator, NULL);
}

static bool driver_start(void) {
	return driver_up() && connect_focuser();
}

static void driver_stop(void) {
	disconnect_serial_device(&primaluce_rotator);
	disconnect_serial_device(&primaluce_focuser);
	tear_down_serial_driver(&primaluce_focuser);
}

// ----------------------------------------------------------------- identity and lifecycle

static void metadata(void) {
	assert_simulator_driver_info(&primaluce_focuser);
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(context.connected && context.last_connection_state == INDIGO_OK_STATE);
	assert_device_interface(INDIGO_INTERFACE_FOCUSER);
	// The handshake asks for the model and the firmware before the full state.
	SERIAL_CHECK_TRUE(wait_for_requests("\"MODNAME\"", 1));
	SERIAL_CHECK_TRUE(wait_for_requests("\"SWVERS\"", 1));
	// The connect sequence: identity, firmware, quiet log level, then the full state.
	SERIAL_CHECK_TRUE(journal_line_has(0, "\"MODNAME\""));
	SERIAL_CHECK_TRUE(journal_line_has(1, "\"SWVERS\""));
	SERIAL_CHECK_TRUE(journal_line_has(2, "\"LOGLEVEL\""));
	SERIAL_CHECK_TRUE(journal_line_has(3, "{\"req\":{\"get\": \"\"}}"));
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "SESTOSENSO2"));
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME, "3.10 / 3.10"));
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_SERIAL_NUM_ITEM_NAME, "SESTOSENSO20716"));
cleanup:
	driver_stop();
}

static void property_contract(void) {
	SERIAL_CHECK_TRUE(driver_up());
	reset_simulator_context(&primaluce_focuser);
	enumerate_simulator_device();
	SERIAL_CHECK_TRUE(!has_defined_property(X_CONFIG_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(X_STATE_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(connect_focuser());
	assert_serial_focuser_class_property_completeness();
	assert_property_has_item(FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME);
	assert_property_has_item(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME);
	assert_property_has_item(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	assert_property_has_item(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME);
	assert_property_has_item(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME);
	assert_property_has_item(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME);
	assert_property_has_item(X_CONFIG_PROPERTY_NAME, X_CONFIG_M1ACC_ITEM_NAME);
	assert_property_has_item(X_CONFIG_PROPERTY_NAME, X_CONFIG_M1HOLD_ITEM_NAME);
	assert_property_has_item(X_STATE_PROPERTY_NAME, X_STATE_MOTOR_TEMP_ITEM_NAME);
	assert_property_has_item(X_STATE_PROPERTY_NAME, X_STATE_VIN_12V_ITEM_NAME);
	assert_property_has_item(X_WIFI_PROPERTY_NAME, X_WIFI_OFF_ITEM_NAME);
	assert_property_has_item(X_WIFI_PROPERTY_NAME, X_WIFI_AP_ITEM_NAME);
	assert_property_has_item(X_WIFI_PROPERTY_NAME, X_WIFI_STA_ITEM_NAME);
	assert_property_has_item(X_WIFI_AP_PROPERTY_NAME, X_WIFI_AP_SSID_ITEM_NAME);
	assert_property_has_item(X_WIFI_AP_PROPERTY_NAME, X_WIFI_AP_PASSWORD_ITEM_NAME);
	assert_property_has_item(X_WIFI_STA_PROPERTY_NAME, X_WIFI_STA_SSID_ITEM_NAME);
	assert_property_has_item(X_WIFI_STA_PROPERTY_NAME, X_WIFI_STA_PASSWORD_ITEM_NAME);
	assert_property_has_item(X_LEDS_PROPERTY_NAME, X_LEDS_OFF_ITEM_NAME);
	assert_property_has_item(X_LEDS_PROPERTY_NAME, X_LEDS_DIM_ITEM_NAME);
	assert_property_has_item(X_LEDS_PROPERTY_NAME, X_LEDS_MIDDLE_ITEM_NAME);
	assert_property_has_item(X_LEDS_PROPERTY_NAME, X_LEDS_ON_ITEM_NAME);
	assert_property_has_item(X_RUNPRESET_PROPERTY_NAME, X_RUNPRESET_L_ITEM_NAME);
	assert_property_has_item(X_RUNPRESET_PROPERTY_NAME, X_RUNPRESET_M_ITEM_NAME);
	assert_property_has_item(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_OFF_ITEM_NAME);
	assert_property_has_item(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_ON_ITEM_NAME);
	assert_property_has_item(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME);
	assert_number_item_in_range(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	// The configuration read from the controller is reported, never written.
	SERIAL_CHECK_TRUE(find_cached_property(X_CONFIG_PROPERTY_NAME)->perm == INDIGO_RO_PERM);
	SERIAL_CHECK_TRUE(find_cached_property(X_STATE_PROPERTY_NAME)->perm == INDIGO_RO_PERM);
	// A SestoSenso reports two supply voltages, so USB stays out of X_STATE.
	SERIAL_CHECK_EQ_INT(2, find_cached_property(X_STATE_PROPERTY_NAME)->count);
	// Everything below is what the controller reported while connecting.
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, 22.5, .005));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 0, 0));
	SERIAL_CHECK_TRUE(number_is(X_STATE_PROPERTY_NAME, X_STATE_MOTOR_TEMP_ITEM_NAME, 37.12, .005));
	SERIAL_CHECK_TRUE(number_is(X_STATE_PROPERTY_NAME, X_STATE_VIN_12V_ITEM_NAME, 13.98, .005));
	SERIAL_CHECK_TRUE(number_is(X_CONFIG_PROPERTY_NAME, X_CONFIG_M1SPD_ITEM_NAME, 2, 0));
	SERIAL_CHECK_TRUE(number_is(X_CONFIG_PROPERTY_NAME, X_CONFIG_M1HOLD_ITEM_NAME, 3, 0));
	SERIAL_CHECK_TRUE(number_is(X_RUNPRESET_L_PROPERTY_NAME, X_CONFIG_M1ACC_ITEM_NAME, 10, 0));
	SERIAL_CHECK_TRUE(switch_is(X_WIFI_PROPERTY_NAME, X_WIFI_AP_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(switch_is(X_LEDS_PROPERTY_NAME, X_LEDS_ON_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(switch_is(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_ON_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(text_is(X_WIFI_AP_PROPERTY_NAME, X_WIFI_AP_SSID_ITEM_NAME, "SESTOSENSO20716"));
	SERIAL_CHECK_TRUE(text_is(X_WIFI_AP_PROPERTY_NAME, X_WIFI_AP_PASSWORD_ITEM_NAME, "primalucelab"));
	// The driver defined properties disappear again when the device is closed.
	disconnect_serial_device(&primaluce_focuser);
	for (int i = 0; i < 50 && find_cached_property(X_CONFIG_PROPERTY_NAME) != NULL; i++) {
		indigo_usleep(100000);
	}
	SERIAL_CHECK_TRUE(find_cached_property(X_CONFIG_PROPERTY_NAME) == NULL);
	SERIAL_CHECK_TRUE(find_cached_property(X_STATE_PROPERTY_NAME) == NULL);
cleanup:
	driver_stop();
}

// An Esatto has no adjustable run configuration but reports the USB supply.
static void esatto_profile(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "ESATTO"));
	SERIAL_CHECK_EQ_INT(3, find_cached_property(X_STATE_PROPERTY_NAME)->count);
	assert_property_has_item(X_STATE_PROPERTY_NAME, X_STATE_VIN_USB_ITEM_NAME);
	SERIAL_CHECK_TRUE(number_is(X_STATE_PROPERTY_NAME, X_STATE_VIN_USB_ITEM_NAME, 5.2, .005));
	SERIAL_CHECK_TRUE(!has_defined_property(X_CONFIG_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(X_RUNPRESET_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(X_RUNPRESET_L_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(X_RUNPRESET_1_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(X_HOLD_CURR_PROPERTY_NAME));
	// An Esatto reports no stored positions.
	SERIAL_CHECK_TRUE(!has_defined_property(X_PRESETS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!has_defined_property(X_PRESET_GOTO_PROPERTY_NAME));
	// The focuser calibration stays available on an Esatto.
	SERIAL_CHECK_TRUE(has_defined_property(X_CALIBRATE_F_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// A SestoSenso 3 speaks a different move command and reports the motor state
// through a separate query.
static void sestosenso3_profile(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "SESTOSENSO3"));
	SERIAL_CHECK_TRUE(has_defined_property(X_CONFIG_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18400, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"GOTO\":18400", 1));
	SERIAL_CHECK_EQ_INT(0, requests("\"MOVE_ABS\""));
	SERIAL_CHECK_TRUE(position_is(18400));
	SERIAL_CHECK_TRUE(wait_for_requests("\"STATUS\":{\"MST\"", 1));
cleanup:
	driver_stop();
}

// Older firmware reports only ABS_POS_STEP, so the driver has to fall back to
// it for both the readback and the completion check.
static void no_abs_pos_profile(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"ABS_POS_STEP\"", 1));
	SERIAL_CHECK_TRUE(position_is(18300));
cleanup:
	driver_stop();
}

// A controller that does not report a motor speed must not offer one.
static void no_speed_profile(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(!has_defined_property(FOCUSER_SPEED_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18150, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18150));
cleanup:
	driver_stop();
}

// Anything that is not a SestoSenso or an Esatto is refused.
static void unsupported_device(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(!connect_focuser());
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_EQ_INT(INDIGO_ALERT_STATE, context.last_connection_state);
	SERIAL_CHECK_TRUE(find_cached_property(X_CONFIG_PROPERTY_NAME) == NULL);
	SERIAL_CHECK_TRUE(!has_defined_property(FOCUSER_POSITION_PROPERTY_NAME) && !has_defined_property(FOCUSER_STEPS_PROPERTY_NAME) && !has_defined_property(FOCUSER_TEMPERATURE_PROPERTY_NAME) && !has_defined_property(X_STATE_PROPERTY_NAME) && !has_defined_property(X_LEDS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!connect_focuser());
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	driver_stop();
}

// A controller that does not answer the identity request is not usable, and
// the port has to be released so the next attempt can succeed.
static void handshake_timeout(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(fault("\"MODNAME\"", "silent"));
	SERIAL_CHECK_TRUE(!connect_focuser());
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// Firmware older than 3.05 is reported but still accepted.
static void old_firmware(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME, "3.00 / 3.10"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// A controller that asks for calibration and reports a motor error still
// connects; the driver only passes the notices on.
static void needs_calibration(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(context.connected && context.last_connection_state == INDIGO_OK_STATE);
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

static void repeated_init_shutdown(void) {
	for (int i = 0; i < 3; i++) {
		SERIAL_CHECK_TRUE(driver_start());
		disconnect_serial_device(&primaluce_focuser);
		SERIAL_CHECK_TRUE(!context.connected);
		tear_down_serial_driver(&primaluce_focuser);
	}
	return;
cleanup:
	driver_stop();
}

static void shutdown_rejected_while_connected(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_EQ_INT(INDIGO_BUSY, primaluce_focuser.entry(INDIGO_DRIVER_SHUTDOWN, NULL));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

static void reconnect(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18500, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18500));
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "N/A"));
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(text_is(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME, "SESTOSENSO2"));
	SERIAL_CHECK_TRUE(position_is(18500));
cleanup:
	driver_stop();
}

// ----------------------------------------------------------------- focuser motion

static void absolute_move(void) {
	SERIAL_CHECK_TRUE(driver_start());
	unsigned int steps_busy = property_state_revision(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_BUSY_STATE);
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 19000, INDIGO_BUSY_STATE));
	// An absolute move holds FOCUSER_STEPS busy too.
	SERIAL_CHECK_TRUE(state_seen(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_BUSY_STATE, steps_busy));
	SERIAL_CHECK_TRUE(wait_for_requests("\"STEP\":19000", 1));
	SERIAL_CHECK_TRUE(position_is(19000));
	SERIAL_CHECK_TRUE(find_cached_property(FOCUSER_STEPS_PROPERTY_NAME)->state == INDIGO_OK_STATE);
	// Moving to where the focuser already stands settles without a new command.
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 19000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(19000));
cleanup:
	driver_stop();
}

// A relative move is turned into an absolute one; outward counts up.
static void relative_move(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 425, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"STEP\":18500", 1));
	SERIAL_CHECK_TRUE(position_is(18500));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 300, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"STEP\":18200", 1));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// The calibrated travel the controller reports bounds the positions a client can request.
static void calibrated_travel(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_max(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME) == 100000);
	SERIAL_CHECK_TRUE(number_max(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME) == 100000);
	// An outward move longer than the remaining travel stops at the calibrated end.
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"STEP\":100000", 1));
cleanup:
	driver_stop();
}

// A motor without its 12 V supply refuses to move, and the client is told why.
static void motor_without_power(void) {
	SERIAL_CHECK_TRUE(driver_start());
	clear_messages();
	SERIAL_CHECK_TRUE(fault("\"MOVE_ABS\"", "nopower"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(message_seen("12 V"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// Stored positions are written to the controller, read back and reached on request.
static void stored_positions(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(has_defined_property(X_PRESETS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(number_is(X_PRESETS_PROPERTY_NAME, "PRESET_3", 0, 0));
	SERIAL_CHECK_TRUE(number_change(X_PRESETS_PROPERTY_NAME, "PRESET_3", 20000, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"PRESET_3\":{\"M1POS\":20000", 1));
	SERIAL_CHECK_TRUE(text_change(X_PRESET_NAMES_PROPERTY_NAME, "PRESET_3", "Focus", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"PRESET_3\":{\"NAME\":\"Focus\"", 1));
	// Only the changed preset is written.
	SERIAL_CHECK_TRUE(requests("\"PRESET_1\"") == 0);
	// The controller refuses a zero position, and the stored one is kept.
	SERIAL_CHECK_TRUE(number_change(X_PRESETS_PROPERTY_NAME, "PRESET_3", 0, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_is(X_PRESETS_PROPERTY_NAME, "PRESET_3", 20000, 0));
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(number_is(X_PRESETS_PROPERTY_NAME, "PRESET_3", 20000, 0));
	SERIAL_CHECK_TRUE(text_is(X_PRESET_NAMES_PROPERTY_NAME, "PRESET_3", "Focus"));
	SERIAL_CHECK_TRUE(switch_change(X_PRESET_GOTO_PROPERTY_NAME, "PRESET_3", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(position_is(20000));
	SERIAL_CHECK_TRUE(switch_is(X_PRESET_GOTO_PROPERTY_NAME, "PRESET_3", false));
	// A preset without a stored position is not reached.
	SERIAL_CHECK_TRUE(switch_change(X_PRESET_GOTO_PROPERTY_NAME, "PRESET_1", INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(position_is(20000));
cleanup:
	driver_stop();
}

// The middle LED brightness is set and read back.
static void led_middle(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(switch_change(X_LEDS_PROPERTY_NAME, X_LEDS_MIDDLE_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"DIMLEDS\":\"middle\"", 1));
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(switch_is(X_LEDS_PROPERTY_NAME, X_LEDS_MIDDLE_ITEM_NAME, true));
cleanup:
	driver_stop();
}

// An inward move longer than the remaining travel stops at zero.
static void relative_move_clamped(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"STEP\":0", 1));
cleanup:
	driver_stop();
}

static void abort_motion(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 90000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(18075, 90000));
	unsigned int position_alerts = property_state_revision(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	// The abort stops the motor at once rather than decelerating.
	SERIAL_CHECK_TRUE(wait_for_requests("\"MOT_ABORT\"", 1));
	// An interrupted move is reported as such, not as a completed one.
	SERIAL_CHECK_TRUE(state_seen(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE, position_alerts));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, false));
	double stopped = cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	indigo_usleep(1500000);
	printf("Aborted at %g of 90000\n", stopped);
	SERIAL_CHECK_TRUE(stopped > 18075 && stopped < 90000);
	// The stop holds: later readbacks report the same position, still short of the target.
	SERIAL_CHECK_TRUE(number_is(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, stopped, 0));
	SERIAL_CHECK_TRUE(property_state(FOCUSER_POSITION_PROPERTY_NAME) == INDIGO_ALERT_STATE);
	// A fresh move has to be accepted right after the abort.
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18100));
cleanup:
	driver_stop();
}

static void abort_while_idle(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	// Nothing moves, so no stop is sent and the position stays settled.
	SERIAL_CHECK_EQ_INT(0, requests("\"MOT_ABORT\"") + requests("\"MOT_STOP\""));
	SERIAL_CHECK_TRUE(switch_is(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// A second motion request that arrives while one is running is refused.
static void overlap_rejected(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 90000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(18075, 90000));
	int relative_moves = requests("\"STEP\":18");
	SERIAL_CHECK_TRUE(rejected_number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100));
	SERIAL_CHECK_EQ_INT(relative_moves, requests("\"STEP\":18"));
	SERIAL_CHECK_TRUE(rejected_number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18500));
	// The running move keeps its target and stays the only move command.
	SERIAL_CHECK_TRUE(number_target(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME) == 90000);
	SERIAL_CHECK_EQ_INT(1, requests("\"MOVE_ABS\""));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

// A move the controller does not acknowledge must not be published as busy.
static void move_command_failures(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(fault("\"MOVE_ABS\"", "silent"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18075, 0));
	// A controller refusal reaches the client with its reason.
	clear_messages();
	SERIAL_CHECK_TRUE(fault("\"MOVE_ABS\"", "reject"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18320, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(message_seen("Invalid command"));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18075, 0));
	SERIAL_CHECK_TRUE(fault("\"MOVE_ABS\"", "garbage"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18350, INDIGO_ALERT_STATE));
	// A controller that refuses MOT_ABORT is stopped with MOT_STOP.
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 90000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(18075, 90000));
	SERIAL_CHECK_TRUE(fault("\"MOT_ABORT\"", "reject"));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"MOT1\":{\"MOT_STOP\"", 1));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	// The driver stays usable after each rejected transaction.
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18300));
cleanup:
	driver_stop();
}

// The controller is already moving when the driver connects.
static void external_motion_observed(void) {
	SERIAL_CHECK_TRUE(driver_up());
	unsigned int busy = property_state_revision(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE);
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(state_seen_within(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE, busy, 5));
	SERIAL_CHECK_TRUE(position_is(20000));
	SERIAL_CHECK_TRUE(number_target(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME) == 20000);
	SERIAL_CHECK_TRUE(property_state(FOCUSER_STEPS_PROPERTY_NAME) == INDIGO_OK_STATE);
	SERIAL_CHECK_EQ_INT(0, requests("\"MOVE_ABS\""));
	// A relative move starts from the position the uncommanded motion reached.
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"STEP\":20100", 1));
	SERIAL_CHECK_TRUE(position_is(20100));
cleanup:
	driver_stop();
}

static void disconnect_during_motion(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 90000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(18075, 90000));
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(!context.connected);
	// The motor is stopped before the port closes.
	SERIAL_CHECK_EQ_INT(1, requests("\"MOT_ABORT\""));
	int polls = requests("\"ABS_POS\"");
	indigo_usleep(2000000);
	SERIAL_CHECK_EQ_INT(polls, requests("\"ABS_POS\""));
	SERIAL_CHECK_TRUE(connect_focuser());
	double stopped = cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	SERIAL_CHECK_TRUE(stopped > 18075 && stopped < 90000);
	SERIAL_CHECK_TRUE(position_is(stopped));
	indigo_usleep(2500000);
	SERIAL_CHECK_TRUE(position_is(stopped));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18100));
cleanup:
	driver_stop();
}

// ----------------------------------------------------------------- focuser settings

static void controller_settings(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 12, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"BKLASH\":12", 1));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 0, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"SPEED\":0", 1));
	SERIAL_CHECK_TRUE(switch_change(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_OFF_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"HOLDCURR_STATUS\":0", 1));
	SERIAL_CHECK_TRUE(switch_change(X_LEDS_PROPERTY_NAME, X_LEDS_DIM_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"DIMLEDS\":\"low\"", 1));
	SERIAL_CHECK_TRUE(switch_change(X_WIFI_PROPERTY_NAME, X_WIFI_OFF_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"AP_SET_STATUS\":\"off\"", 1));
	SERIAL_CHECK_TRUE(text_change(X_WIFI_AP_PROPERTY_NAME, X_WIFI_AP_SSID_ITEM_NAME, "INDIGO-AP", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"SSID\":\"INDIGO-AP\"", 1));
	// The settings the driver reads back on the next connect must be the ones
	// it wrote.
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(number_is(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 12, 0));
	SERIAL_CHECK_TRUE(switch_is(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_OFF_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(switch_is(X_LEDS_PROPERTY_NAME, X_LEDS_DIM_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(switch_is(X_WIFI_PROPERTY_NAME, X_WIFI_OFF_ITEM_NAME, true));
cleanup:
	driver_stop();
}

// Station mode is selected through LANCFG; the firmware rejects the
// STA_SET_STATUS command the driver used to send.
static void wifi_station_mode(void) {
	SERIAL_CHECK_TRUE(driver_start());
	// The network to join has to be settable before station mode is useful.
	SERIAL_CHECK_TRUE(text_change(X_WIFI_STA_PROPERTY_NAME, X_WIFI_STA_SSID_ITEM_NAME, "INDIGO-STA", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"WIFISTA\":{\"SSID\":\"INDIGO-STA\"", 1));
	SERIAL_CHECK_TRUE(switch_change(X_WIFI_PROPERTY_NAME, X_WIFI_STA_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"LANCFG\":\"sta\"", 1));
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(switch_is(X_WIFI_PROPERTY_NAME, X_WIFI_STA_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(switch_change(X_WIFI_PROPERTY_NAME, X_WIFI_AP_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"LANCFG\":\"ap\"", 1));
	SERIAL_CHECK_TRUE(wait_for_requests("\"AP_SET_STATUS\":\"on\"", 1));
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(connect_focuser());
	SERIAL_CHECK_TRUE(switch_is(X_WIFI_PROPERTY_NAME, X_WIFI_AP_ITEM_NAME, true));
	// A request the firmware rejects must not be reported as done.
	SERIAL_CHECK_TRUE(fault("\"LANCFG\"", "reject"));
	SERIAL_CHECK_TRUE(switch_change(X_WIFI_PROPERTY_NAME, X_WIFI_STA_ITEM_NAME, INDIGO_ALERT_STATE));
cleanup:
	driver_stop();
}

// A preset reprograms the run configuration, which the driver reads back.
static void run_preset(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(switch_change(X_RUNPRESET_PROPERTY_NAME, X_RUNPRESET_M_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"RUNPRESET\":\"medium\"", 1));
	SERIAL_CHECK_TRUE(number_is(X_CONFIG_PROPERTY_NAME, X_CONFIG_M1SPD_ITEM_NAME, 2, 0));
	// The momentary preset item is released again.
	SERIAL_CHECK_TRUE(switch_is(X_RUNPRESET_PROPERTY_NAME, X_RUNPRESET_M_ITEM_NAME, false));
	SERIAL_CHECK_TRUE(switch_change(X_RUNPRESET_PROPERTY_NAME, X_RUNPRESET_L_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"RUNPRESET\":\"light\"", 1));
cleanup:
	driver_stop();
}

// Every settings command is acknowledged, so a lost acknowledgement has to
// surface as ALERT rather than a silent success.
static void settings_reported_failures(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(fault("\"BKLASH\"", "silent"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 30, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 0, 0));
	SERIAL_CHECK_TRUE(fault("\"SPEED\"", "garbage"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 0, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(fault("\"HOLDCURR_STATUS\"", "silent"));
	SERIAL_CHECK_TRUE(switch_change(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_OFF_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_ON_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(fault("\"DIMLEDS\"", "silent"));
	SERIAL_CHECK_TRUE(switch_change(X_LEDS_PROPERTY_NAME, X_LEDS_OFF_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(X_LEDS_PROPERTY_NAME, X_LEDS_ON_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(fault("\"AP_SET_STATUS\"", "silent"));
	SERIAL_CHECK_TRUE(switch_change(X_WIFI_PROPERTY_NAME, X_WIFI_OFF_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(X_WIFI_PROPERTY_NAME, X_WIFI_AP_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(fault("\"RUNPRESET\"", "silent"));
	SERIAL_CHECK_TRUE(switch_change(X_RUNPRESET_PROPERTY_NAME, X_RUNPRESET_M_ITEM_NAME, INDIGO_ALERT_STATE));
	// Every control keeps working once the controller answers again.
	SERIAL_CHECK_TRUE(number_change(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 30, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(switch_change(X_HOLD_CURR_PROPERTY_NAME, X_HOLD_CURR_OFF_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(switch_change(X_LEDS_PROPERTY_NAME, X_LEDS_OFF_ITEM_NAME, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

// The calibration walks the controller through its documented sequence and
// finishes by reading the new coordinate back.
static void focuser_calibration(void) {
	SERIAL_CHECK_TRUE(driver_start());
	unsigned int busy = property_state_revision(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE);
	double start = cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"CAL_FOCUSER\":\"Init\"", 1));
	SERIAL_CHECK_TRUE(wait_for_requests("\"CAL_DIR\":\"normal\"", 1));
	SERIAL_CHECK_TRUE(wait_for_requests("\"CAL_FOCUSER\":\"StoreAsMinPos\"", 1));
	SERIAL_CHECK_TRUE(wait_for_requests("\"CAL_FOCUSER\":\"GoOutToFindMaxPos\"", 1));
	// The calibration run moves the draw tube while the idle poll follows it: the run is the driver's
	// own motion, so the position never turns BUSY and END is accepted to stop it.
	indigo_usleep(5000000);
	SERIAL_CHECK_TRUE(cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME) > start);
	SERIAL_CHECK_TRUE(property_state_revision(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE) == busy);
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_END_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"CAL_FOCUSER\":\"StoreAsMaxPos\"", 1));
	SERIAL_CHECK_TRUE(switch_is(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_END_ITEM_NAME, false));
	// A failed step is reported instead of being published as a calibration.
	SERIAL_CHECK_TRUE(fault("\"CAL_FOCUSER\":\"Init\"", "silent"));
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME, false));
	// An abort stops a calibration in progress and ends it ALERT.
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"MOT_ABORT\"", 1));
	SERIAL_CHECK_TRUE(wait_for_property_state(X_CALIBRATE_F_PROPERTY_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME, false));
cleanup:
	driver_stop();
}

// The status poll refreshes the probe and the supply readings.
static void status_polling(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(wait_for_requests("\"EXT_T\"", 1));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, 22.5, .005));
	SERIAL_CHECK_TRUE(number_is(X_STATE_PROPERTY_NAME, X_STATE_MOTOR_TEMP_ITEM_NAME, 37.12, .005));
	SERIAL_CHECK_TRUE(number_is(X_STATE_PROPERTY_NAME, X_STATE_VIN_12V_ITEM_NAME, 13.98, .005));
	// A lost poll answer is reported ALERT with the last valid reading, the next poll restores OK.
	unsigned int alerts = property_state_revision(FOCUSER_TEMPERATURE_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(fault("\"EXT_T\"", "silent"));
	SERIAL_CHECK_TRUE(state_seen_within(FOCUSER_TEMPERATURE_PROPERTY_NAME, INDIGO_ALERT_STATE, alerts, 15));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, 22.5, .005));
	unsigned int recoveries = property_state_revision(FOCUSER_TEMPERATURE_PROPERTY_NAME, INDIGO_OK_STATE);
	SERIAL_CHECK_TRUE(state_seen_within(FOCUSER_TEMPERATURE_PROPERTY_NAME, INDIGO_OK_STATE, recoveries, 15));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// A unit without an external probe reports -127, which is published IDLE once and never as a value.
static void no_probe(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_TEMPERATURE_PROPERTY_NAME, INDIGO_IDLE_STATE));
	SERIAL_CHECK_TRUE(cached_number_value(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME) != -127);
	unsigned int revision = property_revision(FOCUSER_TEMPERATURE_PROPERTY_NAME);
	int polls = requests("\"EXT_T\"");
	for (int i = 0; i < 600 && requests("\"EXT_T\"") <= polls; i++) {
		indigo_usleep(25000);
	}
	SERIAL_CHECK_TRUE(requests("\"EXT_T\"") > polls);
	indigo_usleep(200000);
	SERIAL_CHECK_EQ_INT(revision, property_revision(FOCUSER_TEMPERATURE_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// An idle position poll that fails publishes ALERT with the last position; the next poll recovers.
static void position_poll_failure(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	unsigned int alerts = property_state_revision(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(fault("\"ABS_POS\"", "garbage"));
	SERIAL_CHECK_TRUE(state_seen_within(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE, alerts, 6));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18075, 0));
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// The hand keypad moves the focuser: BUSY then OK at the measured position, no command is sent.
static void hand_keypad_motion(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	unsigned int busy = property_state_revision(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE);
	SERIAL_CHECK_TRUE(fault("handmove", "21000"));
	SERIAL_CHECK_TRUE(state_seen_within(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE, busy, 5));
	SERIAL_CHECK_TRUE(position_is(21000));
	SERIAL_CHECK_TRUE(number_target(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME) == 21000);
	SERIAL_CHECK_TRUE(property_state(FOCUSER_STEPS_PROPERTY_NAME) == INDIGO_OK_STATE);
	SERIAL_CHECK_EQ_INT(0, requests("\"MOVE_ABS\""));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 20900, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(20900));
cleanup:
	driver_stop();
}

// A move whose motor reports running but never advances is stopped and ends ALERT.
static void stalled_move(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(fault("\"MOVE_ABS\"", "stall"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 19000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"MOT_ABORT\"", 1));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18075, 0));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// A single lost readback during a move is retried; a persistent one stops the motor and ends ALERT.
static void move_readback_failures(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 21000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(fault("\"ABS_POS\"", "silent"));
	SERIAL_CHECK_TRUE(position_is(21000));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_OK_STATE));
	SERIAL_CHECK_EQ_INT(0, requests("\"MOT_ABORT\""));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 60000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(21000, 60000));
	SERIAL_CHECK_TRUE(fault("\"ABS_POS\"", "always_garbage"));
	SERIAL_CHECK_TRUE(wait_for_requests("\"MOT_ABORT\"", 1));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(remove_fault());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 21000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(21000));
cleanup:
	driver_stop();
}

// A stop the controller refuses ends FOCUSER_ABORT_MOTION ALERT and the move is not completed; a retry stops it.
static void abort_refused(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 90000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(18075, 90000));
	SERIAL_CHECK_TRUE(fault("\"MOT_", "always_reject"));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, false));
	indigo_usleep(500000);
	SERIAL_CHECK_TRUE(property_state(FOCUSER_POSITION_PROPERTY_NAME) == INDIGO_BUSY_STATE);
	SERIAL_CHECK_TRUE(remove_fault());
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
cleanup:
	driver_stop();
}

// An abort that overtakes a move still queued sends the stop once and never the move.
static void abort_overtakes_queued_move(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(fault("\"ABS_POS\"", "always_slow"));
	int polls = requests("\"ABS_POS\"");
	SERIAL_CHECK_TRUE(wait_for_requests("\"ABS_POS\"", polls + 1));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, PRIMALUCE_FOCUSER_NAME, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 19000));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_switch_property_1(&simulator_test_client, PRIMALUCE_FOCUSER_NAME, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(remove_fault());
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_EQ_INT(0, requests("\"MOVE_ABS\""));
	SERIAL_CHECK_EQ_INT(1, requests("\"MOT_ABORT\""));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18075, 0));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// A poll in flight when a move is accepted neither completes nor overwrites it.
static void request_versus_poll(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(fault("\"ABS_POS\"", "slow"));
	int polls = requests("\"ABS_POS\"");
	SERIAL_CHECK_TRUE(wait_for_requests("\"ABS_POS\"", polls + 1));
	atomic_store(&position_log_count, 0);
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, PRIMALUCE_FOCUSER_NAME, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300));
	SERIAL_CHECK_TRUE(position_is(18300));
	SERIAL_CHECK_EQ_INT(1, requests("\"MOVE_ABS\""));
	// The property stays busy from the request until the move ends, and its first result is OK.
	unsigned int count = atomic_load(&position_log_count);
	SERIAL_CHECK_TRUE(count >= 2 && count <= ARRAY_SIZE(position_log));
	int first_result = -1;
	for (unsigned int i = 0; i < count && first_result < 0; i++) {
		if (position_log[i] != INDIGO_BUSY_STATE) {
			first_result = (int)i;
		}
	}
	SERIAL_CHECK_TRUE(first_result > 0);
	SERIAL_CHECK_EQ_INT(INDIGO_OK_STATE, position_log[first_result]);
cleanup:
	driver_stop();
}

// A second request refused while the accepted move is still queued behind a poll in flight does
// not hide that move: the poll does not take its target and the queued move goes where it was sent.
static void refusal_keeps_queued_move(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(position_is(18075));
	SERIAL_CHECK_TRUE(fault("\"ABS_POS\"", "slow"));
	int polls = requests("\"ABS_POS\"");
	SERIAL_CHECK_TRUE(wait_for_requests("\"ABS_POS\"", polls + 1));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, PRIMALUCE_FOCUSER_NAME, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, PRIMALUCE_FOCUSER_NAME, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18100));
	SERIAL_CHECK_TRUE(position_is(18300));
	SERIAL_CHECK_EQ_INT(1, requests("\"MOVE_ABS\""));
	SERIAL_CHECK_EQ_INT(1, requests("\"STEP\":18300"));
cleanup:
	driver_stop();
}

// Backlash and calibration requested during a move are refused without a command.
static void settings_during_motion(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 90000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(18075, 90000));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 40, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_is(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 0, 0));
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(X_CALIBRATE_F_PROPERTY_NAME, X_CALIBRATE_F_START_ITEM_NAME, false));
	SERIAL_CHECK_EQ_INT(0, requests("\"BKLASH\":40") + requests("\"CAL_FOCUSER\""));
	SERIAL_CHECK_TRUE(property_state(FOCUSER_POSITION_PROPERTY_NAME) == INDIGO_BUSY_STATE);
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 40, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

// A transport lost during a move ends both motion properties ALERT and every later request ALERT.
static void transport_loss_during_motion(void) {
	SERIAL_CHECK_TRUE(driver_start());
	int handshakes = requests("\"MODNAME\"");
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 90000, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_in_motion(18075, 90000));
	SERIAL_CHECK_TRUE(fault("\"ABS_POS\"", "close"));
	SERIAL_CHECK_TRUE(motion_ended(INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(property_state(FOCUSER_STEPS_PROPERTY_NAME) != INDIGO_BUSY_STATE);
	SERIAL_CHECK_EQ_INT(handshakes, requests("\"MODNAME\""));
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	driver_stop();
}

// A WiFi mode change restarts the controller, so it is refused while the rotator shares the connection.
static void controller_restart_refused_with_sibling(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(connect_rotator());
	reset_simulator_context(&primaluce_focuser);
	enumerate_simulator_device();
	SERIAL_CHECK_TRUE(switch_change(X_WIFI_PROPERTY_NAME, X_WIFI_STA_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_is(X_WIFI_PROPERTY_NAME, X_WIFI_AP_ITEM_NAME, true));
	SERIAL_CHECK_EQ_INT(0, requests("\"REBOOT\"") + requests("\"set\":{\"LANCFG\""));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
cleanup:
	driver_stop();
}

// Losing the transport has to be reported on every request.
static void transport_loss(void) {
	SERIAL_CHECK_TRUE(driver_start());
	int polls = requests("\"MODNAME\"");
	SERIAL_CHECK_TRUE(fault("\"BKLASH\"", "close"));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 30, INDIGO_ALERT_STATE));
	SERIAL_CHECK_EQ_INT(polls, requests("\"MODNAME\""));
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_change(X_LEDS_PROPERTY_NAME, X_LEDS_OFF_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(switch_change(FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_ALERT_STATE));
	// The driver must still release the dead handle cleanly.
	disconnect_serial_device(&primaluce_focuser);
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	driver_stop();
}

// ----------------------------------------------------------------- rotator

static void rotator_metadata(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(connect_rotator());
	assert_device_interface(INDIGO_INTERFACE_ROTATOR);
	assert_property_has_item(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME);
	assert_property_has_item(ROTATOR_ABORT_MOTION_PROPERTY_NAME, ROTATOR_ABORT_MOTION_ITEM_NAME);
	assert_property_has_item(X_CALIBRATE_R_PROPERTY_NAME, X_CALIBRATE_R_START_ITEM_NAME);
	assert_number_item_in_range(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME);
	// A position can be synced as well as reached.
	assert_property_has_item(ROTATOR_ON_POSITION_SET_PROPERTY_NAME, ROTATOR_ON_POSITION_SET_SYNC_ITEM_NAME);
	// Connecting the rotator switches the ARCO port on.
	SERIAL_CHECK_TRUE(wait_for_requests("\"ARCO\":1", 1));
	SERIAL_CHECK_TRUE(number_is(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 0, 0));
cleanup:
	driver_stop();
}

// Disconnecting the rotator switches the ARCO port off again.
static void rotator_lifecycle(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(connect_rotator());
	disconnect_serial_device(&primaluce_rotator);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(wait_for_requests("\"ARCO\":0", 1));
	SERIAL_CHECK_TRUE(connect_rotator());
	SERIAL_CHECK_TRUE(wait_for_requests("\"ARCO\":1", 2));
cleanup:
	driver_stop();
}

// Both logical devices share one serial connection; either may be connected
// alone and neither disconnect may close the other's handle.
static void shared_connection(void) {
	SERIAL_CHECK_TRUE(driver_start());
	SERIAL_CHECK_TRUE(connect_rotator());
	reset_simulator_context(&primaluce_focuser);
	enumerate_simulator_device();
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18200));
	// The focuser keeps working after the rotator is disconnected.
	disconnect_serial_device(&primaluce_rotator);
	reset_simulator_context(&primaluce_focuser);
	enumerate_simulator_device();
	SERIAL_CHECK_TRUE(number_change(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 18300, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(position_is(18300));
	// And the rotator keeps working after the focuser is disconnected.
	SERIAL_CHECK_TRUE(connect_rotator());
	disconnect_serial_device(&primaluce_focuser);
	reset_simulator_context(&primaluce_rotator);
	enumerate_simulator_device();
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ABORT_MOTION_PROPERTY_NAME, ROTATOR_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

static void rotator_move(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(connect_rotator());
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 45, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"DEG\":45", 1));
	SERIAL_CHECK_TRUE(rotator_position_is(45));
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 10, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"DEG\":10", 1));
	SERIAL_CHECK_TRUE(rotator_position_is(10));
cleanup:
	driver_stop();
}

static void rotator_abort(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(connect_rotator());
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 300, INDIGO_BUSY_STATE));
	unsigned int alerts = property_state_revision(ROTATOR_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ABORT_MOTION_PROPERTY_NAME, ROTATOR_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"MOT2\":{\"MOT_STOP\"", 1));
	SERIAL_CHECK_TRUE(state_seen(ROTATOR_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE, alerts));
	// A failed stop is reported instead of being published as a stop.
	SERIAL_CHECK_TRUE(fault("\"MOT2\":{\"MOT_STOP\"", "silent"));
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ABORT_MOTION_PROPERTY_NAME, ROTATOR_ABORT_MOTION_ITEM_NAME, INDIGO_ALERT_STATE));
cleanup:
	driver_stop();
}

// The ARCO calibration is started with set and stays busy until the controller reports it stopped.
static void rotator_calibration(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(connect_rotator());
	unsigned int completions = property_state_revision(X_CALIBRATE_R_PROPERTY_NAME, INDIGO_OK_STATE);
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_R_PROPERTY_NAME, X_CALIBRATE_R_START_ITEM_NAME, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"set\":{\"MOT2\":{\"CAL_STATUS\":\"exec\"", 1));
	SERIAL_CHECK_TRUE(state_seen(X_CALIBRATE_R_PROPERTY_NAME, INDIGO_OK_STATE, completions));
	SERIAL_CHECK_TRUE(switch_is(X_CALIBRATE_R_PROPERTY_NAME, X_CALIBRATE_R_START_ITEM_NAME, false));
	// An abort stops a running calibration.
	unsigned int alerts = property_state_revision(X_CALIBRATE_R_PROPERTY_NAME, INDIGO_ALERT_STATE);
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_R_PROPERTY_NAME, X_CALIBRATE_R_START_ITEM_NAME, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"set\":{\"MOT2\":{\"CAL_STATUS\":\"exec\"", 2));
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ABORT_MOTION_PROPERTY_NAME, ROTATOR_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"CAL_STATUS\":\"stop\"", 1));
	SERIAL_CHECK_TRUE(state_seen(X_CALIBRATE_R_PROPERTY_NAME, INDIGO_ALERT_STATE, alerts));
	SERIAL_CHECK_TRUE(fault("\"CAL_STATUS\":\"exec\"", "silent"));
	SERIAL_CHECK_TRUE(switch_change(X_CALIBRATE_R_PROPERTY_NAME, X_CALIBRATE_R_START_ITEM_NAME, INDIGO_ALERT_STATE));
cleanup:
	driver_stop();
}

// A sync redefines the angle without moving the rotator.
static void rotator_sync(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(connect_rotator());
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ON_POSITION_SET_PROPERTY_NAME, ROTATOR_ON_POSITION_SET_SYNC_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 120, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_requests("\"SYNC_POS\":{\"DEG\":120", 1));
	SERIAL_CHECK_TRUE(requests("\"MOVE_ABS\"") == 0);
	SERIAL_CHECK_TRUE(rotator_position_is(120));
	// A move after the sync is made in the synced angles.
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ON_POSITION_SET_PROPERTY_NAME, ROTATOR_ON_POSITION_SET_GOTO_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 130, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(rotator_position_is(130));
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ON_POSITION_SET_PROPERTY_NAME, ROTATOR_ON_POSITION_SET_SYNC_ITEM_NAME, INDIGO_OK_STATE));
	// A refused sync keeps the angle the rotator had.
	SERIAL_CHECK_TRUE(fault("\"SYNC_POS\"", "reject"));
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 200, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_is(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 130, 0));
	SERIAL_CHECK_TRUE(switch_change(ROTATOR_ON_POSITION_SET_PROPERTY_NAME, ROTATOR_ON_POSITION_SET_GOTO_ITEM_NAME, INDIGO_OK_STATE));
cleanup:
	driver_stop();
}

static void rotator_move_failure(void) {
	SERIAL_CHECK_TRUE(driver_up());
	SERIAL_CHECK_TRUE(connect_rotator());
	SERIAL_CHECK_TRUE(fault("\"MOT2\":{\"MOVE_ABS\"", "silent"));
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 30, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(number_change(ROTATOR_POSITION_PROPERTY_NAME, ROTATOR_POSITION_ITEM_NAME, 30, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(rotator_position_is(30));
cleanup:
	driver_stop();
}

// ----------------------------------------------------------------- runner

typedef struct { const char *name; void (*run)(void); const char *profile; } simulated_case;

int main(void) {
	const simulated_case cases[] = {
		{ "metadata", metadata, "normal" },
		{ "property_contract", property_contract, "normal" },
		{ "esatto_profile", esatto_profile, "esatto" },
		{ "sestosenso3_profile", sestosenso3_profile, "sestosenso3" },
		{ "no_abs_pos_profile", no_abs_pos_profile, "no-abs-pos" },
		{ "no_speed_profile", no_speed_profile, "no-speed" },
		{ "unsupported_device", unsupported_device, "unsupported" },
		{ "handshake_timeout", handshake_timeout, "normal" },
		{ "old_firmware", old_firmware, "old-firmware" },
		{ "needs_calibration", needs_calibration, "needs-calibration" },
		{ "repeated_init_shutdown", repeated_init_shutdown, "normal" },
		{ "shutdown_rejected_while_connected", shutdown_rejected_while_connected, "normal" },
		{ "reconnect", reconnect, "normal" },
		{ "absolute_move", absolute_move, "normal" },
		{ "relative_move", relative_move, "normal" },
		{ "relative_move_clamped", relative_move_clamped, "normal" },
		{ "calibrated_travel", calibrated_travel, "normal" },
		{ "motor_without_power", motor_without_power, "normal" },
		{ "abort_motion", abort_motion, "normal" },
		{ "abort_while_idle", abort_while_idle, "normal" },
		{ "overlap_rejected", overlap_rejected, "normal" },
		{ "move_command_failures", move_command_failures, "normal" },
		{ "external_motion_observed", external_motion_observed, "external-motion" },
		{ "disconnect_during_motion", disconnect_during_motion, "normal" },
		{ "controller_settings", controller_settings, "normal" },
		{ "led_middle", led_middle, "normal" },
		{ "stored_positions", stored_positions, "normal" },
		{ "wifi_station_mode", wifi_station_mode, "normal" },
		{ "run_preset", run_preset, "normal" },
		{ "settings_reported_failures", settings_reported_failures, "normal" },
		{ "focuser_calibration", focuser_calibration, "normal" },
		{ "status_polling", status_polling, "normal" },
		{ "transport_loss", transport_loss, "normal" },
		{ "no_probe", no_probe, "no-probe" },
		{ "position_poll_failure", position_poll_failure, "normal" },
		{ "hand_keypad_motion", hand_keypad_motion, "normal" },
		{ "stalled_move", stalled_move, "normal" },
		{ "move_readback_failures", move_readback_failures, "normal" },
		{ "abort_refused", abort_refused, "normal" },
		{ "abort_overtakes_queued_move", abort_overtakes_queued_move, "normal" },
		{ "request_versus_poll", request_versus_poll, "normal" },
		{ "refusal_keeps_queued_move", refusal_keeps_queued_move, "normal" },
		{ "settings_during_motion", settings_during_motion, "normal" },
		{ "transport_loss_during_motion", transport_loss_during_motion, "normal" },
		{ "controller_restart_refused_with_sibling", controller_restart_refused_with_sibling, "normal" },
		{ "rotator_metadata", rotator_metadata, "normal" },
		{ "rotator_lifecycle", rotator_lifecycle, "normal" },
		{ "shared_connection", shared_connection, "normal" },
		{ "rotator_move", rotator_move, "normal" },
		{ "rotator_abort", rotator_abort, "normal" },
		{ "rotator_calibration", rotator_calibration, "normal" },
		{ "rotator_sync", rotator_sync, "normal" },
		{ "rotator_move_failure", rotator_move_failure, "normal" }
	};
	setvbuf(stdout, NULL, _IOLBF, 0);
	simulator_test_client.send_message = record_message;
	simulator_test_client.update_property = observe_update;
	if (mkdtemp(fixture_directory) == NULL) {
		fprintf(stderr, "Cannot create fixture directory\n");
		return 1;
	}
	snprintf(event_path, sizeof(event_path), "%s/events.log", fixture_directory);
	snprintf(fault_path, sizeof(fault_path), "%s/fault", fixture_directory);
	setenv("INDIGO_PRIMALUCE_EVENTS", event_path, 1);
	setenv("INDIGO_PRIMALUCE_FAULT", fault_path, 1);
	const char *filter = getenv("PRIMALUCE_TEST_FILTER");
	int failures = 0;
	for (int i = 0; i < ARRAY_SIZE(cases); i++) {
		if (filter != NULL && strstr(cases[i].name, filter) == NULL) {
			continue;
		}
		unlink(fault_path);
		const char *arguments[] = { "--profile", cases[i].profile, NULL, NULL };
		if (getenv("PRIMALUCE_TEST_TRACE") != NULL) {
			arguments[2] = "--trace";
		}
		if (!start_external_serial_simulator_with_args(&fixture, FOCUSER_PRIMALUCE_SIMULATOR_EXECUTABLE, arguments)) {
			fprintf(stderr, "Simulator startup failed\n");
			failures++;
			break;
		}
		fflush(NULL);
		pid_t child = fork();
		if (child == 0) {
			alarm(120);
			indigo_test_case test = { cases[i].name, cases[i].run };
			_exit(indigo_run_tests("PrimaluceLab", &test, 1));
		}
		int status = 0;
		if (child > 0) {
			while (waitpid(child, &status, 0) < 0) {
				if (errno != EINTR) {
					status = -1;
					break;
				}
			}
		}
		stop_external_serial_simulator(&fixture);
		if (child < 0 || status == -1 || !WIFEXITED(status) || WEXITSTATUS(status)) {
			failures++;
			printf("FAIL: %s (exit=%d, signal=%d)\n", cases[i].name, WIFEXITED(status) ? WEXITSTATUS(status) : -1, WIFSIGNALED(status) ? WTERMSIG(status) : 0);
		}
	}
	unlink(fault_path);
	unlink(event_path);
	rmdir(fixture_directory);
	unsetenv("INDIGO_PRIMALUCE_EVENTS");
	unsetenv("INDIGO_PRIMALUCE_FAULT");
	printf("PrimaluceLab: %d failing scenarios\n", failures);
	return failures ? 1 : 0;
}
