// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// indigo_aux_dragonfly acceptance suite against the loopback UDP Dragonfly
// simulator. The simulator models the whole controller, so the sensor values
// asserted here are the roof/park model of dome_dragonfly/README.md seen
// through the AUX driver, which exposes all eight channels.

#include <indigo_drivers/aux_dragonfly/indigo_aux_dragonfly.h>
#include "serial_simulator_test_common.h"
#include "aux_test_isolation.h"

#ifndef AUX_DRAGONFLY_SIMULATOR_EXECUTABLE
#define AUX_DRAGONFLY_SIMULATOR_EXECUTABLE "build/integration/aux_dragonfly_simulator"
#endif

#define AUX_OUTLET_PULSE_LENGTHS_NAME AUX_OUTLET_PULSE_LENGTHS_PROPERTY_NAME

static const char *const dragonfly_base_properties[] = {
	INFO_PROPERTY_NAME,
	CONFIG_PROPERTY_NAME,
	PROFILE_NAME_PROPERTY_NAME,
	PROFILE_PROPERTY_NAME,
	CONNECTION_PROPERTY_NAME,
	DEVICE_PORT_PROPERTY_NAME,
	AUTHENTICATION_PROPERTY_NAME,
	AUX_OUTLET_NAMES_PROPERTY_NAME,
	AUX_SENSOR_NAMES_PROPERTY_NAME
};

static const char *const dragonfly_hidden_properties[] = {
	DEVICE_PORTS_PROPERTY_NAME,
	DEVICE_BAUDRATE_PROPERTY_NAME,
	SIMULATION_PROPERTY_NAME
};

static const char *const dragonfly_connected_properties[] = {
	AUX_GPIO_OUTLETS_PROPERTY_NAME,
	AUX_OUTLET_PULSE_LENGTHS_NAME,
	AUX_GPIO_SENSORS_PROPERTY_NAME
};

static const simulator_driver_case primary = {
	"Lunatico Dragonfly Relay Controller",
	"indigo_aux_dragonfly",
	"Dragonfly Controller",
	indigo_aux_dragonfly,
	false,
	dragonfly_base_properties, ARRAY_SIZE(dragonfly_base_properties),
	dragonfly_hidden_properties, ARRAY_SIZE(dragonfly_hidden_properties),
	dragonfly_connected_properties, ARRAY_SIZE(dragonfly_connected_properties),
	NULL, 0
};

// Simulator sensor model: channel 1 roof open, channel 2 roof closed,
// channels 3...7 constant, channel 8 mount parked. The default profile starts
// with a closed roof and a parked mount.
static const double closed_and_parked_sensors[] = { 10, 900, 13, 14, 15, 16, 17, 900 };

static bool wait_for_switch(const char *property, const char *item, bool value) {
	return aux_wait_switch(property, item, value);
}

static bool set_outlet(const char *item, bool value) {
	return indigo_change_switch_property_1(&simulator_test_client, primary.device_name, AUX_GPIO_OUTLETS_PROPERTY_NAME, item, value) == INDIGO_OK;
}

static bool set_pulse_length(const char *item, double value) {
	return indigo_change_number_property_1(&simulator_test_client, primary.device_name, AUX_OUTLET_PULSE_LENGTHS_NAME, item, value) == INDIGO_OK;
}

static void outlet_item_name(char *buffer, size_t size, int channel) {
	snprintf(buffer, size, "OUTLET_%d", channel);
}

static void outlet_name_item_name(char *buffer, size_t size, int channel) {
	snprintf(buffer, size, "GPIO_OUTLET_NAME_%d", channel);
}

static void sensor_item_name(char *buffer, size_t size, int channel) {
	snprintf(buffer, size, "GPIO_SENSOR_NAME_%d", channel);
}

// The defined-property list of the harness is append-only, so the live
// visibility of the connection-dependent properties is read from the property
// cache, which does follow deletion.
static bool connected_properties_published(bool expected) {
	for (int i = 0; i < ARRAY_SIZE(dragonfly_connected_properties); i++) {
		if ((find_cached_property(dragonfly_connected_properties[i]) != NULL) != expected) {
			fprintf(stderr, "%s is %spublished\n", dragonfly_connected_properties[i], expected ? "not " : "");
			return false;
		}
	}
	return true;
}

// Metadata, the full published property inventory before and after connection,
// every item of every driver-defined property, and the identity readback.
static void identity_and_inventory(void) {
	char item[32];

	assert_simulator_driver_info(&primary);
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&primary));
	enumerate_simulator_device();
	assert_device_interface(INDIGO_INTERFACE_AUX_GPIO);
	assert_defined_properties(dragonfly_base_properties, ARRAY_SIZE(dragonfly_base_properties));
	assert_not_defined_properties(dragonfly_hidden_properties, ARRAY_SIZE(dragonfly_hidden_properties));
	assert_not_defined_properties(dragonfly_connected_properties, ARRAY_SIZE(dragonfly_connected_properties));
	assert_defined_property_count(ARRAY_SIZE(dragonfly_base_properties));
	for (int i = 1; i <= 8; i++) {
		outlet_name_item_name(item, sizeof(item), i);
		assert_property_has_item(AUX_OUTLET_NAMES_PROPERTY_NAME, item);
		sensor_item_name(item, sizeof(item), i);
		assert_property_has_item(AUX_SENSOR_NAMES_PROPERTY_NAME, item);
	}
	SERIAL_CHECK_TRUE(connect_serial_device(&primary, aux_simulator.port));
	assert_defined_properties(dragonfly_connected_properties, ARRAY_SIZE(dragonfly_connected_properties));
	assert_not_defined_properties(dragonfly_hidden_properties, ARRAY_SIZE(dragonfly_hidden_properties));
	assert_defined_property_count(ARRAY_SIZE(dragonfly_base_properties) + ARRAY_SIZE(dragonfly_connected_properties));
	for (int i = 1; i <= 8; i++) {
		outlet_item_name(item, sizeof(item), i);
		assert_property_has_item(AUX_GPIO_OUTLETS_PROPERTY_NAME, item);
		assert_property_has_item(AUX_OUTLET_PULSE_LENGTHS_NAME, item);
		sensor_item_name(item, sizeof(item), i);
		assert_property_has_item(AUX_GPIO_SENSORS_PROPERTY_NAME, item);
		assert_number_item_in_range(AUX_GPIO_SENSORS_PROPERTY_NAME, item);
	}
	indigo_item *model = find_cached_item(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME);
	indigo_item *firmware = find_cached_item(INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME);
	SERIAL_CHECK_TRUE(model != NULL && !strcmp(model->text.value, "Dragonfly"));
	SERIAL_CHECK_TRUE(firmware != NULL && !strcmp(firmware->text.value, "5.29"));
cleanup:
	aux_stop(&primary);
}

// All eight analog sensors are published with the simulator's values.
static void sensors(void) {
	char item[32];

	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	for (int i = 0; i < 8; i++) {
		sensor_item_name(item, sizeof(item), i + 1);
		SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_GPIO_SENSORS_PROPERTY_NAME, item, closed_and_parked_sensors[i], .01));
	}
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_SENSORS_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	aux_stop(&primary);
}

// Every relay can be switched on and off; the driver reports the state the
// controller actually reached, not the requested one.
static void relays(void) {
	char item[32];

	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	for (int i = 1; i <= 8; i++) {
		outlet_item_name(item, sizeof(item), i);
		SERIAL_CHECK_TRUE(set_outlet(item, true));
		SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, item, true));
	}
	for (int i = 1; i <= 8; i++) {
		outlet_item_name(item, sizeof(item), i);
		SERIAL_CHECK_TRUE(set_outlet(item, false));
		SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, item, false));
	}
cleanup:
	aux_stop(&primary);
}

// A non-zero pulse length turns the relay into a timed pulse that the driver
// clears on its own when the controller has released it.
static void pulse(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(set_pulse_length("OUTLET_1", 500));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_OUTLET_PULSE_LENGTHS_NAME, "OUTLET_1", 500, .01));
	SERIAL_CHECK_TRUE(set_outlet("OUTLET_1", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_1", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_1", false));
cleanup:
	aux_stop(&primary);
}

// Two pulses of different lengths started back to back both have to complete.
static void overlapping_pulses(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(set_pulse_length("OUTLET_2", 1500));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_OUTLET_PULSE_LENGTHS_NAME, "OUTLET_2", 1500, .01));
	SERIAL_CHECK_TRUE(set_pulse_length("OUTLET_3", 400));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_OUTLET_PULSE_LENGTHS_NAME, "OUTLET_3", 400, .01));
	SERIAL_CHECK_TRUE(set_outlet("OUTLET_2", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_2", true));
	SERIAL_CHECK_TRUE(set_outlet("OUTLET_3", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_3", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_3", false));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_2", false));
cleanup:
	aux_stop(&primary);
}

// Renaming outlets and sensors relabels the dependent items. The rename
// properties are persistent, so they are also the CONFIG_SAVE payload.
static void names(void) {
	indigo_item *item = NULL;

	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_EQ_INT(indigo_change_text_property_1(&simulator_test_client, primary.device_name, AUX_OUTLET_NAMES_PROPERTY_NAME, "GPIO_OUTLET_NAME_2", "Flat panel"), INDIGO_OK);
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_OUTLET_NAMES_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_OUTLETS_PROPERTY_NAME, INDIGO_OK_STATE));
	item = find_cached_item(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_2");
	SERIAL_CHECK_TRUE(item != NULL && !strcmp(item->label, "Flat panel"));
	item = find_cached_item(AUX_OUTLET_PULSE_LENGTHS_NAME, "OUTLET_2");
	SERIAL_CHECK_TRUE(item != NULL && !strcmp(item->label, "Flat panel"));
	SERIAL_CHECK_EQ_INT(indigo_change_text_property_1(&simulator_test_client, primary.device_name, AUX_SENSOR_NAMES_PROPERTY_NAME, "GPIO_SENSOR_NAME_4", "Rain"), INDIGO_OK);
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_SENSOR_NAMES_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_SENSORS_PROPERTY_NAME, INDIGO_OK_STATE));
	item = find_cached_item(AUX_GPIO_SENSORS_PROPERTY_NAME, "GPIO_SENSOR_NAME_4");
	SERIAL_CHECK_TRUE(item != NULL && !strcmp(item->label, "Rain"));
cleanup:
	aux_stop(&primary);
}

// A password protected controller rejects relay writes until AUTHENTICATION
// earns a read/write access level.
static void authentication(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(set_outlet("OUTLET_1", true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_OUTLETS_PROPERTY_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_EQ_INT(indigo_change_text_property_1(&simulator_test_client, primary.device_name, AUTHENTICATION_PROPERTY_NAME, AUTHENTICATION_PASSWORD_ITEM_NAME, "123"), INDIGO_OK);
	SERIAL_CHECK_TRUE(wait_for_property_state(AUTHENTICATION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(set_outlet("OUTLET_1", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_1", true));
cleanup:
	aux_stop(&primary);
}

// Connection is refused for anything that is not a Dragonfly, for an
// unparsable identity reply, for a silent controller and for a reply that does
// not fit the response buffer.
static void rejected_connection(void) {
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&primary));
	SERIAL_CHECK_TRUE(aux_reject(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(wait_for_property_state(CONNECTION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connected_properties_published(false));
cleanup:
	aux_stop(&primary);
}

// A rejected relay command leaves the outlet property in ALERT.
static void relay_error(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(set_outlet(AUX_GPIO_OUTLETS_OUTLET_1_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_OUTLETS_PROPERTY_NAME, INDIGO_ALERT_STATE));
cleanup:
	aux_stop(&primary);
}

// A relay readback that cannot be parsed fails the whole outlet change.
static void relay_read_error(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(set_outlet(AUX_GPIO_OUTLETS_OUTLET_1_ITEM_NAME, true));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_OUTLETS_PROPERTY_NAME, INDIGO_ALERT_STATE));
cleanup:
	aux_stop(&primary);
}

// A truncated sensor reply is reported through the sensor property, no partial
// values are published, and the failure does not take the device down.
static void sensor_error(void) {
	char item[32];

	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_SENSORS_PROPERTY_NAME, INDIGO_ALERT_STATE));
	for (int i = 1; i <= 8; i++) {
		sensor_item_name(item, sizeof(item), i);
		SERIAL_CHECK_EQ_INT(0, (int)cached_number_value(AUX_GPIO_SENSORS_PROPERTY_NAME, item));
	}
	SERIAL_CHECK_TRUE(set_outlet("OUTLET_1", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_1", true));
cleanup:
	aux_stop(&primary);
}

// Disconnect and reconnect over the same simulator; the second connection
// republishes the connection-dependent properties and the sensor poll resumes.
static void reconnect(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(connected_properties_published(true));
	disconnect_serial_device(&primary);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connected_properties_published(false));
	SERIAL_CHECK_TRUE(connect_serial_device(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(connected_properties_published(true));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_GPIO_SENSORS_PROPERTY_NAME, "GPIO_SENSOR_NAME_3", 13, .01));
cleanup:
	aux_stop(&primary);
}

// A redundant disconnect is tolerated and SHUTDOWN is refused while the device
// is still connected.
static void lifecycle(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_EQ_INT(INDIGO_BUSY, primary.entry(INDIGO_DRIVER_SHUTDOWN, NULL));
	SERIAL_CHECK_TRUE(context.connected);
	disconnect_serial_device(&primary);
	disconnect_serial_device(&primary);
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	aux_stop(&primary);
}

// Disconnecting while a long pulse is still running must not leave a pending
// completion behind, and the driver has to tear down cleanly.
static void disconnect_during_pulse(void) {
	SERIAL_CHECK_TRUE(start_serial_driver(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(set_pulse_length("OUTLET_5", 100000));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_OUTLET_PULSE_LENGTHS_NAME, "OUTLET_5", 100000, .01));
	SERIAL_CHECK_TRUE(set_outlet("OUTLET_5", true));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_5", true));
	disconnect_serial_device(&primary);
	SERIAL_CHECK_TRUE(!context.connected);
	SERIAL_CHECK_TRUE(connect_serial_device(&primary, aux_simulator.port));
	SERIAL_CHECK_TRUE(wait_for_switch(AUX_GPIO_OUTLETS_PROPERTY_NAME, "OUTLET_5", true));
cleanup:
	aux_stop(&primary);
}

int main(void) {
	const aux_simulated_case tests[] = {
		{ "identity_and_inventory", identity_and_inventory, "normal" },
		{ "sensors", sensors, "normal" },
		{ "relays", relays, "normal" },
		{ "pulse", pulse, "normal" },
		{ "overlapping_pulses", overlapping_pulses, "normal" },
		{ "names", names, "normal" },
		{ "authentication", authentication, "protected" },
		{ "wrong_identity", rejected_connection, "wrong-model" },
		{ "unparsable_identity", rejected_connection, "bad-version" },
		{ "silent_device", rejected_connection, "no-reply" },
		{ "oversized_reply", rejected_connection, "oversized" },
		{ "relay_error", relay_error, "relay-error" },
		{ "relay_read_error", relay_read_error, "relay-read-error" },
		{ "sensor_error", sensor_error, "short-sensors" },
		{ "reconnect", reconnect, "normal" },
		{ "lifecycle", lifecycle, "normal" },
		{ "disconnect_during_pulse", disconnect_during_pulse, "normal" }
	};
	return run_aux_simulated("dragonfly", AUX_DRAGONFLY_SIMULATOR_EXECUTABLE, tests, ARRAY_SIZE(tests));
}
