// Copyright (c) 2026 INDIGO initiative
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// indigo_focuser_lunatico acceptance suite. The driver shares its whole
// implementation with indigo_rotator_lunatico and differs only in the class of
// the Main port, so this suite owns the focuser class coverage, the powerbox
// (AUX) coverage, the identity and port-existence coverage and the shared
// connection lifecycle; test_rotator_lunatico_simulator.c owns the rotator
// class coverage.
//
// Every scenario runs in its own forked process against a fresh controller
// simulator, so the scenarios are independent and a hung driver cannot leak
// into the next one.

#include <indigo_drivers/focuser_lunatico/indigo_focuser_lunatico.h>
#include "serial_simulator_test_common.h"
#include "aux_test_isolation.h"
#include "lunatico_test_common.h"

#ifndef LUNATICO_SIMULATOR
#define LUNATICO_SIMULATOR "build/integration/focuser_lunatico_simulator"
#endif

#define DRIVER "indigo_focuser_lunatico"

static const simulator_driver_case main_focuser = { "Lunatico Main focuser", DRIVER, "Focuser Lunatico (Main)", indigo_focuser_lunatico, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0 };
static const simulator_driver_case exp_focuser = { "Lunatico Exp focuser", DRIVER, "Focuser Lunatico (Exp)", indigo_focuser_lunatico, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0 };
static const simulator_driver_case third_focuser = { "Lunatico Third focuser", DRIVER, "Focuser Lunatico (Third)", indigo_focuser_lunatico, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0 };
static const simulator_driver_case exp_rotator = { "Lunatico Exp rotator", DRIVER, "Rotator Lunatico (Exp)", indigo_focuser_lunatico, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0 };
static const simulator_driver_case exp_aux = { "Lunatico Exp powerbox", DRIVER, "Powerbox Lunatico (Exp)", indigo_focuser_lunatico, false, NULL, 0, NULL, 0, NULL, 0, NULL, 0 };

static const simulator_driver_case *selected = &main_focuser;

// Home position of the three simulated ports. Port 0 starts at 1800 steps,
// which is also 0 deg for a rotator with the default steps per revolution.
#define HOME_MAIN   1800
#define HOME_OTHER  1000

static bool lunatico_wait_for_device(bool configurable) {
	if (!configurable) {
		// The migrated driver attaches every logical device during
		// INDIGO_DRIVER_INIT, so it is already there and only has to be
		// enumerated into the property cache.
		enumerate_simulator_device();
		return has_defined_property(CONNECTION_PROPERTY_NAME);
	}
	// configure_ports() is dispatched with INDIGO_ASYNC, so the change request
	// is acknowledged before the device exists. Wait on the definitions the new
	// device broadcasts as it attaches rather than enumerating into a device
	// whose attach is still in flight (LIB-012).
	for (int i = 0; i < 200; i++) {
		if (has_defined_property(CONNECTION_PROPERTY_NAME)) {
			return true;
		}
		indigo_usleep(50000);
	}
	fprintf(stderr, "port device did not appear\n");
	return false;
}

// Bring the driver up and connect one logical device.
//
// Before the generator migration the Exp and Third devices are created on
// demand by configure_ports() from LUNATICO_MODEL and LUNATICO_PORT_*_CONFIG,
// and every port device exposes its own DEVICE_PORT. The migrated driver
// declares all seven logical devices statically, has no port configuration
// properties, and hides DEVICE_PORT on everything but the Main device, whose
// DEVICE_PORT its slaves open through. Requesting the reconfiguration only when
// those properties exist, and always pointing the Main device's DEVICE_PORT at
// the simulator, keeps one suite valid on both sides of the migration.
static bool lunatico_start(const simulator_driver_case *device, const char *port_class) {
	selected = device;
	if (!bring_up_serial_driver(&main_focuser)) {
		return false;
	}
	bool configurable = has_defined_property("LUNATICO_MODEL");
	char url[PATH_MAX];
	lunatico_url(url, sizeof(url));
	if (device != &main_focuser) {
		reset_simulator_context(device);
		if (configurable) {
			indigo_change_switch_property_1(&simulator_test_client, main_focuser.device_name, "LUNATICO_MODEL", "PLATYPUS", true);
			const char *port_property = strstr(device->device_name, "(Exp)") ? "LUNATICO_PORT_EXP_CONFIG" : "LUNATICO_PORT_THIRD_CONFIG";
			indigo_change_switch_property_1(&simulator_test_client, main_focuser.device_name, port_property, port_class, true);
		}
		if (!lunatico_wait_for_device(configurable)) {
			return false;
		}
	}
	indigo_change_text_property_1_raw(&simulator_test_client, main_focuser.device_name, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, url);
	indigo_usleep(200000);
	return connect_serial_device(device, url);
}

static bool start_main(void) {
	return lunatico_start(&main_focuser, NULL);
}

// The driver refuses INDIGO_DRIVER_SHUTDOWN while any logical device is still
// connected, and the property cache tracks one device at a time.
static void stop(void) {
	if (selected != &main_focuser) {
		disconnect_serial_device(selected);
	}
	disconnect_serial_device(&main_focuser);
	aux_stop(&main_focuser);
}

static const char *cached_text_value(const char *property_name, const char *item_name) {
	indigo_item *item = find_cached_item(property_name, item_name);
	return item == NULL ? "" : item->text.value;
}

// Sync the focuser to a known position without moving it, so a scenario does
// not depend on the simulated power-up position.
static bool sync_to(const simulator_driver_case *device, int position) {
	if (!lunatico_set_switch(device, FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_SYNC_ITEM_NAME, INDIGO_OK_STATE)) {
		return false;
	}
	if (!lunatico_set_number(device, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, position, INDIGO_OK_STATE)) {
		return false;
	}
	return wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, position, .1);
}

static bool select_goto_mode(const simulator_driver_case *device) {
	return lunatico_set_switch(device, FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_GOTO_ITEM_NAME, INDIGO_OK_STATE);
}

// The connect handler arms a one-shot completion poll and publishes CONNECTION
// OK before that poll fires, so a request issued immediately after connecting
// races it. Scenarios that are not about that race wait for the poll to have
// run; !step ismoving# is issued by nothing else at connect.
static bool settle_after_connect(int port) {
	char command[32];
	snprintf(command, sizeof(command), "!step ismoving %d#", port);
	return lunatico_wait_for_command(command);
}

// --------------------------------------------------------------------------------- identity

// The Main port must come up as a focuser with the identity read from
// !seletek version#, and with the transport and configuration properties the
// driver documents.
static void identity_and_inventory(void) {
	SERIAL_CHECK_TRUE(start_main());
	assert_device_interface(INDIGO_INTERFACE_FOCUSER);
	assert_serial_focuser_class_property_completeness();
	SERIAL_CHECK_TRUE(lunatico_sent("!seletek version#"));
	// !seletek version:3529# is operating mode 0, model 3 (Platypus),
	// firmware 5.29.
	SERIAL_CHECK_TRUE(!strcmp(cached_text_value(INFO_PROPERTY_NAME, INFO_DEVICE_MODEL_ITEM_NAME), "Platypus"));
	SERIAL_CHECK_TRUE(!strcmp(cached_text_value(INFO_PROPERTY_NAME, INFO_DEVICE_FW_REVISION_ITEM_NAME), "5.29"));
	SERIAL_CHECK_TRUE(has_defined_property(DEVICE_PORT_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(DEVICE_PORTS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(DEVICE_BAUDRATE_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(!strcmp(cached_text_value(DEVICE_BAUDRATE_PROPERTY_NAME, DEVICE_BAUDRATE_ITEM_NAME), "115200"));
	// Focuser class properties the driver unhides.
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_TEMPERATURE_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_LIMITS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_BACKLASH_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_SPEED_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_MODE_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_COMPENSATION_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_ON_POSITION_SET_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_REVERSE_MOTION_PROPERTY_NAME));
	// Driver-specific properties, all defined on connect.
	SERIAL_CHECK_TRUE(has_defined_property(X_FOCUSER_STEP_MODE_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(X_FOCUSER_POWER_CONTROL_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(X_FOCUSER_TEMPERATURE_SENSOR_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(X_FOCUSER_MOTOR_WIRING_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(X_FOCUSER_MOTOR_TYPE_PROPERTY_NAME));
	assert_property_has_items(X_FOCUSER_STEP_MODE_PROPERTY_NAME, (const char *[]){ "FULL", "HALF" }, 2);
	assert_property_has_items(X_FOCUSER_POWER_CONTROL_PROPERTY_NAME, (const char *[]){ "MOVE_POWER", "STOP_POWER" }, 2);
	assert_property_has_items(X_FOCUSER_TEMPERATURE_SENSOR_PROPERTY_NAME, (const char *[]){ "INTERNAL", "EXTERNAL" }, 2);
	assert_property_has_items(X_FOCUSER_MOTOR_WIRING_PROPERTY_NAME, (const char *[]){ "LUNATICO", "MOONLITE" }, 2);
	assert_property_has_items(X_FOCUSER_MOTOR_TYPE_PROPERTY_NAME, (const char *[]){ "UNIPOLAR", "BIPOLAR", "DC", "STEP_DIR" }, 4);
	// The connect sequence has to leave the controller configured.
	SERIAL_CHECK_TRUE(lunatico_sent("!step delswlimits 0#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!step movepow 0 1023#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!step stoppow 0 0#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!step model 0 0#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!step halfstep 0 0#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!step wiremode 0 0#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!step speedrangeus 0 10000 10000#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!step getpos 0#"));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, HOME_MAIN, .1));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- absolute motion

// One absolute GOTO on a given port, asserting the exact command, the BUSY
// window, the published progress and the final position.
static void absolute_move_on(const simulator_driver_case *device, int port, int home) {
	SERIAL_CHECK_TRUE(lunatico_start(device, "FOCUSER"));
	assert_device_interface(INDIGO_INTERFACE_FOCUSER);
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, home, .1));
	SERIAL_CHECK_TRUE(select_goto_mode(device));
	lunatico_forget_commands();
	int target = home + 300;
	unsigned int revision = property_revision(FOCUSER_POSITION_PROPERTY_NAME);
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, device->device_name, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, target));
	// The move is reported BUSY and the driver must publish measured progress,
	// never the requested target, before the controller confirms arrival.
	SERIAL_CHECK_TRUE(wait_for_property_state_seen_after(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE, revision));
	char command[64];
	snprintf(command, sizeof(command), "!step goto %d %d 0#", port, target);
	SERIAL_CHECK_TRUE(lunatico_wait_for_command(command));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, target, .1));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	snprintf(command, sizeof(command), "!step ismoving %d#", port);
	SERIAL_CHECK_TRUE(lunatico_sent(command));
cleanup:
	stop();
}

static void main_absolute_move(void) { absolute_move_on(&main_focuser, 0, HOME_MAIN); }

static void exp_absolute_move(void) { absolute_move_on(&exp_focuser, 1, HOME_OTHER); }

static void third_absolute_move(void) { absolute_move_on(&third_focuser, 2, HOME_OTHER); }

// A GOTO to the position the driver is already at must be answered OK without
// any motion command.
static void no_op_goto_sends_no_command(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 1500));
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1500, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_not_sent("!step goto 0 1500 0#"));
cleanup:
	stop();
}

// SYNC updates the controller's position counter through !step setpos# and must
// not start a move.
static void sync_updates_counter_without_moving(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 4200));
	SERIAL_CHECK_TRUE(lunatico_sent("!step setpos 0 4200#"));
	SERIAL_CHECK_TRUE(lunatico_not_sent("!step goto 0 4200 0#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 4200, .1));
cleanup:
	stop();
}

// A SYNC to the position the driver has not read yet must still reach the
// controller. Defect LU-09: the pre-migration driver compared the request
// against a measured position that the connection handler never filled in, so
// the very first request for position 0 was answered OK with no command at all
// while the focuser stayed where it was.
static void sync_to_zero_right_after_connect(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(settle_after_connect(0));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, HOME_MAIN, .1));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_SYNC_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step setpos 0 0#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0, .1));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- relative motion

// A relative move is issued as an absolute GOTO whose target the driver derives
// from the measured position and FOCUSER_DIRECTION.
static void relative_steps_follow_direction(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 1000));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_OUTWARD_ITEM_NAME, INDIGO_OK_STATE));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1100, .1));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	// A relative move carries no backlash compensation.
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step goto 0 1100 0#"));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME, INDIGO_OK_STATE));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1000, .1));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_STEPS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step goto 0 1000 0#"));
cleanup:
	stop();
}

// An inward relative move larger than the current position must clamp at the
// minimum instead of asking the controller for a negative target.
static void relative_steps_clamp_at_minimum(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 200));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_DIRECTION_PROPERTY_NAME, FOCUSER_DIRECTION_MOVE_INWARD_ITEM_NAME, INDIGO_OK_STATE));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 500, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 0, .1));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step goto 0 0 0#"));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- stop

// Abort has to stop the controller, publish the measured stopped position and
// leave the focuser ready for a fresh move.
static void abort_stops_motion_and_allows_a_fresh_move(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 0));
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 100000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE));
	// The change branch publishes BUSY before the queued handler starts the move,
	// so the abort has to wait for the motion to be under way.
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step goto 0 100000 0#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 100, 100));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step stop 0#"));
	SERIAL_CHECK_TRUE(wait_for_property_not_busy(FOCUSER_POSITION_PROPERTY_NAME));
	double stopped = cached_number_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME);
	SERIAL_CHECK_TRUE(stopped > 0 && stopped < 100000);
	// A fresh move must work after an abort.
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 1000));
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1100, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1100, .1));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	stop();
}

// Abort with nothing moving is a valid request and still stops the controller.
static void abort_while_idle_is_accepted(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step stop 0#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, HOME_MAIN, .1));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- settings

// FOCUSER_SPEED is a step rate in kHz and reaches the controller as a
// microsecond range, !step speedrangeus <port> <us> <us># with us = 1000 / kHz.
static void speed_is_sent_as_a_microsecond_range(void) {
	SERIAL_CHECK_TRUE(start_main());
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 0.2, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step speedrangeus 0 5000 5000#"));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 20, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step speedrangeus 0 50 50#"));
cleanup:
	stop();
}

// FOCUSER_LIMITS are software limits of the controller. The full range deletes
// them, a narrower range writes them, and the controller then refuses a target
// outside them.
static void limits_are_written_and_enforced(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(settle_after_connect(0));
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 1000));
	lunatico_forget_commands();
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MAX_POSITION_ITEM_NAME, 2000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step setswlimits 0 0 2000#"));
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	// The controller rejects the goto, which the driver has to report.
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 3000, INDIGO_ALERT_STATE));
	// Restoring the full range deletes the controller's limits again.
	lunatico_forget_commands();
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MAX_POSITION_ITEM_NAME, 100000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step delswlimits 0#"));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1300, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1300, .1));
cleanup:
	stop();
}

// A minimum above the maximum is a driver-side operational constraint, not a
// framework range check, so the driver rejects it with its own message.
static void inverted_limits_are_rejected(void) {
	SERIAL_CHECK_TRUE(start_main());
	lunatico_forget_commands();
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MIN_POSITION_ITEM_NAME, 50000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_OK_STATE));
	lunatico_forget_commands();
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MAX_POSITION_ITEM_NAME, 100));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(lunatico_not_sent("!step setswlimits 0 50000 100#"));
cleanup:
	stop();
}

// FOCUSER_BACKLASH is passed to the controller as the third argument of
// !step goto#, and only for absolute moves.
static void backlash_is_passed_to_goto(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 1000));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_BACKLASH_PROPERTY_NAME, FOCUSER_BACKLASH_ITEM_NAME, 50, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1200, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step goto 0 1200 50#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1200, .1));
cleanup:
	stop();
}

// Reverse motion and the motor wiring selection are combined into one
// !step wiremode# value: 0/1 for Lunatico normal/reversed, 2/3 for Moonlite.
static void wiring_combines_reverse_motion_and_motor_wiring(void) {
	SERIAL_CHECK_TRUE(start_main());
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_ENABLED_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step wiremode 0 1#"));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_MOTOR_WIRING_PROPERTY_NAME, "MOONLITE", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step wiremode 0 3#"));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_DISABLED_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step wiremode 0 2#"));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_MOTOR_WIRING_PROPERTY_NAME, "LUNATICO", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step wiremode 0 0#"));
cleanup:
	stop();
}

// The remaining driver-specific motor settings each map onto one command.
static void motor_settings_reach_the_controller(void) {
	SERIAL_CHECK_TRUE(start_main());
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_MOTOR_TYPE_PROPERTY_NAME, "BIPOLAR", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step model 0 1#"));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_MOTOR_TYPE_PROPERTY_NAME, "STEP_DIR", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step model 0 3#"));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_STEP_MODE_PROPERTY_NAME, "HALF", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step halfstep 0 1#"));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_STEP_MODE_PROPERTY_NAME, "FULL", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step halfstep 0 0#"));
	// Coil current is a percentage the driver scales by 10.23 to the
	// controller's 0...1023 range.
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, X_FOCUSER_POWER_CONTROL_PROPERTY_NAME, "MOVE_POWER", 50, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step movepow 0 511#"));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, X_FOCUSER_POWER_CONTROL_PROPERTY_NAME, "STOP_POWER", 10, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step stoppow 0 102#"));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- temperature

// The internal sensor is read at connect and polled afterwards; selecting the
// external sensor switches the polled sensor index.
static void temperature_is_read_and_the_sensor_is_selectable(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!read temps 0#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, lunatico_internal_celsius(LUNATICO_RAW_INTERNAL_20C), .05));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_TEMPERATURE_SENSOR_PROPERTY_NAME, "EXTERNAL", INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!read temps 1#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, lunatico_external_celsius(LUNATICO_RAW_EXTERNAL_20C), .05));
cleanup:
	stop();
}

// A raw reading below the driver's NO_TEMP_READING threshold means no sensor is
// connected, which is reported as IDLE rather than as a failure.
static void absent_temperature_sensor_is_idle(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!read temps 0#"));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_TEMPERATURE_PROPERTY_NAME, INDIGO_IDLE_STATE));
cleanup:
	stop();
}

// In automatic mode a temperature change of at least one degree has to produce
// a compensating move of FOCUSER_COMPENSATION steps per degree, in the
// direction opposite to the change.
static void temperature_compensation_moves_the_focuser(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, 20, .05));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, 10, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_AUTOMATIC_ITEM_NAME, INDIGO_OK_STATE));
	// The driver deliberately restarts compensation from the reading that follows
	// the switch to automatic mode, so one temperature poll has to seed the
	// reference before the change is injected.
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!read temps 0#"));
	lunatico_forget_commands();
	// Raw 567 is 30.08 C, so the difference is 10.08 C and the compensation is
	// (int)(10.08 * 10) = 100 steps inward from 1800.
	SERIAL_CHECK_TRUE(lunatico_control("temperature:567"));
	SERIAL_CHECK_TRUE(lunatico_wait_for_command("!step goto 0 1700 0#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 1700, .1));
cleanup:
	stop();
}

// In manual mode no compensation may happen however far the temperature drifts.
static void manual_mode_does_not_compensate(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_COMPENSATION_PROPERTY_NAME, FOCUSER_COMPENSATION_ITEM_NAME, 10, INDIGO_OK_STATE));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_control("temperature:567"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_TEMPERATURE_PROPERTY_NAME, FOCUSER_TEMPERATURE_ITEM_NAME, 30.08, .05));
	SERIAL_CHECK_TRUE(lunatico_not_sent("!step goto 0 1700 0#"));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, HOME_MAIN, .1));
cleanup:
	stop();
}

// Automatic mode takes the manual motion controls away and makes the position
// read-only; manual mode restores them.
static void mode_switches_manual_controls(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_AUTOMATIC_ITEM_NAME, INDIGO_OK_STATE));
	indigo_property *position = find_cached_property(FOCUSER_POSITION_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(position != NULL && position->perm == INDIGO_RO_PERM);
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_MODE_PROPERTY_NAME, FOCUSER_MODE_MANUAL_ITEM_NAME, INDIGO_OK_STATE));
	position = find_cached_property(FOCUSER_POSITION_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(position != NULL && position->perm == INDIGO_RW_PERM);
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_STEPS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(FOCUSER_ABORT_MOTION_PROPERTY_NAME));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- failures

// A rejected GOTO must be reported and must not be overwritten by the poll that
// would otherwise find the focuser idle at the unchanged position.
static void goto_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(settle_after_connect(0));
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000, INDIGO_ALERT_STATE));
	// The failure has to survive a poll interval.
	indigo_usleep(1500000);
	indigo_property *position = find_cached_property(FOCUSER_POSITION_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(position != NULL && position->state == INDIGO_ALERT_STATE);
cleanup:
	stop();
}

// The same applies to a rejected relative move.
static void relative_move_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(settle_after_connect(0));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_STEPS_PROPERTY_NAME, FOCUSER_STEPS_ITEM_NAME, 100, INDIGO_ALERT_STATE));
	indigo_usleep(1500000);
	indigo_property *steps = find_cached_property(FOCUSER_STEPS_PROPERTY_NAME);
	SERIAL_CHECK_TRUE(steps != NULL && steps->state == INDIGO_ALERT_STATE);
cleanup:
	stop();
}

// A rejected SYNC must be reported rather than silently accepted.
static void sync_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_ON_POSITION_SET_PROPERTY_NAME, FOCUSER_ON_POSITION_SET_SYNC_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 4200, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step setpos 0 4200#"));
cleanup:
	stop();
}

// A rejected stop is reported on FOCUSER_ABORT_MOTION.
static void stop_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_ABORT_MOTION_PROPERTY_NAME, FOCUSER_ABORT_MOTION_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(lunatico_sent("!step stop 0#"));
cleanup:
	stop();
}

// A corrupt position readback during a move is reported on the position.
static void read_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 2000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_ALERT_STATE));
cleanup:
	stop();
}

// A rejected setting must not be reported as success. One scenario per
// controller setting, each driven by its own simulator failure profile.
static void step_mode_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_STEP_MODE_PROPERTY_NAME, "HALF", INDIGO_ALERT_STATE));
cleanup:
	stop();
}

static void wiring_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, FOCUSER_REVERSE_MOTION_PROPERTY_NAME, FOCUSER_REVERSE_MOTION_ENABLED_ITEM_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_MOTOR_WIRING_PROPERTY_NAME, "MOONLITE", INDIGO_ALERT_STATE));
cleanup:
	stop();
}

static void motor_type_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_set_switch(&main_focuser, X_FOCUSER_MOTOR_TYPE_PROPERTY_NAME, "DC", INDIGO_ALERT_STATE));
cleanup:
	stop();
}

static void power_control_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, X_FOCUSER_POWER_CONTROL_PROPERTY_NAME, "MOVE_POWER", 50, INDIGO_ALERT_STATE));
cleanup:
	stop();
}

static void speed_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_SPEED_PROPERTY_NAME, FOCUSER_SPEED_ITEM_NAME, 0.2, INDIGO_ALERT_STATE));
cleanup:
	stop();
}

static void limits_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_LIMITS_PROPERTY_NAME, FOCUSER_LIMITS_MAX_POSITION_ITEM_NAME, 2000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_LIMITS_PROPERTY_NAME, INDIGO_ALERT_STATE));
cleanup:
	stop();
}

// A GOTO issued while the one-shot poll armed by the connection handler is
// still pending has to complete anyway. This is the overlapping-request case of
// defect LU-05: the pre-migration driver arms the completion poll through
// PORT_DATA.focuser_timer, indigo_set_timer() refuses a non-NULL reference
// outright and logs "Attempt to set timer with non-NULL reference", so the move
// is finished only because the already pending poll happens to pick it up. The
// scenario pins the observable outcome, which the migration must preserve
// without relying on that coincidence.
static void goto_overlapping_the_connect_poll(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	SERIAL_CHECK_TRUE(lunatico_set_number(&main_focuser, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, HOME_MAIN + 400, INDIGO_BUSY_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, HOME_MAIN + 400, .1));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- identity refusal

// The controller identity is verified at connect, so a wrong model, a
// bootloader-mode controller, an unparsable version, no reply at all and a
// reply with no terminator must each refuse the connection instead of coming up
// half configured.
static void connection_is_refused(void) {
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&main_focuser));
	selected = &main_focuser;
	char url[PATH_MAX];
	lunatico_url(url, sizeof(url));
	SERIAL_CHECK_TRUE(aux_reject(&main_focuser, url));
	SERIAL_CHECK_TRUE(wait_for_property_state(CONNECTION_PROPERTY_NAME, INDIGO_ALERT_STATE));
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	stop();
}

// A port the controller does not have must be refused. A Limpet has only the
// Main port and an Armadillo has no Third port.
static void absent_port_is_refused(const simulator_driver_case *device) {
	selected = device;
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&main_focuser));
	bool configurable = has_defined_property("LUNATICO_MODEL");
	char url[PATH_MAX];
	lunatico_url(url, sizeof(url));
	reset_simulator_context(device);
	if (configurable) {
		indigo_change_switch_property_1(&simulator_test_client, main_focuser.device_name, "LUNATICO_MODEL", "PLATYPUS", true);
		indigo_change_switch_property_1(&simulator_test_client, main_focuser.device_name, strstr(device->device_name, "(Exp)") ? "LUNATICO_PORT_EXP_CONFIG" : "LUNATICO_PORT_THIRD_CONFIG", "FOCUSER", true);
	}
	SERIAL_CHECK_TRUE(lunatico_wait_for_device(configurable));
	indigo_change_text_property_1_raw(&simulator_test_client, main_focuser.device_name, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, url);
	indigo_usleep(200000);
	SERIAL_CHECK_TRUE(aux_reject(device, url));
	SERIAL_CHECK_TRUE(!context.connected);
cleanup:
	stop();
}

static void limpet_has_no_exp_port(void) { absent_port_is_refused(&exp_focuser); }

static void armadillo_has_no_third_port(void) { absent_port_is_refused(&third_focuser); }

// --------------------------------------------------------------------------------- lifecycle

static void reconnect_after_disconnect(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	disconnect_serial_device(&main_focuser);
	SERIAL_CHECK_TRUE(!context.connected);
	// The driver-specific properties are deleted on disconnect.
	SERIAL_CHECK_TRUE(find_cached_property(X_FOCUSER_STEP_MODE_PROPERTY_NAME) == NULL);
	char url[PATH_MAX];
	lunatico_url(url, sizeof(url));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(connect_serial_device(&main_focuser, url));
	SERIAL_CHECK_TRUE(lunatico_sent("!seletek version#"));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(has_defined_property(X_FOCUSER_STEP_MODE_PROPERTY_NAME));
cleanup:
	stop();
}

// Disconnecting while a move is running must not hang and must not leave the
// poll running against a closed transport.
static void disconnect_during_motion(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(sync_to(&main_focuser, 0));
	SERIAL_CHECK_TRUE(select_goto_mode(&main_focuser));
	SERIAL_CHECK_EQ_INT(INDIGO_OK, indigo_change_number_property_1(&simulator_test_client, main_focuser.device_name, FOCUSER_POSITION_PROPERTY_NAME, FOCUSER_POSITION_ITEM_NAME, 100000));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_BUSY_STATE));
	disconnect_serial_device(&main_focuser);
	SERIAL_CHECK_TRUE(!context.connected);
	lunatico_forget_commands();
	// Nothing may be sent to the controller after the transport is closed.
	indigo_usleep(1500000);
	SERIAL_CHECK_TRUE(lunatico_not_sent("!step getpos 0#"));
	SERIAL_CHECK_TRUE(lunatico_not_sent("!step ismoving 0#"));
cleanup:
	stop();
}

// The Main and Exp devices share one controller connection. Either order must
// work, a sibling must survive the other one disconnecting, and the last close
// owns the transport.
static void shared_connection_survives_sibling_disconnect(void) {
	selected = &exp_focuser;
	SERIAL_CHECK_TRUE(bring_up_serial_driver(&main_focuser));
	bool configurable = has_defined_property("LUNATICO_MODEL");
	char url[PATH_MAX];
	lunatico_url(url, sizeof(url));
	if (configurable) {
		indigo_change_switch_property_1(&simulator_test_client, main_focuser.device_name, "LUNATICO_MODEL", "PLATYPUS", true);
	}
	// Connect the Exp device first, so the secondary opens the transport.
	reset_simulator_context(&exp_focuser);
	SERIAL_CHECK_TRUE(lunatico_wait_for_device(configurable));
	indigo_change_text_property_1_raw(&simulator_test_client, main_focuser.device_name, DEVICE_PORT_PROPERTY_NAME, DEVICE_PORT_ITEM_NAME, url);
	indigo_usleep(200000);
	SERIAL_CHECK_TRUE(connect_serial_device(&exp_focuser, url));
	// Now the Main device joins the same connection.
	SERIAL_CHECK_TRUE(connect_serial_device(&main_focuser, url));
	SERIAL_CHECK_TRUE(wait_for_property_state(FOCUSER_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	// Closing Main must leave Exp working on the still open transport.
	disconnect_serial_device(&main_focuser);
	reset_simulator_context(&exp_focuser);
	enumerate_simulator_device();
	SERIAL_CHECK_TRUE(context.connected || has_defined_property(FOCUSER_POSITION_PROPERTY_NAME));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(sync_to(&exp_focuser, 1200));
	SERIAL_CHECK_TRUE(lunatico_sent("!step setpos 1 1200#"));
cleanup:
	disconnect_serial_device(&exp_focuser);
	disconnect_serial_device(&main_focuser);
	aux_stop(&main_focuser);
}

// The driver must refuse to unload while a device is still connected.
static void shutdown_is_refused_while_connected(void) {
	SERIAL_CHECK_TRUE(start_main());
	SERIAL_CHECK_EQ_INT(INDIGO_BUSY, main_focuser.entry(INDIGO_DRIVER_SHUTDOWN, NULL));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- powerbox

// The powerbox device exposes the DB9 digital outputs and analog inputs. Both
// are horizontally flipped, so outlet item 1 writes pin 4 and sensor item 1
// reads pin 8; the simulator answers a distinct value per analog pin, which is
// what makes the mapping observable.
static void powerbox_outlets_and_sensors(void) {
	SERIAL_CHECK_TRUE(lunatico_start(&exp_aux, "AUX_POWERBOX"));
	assert_device_interface(INDIGO_INTERFACE_AUX_GPIO | INDIGO_INTERFACE_AUX_POWERBOX);
	SERIAL_CHECK_TRUE(has_defined_property(AUX_OUTLET_NAMES_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(AUX_SENSOR_NAMES_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(AUX_POWER_OUTLET_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(has_defined_property(AUX_GPIO_SENSORS_PROPERTY_NAME));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_SENSORS_PROPERTY_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_GPIO_SENSORS_PROPERTY_NAME, AUX_GPIO_SENSOR_NAME_1_ITEM_NAME, 508, .5));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_GPIO_SENSORS_PROPERTY_NAME, AUX_GPIO_SENSOR_NAME_2_ITEM_NAME, 507, .5));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_GPIO_SENSORS_PROPERTY_NAME, AUX_GPIO_SENSOR_NAME_3_ITEM_NAME, 506, .5));
	SERIAL_CHECK_TRUE(wait_for_number_item_value(AUX_GPIO_SENSORS_PROPERTY_NAME, AUX_GPIO_SENSOR_NAME_4_ITEM_NAME, 505, .5));
	lunatico_forget_commands();
	SERIAL_CHECK_TRUE(lunatico_set_switch(&exp_aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, INDIGO_OK_STATE));
	SERIAL_CHECK_TRUE(aux_wait_switch(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, true));
	// Every outlet is written on each change, item 1 last of the four pins.
	SERIAL_CHECK_TRUE(lunatico_sent("!write dig 1 4 1#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!write dig 1 3 0#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!write dig 1 2 0#"));
	SERIAL_CHECK_TRUE(lunatico_sent("!write dig 1 1 0#"));
	// The powerbox port has no stepper, so the motor settings stay hidden.
	SERIAL_CHECK_TRUE(find_cached_property(X_FOCUSER_STEP_MODE_PROPERTY_NAME) == NULL);
	SERIAL_CHECK_TRUE(find_cached_property(X_FOCUSER_MOTOR_TYPE_PROPERTY_NAME) == NULL);
cleanup:
	stop();
}

// Renaming an outlet or a sensor relabels the corresponding item.
static void powerbox_names_relabel_items(void) {
	SERIAL_CHECK_TRUE(lunatico_start(&exp_aux, "AUX_POWERBOX"));
	SERIAL_CHECK_TRUE(lunatico_set_text(&exp_aux, AUX_OUTLET_NAMES_PROPERTY_NAME, AUX_POWER_OUTLET_NAME_1_ITEM_NAME, "Dew heater", INDIGO_OK_STATE));
	indigo_item *outlet = find_cached_item(AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME);
	SERIAL_CHECK_TRUE(outlet != NULL && !strcmp(outlet->label, "Dew heater"));
	SERIAL_CHECK_TRUE(lunatico_set_text(&exp_aux, AUX_SENSOR_NAMES_PROPERTY_NAME, AUX_GPIO_SENSOR_NAME_1_ITEM_NAME, "Rain", INDIGO_OK_STATE));
	indigo_item *sensor = find_cached_item(AUX_GPIO_SENSORS_PROPERTY_NAME, AUX_GPIO_SENSOR_NAME_1_ITEM_NAME);
	SERIAL_CHECK_TRUE(sensor != NULL && !strcmp(sensor->label, "Rain"));
cleanup:
	stop();
}

static void powerbox_outlet_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(lunatico_start(&exp_aux, "AUX_POWERBOX"));
	SERIAL_CHECK_TRUE(lunatico_set_switch(&exp_aux, AUX_POWER_OUTLET_PROPERTY_NAME, AUX_POWER_OUTLET_1_ITEM_NAME, INDIGO_ALERT_STATE));
cleanup:
	stop();
}

static void powerbox_sensor_failure_is_reported(void) {
	SERIAL_CHECK_TRUE(lunatico_start(&exp_aux, "AUX_POWERBOX"));
	SERIAL_CHECK_TRUE(wait_for_property_state(AUX_GPIO_SENSORS_PROPERTY_NAME, INDIGO_ALERT_STATE));
cleanup:
	stop();
}

// --------------------------------------------------------------------------------- rotator on a secondary port

// The focuser entry point can still drive a rotator on a secondary port, which
// is the whole point of the configurable ports.
static void rotator_on_the_exp_port(void) {
	SERIAL_CHECK_TRUE(lunatico_start(&exp_rotator, "ROTATOR"));
	assert_device_interface(INDIGO_INTERFACE_ROTATOR);
	assert_serial_rotator_class_property_completeness();
	SERIAL_CHECK_TRUE(wait_for_property_state(ROTATOR_POSITION_PROPERTY_NAME, INDIGO_OK_STATE));
	// The temperature sensor selection is focuser-only.
	SERIAL_CHECK_TRUE(find_cached_property(X_FOCUSER_TEMPERATURE_SENSOR_PROPERTY_NAME) == NULL);
	SERIAL_CHECK_TRUE(has_defined_property(X_ROTATOR_MOTOR_TYPE_PROPERTY_NAME));
cleanup:
	stop();
}

int main(void) {
	const aux_simulated_case tests[] = {
		{ "identity_and_inventory", identity_and_inventory, "normal" },
		{ "main_absolute_move", main_absolute_move, "normal" },
		{ "exp_absolute_move", exp_absolute_move, "normal" },
		{ "third_absolute_move", third_absolute_move, "normal" },
		{ "no_op_goto", no_op_goto_sends_no_command, "normal" },
		{ "sync_without_moving", sync_updates_counter_without_moving, "normal" },
		{ "sync_to_zero_after_connect", sync_to_zero_right_after_connect, "normal" },
		{ "relative_steps", relative_steps_follow_direction, "normal" },
		{ "relative_steps_clamp", relative_steps_clamp_at_minimum, "normal" },
		{ "abort_motion", abort_stops_motion_and_allows_a_fresh_move, "normal" },
		{ "abort_while_idle", abort_while_idle_is_accepted, "normal" },
		{ "speed", speed_is_sent_as_a_microsecond_range, "normal" },
		{ "limits", limits_are_written_and_enforced, "normal" },
		{ "inverted_limits", inverted_limits_are_rejected, "normal" },
		{ "backlash", backlash_is_passed_to_goto, "normal" },
		{ "wiring", wiring_combines_reverse_motion_and_motor_wiring, "normal" },
		{ "motor_settings", motor_settings_reach_the_controller, "normal" },
		{ "temperature", temperature_is_read_and_the_sensor_is_selectable, "normal" },
		{ "absent_temperature_sensor", absent_temperature_sensor_is_idle, "no-temp-sensor" },
		{ "temperature_compensation", temperature_compensation_moves_the_focuser, "normal" },
		{ "manual_mode_does_not_compensate", manual_mode_does_not_compensate, "normal" },
		{ "focuser_mode", mode_switches_manual_controls, "normal" },
		{ "goto_failure", goto_failure_is_reported, "goto-error" },
		{ "relative_move_failure", relative_move_failure_is_reported, "goto-error" },
		{ "sync_failure", sync_failure_is_reported, "setpos-error" },
		{ "stop_failure", stop_failure_is_reported, "stop-error" },
		{ "read_failure", read_failure_is_reported, "read-error" },
		{ "step_mode_failure", step_mode_failure_is_reported, "step-mode-error" },
		{ "wiring_failure", wiring_failure_is_reported, "wiring-error" },
		{ "motor_type_failure", motor_type_failure_is_reported, "motor-error" },
		{ "power_control_failure", power_control_failure_is_reported, "power-error" },
		{ "speed_failure", speed_failure_is_reported, "speed-error" },
		{ "limits_failure", limits_failure_is_reported, "limits-error" },
		{ "goto_overlapping_connect_poll", goto_overlapping_the_connect_poll, "normal" },
		{ "wrong_model", connection_is_refused, "wrong-model" },
		{ "bootloader", connection_is_refused, "bootloader" },
		{ "bad_version", connection_is_refused, "bad-version" },
		{ "silent", connection_is_refused, "silent" },
		{ "oversized", connection_is_refused, "oversized" },
		{ "limpet_has_no_exp_port", limpet_has_no_exp_port, "limpet" },
		{ "armadillo_has_no_third_port", armadillo_has_no_third_port, "armadillo" },
		{ "reconnect", reconnect_after_disconnect, "normal" },
		{ "disconnect_during_motion", disconnect_during_motion, "normal" },
		{ "shared_connection", shared_connection_survives_sibling_disconnect, "normal" },
		{ "shutdown_refused_while_connected", shutdown_is_refused_while_connected, "normal" },
		{ "powerbox", powerbox_outlets_and_sensors, "normal" },
		{ "powerbox_names", powerbox_names_relabel_items, "normal" },
		{ "powerbox_outlet_failure", powerbox_outlet_failure_is_reported, "outlet-error" },
		{ "powerbox_sensor_failure", powerbox_sensor_failure_is_reported, "sensor-error" },
		{ "rotator_on_exp", rotator_on_the_exp_port, "normal" },
	};
	return run_aux_simulated("Lunatico focuser", LUNATICO_SIMULATOR, tests, ARRAY_SIZE(tests));
}
