// Talon6 ROR serial simulator
//
// Copyright (c) 2026 CloudMakers, s. r. o.
// All rights reserved.
//
// You can use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// This source file was generated by a Codex agent.

#define _DEFAULT_SOURCE
#define _XOPEN_SOURCE 600

#include <errno.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "../../../indigo_test/simulator_common/serial_simulator_common.h"

#define CLOSED_POSITION 0
#define OPENED_POSITION 819100
#define RESPONSE_LENGTH 128

typedef struct {
	bool headless;
	bool trace;
	const char *ready_file;
} simulator_options;

static simulator_options options = {
	.headless = false,
	.trace = true,
	.ready_file = NULL
};

static const char *simulator_name = "dome_talon6ror";
static volatile sig_atomic_t running = 1;
static int serial_fd = -1;
static int position = CLOSED_POSITION;
static int direction = 0;
static int moving_reports = 0;
static int last_action = 0;

static uint8_t configuration[55] = {
	0x80, 0x81, 0xB4, 0x80, 0x81, 0x8C, 0x80, 0x80, 0x82, 0x80, 0x80, 0xE4, 0x80, 0x80, 0x8E, 0x80, 0x80, 0x94, 0x80, 0x80, 0xF8, 0x80, 0x80, 0xBC, 0x80, 0x80, 0xB6, 0x80, 0x80, 0xBC, 0x80, 0x80, 0x80, 0x80, 0x80, 0xF8, 0x83, 0x86, 0xD0, 0x80, 0x80, 0x85, 0x80, 0x80, 0x80, 0x84, 0xA0, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0xF8, 0x9E
};

static void usage(const char *name) {
	printf("Talon6 ROR serial simulator\n");
	printf("Usage: %s [OPTIONS]\n", name);
	printf("  --headless              Disable terminal-oriented output\n");
	printf("  --ready-file <path>     Write INDIGO_SIMULATOR_PORT after PTY setup\n");
	printf("  --trace                 Log protocol requests and replies\n");
	printf("  -h, --help              Show this help and exit\n");
}

static void signal_handler(int sig) {
	(void)sig;
	running = 0;
	if (serial_fd >= 0) {
		close(serial_fd);
		serial_fd = -1;
	}
}

static bool parse_args(int argc, char *argv[]) {
	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
			usage(argv[0]);
			exit(0);
		} else if (!strcmp(argv[i], "--headless")) {
			options.headless = true;
			options.trace = false;
		} else if (!strcmp(argv[i], "--trace")) {
			options.trace = true;
		} else if (!strcmp(argv[i], "--ready-file")) {
			if (++i == argc) {
				fprintf(stderr, "--ready-file requires a path\n");
				return false;
			}
			options.ready_file = argv[i];
		} else {
			fprintf(stderr, "Unknown option '%s'\n", argv[i]);
			return false;
		}
	}
	return true;
}

static void pack_value(uint8_t *buffer, int value) {
	buffer[0] = 0x80 | ((value >> 14) & 0x7F);
	buffer[1] = 0x80 | ((value >> 7) & 0x7F);
	buffer[2] = 0x80 | (value & 0x7F);
}

static void append_checksum(uint8_t *buffer, int first, int last, int checksum_index) {
	int sum = 0;
	for (int i = first; i <= last; i++) {
		sum += buffer[i];
	}
	buffer[checksum_index] = 0x80 | (-(sum % 128) & 0x7F);
}

static void update_motion(void) {
	if (direction == 0) {
		return;
	}
	if (moving_reports > 0) {
		moving_reports--;
		return;
	}
	if (direction > 0) {
		position = OPENED_POSITION;
		direction = 0;
	} else if (direction < 0) {
		position = CLOSED_POSITION;
		direction = 0;
	}
}

static void make_status(uint8_t *response, size_t *length) {
	uint8_t status[21] = { 0 };
	int state = 4;

	update_motion();
	if (direction > 0) {
		state = 2;
	} else if (direction < 0) {
		state = 3;
	} else if (position == OPENED_POSITION) {
		state = 0;
	} else if (position == CLOSED_POSITION) {
		state = 1;
	}

	memset(status, 0x80, sizeof(status));
	status[0] = 0x80 | ((state & 0x07) << 4) | (last_action & 0x0F);
	pack_value(status + 1, position);
	status[4] = 0x86;
	status[5] = 0xC4;
	status[14] = 0x80 | (position == CLOSED_POSITION ? (1 << 4) : 0) | (position == OPENED_POSITION ? (1 << 3) : 0);
	status[17] = 0x84;
	append_checksum(status, 0, 19, 20);

	response[0] = '&';
	response[1] = 'G';
	memcpy(response + 2, status, sizeof(status));
	response[23] = '#';
	*length = 24;
}

static void make_config(uint8_t *response, size_t *length) {
	response[0] = '&';
	response[1] = 'p';
	memcpy(response + 2, configuration, sizeof(configuration));
	response[57] = '#';
	*length = 58;
}

static void write_response(const uint8_t *response, size_t length) {
	if (options.trace) {
		fprintf(stderr, "->");
		for (size_t i = 0; i < length; i++) {
			if (response[i] >= 32 && response[i] <= 126) {
				fprintf(stderr, " %c", response[i]);
			} else {
				fprintf(stderr, " %02X", response[i]);
			}
		}
		fprintf(stderr, "\n");
	}
	serial_simulator_write_all(serial_fd, (const char *)response, length);
}

static void handle_command(const uint8_t *command, size_t length) {
	uint8_t response[RESPONSE_LENGTH] = { 0 };
	size_t response_length = 0;

	if (options.trace) {
		fprintf(stderr, "<-");
		for (size_t i = 0; i < length; i++) {
			if (command[i] >= 32 && command[i] <= 126) {
				fprintf(stderr, " %c", command[i]);
			} else {
				fprintf(stderr, " %02X", command[i]);
			}
		}
		fprintf(stderr, "\n");
	}

	if (length == 4 && !memcmp(command, "&V%#", 4)) {
		memcpy(response, "&V3.20N--#", 10);
		response_length = 10;
	} else if (length == 4 && !memcmp(command, "&G%#", 4)) {
		make_status(response, &response_length);
	} else if (length == 4 && !memcmp(command, "&O%#", 4)) {
		direction = 1;
		moving_reports = 3;
		last_action = 1;
		memcpy(response, "&#", 2);
		response_length = 2;
	} else if (length == 4 && (!memcmp(command, "&P%#", 4) || !memcmp(command, "&C%#", 4))) {
		direction = -1;
		moving_reports = 3;
		last_action = 2;
		memcpy(response, "&#", 2);
		response_length = 2;
	} else if (length == 4 && !memcmp(command, "&S%#", 4)) {
		direction = 0;
		moving_reports = 0;
		last_action = 13;
		memcpy(response, "&#", 2);
		response_length = 2;
	} else if (length == 4 && !memcmp(command, "&p%#", 4)) {
		make_config(response, &response_length);
	} else if (length >= 59 && command[0] == '&' && command[1] == 'a' && command[length - 2] == '%' && command[length - 1] == '#') {
		memcpy(configuration, command + 2, sizeof(configuration));
		memcpy(response, "&#", 2);
		response_length = 2;
	} else {
		memcpy(response, "&ERROR#", 7);
		response_length = 7;
	}
	write_response(response, response_length);
}

static void run_protocol_loop(void) {
	uint8_t buffer[RESPONSE_LENGTH] = { 0 };
	size_t length = 0;

	while (running) {
		uint8_t c = 0;
		ssize_t bytes_read = read(serial_fd, &c, 1);
		if (bytes_read < 0) {
			if (errno == EINTR) {
				continue;
			}
			if (errno == EAGAIN || errno == EWOULDBLOCK || errno == EIO) {
				usleep(1000);
				continue;
			}
			perror("read");
			break;
		}
		if (bytes_read == 0) {
			usleep(1000);
			continue;
		}
		if (length < sizeof(buffer)) {
			buffer[length++] = c;
		} else {
			length = 0;
		}
		if (c == '#') {
			handle_command(buffer, length);
			length = 0;
		}
	}
}

int main(int argc, char *argv[]) {
	char port[256] = { 0 };

	if (!parse_args(argc, argv)) {
		return 1;
	}
	signal(SIGTERM, signal_handler);
	signal(SIGINT, signal_handler);

	serial_fd = serial_simulator_open_pty(port, sizeof(port));
	if (serial_fd < 0) {
		return 1;
	}
	if (options.ready_file != NULL && !serial_simulator_write_ready_file(options.ready_file, simulator_name, port)) {
		close(serial_fd);
		return 1;
	}
	if (!options.headless) {
		printf("Talon6 ROR simulator ready on %s\n", port);
	}

	run_protocol_loop();
	if (serial_fd >= 0) {
		close(serial_fd);
	}
	return 0;
}
