.TH GRAB_GRAY_IMAGE "1" "January 2004" "grab_gray_image" "User Commands"
.SH NAME
grab_gray_image \- grab an image using libdc1394
.SH SYNOPSIS
.B grab_gray_image
.SH DESCRIPTION
Get one gray image using libdc1394 and store it in portable grayscale map format in Image.pgm
.SH OPTIONS
.TP
none
.PP
.SH BUGS
The filename should be a commandline argument
.SH AUTHOR
This manual page was written by Peter De Schrijver <p2@debian.org> for the Debian GNU/Linux system (but may be used by others) and added to upstream by Peter Antoniac <theseinfeld@users.sf.net>.

