// Copyright (c) 2026 INDIGO initiative
// Copyright (c) 2026 CloudMakers, s. r. o.
// All rights reserved.
//
// You may use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code is generated by AI

// LX200 host-side protocol simulator, version 5.
#define _DEFAULT_SOURCE
#define _XOPEN_SOURCE 600

#include <ctype.h>
#include <errno.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

#include "../../../indigo_test/simulator_common/serial_simulator_common.h"
#include "../../../indigo_test/simulator_common/serial_motion.h"

typedef enum {
	MODEL_MEADE,
	MODEL_ONSTEP, MODEL_10MIC, MODEL_GEMINI, MODEL_STARGO, MODEL_STARGO2, MODEL_AP, MODEL_AGOTINO, MODEL_ZWO, MODEL_NYX, MODEL_OAT, MODEL_TEEN, MODEL_GENERIC, MODEL_ASI, MODEL_ESP32GO, MODEL_CLASSIC
} simulator_model;

typedef struct {
	bool headless;
	bool trace;
	bool tcp;
	// Whether :GU# carries the documented k for the king rate. OnStepX 10.28x does not, so the
	// default is the firmware that omits it and only answers the rate through :GT#.
	bool status_king;
	// A Gemini that has not been aligned, or that has no object selected, answers :CM# with
	// "No object!#" instead of the name of the object it synchronised to. Gemini Level 5
	// command description, Synchronize section. The default is the aligned mount, so existing
	// cases keep their meaning.
	bool unaligned;
	// A Gemini whose park does not take: the command is accepted, the mount never starts the
	// operation and :h?# keeps answering 0, which the command description gives both for "No
	// Prk command received" and for "Park operation failed". Gemini Level 5, :h?#.
	bool park_fails;
	// A Gemini that another client put into Double Precision with :u#: every coordinate comes
	// back as a signed decimal with six digits after the point, and :GG# answers the extended
	// offset with minutes and seconds. Gemini Level 5 command description, :u# and :GG#.
	bool double_precision;
	const char *ready_file;
	simulator_model model;
} simulator_options;

typedef struct {
	int date_day;
	int date_month;
	int date_year;
	int time_hour;
	int time_minute;
	int time_second;
	int time_offset;
	int time_dst;
	char latitude[16];
	char longitude[16];
	bool high_precision;
	long ra_cs;
	long dec_as;
	long target_ra_cs;
	long target_dec_as;
	bool slewing;
	bool tracking;
	bool parked;
	bool at_home;
	char tracking_rate;
	double classic_frequency;
	char slew_rate;
	char pec;
	int focuser_position;
	int focuser_move;
	int focuser_speed;
	int aux_value[9];
	bool meridian_flip;
	bool meridian_track;
	int meridian_limit;
	int max_slew_speed;
	int tracking_error;
	int alignment_points;
	// A NYX-101 that was reset at its home position with :hF# behaves like a cold started
	// controller: it refuses :hP# with 0 until tracking is enabled again. Observed on firmware
	// 1.32.1, see indigo_drivers/mount_lx200/REFACTOR.md.
	bool standby;
	// An OpenAstroTracker stops its tracking motor for the duration of every slew and starts it
	// again when the slew ends, so the tracking it reports goes away and comes back on its own.
	// Observed on firmware v1.13.20, Mount::startSlewingToTarget() in the firmware source.
	bool oat_tracking_resume;
	// A Gemini keeps its real time clock at UTC, so the offset has to be given before the date
	// and the local time; the command description says so under :SG# and the controller refuses
	// a date it cannot place on a timeline. Cleared once per session, like the controller does
	// at power-up. Gemini Level 5 command description, :SG#.
	bool offset_set;
	// The position an aGotino keeps reporting for as long as a slew is running. Its firmware
	// recomputes the strings :GR# and :GD# answer from only after the slew loop ends, which its
	// own source marks as a known limitation. Observed on firmware 230312.
	long frozen_ra_cs;
	long frozen_dec_as;
} simulator_state;

static simulator_options options = {
	.headless = false,
	.trace = true,
	.ready_file = NULL,
	.model = MODEL_MEADE
};
static simulator_state state = {
	.date_day = 1,
	.date_month = 1,
	.date_year = 2026,
	.time_hour = 22,
	.time_minute = 15,
	.time_second = 30,
	.time_offset = 2,
	.time_dst = 1,
	.meridian_flip = true,
	.meridian_limit = 0,
	.max_slew_speed = 720,
	.alignment_points = 3,
	.latitude = "+48*08",
	.longitude = "-17*06",
	.high_precision = true,
	.ra_cs = 6L * 60L * 60L * 100L,
	.dec_as = 45L * 60L * 60L,
	.target_ra_cs = 6L * 60L * 60L * 100L,
	.target_dec_as = 45L * 60L * 60L,
	.slewing = false,
	.tracking = false,
	.parked = false,
	.at_home = true,
	.tracking_rate = 'Q',
	.slew_rate = 'M',
	.pec = 'I',
	.focuser_position = 0,
	.focuser_move = 0,
	.focuser_speed = 1,
	.aux_value = { 0, 1, 128, 0, 0, 0, 0, 0, 0 }
};

static const char *simulator_name = "mount_lx200";
static volatile sig_atomic_t running = 1;
static int serial_fd = -1;
static int listen_fd = -1;

static void usage(const char *name) {
	printf("LX200 mount serial simulator\n");
	printf("Usage: %s [OPTIONS]\n", name);
	printf("  --headless              Disable terminal-oriented output\n");
	printf("  --status-king           Report the king rate as k in :GU#, as the protocol documents\n");
	printf("  --unaligned             Answer :CM# with the Gemini \"No object!\" refusal\n");
	printf("  --park-fails            Accept the Gemini park but keep answering :h?# with 0\n");
	printf("  --double-precision      Answer Gemini coordinates as decimals and :GG# extended\n");
	printf("  --model <name>          a supported LX200 profile\n");
	printf("  --ready-file <path>     Write INDIGO_SIMULATOR_PORT after PTY setup\n");
	printf("  --tcp                   Serve an opt-in localhost TCP transport\n");
	printf("  --trace                 Log protocol requests and replies\n");
	printf("  -h, --help              Show this help and exit\n");
}

static const char *model_names[] = { "meade", "onstep", "10mic", "gemini", "stargo", "stargo2", "ap", "agotino", "zwo", "nyx", "oat", "teen", "generic", "asi", "esp32go", "classic" };
static const char *products[] = { "Autostar", "On-Step", "10micron", "Losmandy", "Avalon", "Avalon", "AstroPhysics", "aGotino", "AM5", "NYX-101", "OpenAstroTracker", "TeenAstro", "Classic", "AM5", "esp32go", "" };

// The aGotino is an Arduino sketch that answers eleven LX200 commands and nothing else. Every
// other request is read, matched against the few it knows and dropped without a reply, which is
// what a driver that asks for a site, a clock or a guide pulse gets from it.
static bool model_is_agotino(void) {
	return options.model == MODEL_AGOTINO;
}

static bool model_is_oat(void) {
	return options.model == MODEL_OAT;
}

// The ESP32Go prints every angle with 0xE1 where the protocol allows * or 0xDF, answers :GR# with
// a tenth of a second of time, carries its whole state in :GU#, and has no command that stops the
// tracking motor and none that releases a mount :hP# sent home. Observed on the source commit
// bbf224a, see indigo_drivers/mount_lx200/REFACTOR.md.
static bool model_is_esp32go(void) {
	return options.model == MODEL_ESP32GO;
}

// misc.cpp of the ESP32Go firmware prints the degree mark with sprintf(..., 225, ...), so every
// declination, altitude, azimuth, latitude and longitude carries 0xE1 instead of the asterisk.
static void esp32go_degree_mark(char *text) {
	char *separator = strchr(text, '*');
	if (separator != NULL) {
		*separator = (char)0xE1;
	}
}

// "asi" is the "zwo" profile plus the AM-series commands and the firmware revision that
// indigo_mount_asi requires; indigo_mount_lx200 never sends those commands.
static bool model_is_zwo(void) {
	return options.model == MODEL_ZWO || options.model == MODEL_ASI;
}

static bool parse_model(const char *value, simulator_model *model) {
	for (int i = 0; i < (int)(sizeof(model_names) / sizeof(*model_names)); i++) {
		if (!strcmp(value, model_names[i])) {
			*model = i;
			return true;
		}
	}
	return false;
}

static bool parse_args(int argc, char *argv[]) {
	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
			usage(argv[0]);
			exit(0);
		} else if (!strcmp(argv[i], "--headless")) {
			options.headless = true;
			options.trace = false;
		} else if (!strcmp(argv[i], "--tcp")) {
			options.tcp = true;
		} else if (!strcmp(argv[i], "--status-king")) {
			options.status_king = true;
		} else if (!strcmp(argv[i], "--unaligned")) {
			options.unaligned = true;
		} else if (!strcmp(argv[i], "--park-fails")) {
			options.park_fails = true;
		} else if (!strcmp(argv[i], "--double-precision")) {
			options.double_precision = true;
		} else if (!strcmp(argv[i], "--trace")) {
			options.trace = true;
		} else if (!strcmp(argv[i], "--model")) {
			if (++i == argc || !parse_model(argv[i], &options.model)) {
				fprintf(stderr, "--model requires a supported LX200 profile\n");
				return false;
			}
		} else if (!strcmp(argv[i], "--ready-file")) {
			if (++i == argc) {
				fprintf(stderr, "--ready-file requires a path\n");
				return false;
			}
			options.ready_file = argv[i];
		} else {
			fprintf(stderr, "Unknown option '%s'\n", argv[i]);
			return false;
		}
	}
	return true;
}

static void signal_handler(int sig) {
	(void)sig;
	running = 0;
	if (serial_fd >= 0) {
		close(serial_fd);
		serial_fd = -1;
	}
}

static void write_response(const char *response) {
	if (options.trace) {
		fprintf(stderr, "<- %s\n", response);
	}
	const char *cursor = response;
	size_t remaining = strlen(response);
	while (running && remaining > 0) {
		ssize_t written = write(serial_fd, cursor, remaining);
		if (written > 0) {
			cursor += written;
			remaining -= (size_t)written;
		} else if (written < 0 && (errno == EINTR || errno == EAGAIN || errno == EWOULDBLOCK || errno == EIO)) {
			usleep(1000);
		} else {
			running = 0;
		}
	}
}

static bool model_is_double_precision(void) {
	return options.model == MODEL_GEMINI && options.double_precision;
}

static void format_ra(char *buffer, size_t size, long value) {
	if (model_is_double_precision()) {
		snprintf(buffer, size, "%+.6f#", value / 360000.0);
		return;
	}
	if (model_is_esp32go()) {
		// lxprintra1() and mount_lxra_str() both append a fifteenth of a second of time as one
		// digit after the seconds, whatever precision mode the mount is in.
		snprintf(buffer, size, "%02ld:%02ld:%02ld.%ld#", value / 360000L, (value / 6000L) % 60, (value / 100L) % 60, ((value % 100L) * 2L / 3L) % 15L);
	} else if (state.high_precision) {
		snprintf(buffer, size, "%02ld:%02ld:%02ld#", value / 360000L, (value / 6000L) % 60, (value / 100L) % 60);
	} else {
		snprintf(buffer, size, "%02ld:%04.1f#", value / 360000L, ((value / 600L) % 600) / 10.0);
	}
}

static void format_dec(char *buffer, size_t size, long value) {
	if (model_is_double_precision()) {
		snprintf(buffer, size, "%+.6f#", value / 3600.0);
		return;
	}
	long degrees = value / 3600L;
	long abs_value = labs(value);
	if (model_is_esp32go()) {
		snprintf(buffer, size, "%c%02ld*%02ld:%02ld#", value < 0 ? '-' : '+', labs(degrees), (abs_value / 60L) % 60, abs_value % 60);
		esp32go_degree_mark(buffer);
		return;
	}
	if (state.high_precision) {
		snprintf(buffer, size, "%c%02ld*%02ld:%02ld#", value < 0 ? '-' : '+', labs(degrees), (abs_value / 60L) % 60, abs_value % 60);
	} else {
		snprintf(buffer, size, "%c%02ld*%02ld#", value < 0 ? '-' : '+', labs(degrees), (abs_value / 60L) % 60);
	}
}

static void set_target_ra(const char *text) {
	state.target_ra_cs = atol(text) * 360000L + atol(text + 3) * 6000L;
	if (text[5] == '.') {
		state.target_ra_cs = atol(text) * 360000L + (long)(atof(text + 3) * 6000.0);
	} else {
		state.target_ra_cs += atol(text + 6) * 100L;
	}
}

static void set_target_dec(const char *text) {
	long degrees = atol(text);
	long value = labs(degrees) * 3600L + atol(text + 4) * 60L;
	if (text[6] == '\'' || text[6] == ':') {
		value += atol(text + 7);
	}
	state.target_dec_as = text[0] == '-' ? -value : value;
}

static serial_motion ra_motion, dec_motion, focus_motion;
static int manual_ra, manual_dec;
static bool parking_requested, homing_requested;
// When the pulse a :Mg[d][n]# command started ends. A NYX-101 counts a running pulse as motion
// and refuses :MS# with error 8 until it is over; observed on firmware 1.32.1, see
// indigo_drivers/mount_lx200/REFACTOR.md.
static double guide_pulse_until;
// A guide pulse moves the axis it is sent to, at the guide rate, for as long as it lasts. The
// rates are the classic half sidereal: 15.041 arcseconds per second of declination and one
// second of right ascension per second, both halved. Without them a pulse only consumed time and
// the simulated mount stood still, which no real mount does.
#define GUIDE_RATE 0.5
#define SIDEREAL_ARCSEC_PER_SECOND 15.041067
static double guide_ra_rate, guide_dec_rate;
// The three stepper positions an OpenAstroTracker reports in :GX#, all derived from the motion
// above rather than made up: the declination stepper carries the offset from the home position
// at the 314.1 steps per degree measured on the bench controller, the right ascension stepper is
// zero unless a slew is under way because tracking is carried by the tracking stepper alone, and
// that one counts down for as long as the mount tracks. Observed on firmware v1.13.20.
#define OAT_DEC_STEPS_PER_DEGREE 314.1
#define OAT_HOME_DEC_AS 324000.0
#define OAT_TRACK_STEPS_PER_SECOND 88.0
static double oat_track_steps;
static double park_ra, park_dec = 324000;
static double last_update;
static char fault_command[128], fault_reply[128];
static FILE *events;
static char preferred_side = 'A';
static bool auto_flip;
static int east_limit = 60, west_limit = 60, horizon = -10, overhead = 85;

static void update_motion(void) {
	double now = serial_motion_time();
	double elapsed = now - last_update;
	last_update = now;
	serial_motion_update(&ra_motion);
	serial_motion_update(&dec_motion);
	if (manual_ra) {
		serial_motion_sync(&ra_motion, fmod(ra_motion.position + manual_ra * elapsed * 6000 + 8640000, 8640000));
	}
	if (manual_dec) {
		serial_motion_sync(&dec_motion, fmax(-324000, fmin(324000, dec_motion.position + manual_dec * elapsed * 3600)));
	}
	// The part of this interval the pulse was still running for.
	double guide_elapsed = fmin(now, guide_pulse_until) - (now - elapsed);
	if (guide_elapsed > 0) {
		if (guide_ra_rate != 0) {
			serial_motion_sync(&ra_motion, fmod(ra_motion.position + guide_ra_rate * guide_elapsed + 8640000, 8640000));
		}
		if (guide_dec_rate != 0) {
			serial_motion_sync(&dec_motion, fmax(-324000, fmin(324000, dec_motion.position + guide_dec_rate * guide_elapsed)));
		}
	}
	if (now >= guide_pulse_until) {
		guide_ra_rate = guide_dec_rate = 0;
	}
	if (state.tracking) {
		oat_track_steps -= OAT_TRACK_STEPS_PER_SECOND * elapsed;
	}
	state.ra_cs = lround(ra_motion.position);
	state.dec_as = lround(dec_motion.position);
	state.slewing = ra_motion.duration > 0 || dec_motion.duration > 0;
	if (!state.slewing && state.oat_tracking_resume) {
		// The firmware restarts the tracker itself, with a compensation for the time it stood
		// still, so the tracking setting of the client survives the slew.
		state.tracking = true;
		state.oat_tracking_resume = false;
	}
	if (!state.slewing && (parking_requested || homing_requested)) {
		state.parked = parking_requested;
		state.at_home = homing_requested;
		parking_requested = homing_requested = false;
	}
	state.focuser_position = lround(serial_motion_update(&focus_motion));
}

// Atomic control-file rename in the test prevents partial injection requests.
static void read_control(void) {
	char path[PATH_MAX];
	snprintf(path, sizeof(path), "%s.control", options.ready_file);
	FILE *file = fopen(path, "r");
	if (file != NULL) {
		char line[256];
		if (fgets(line, sizeof(line), file)) {
			line[strcspn(line, "\r\n")] = 0;
			char *tab = strchr(line, '\t');
			if (tab != NULL) {
				*tab++ = 0;
				snprintf(fault_command, sizeof(fault_command), "%s", line);
				snprintf(fault_reply, sizeof(fault_reply), "%s", tab);
			}
		}
		fclose(file);
		unlink(path);
	}
}

static void start_reference_motion(bool parking) {
	manual_ra = manual_dec = 0;
	state.tracking = false;
	state.parked = state.at_home = false;
	parking_requested = parking;
	homing_requested = !parking;
	serial_motion_start(&ra_motion, parking ? park_ra : 0, 1800000);
	serial_motion_start(&dec_motion, parking ? park_dec : 324000, 162000);
}

// The command dispatch of the aGotino sketch, in its own order: the two coordinate queries, the
// :GV* family, the two target setters, everything that starts with M or with Q, the sync and the
// distance bar. Everything else - a site query, a clock query, a status word - is read off the
// line and dropped without a reply, so a driver that sends one waits out its own timeout.
// Answers false when the request is one the sketch does not act on, and handles the requests
// whose reply differs from the shared implementation itself.
static bool agotino_dispatch(const char *command) {
	if (!strcmp(command, "GR") || !strcmp(command, "GD") || !strcmp(command, "CM") || !strcmp(command, "D")) {
		return true;
	}
	if (!strncmp(command, "Sr", 2) || !strncmp(command, "Sd", 2)) {
		return true;
	}
	if (!strncmp(command, "GV", 2)) {
		// Only the product name and the version have an answer; every other :GV* is acknowledged
		// with the bare terminator the sketch prints after the switch.
		if (!strcmp(command, "GVP") || !strcmp(command, "GVN")) {
			return true;
		}
		write_response("#");
		return false;
	}
	// A slow move and a stop have no reply, and neither has a guide pulse: the sketch matches the
	// M of :Mg..., finds no direction in the g and drops the request, which is exactly why a
	// pulse on an aGotino moves nothing.
	if (*command == 'M') {
		return !strncmp(command, "Mg", 2) ? false : true;
	}
	return *command == 'Q';
}

static void handle_command(const char *command) {
	char response[128] = { 0 };
	update_motion();
	read_control();
	if (events != NULL) {
		fprintf(events, "%.9f\t%s\n", serial_motion_time(), command);
		fflush(events);
	}
	if (*fault_command && !strcmp(command, fault_command)) {
		*fault_command = 0;
		if (model_is_agotino() && !strcmp(command, "D") && !strcmp(fault_reply, "COMPLETE")) {
			// Deterministically finish after this poll's frozen GR/GD but before its distance bar.
			serial_motion_sync(&ra_motion, state.target_ra_cs);
			serial_motion_sync(&dec_motion, state.target_dec_as);
			update_motion();
		} else {
			if (strcmp(fault_reply, "DROP")) {
				write_response(fault_reply);
			}
			return;
		}
	}
	if (options.model == MODEL_CLASSIC && (!strncmp(command, "GV", 2) || !strncmp(command, "Mg", 2) || !strcmp(command, "TS") || !strcmp(command, "TL"))) {
		return;
	}
	if (model_is_agotino() && !agotino_dispatch(command)) {
		return;
	}
	if (options.trace) {
		fprintf(stderr, "-> :%s#\n", command);
	}
	if (!strncmp(command, "192", 3)) {
		state.tracking = true;
	} else if (!strncmp(command, "191", 3)) {
		state.tracking = false;
	} else if (!strcmp(command, "Te") || !strncmp(command, "MT", 2)) {
		state.tracking = strcmp(command, "MT0") != 0;
		if (state.tracking) {
			state.standby = false;
		}
		write_response("1");
	} else if (!strcmp(command, "Td")) {
		state.tracking = false;
		write_response("1");
	} else if (!strcmp(command, "Gm")) {
		write_response("W#");
	} else if (!strcmp(command, "GX") && model_is_oat()) {
		// The status word of an OpenAstroTracker, in the order its getStatusStateString() tests
		// them. STATUS_PARKED is defined as zero in the firmware, so "Parked" is the name it
		// gives to a mount with no status bit set at all: every idle mount reports it, wherever
		// its axes stand, and "Idle" is never reached for one. A driver that reads it as the
		// park state locks the mount out of its own tracking switch.
		const char *status = parking_requested ? "Parking" : homing_requested ? "Homing" : state.slewing ? "SlewToTarget" : state.tracking ? "Tracking" : "Parked";
		char flags[] = "------";
		if (state.slewing) {
			flags[0] = 'R';
			flags[1] = 'd';
		}
		if (state.tracking) {
			flags[2] = 'T';
		}
		char right_ascension[32], declination[32];
		format_ra(right_ascension, sizeof(right_ascension), state.ra_cs);
		format_dec(declination, sizeof(declination), state.dec_as);
		right_ascension[strcspn(right_ascension, "#")] = 0;
		declination[strcspn(declination, "#")] = 0;
		long dec_steps = lround((OAT_HOME_DEC_AS - dec_motion.position) / 3600.0 * OAT_DEC_STEPS_PER_DEGREE);
		long ra_steps = state.slewing ? lround((ra_motion.target - ra_motion.position) / 100.0 * OAT_DEC_STEPS_PER_DEGREE / 60.0) : 0;
		snprintf(response, sizeof(response), "%s,%s,%ld,%ld,%ld,%s,%s,,#", status, flags, ra_steps, dec_steps, lround(oat_track_steps), right_ascension, declination);
		write_response(response);
	} else if (!strcmp(command, "GX")) {
		write_response(state.parked ? "Parked#" : parking_requested ? "Parking#" : homing_requested ? "Homing#" : state.slewing ? "Slewing#" : state.tracking ? "Tracking#" : "Idle#");
	} else if (!strcmp(command, "GXI")) {
		snprintf(response, sizeof(response), "%c0%c%c000000000W#", state.slewing ? '2' : state.tracking ? '1' : '0', state.parked ? 'P' : parking_requested ? 'I' : 'p', state.at_home ? 'H' : 'x');
		write_response(response);
	} else if (!strcmp(command, "X34")) {
		snprintf(response, sizeof(response), "m%d%d#", state.slewing || manual_ra ? 5 : state.tracking ? 1 : 0, state.slewing || manual_dec ? 5 : 0);
		write_response(response);
	} else if (!strcmp(command, "X38")) {
		write_response(state.parked ? "p2#" : parking_requested ? "pB#" : "p0#");
	} else if (!strcmp(command, "TTSFh") || !strcmp(command, "TTSFd")) {
		write_response("1");
	} else if (!strcmp(command, "X22")) {
		write_response("50b60#");
	} else if (!strcmp(command, "Ggr")) {
		write_response("0.5#");
	} else if (!strcmp(command, "GBu")) {
		write_response("1");
	} else if (!strcmp(command, "GX96")) {
		snprintf(response, sizeof(response), "%c#", preferred_side);
		write_response(response);
	} else if (!strcmp(command, "GX95")) {
		write_response(auto_flip ? "1#" : "0#");
	} else if (!strcmp(command, "GXE9") || !strcmp(command, "GXEA") || !strcmp(command, "Gh") || !strcmp(command, "Go")) {
		int value = !strcmp(command, "GXE9") ? east_limit : !strcmp(command, "GXEA") ? west_limit : !strcmp(command, "Gh") ? horizon : overhead;
		snprintf(response, sizeof(response), "%d#", value);
		write_response(response);
	} else if (!strncmp(command, "SX96,", 5)) {
		preferred_side = command[5];
		write_response("1");
	} else if (!strncmp(command, "SX95,", 5)) {
		auto_flip = command[5] == '1';
		write_response("1");
	} else if (!strncmp(command, "SXE9,", 5) || !strncmp(command, "SXEA,", 5) || !strncmp(command, "Sh", 2) || !strncmp(command, "So", 2)) {
		if (!strncmp(command, "SXE9,", 5)) { east_limit = atoi(command + 5); }
		if (!strncmp(command, "SXEA,", 5)) { west_limit = atoi(command + 5); }
		if (!strncmp(command, "Sh", 2)) { horizon = atoi(command + 2); }
		if (!strncmp(command, "So", 2)) { overhead = atoi(command + 2); }
		write_response("1");
	} else if (!strcmp(command, "WL>")) {
		write_response("INDIGO:test-password#");
	} else if (!strcmp(command, "WLD")) {
		write_response("network:192.0.2.1#");
	} else if (!strcmp(command, "GX9D")) {
		// Pitch and roll as a NYX-101 reports them: signed, and the roll is usually negative.
		write_response("34.5:-0.7#");
	} else if (!strcmp(command, "GX9E")) {
		write_response("123.5#");
	} else if (!strcmp(command, "GX9A")) {
		write_response("12.5#");
	} else if (!strcmp(command, "GX9B")) {
		write_response("1013.25#");
	} else if (!strcmp(command, "GX9V")) {
		write_response("12.8#");
	} else if (!strcmp(command, "hQ")) {
		// A NYX-101 refuses to store a park position while it is parked.
		if (options.model == MODEL_NYX && state.parked) {
			write_response("0");
			return;
		}
		park_ra = ra_motion.position;
		park_dec = dec_motion.position;
		write_response("1");
	} else if (!strncmp(command, "WA", 2) || !strncmp(command, "WB", 2) || !strncmp(command, "WS", 2) || !strncmp(command, "WP", 2) || (!strncmp(command, "SX", 2) && strncmp(command, "SXX", 3)) || !strncmp(command, "Sv", 2) || !strcmp(command, "hQ")) {
		write_response("1");
	} else if (!strcmp(command, "WLC")) {
		write_response("1");
	} else if (!strcmp(command, "TK")) {
		state.tracking_rate = 'K';
	} else if (!strncmp(command, "RT", 2)) {
		state.tracking = command[2] != '9';
	} else if (!strcmp(command, "Mn") || !strcmp(command, "Ms")) {
		manual_dec = command[1] == 'n' ? 1 : -1;
	} else if (!strcmp(command, "Me") || !strcmp(command, "Mw")) {
		manual_ra = command[1] == 'e' ? 1 : -1;
	} else if (!strcmp(command, "Qn") || !strcmp(command, "Qs")) {
		manual_dec = 0;
	} else if (!strcmp(command, "Qe") || !strcmp(command, "Qw")) {
		manual_ra = 0;
	} else if (!strcmp(command, "hR") || !strcmp(command, "hU")) {
		state.parked = false;
		if (model_is_oat()) {
			// :hU# is startSlewing(TRACKING) in the firmware, so unparking is literally turning
			// tracking on, and it is acknowledged with 1.
			state.tracking = true;
		}
		if (options.model == MODEL_ONSTEP || model_is_oat() || (options.model == MODEL_NYX && !strcmp(command, "hR"))) { write_response("1"); }
	} else if (!strcmp(command, "X362")) {
		start_reference_motion(true);
		write_response("pB#");
	} else if (!strcmp(command, "X370")) {
		state.parked = false;
		write_response("p0#");
	} else if (!strcmp(command, "X361") || !strcmp(command, "hF")) {
		if (!strcmp(command, "X361") || options.model == MODEL_10MIC) {
			start_reference_motion(false);
		} else {
			state.at_home = true;
			state.tracking = false;
			if (options.model == MODEL_NYX) {
				state.standby = true;
			}
		}
		if (!strcmp(command, "X361")) { write_response("pA#"); }
	} else if (!strcmp(command, "GVP")) {
		snprintf(response, sizeof(response), "%s#", products[options.model]);
		write_response(response);
	} else if (!strcmp(command, "GV")) {
		write_response(options.model == MODEL_ASI ? "1.2.4#" : "1.0.0#");
	} else if (options.model == MODEL_ASI && !strcmp(command, "GTa")) {
		// meridian settings: auto-flip, track-past, signed degree limit
		snprintf(response, sizeof(response), "%c%c%+03d#", state.meridian_flip ? '1' : '0', state.meridian_track ? '1' : '0', state.meridian_limit);
		write_response(response);
	} else if (options.model == MODEL_ASI && !strncmp(command, "STa", 3) && strlen(command) == 8) {
		state.meridian_flip = command[3] != '0';
		state.meridian_track = command[4] != '0';
		state.meridian_limit = atoi(command + 5);
		write_response("1");
	} else if (options.model == MODEL_ASI && !strcmp(command, "GRl")) {
		snprintf(response, sizeof(response), "%d#", state.max_slew_speed);
		write_response(response);
	} else if (options.model == MODEL_ASI && !strncmp(command, "SRl", 3)) {
		state.max_slew_speed = atoi(command + 3);
		write_response("1");
	} else if (options.model == MODEL_ASI && !strcmp(command, "GAT")) {
		// tracking status: "0", "1" or "e<code>"
		if (state.tracking_error) {
			snprintf(response, sizeof(response), "e%d#", state.tracking_error);
		} else {
			snprintf(response, sizeof(response), "%d#", state.tracking ? 1 : 0);
		}
		write_response(response);
	} else if (options.model == MODEL_ASI && !strcmp(command, "NSC")) {
		state.alignment_points = 0;
		write_response("1");
	} else if (!strcmp(command, "GVF")) {
		write_response(options.model == MODEL_ONSTEP ? "OnStep 4.24j#" : "ETX Autostar|A|43Eg|Apr 03 2007@11:25:53#");
	} else if (!strcmp(command, "GVN")) {
		write_response(options.model == MODEL_NYX ? "1.35#" : model_is_agotino() ? "230312#" : model_is_oat() ? "v1.13.20#" : model_is_esp32go() ? "06.9#" : "43Eg#");
	} else if (!strcmp(command, "GVD")) {
		write_response("Apr 03 2007#");
	} else if (!strcmp(command, "GVT")) {
		write_response("11:25:53#");
	} else if (!strcmp(command, "GU") && model_is_esp32go()) {
		// %c%c%c%c%d of tracking, parked, slewing, pier side and the tracking rate index. The
		// parked flag is the one mount_goto_home() raises when it starts the :hP# slew, so it is
		// already set while the mount is on its way home.
		snprintf(response, sizeof(response), "%c%c%c%c%d#", state.tracking ? 'T' : 't', state.at_home || homing_requested ? 'P' : 'p', state.slewing ? 'S' : 's', 'E', state.tracking_rate == 'S' ? 2 : state.tracking_rate == 'L' ? 3 : state.tracking_rate == 'K' ? 4 : 1);
		write_response(response);
	} else if (!strcmp(command, "GU")) {
		// OnStepX 10.28x never puts the documented k in its status: a mount on the king rate
		// reports exactly what a mount on the sidereal rate reports, and only :GT# tells them
		// apart. The NYX firmware that derives from it does report the k, which the NYX-101 run
		// verified on the mount, so the quirk belongs to OnStep alone. --status-king restores the
		// documented character for an OnStep build that has it.
		bool report_king = state.tracking_rate == 'K' && (options.model != MODEL_ONSTEP || options.status_king);
		const char *rate = state.tracking_rate == 'L' ? "(" : state.tracking_rate == 'S' ? "O" : report_king ? "k" : "";
		snprintf(response, sizeof(response), "G%s%s%s%sW%s%s#", state.tracking ? "" : "n", state.slewing ? "" : "N", state.parked ? "P" : parking_requested ? "I" : "p", state.at_home ? "H" : homing_requested ? "h" : "", auto_flip ? "a" : "", rate);
		write_response(response);
	} else if (!strncmp(command, "SC", 2)) {
		if (options.model == MODEL_GEMINI && !state.offset_set) {
			// "The time difference has to be set before setting the calendar date (SC) and
			// local time (SL), since the Real Time Clock is running at UTC."
			write_response("0");
			return;
		}
		state.date_month = atoi(command + 2);
		state.date_day = atoi(command + 5);
		state.date_year = 2000 + atoi(command + 8);
		write_response(options.model == MODEL_MEADE ? "1Updating Planetary Data#                                #" : "1");
	} else if (!strcmp(command, "GC")) {
		snprintf(response, sizeof(response), "%02d/%02d/%02d#", state.date_month, state.date_day, state.date_year % 100);
		write_response(response);
	} else if (!strncmp(command, "SG", 2)) {
		state.time_offset = atoi(command + 2);
		state.offset_set = true;
		write_response("1");
	} else if (!strcmp(command, "GG")) {
		if (model_is_double_precision()) {
			// The extended form is new in L5. A timezone at thirty minutes is what makes the
			// difference between reading the hours and reading the whole value.
			snprintf(response, sizeof(response), "%+03d:30:00#", state.time_offset);
		} else {
			snprintf(response, sizeof(response), "%+03d#", state.time_offset);
		}
		write_response(response);
	} else if (!strncmp(command, "SH", 2)) {
		state.time_dst = atoi(command + 2);
	} else if (!strcmp(command, "GH")) {
		snprintf(response, sizeof(response), "%d#", state.time_dst);
		write_response(response);
	} else if (options.model == MODEL_GEMINI && !strncmp(command, "SL", 2) && !state.offset_set) {
		write_response("0");
	} else if (!strncmp(command, "SL", 2)) {
		state.time_hour = atoi(command + 2);
		state.time_minute = atoi(command + 5);
		state.time_second = atoi(command + 8);
		write_response("1");
	} else if (!strcmp(command, "GL")) {
		snprintf(response, sizeof(response), "%02d:%02d:%02d#", state.time_hour, state.time_minute, state.time_second);
		write_response(response);
	} else if (!strcmp(command, "GS")) {
		write_response("12:00:00#");
	} else if (!strcmp(command, "GT")) {
		// A NYX-101 answers :GT# with 0 while tracking is disabled, which is not a rate. The
		// frequencies are the ones an OnStepX reports: the king rate is 0.028 Hz below sidereal
		// and is the only way to tell the two apart on a firmware whose status omits the k.
		if (options.model == MODEL_CLASSIC) {
			snprintf(response, sizeof(response), "%.1f#", state.tracking_rate == 'M' ? state.classic_frequency : 60.1);
			write_response(response);
		} else if (model_is_zwo()) {
			write_response(state.tracking_rate == 'L' ? "1#" : state.tracking_rate == 'S' ? "2#" : "0#");
		} else if ((options.model == MODEL_NYX || options.model == MODEL_ONSTEP) && !state.tracking) {
			write_response("0#");
		} else if (state.tracking_rate == 'L') {
			write_response("57.90000#");
		} else if (state.tracking_rate == 'S') {
			write_response("60.00000#");
		} else if (state.tracking_rate == 'K') {
			write_response("60.13600#");
		} else {
			write_response("60.16427#");
		}
	} else if (!strncmp(command, "Sg", 2)) {
		if (model_is_oat() && command[2] != '+' && command[2] != '-') {
			// An OpenAstroTracker takes :SgsDDD*MM# and answers anything without the sign with
			// 0, keeping the site it had. A driver that writes the unsigned form of the LX200
			// protocol never changes the site and is never told.
			write_response("0");
			return;
		}
		strncpy(state.longitude, command + 2, sizeof(state.longitude) - 1);
		write_response("1");
	} else if (!strcmp(command, "Gg")) {
		snprintf(response, sizeof(response), "%s#", state.longitude);
		if (model_is_esp32go()) {
			// lxprintlong1() marks the degrees the same way as every other angle. Without the
			// 0xE1 the driver's indigo_stod() stops at it and the arcminutes of the site are
			// silently lost.
			esp32go_degree_mark(response);
		}
		write_response(response);
	} else if (!strncmp(command, "St", 2)) {
		strncpy(state.latitude, command + 2, sizeof(state.latitude) - 1);
		write_response("1");
	} else if (!strcmp(command, "Gt")) {
		snprintf(response, sizeof(response), "%s#", state.latitude);
		if (model_is_esp32go()) {
			esp32go_degree_mark(response);
		}
		write_response(response);
	} else if (!strcmp(command, "U0")) {
		state.high_precision = false;
	} else if (!strcmp(command, "U1")) {
		state.high_precision = true;
	} else if (!strcmp(command, "U") || !strcmp(command, "P")) {
		state.high_precision = !state.high_precision;
	} else if (!strncmp(command, "Sr", 2)) {
		set_target_ra(command + 2);
		write_response("1");
	} else if (!strcmp(command, "Gr")) {
		format_ra(response, sizeof(response), state.target_ra_cs);
		write_response(response);
	} else if (!strcmp(command, "GR") || !strcmp(command, "GRH")) {
		format_ra(response, sizeof(response), model_is_agotino() && state.slewing ? state.frozen_ra_cs : state.ra_cs);
		write_response(response);
	} else if (!strncmp(command, "Sd", 2)) {
		set_target_dec(command + 2);
		write_response("1");
	} else if (!strcmp(command, "Gd")) {
		format_dec(response, sizeof(response), state.target_dec_as);
		write_response(response);
	} else if (!strcmp(command, "GD") || !strcmp(command, "GDH")) {
		format_dec(response, sizeof(response), model_is_agotino() && state.slewing ? state.frozen_dec_as : state.dec_as);
		if (model_is_agotino()) {
			// The sketch separates the degrees with the degree sign of the LX200 protocol, 0xDF,
			// where every other profile in this simulator uses the asterisk.
			char *separator = strchr(response, '*');
			if (separator != NULL) {
				*separator = (char)0xDF;
			}
		}
		if (model_is_oat()) {
			// An OpenAstroTracker separates the arcminutes from the arcseconds with the
			// arcminute mark: +45*00'00. Firmware v1.13.20.
			char *separator = strrchr(response, ':');
			if (separator != NULL) {
				*separator = '\'';
			}
		}
		write_response(response);
	} else if (!strcmp(command, "CM")) {
		if (options.model == MODEL_GEMINI && options.unaligned) {
			// The mount refuses the synchronisation and keeps the position it had. The reply is
			// a plain string like the successful one, which is what makes a driver that only
			// checks for an empty answer report a sync that never happened.
			write_response("No object!#");
			return;
		}
		serial_motion_sync(&ra_motion, state.target_ra_cs);
		serial_motion_sync(&dec_motion, state.target_dec_as);
		state.parked = false;
		write_response("M31 EX GAL MAG 3.5 SZ178.0'#");
	} else if (!strcmp(command, "MS")) {
		// A NYX-101 answers a goto issued while one of its pulses is still running with the
		// "already in motion" error instead of starting the slew.
		if (options.model == MODEL_NYX && serial_motion_time() < guide_pulse_until) {
			write_response("8");
			return;
		}
		state.frozen_ra_cs = state.ra_cs;
		state.frozen_dec_as = state.dec_as;
		serial_motion_start(&ra_motion, state.target_ra_cs, 1800000);
		serial_motion_start(&dec_motion, state.target_dec_as, 162000);
		state.at_home = false;
		state.slewing = true;
		state.tracking = true;
		state.parked = false;
		if (model_is_oat()) {
			// The firmware stops the tracking motor for the length of the goto and starts it
			// again when the slew ends, so :GX# reports no tracking while the mount is moving.
			state.tracking = false;
			state.oat_tracking_resume = true;
		}
		write_response("0");
	} else if (!strcmp(command, "D")) {
		// The aGotino answers a running slew with the DEL character its sketch prints; the other
		// profiles use the asterisk of a classic distance bar. Either is a non-empty reply, which
		// is all the protocol says about it.
		write_response(state.slewing ? (model_is_agotino() ? "\177#" : "*#") : "#");
	} else if (!strcmp(command, "Q")) {
		if (model_is_agotino() && state.slewing) {
			// The sketch breaks out of its slew loop on :Q# and then stores the target as the
			// current position, the same way it does when the loop ran to the end. The motors
			// stop where they are, so the mount points short of what it reports from then on,
			// and nothing in the protocol can find that out. Its own source marks this as a
			// known limitation. Observed on firmware 230312.
			serial_motion_sync(&ra_motion, state.target_ra_cs);
			serial_motion_sync(&dec_motion, state.target_dec_as);
		}
		serial_motion_stop(&ra_motion);
		serial_motion_stop(&dec_motion);
		manual_ra = manual_dec = 0;
		parking_requested = homing_requested = false;
		state.slewing = false;
	} else if (model_is_esp32go() && (!strcmp(command, "AP") || !strcmp(command, "AL"))) {
		// :AP# and :AL# reach telescope->track alone. The tracking loop recomputes the motor
		// speed from track_speed on its next pass, so neither command starts or stops the
		// tracking motor and :GU# keeps reporting what it reported before.
	} else if (!strcmp(command, "AP") || !strcmp(command, "X122")) {
		state.tracking = true;
	} else if (!strcmp(command, "AL") || !strcmp(command, "X120")) {
		state.tracking = false;
	} else if (model_is_esp32go() && !strcmp(command, "GW")) {
		// The :G grammar of this firmware has no W, so the request is read and dropped.
	} else if (!strcmp(command, "GW")) {
		write_response(state.tracking ? "PT1#" : state.parked ? "PNP#" : "PN1#");
	} else if (!strcmp(command, "Gstat")) {
		write_response(state.parked ? "5#" : parking_requested ? "2#" : homing_requested ? "4#" : state.slewing ? "6#" : state.tracking ? "0#" : "7#");
	} else if (!strcmp(command, "Gv")) {
		// ! is the stall of a Gemini; it is reached through the fault injection rather than a
		// permanent option, because what matters is the recovery on the next valid velocity.
		write_response(state.slewing ? "S" : state.tracking ? "T" : "N");
	} else if (model_is_esp32go() && !strcmp(command, "hP")) {
		// mount_goto_home() sends both axes to the stored home position and raises the parked
		// flag right away, and there is no reply and no command that releases it again.
		start_reference_motion(false);
	} else if (model_is_esp32go() && !strcmp(command, "hS")) {
		// set_home() stores the position the mount stands on, without a reply.
	} else if (!strcmp(command, "hP") || !strcmp(command, "hC") || !strcmp(command, "X362") || !strcmp(command, "Ch") || !strcmp(command, "KA")) {
		if (!strcmp(command, "hP") && options.model == MODEL_NYX && state.standby) {
			write_response("0");
			return;
		}
		if (options.model == MODEL_GEMINI && options.park_fails) {
			// The command is taken and nothing happens, which is all a client can observe.
			return;
		}
		start_reference_motion(strcmp(command, "hC") != 0 || options.model == MODEL_GEMINI);
		// OnStepX documents :hP# with a 0/1 reply and :hC# with none, and the NYX firmware that
		// derives from it does the same. A simulator that answers the home command anyway hides
		// a driver that waits for a reply the mount never sends.
		if (model_is_zwo() || ((options.model == MODEL_ONSTEP || options.model == MODEL_NYX) && !strcmp(command, "hP"))) { write_response("1"); }
	} else if (!strcmp(command, "PO") || !strcmp(command, "hW") || !strcmp(command, "X370")) {
		state.tracking = true;
		state.slewing = false;
		state.parked = false;
	} else if (!strcmp(command, "h?")) {
		write_response(state.parked ? "1" : parking_requested ? "2" : "0");
	} else if (options.model == MODEL_CLASSIC && !strncmp(command, "ST", 2)) {
		state.classic_frequency = atof(command + 2);
		write_response("1");
	} else if (!strcmp(command, "TQ")) {
		state.tracking_rate = 'Q';
	} else if (!strcmp(command, "TS") || !strcmp(command, "TSOLAR")) {
		state.tracking_rate = 'S';
	} else if (!strcmp(command, "TL")) {
		state.tracking_rate = 'L';
	} else if (!strcmp(command, "TM")) {
		state.tracking_rate = 'M';
	} else if (!strcmp(command, "RG")) {
		state.slew_rate = 'G';
	} else if (!strcmp(command, "RC")) {
		state.slew_rate = 'C';
	} else if (!strcmp(command, "RM")) {
		state.slew_rate = 'M';
	} else if (options.model == MODEL_ASI && strlen(command) == 2 && command[0] == 'R' && command[1] >= '0' && command[1] <= '9') {
		// AM-series numeric slew rates; the driver expects no reply
		state.slew_rate = command[1] <= '1' ? 'G' : command[1] <= '4' ? 'C' : command[1] <= '7' ? 'M' : 'S';
	} else if (!strcmp(command, "RS")) {
		state.slew_rate = 'S';
	} else if (!strncmp(command, "Mg", 2) || !strcmp(command, "Mn") || !strcmp(command, "Ms") || !strcmp(command, "Mw") || !strcmp(command, "Me") || !strcmp(command, "Qn") || !strcmp(command, "Qs") || !strcmp(command, "Qw") || !strcmp(command, "Qe")) {
		if (!strncmp(command, "Mg", 2) && strlen(command) > 3) {
			guide_pulse_until = serial_motion_time() + atoi(command + 3) / 1000.0;
			guide_ra_rate = guide_dec_rate = 0;
			// One second of right ascension is 100 centiseconds, one second of declination is
			// one arcsecond, and west and north are the increasing directions of both.
			if (command[2] == 'n' || command[2] == 's') {
				guide_dec_rate = (command[2] == 'n' ? 1 : -1) * GUIDE_RATE * SIDEREAL_ARCSEC_PER_SECOND;
			} else if (command[2] == 'w' || command[2] == 'e') {
				guide_ra_rate = (command[2] == 'e' ? 1 : -1) * GUIDE_RATE * 100;
			}
		}
		/* no reply */
	} else if (!strcmp(command, "F+")) {
		state.focuser_move = state.focuser_speed;
	} else if (!strcmp(command, "F-")) {
		state.focuser_move = -state.focuser_speed;
	} else if (!strcmp(command, "FS")) {
		state.focuser_speed = 1;
	} else if (!strcmp(command, "FF")) {
		state.focuser_speed = 5;
	} else if (!strcmp(command, "FQ")) {
		state.focuser_move = 0;
		serial_motion_stop(&focus_motion);
	} else if (!strcmp(command, "FP")) {
		snprintf(response, sizeof(response), "%d#", state.focuser_position);
		write_response(response);
	} else if (!strncmp(command, "FR", 2)) {
		serial_motion_start(&focus_motion, focus_motion.position + atoi(command + 2), 1000);
	} else if (!strcmp(command, "FT")) {
		write_response(focus_motion.duration > 0 ? "M#" : "S#");
	} else if (!strcmp(command, "Fa")) {
		// OnStep answers 1 only in a build that has a focuser, and 0 to every focuser command
		// in one that has none, including the :FT# a move waits on.
		write_response("1");
	} else if (!strcmp(command, "$QZ?")) {
		snprintf(response, sizeof(response), "%c#", state.pec);
		write_response(response);
	} else if (!strcmp(command, "$QZ+")) {
		state.pec = 'P';
	} else if (!strcmp(command, "$QZ-")) {
		state.pec = 'I';
	} else if (!strcmp(command, "GXY0")) {
		write_response("10110000#");
	} else if (!strncmp(command, "GXY", 3)) {
		int slot = atoi(command + 3);
		snprintf(response, sizeof(response), "%s,%d#", slot % 2 ? "Switch" : "Heater", slot % 2 ? 1 : 2);
		write_response(response);
	} else if (!strncmp(command, "GXX", 3)) {
		int slot = atoi(command + 3);
		snprintf(response, sizeof(response), "%d#", slot >= 1 && slot <= 8 ? state.aux_value[slot] : 0);
		write_response(response);
	} else if (!strncmp(command, "SXX", 3)) {
		int slot = atoi(command + 3);
		const char *value = strstr(command, ",V");
		if (slot >= 1 && slot <= 8 && value != NULL) {
			state.aux_value[slot] = atoi(value + 2);
		}
		write_response("1");
	}
}

static void handle_byte(char ch, char *buffer, size_t *length) {
	if ((unsigned char)ch == 6) {
		write_response("P");
		return;
	}
	if ((ch == ':' && *length == 0) || ch == '>') {
		*length = 0;
		return;
	}
	if (ch == '#') {
		buffer[*length] = 0;
		handle_command(buffer);
		*length = 0;
		return;
	}
	if (*length + 1 < 128) {
		buffer[(*length)++] = ch;
	}
}

int main(int argc, char *argv[]) {
	if (!parse_args(argc, argv)) {
		return 2;
	}
	char port[PATH_MAX];
	if (options.tcp) {
		listen_fd = socket(AF_INET, SOCK_STREAM, 0);
		struct sockaddr_in address = { 0 };
		address.sin_family = AF_INET;
		inet_pton(AF_INET, "127.0.0.1", &address.sin_addr);
		if (listen_fd < 0 || bind(listen_fd, (struct sockaddr *)&address, sizeof(address)) < 0 || listen(listen_fd, 4) < 0) {
			perror("LX200 simulator TCP listen");
			return 1;
		}
		socklen_t size = sizeof(address);
		if (getsockname(listen_fd, (struct sockaddr *)&address, &size) < 0) {
			return 1;
		}
		snprintf(port, sizeof(port), "lx200://127.0.0.1:%u", ntohs(address.sin_port));
	} else {
		serial_fd = serial_simulator_open_pty(port, sizeof(port));
		if (serial_fd < 0) {
			return 1;
		}
	}
	if (options.ready_file != NULL && !serial_simulator_write_ready_file(options.ready_file, simulator_name, port)) {
		close(serial_fd);
		return 1;
	}
	if (!options.headless) {
		printf("LX200 mount simulator ready on %s\n", port);
	}
	signal(SIGINT, signal_handler);
	signal(SIGTERM, signal_handler);
	signal(SIGPIPE, SIG_IGN);
	serial_motion_sync(&ra_motion, state.ra_cs);
	serial_motion_sync(&dec_motion, state.dec_as);
	serial_motion_sync(&focus_motion, 0);
	last_update = serial_motion_time();
	if (options.ready_file != NULL) {
		char path[PATH_MAX];
		snprintf(path, sizeof(path), "%s.events", options.ready_file);
		events = fopen(path, "w");
	}
	char command[128] = { 0 };
	size_t command_length = 0;
	while (running) {
		fd_set readfds;
		FD_ZERO(&readfds);
		int active_fd = serial_fd >= 0 ? serial_fd : listen_fd;
		FD_SET(active_fd, &readfds);
		struct timeval timeout = { 0, 100000 };
		int selected = select(active_fd + 1, &readfds, NULL, NULL, &timeout);
		if (selected < 0) {
			if (errno == EINTR) {
				continue;
			}
			break;
		}
		if (selected == 0 || !FD_ISSET(active_fd, &readfds)) {
			continue;
		}
		if (serial_fd < 0) {
			serial_fd = accept(listen_fd, NULL, NULL);
			command_length = 0;
			if (serial_fd >= 0 && events != NULL) {
				fprintf(events, "%.9f\tCONNECT\n", serial_motion_time());
				fflush(events);
			}
			continue;
		}
		char buffer[64];
		ssize_t count = read(serial_fd, buffer, sizeof(buffer));
		if (count > 0) {
			for (ssize_t i = 0; i < count; i++) {
				handle_byte(buffer[i], command, &command_length);
			}
		} else if (count < 0 && (errno == EINTR || errno == EAGAIN || errno == EWOULDBLOCK || errno == EIO)) {
			usleep(1000);
		} else if (count == 0) {
			if (options.tcp) {
				close(serial_fd);
				serial_fd = -1;
				if (events != NULL) {
					fprintf(events, "%.9f\tCLOSE\n", serial_motion_time());
					fflush(events);
				}
			} else {
				usleep(1000);
			}
		} else {
			break;
		}
	}
	if (listen_fd >= 0) { close(listen_fd); }
	if (events != NULL) { fclose(events); }
	if (serial_fd >= 0) {
		close(serial_fd);
	}
	return 0;
}
