// WeMacro Rail serial simulator
//
// Copyright (c) 2026 CloudMakers, s. r. o.
// All rights reserved.
//
// You can use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// This source file was generated by a Codex agent.

#define _DEFAULT_SOURCE
#define _XOPEN_SOURCE 600

#include <errno.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "../../../indigo_test/simulator_common/serial_simulator_common.h"

typedef struct {
	bool headless;
	bool trace;
	const char *ready_file;
} simulator_options;

static simulator_options options = {
	.headless = false,
	.trace = true,
	.ready_file = NULL
};

static const char *simulator_name = "focuser_wemacro";
static volatile sig_atomic_t running = 1;
static int serial_fd = -1;
static bool sent_initial_state = false;
static bool pending_state = false;
static uint8_t state = 0xf0;
static uint32_t batch_count = 0;
static bool batch_back = false;

static void usage(const char *name) {
	printf("WeMacro Rail serial simulator\n");
	printf("Usage: %s [OPTIONS]\n", name);
	printf("  --headless              Disable terminal-oriented output\n");
	printf("  --ready-file <path>     Write INDIGO_SIMULATOR_PORT after PTY setup\n");
	printf("  --trace                 Log protocol requests and replies\n");
	printf("  -h, --help              Show this help and exit\n");
}

static void signal_handler(int sig) {
	(void)sig;
	running = 0;
	if (serial_fd >= 0) {
		close(serial_fd);
		serial_fd = -1;
	}
}

static bool parse_args(int argc, char *argv[]) {
	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
			usage(argv[0]);
			exit(0);
		} else if (!strcmp(argv[i], "--headless")) {
			options.headless = true;
			options.trace = false;
		} else if (!strcmp(argv[i], "--trace")) {
			options.trace = true;
		} else if (!strcmp(argv[i], "--ready-file")) {
			if (++i == argc) {
				fprintf(stderr, "--ready-file requires a path\n");
				return false;
			}
			options.ready_file = argv[i];
		} else {
			fprintf(stderr, "Unknown option '%s'\n", argv[i]);
			return false;
		}
	}
	return true;
}

static void send_state(uint8_t value) {
	uint8_t response[3] = { 0xa5, 0x5a, value };
	if (options.trace) {
		fprintf(stderr, "-> %02x %02x %02x\n", response[0], response[1], response[2]);
	}
	serial_simulator_write_all(serial_fd, (const char *)response, sizeof(response));
}

static void trace_command(const uint8_t *command) {
	if (options.trace) {
		fprintf(stderr, "<-");
		for (int i = 0; i < 12; i++) {
			fprintf(stderr, " %02x", command[i]);
		}
		fprintf(stderr, "\n");
	}
}

static uint32_t command_value(const uint8_t *command) {
	return ((uint32_t)command[6] << 24) | ((uint32_t)command[7] << 16) | ((uint32_t)command[8] << 8) | command[9];
}

static void handle_command(const uint8_t *command) {
	uint8_t cmd = command[2];
	trace_command(command);

	if (cmd == 0x20) {
		batch_count = 0;
		pending_state = true;
		state = 0xf5;
	} else if (cmd == 0x40 || cmd == 0x41) {
		pending_state = true;
		state = cmd == 0x40 ? 0xf5 : 0xf6;
	} else if ((cmd & 0xf0) == 0x10) {
		batch_count = command_value(command) + 1;
		batch_back = (cmd & 0x08) != 0;
		pending_state = true;
		state = 0xf7;
	} else if (cmd == 0x04 || (cmd & 0x80) == 0x80) {
		pending_state = false;
	}
}

static bool read_command(uint8_t *command) {
	size_t length = 0;
	while (running && length < 12) {
		uint8_t byte = 0;
		ssize_t bytes_read = read(serial_fd, &byte, 1);
		if (bytes_read < 0) {
			if (errno == EINTR) {
				continue;
			}
			if (errno == EAGAIN || errno == EWOULDBLOCK || errno == EIO) {
				return false;
			}
			perror("read");
			running = 0;
			return false;
		}
		if (bytes_read == 0) {
			return false;
		}
		if (length == 0 && byte != 0xa5) {
			continue;
		}
		if (length == 1 && byte != 0x5a) {
			length = 0;
			continue;
		}
		command[length++] = byte;
	}
	return length == 12;
}

static void run_protocol_loop(void) {
	while (running) {
		uint8_t command[12] = { 0 };
		if (!sent_initial_state) {
			send_state(0xf0);
			sent_initial_state = true;
		} else if (pending_state) {
			send_state(state);
			if (state == 0xf7) {
				if (batch_count > 0) {
					batch_count--;
				}
				if (batch_count == 0) {
					if (batch_back) {
						state = 0xf6;
					} else {
						pending_state = false;
					}
				}
			} else {
				pending_state = false;
			}
		}
		if (read_command(command)) {
			handle_command(command);
		} else {
			usleep(1000);
		}
	}
}

int main(int argc, char *argv[]) {
	char port[256] = { 0 };

	if (!parse_args(argc, argv)) {
		return 1;
	}
	signal(SIGTERM, signal_handler);
	signal(SIGINT, signal_handler);

	serial_fd = serial_simulator_open_pty(port, sizeof(port));
	if (serial_fd < 0) {
		return 1;
	}
	if (options.ready_file != NULL && !serial_simulator_write_ready_file(options.ready_file, simulator_name, port)) {
		close(serial_fd);
		return 1;
	}
	if (!options.headless) {
		printf("WeMacro Rail simulator ready on %s\n", port);
	}

	run_protocol_loop();
	if (serial_fd >= 0) {
		close(serial_fd);
	}
	return 0;
}
