// Copyright (c) 2026 CloudMakers, s. r. o.
// All rights reserved.
//
// You can use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// version history
// 3.0 by Peter Polakovic <peter.polakovic@cloudmakers.eu>

// Code is generated by AI

/** INDIGO ASCOM Alpaca client driver, HTTP/1.1 client
 \file indigo_system_alpaca_http.h
 */

#ifndef system_alpaca_http_h
#define system_alpaca_http_h

#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Default timeouts in milliseconds, used for every alpaca_http_timeouts member that is zero or negative.
 */
#define ALPACA_HTTP_DEFAULT_CONNECT_TIMEOUT			5000
#define ALPACA_HTTP_DEFAULT_FIRST_BYTE_TIMEOUT	10000
#define ALPACA_HTTP_DEFAULT_INTER_BYTE_TIMEOUT	10000
#define ALPACA_HTTP_DEFAULT_TOTAL_TIMEOUT				120000

/** Largest accepted status line plus header block of one response, and largest accepted chunk size line or trailer block, in bytes.
 */
#define ALPACA_HTTP_MAX_HEADER_SIZE							16384

/** Sizes of the header value copies in alpaca_http_response, including the terminating NUL. Longer values are cut.
 */
#define ALPACA_HTTP_CONTENT_TYPE_SIZE						128
#define ALPACA_HTTP_CONTENT_ENCODING_SIZE				32
#define ALPACA_HTTP_LOCATION_SIZE								512

/** Smallest text buffer accepted by alpaca_http_format_double().
 */
#define ALPACA_HTTP_DOUBLE_SIZE									32

/** Result of a request. Everything except ALPACA_HTTP_OK means that no complete response was received
 and that the connection was closed; the next request opens a new one.
 */
typedef enum {
	/** A complete response was received. The HTTP status code is in alpaca_http_response.status and can be anything from 200 to 599; a 4xx or 5xx response is a successful exchange and its body is available as usual. */
	ALPACA_HTTP_OK = 0,
	/** The arguments were rejected (NULL, a path that does not start with '/', white space or control characters in the path or query, extra headers not terminated by CRLF, a request larger than 1 MB). Nothing was sent. */
	ALPACA_HTTP_INVALID_REQUEST,
	/** The host name was not resolved or the connection was refused or failed before the connect timeout. Nothing was sent. */
	ALPACA_HTTP_CONNECT_FAILED,
	/** The connection was not established within the connect timeout or the total timeout. Nothing was sent. */
	ALPACA_HTTP_CONNECT_TIMEOUT,
	/** The request was written, but no byte of the response arrived within the first byte timeout or the total timeout. The server may or may not have executed the request. */
	ALPACA_HTTP_FIRST_BYTE_TIMEOUT,
	/** The response started and then stalled for longer than the inter byte timeout, or the total timeout expired while the request was being written or the response was being received. */
	ALPACA_HTTP_TRANSFER_TIMEOUT,
	/** The socket reported an error at any point (typically a reset by the peer), or the peer closed the connection without sending a single byte of the response. The server may or may not have executed the request. */
	ALPACA_HTTP_RESET,
	/** The peer closed the connection in an orderly way after the response started, but before its header block, its Content-Length body or its chunked body was complete. The body holds the bytes received so far. */
	ALPACA_HTTP_TRUNCATED,
	/** The response is not HTTP/1.x: bad status line, header line without a colon, bad or conflicting Content-Length, bad chunk framing, too many interim responses, a Transfer-Encoding with a coding other than chunked (the client asks for none and decodes none). */
	ALPACA_HTTP_MALFORMED,
	/** The header block exceeds ALPACA_HTTP_MAX_HEADER_SIZE or the body exceeds the maximum size of the response buffer. The body holds the bytes accepted so far. */
	ALPACA_HTTP_TOO_LARGE
} alpaca_http_result;

/** Growable byte buffer owned by the caller and reused across requests. It is used for response bodies
 and by the form/query builder. The content is always NUL-terminated and the terminator is not counted in size,
 so text content can be used as a C string and binary content by data and size.
 The allocation only grows, in steps that at least double it, and never beyond max_size + 1 bytes.
 A zeroed structure is not valid, call alpaca_http_buffer_init() first.
 */
typedef struct {
	char *data;				///< content followed by NUL, or NULL as long as nothing was stored
	size_t size;			///< content size in bytes without the terminator
	size_t capacity;	///< allocated bytes
	size_t max_size;	///< hard limit of size
} alpaca_http_buffer;

/** Timeouts of one request in milliseconds. Zero or negative selects the default, so no member can switch a deadline off.
 */
typedef struct {
	int connect;			///< establishing the TCP connection (per resolved address of the host)
	int first_byte;		///< from the request being written to the first byte of the response; covers the time the device needs to execute a blocking method
	int inter_byte;		///< longest silence between two reads once the response started
	int total;				///< whole call including a reconnect and the retry
} alpaca_http_timeouts;

/** Optional settings of one request. A NULL pointer or a zeroed structure selects the defaults.
 */
typedef struct {
	alpaca_http_timeouts timeouts;
	/** Extra request header lines, each terminated by CRLF, e.g. "Accept: application/imagebytes, application/json\r\n", or NULL. Host, Connection, User-Agent, Content-Type and Content-Length are generated and must not be repeated here. */
	const char *headers;
	/** A PUT may be written a second time when a reused connection fails after the request was written and before any byte of the response arrived. Leave it false for methods that are not idempotent (relative moves, pulse guiding, start of an exposure). GET requests are always replayable.
	 A PUT that is not replayable and hits that failure ends with ALPACA_HTTP_RESET, although the device may have executed it. Servers that close the connection after every response without announcing it with "Connection: close" make this possible in the short interval before their close arrives here. To rule it out, call alpaca_http_connection_close() before such a PUT: over a new connection nothing is ever repeated and a failure is never caused by reuse. */
	bool replayable;
} alpaca_http_options;

/** Response owned by the caller and reused across requests, typically a member of the driver private data.
 Initialise it once with alpaca_http_response_init() and release it with alpaca_http_response_free().
 Every request overwrites all members; the body content of the previous response is gone as soon as the next request starts.
 */
typedef struct {
	int status;																								///< HTTP status code, 0 if no complete header block of a final (not 1xx) response was received
	char content_type[ALPACA_HTTP_CONTENT_TYPE_SIZE];					///< Content-Type value as received (may carry parameters such as "; charset=utf-8"), empty if absent
	char content_encoding[ALPACA_HTTP_CONTENT_ENCODING_SIZE];	///< Content-Encoding value, empty if absent; the body is NOT decoded
	char location[ALPACA_HTTP_LOCATION_SIZE];									///< Location value of a redirect, empty if absent; redirects are never followed
	alpaca_http_buffer body;																	///< response body, NUL-terminated
} alpaca_http_response;

/** Connection to one host:port. The caller serialises access: one connection object must not be used by two threads
 at the same time, and the response passed to a request must not be touched until the request returns.
 Different connection objects share no state, so several of them, also to the same server, can be used concurrently from different threads.
 */
typedef struct alpaca_http_connection alpaca_http_connection;

/** Initialise an empty buffer that can hold at most max_size bytes of content. Nothing is allocated yet.
 */
extern void alpaca_http_buffer_init(alpaca_http_buffer *buffer, size_t max_size);

/** Release the allocation. The buffer stays initialised with the same max_size and can be used again.
 */
extern void alpaca_http_buffer_free(alpaca_http_buffer *buffer);

/** Drop the content and keep the allocation.
 */
extern void alpaca_http_buffer_clear(alpaca_http_buffer *buffer);

/** Make sure that size bytes of content plus the terminator fit without another allocation. Returns false if size exceeds max_size.
 */
extern bool alpaca_http_buffer_reserve(alpaca_http_buffer *buffer, size_t size);

/** Append size bytes. Returns false and leaves the content unchanged if the result would exceed max_size.
 */
extern bool alpaca_http_buffer_append(alpaca_http_buffer *buffer, const void *data, size_t size);

/** Append text percent-encoded: everything except A-Z a-z 0-9 '-' '.' '_' '~' becomes %XX with upper case hex digits, byte by byte, so UTF-8 text is encoded correctly.
 A space becomes %20 and '+' becomes %2B, which is valid and unambiguous both in a URL query and in an application/x-www-form-urlencoded body.
 Returns false and leaves the content unchanged if the result would exceed max_size.
 */
extern bool alpaca_http_buffer_append_encoded(alpaca_http_buffer *buffer, const char *text);

/** Form and query builder. Each call appends "name=value", preceded by '&' unless the buffer is empty, with name and value percent-encoded.
 The same text is valid as the query of a GET and as the form body of a PUT. Start a new form with alpaca_http_buffer_clear().
 Names are written as given: Alpaca form keys are case sensitive, pass the exact casing of the specification.
 The functions return false and leave the content unchanged if the result would exceed max_size (or, for doubles, if the value is not finite).
 */
extern bool alpaca_http_form_add_string(alpaca_http_buffer *form, const char *name, const char *value);

/** Integers are written in decimal notation without grouping.
 */
extern bool alpaca_http_form_add_int(alpaca_http_buffer *form, const char *name, long long value);

/** Booleans are written as "True" and "False", the way the ASCOM reference clients (ASCOMLibrary, alpyca) send them.
 */
extern bool alpaca_http_form_add_bool(alpaca_http_buffer *form, const char *name, bool value);

/** Doubles are written with alpaca_http_format_double().
 */
extern bool alpaca_http_form_add_double(alpaca_http_buffer *form, const char *name, double value);

/** Format a double independently of LC_NUMERIC: '.' as the decimal separator, no grouping, the shortest of 15, 16 or 17 significant digits
 that reads back as exactly the same value, e.g. "1.5", "0.1", "-12.25", "1e-05". Returns false if the value is not finite or size is below ALPACA_HTTP_DOUBLE_SIZE.
 */
extern bool alpaca_http_format_double(char *text, size_t size, double value);

/** Initialise a response whose body can hold at most max_body_size bytes. Larger bodies are refused with ALPACA_HTTP_TOO_LARGE.
 */
extern void alpaca_http_response_init(alpaca_http_response *response, size_t max_body_size);

/** Release the body of a response. The response stays initialised and can be used again.
 */
extern void alpaca_http_response_free(alpaca_http_response *response);

/** Check the media type of a response without regard to case and to parameters, e.g. alpaca_http_response_is(response, "application/imagebytes").
 */
extern bool alpaca_http_response_is(const alpaca_http_response *response, const char *content_type);

/** Create a connection object for host:port. The host is a name or a numeric IPv4 or IPv6 address (without brackets, an IPv6 zone such as "%en0" is allowed).
 Nothing is connected yet, the socket is opened by the first request. Returns NULL if host is NULL, empty or too long or the port is out of range.
 */
extern alpaca_http_connection *alpaca_http_connection_create(const char *host, int port);

/** Close the socket if it is open. The object stays valid and the next request connects again.
 */
extern void alpaca_http_connection_close(alpaca_http_connection *connection);

/** Close the socket and release the object. NULL is ignored.
 */
extern void alpaca_http_connection_free(alpaca_http_connection *connection);

/** Check without blocking whether a kept-alive socket is still usable. A socket that the peer closed in the meantime, or that holds unexpected data, is closed here.
 Every request does the same check before it reuses the socket.
 */
extern bool alpaca_http_connection_is_open(alpaca_http_connection *connection);

/** Number of TCP connections this object has established so far, for diagnostics and tests.
 */
extern unsigned alpaca_http_connection_connects(const alpaca_http_connection *connection);

/** Send "GET path[?query]" and receive the response.
 The path must start with '/'. The query is already encoded text without the leading '?' (see the form builder), or NULL.
 The socket is opened on demand and kept open afterwards if the server allows it.
 If a reused socket turns out to be stale, the request is sent once more over a new connection: always when that is detected before anything was written,
 and for replayable requests also when the reused socket fails after the request was written and before a single byte of the response arrived.
 A request whose response already started is never repeated, and neither is a request over a new connection.
 Interim 1xx responses are skipped, redirects are reported as their 3xx status and not followed.
 The call never blocks longer than the total timeout (plus the connect timeout for each further address of a host name that resolves to several addresses).
 */
extern alpaca_http_result alpaca_http_get(alpaca_http_connection *connection, const char *path, const char *query, const alpaca_http_options *options, alpaca_http_response *response);

/** Send "PUT path[?query]" with an application/x-www-form-urlencoded body and receive the response.
 The form is already encoded text (see the form builder); NULL or "" sends an empty body with Content-Length: 0. Everything else is as for alpaca_http_get().
 */
extern alpaca_http_result alpaca_http_put(alpaca_http_connection *connection, const char *path, const char *query, const char *form, const alpaca_http_options *options, alpaca_http_response *response);

/** Short description of a result for logs and messages.
 */
extern const char *alpaca_http_result_text(alpaca_http_result result);

#ifdef __cplusplus
}
#endif

#endif /* system_alpaca_http_h */
