// Copyright (c) 2026 CloudMakers, s. r. o.
// All rights reserved.
//
// You can use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// version history
// 3.0 by Peter Polakovic <peter.polakovic@cloudmakers.eu>

// Code is generated by AI

/** INDIGO ASCOM Alpaca client driver, interface between the driver core and the device class modules
 \file indigo_system_alpaca_private.h

 HOW THE DRIVER IS BUILT

 The core (indigo_system_alpaca.c) owns the bridge device "Alpaca", discovery, the list of servers and devices, and
 the common behaviour of every proxy device: CONNECTION, INFO, the capability cache, polling and transport loss.
 A device class module (indigo_system_alpaca_<class>.c) maps one Alpaca device type onto one INDIGO device class.
 It exports a single alpaca_class and is never called by anything but the core. Everything a module needs is
 declared in this header and in indigo_system_alpaca_transport.h; a module never includes or changes the core.

 One Alpaca device is represented by one alpaca_private_data. It is the private data of the primary INDIGO device
 and of its secondary device (a guider of a camera or a telescope), like the private data shared by the logical
 devices of one physical device in a generated driver. The record of the server (alpaca_server) is shared by all
 devices of that server.

 HOW A CLASS MODULE IS WRITTEN

 1. Class data. Declare a struct with the property pointers and the state of the class and name its size in the
    class descriptor. The core allocates it zeroed before attach and frees it after detach. Reach it with
    CLASS_DATA, usually through a macro of the module:

        typedef struct {
          indigo_property *x_something_property;
          alpaca_operation move;
        } focuser_data;
        #define FOCUSER_DATA ((focuser_data *)CLASS_DATA)

 2. attach (driver queue; for a secondary device the handler queue of its primary device). No request to the device.

        static indigo_result focuser_attach(indigo_device *device) {
          if (indigo_focuser_attach(device, DRIVER_NAME, DRIVER_VERSION) == INDIGO_OK) {
            ... create the X_ properties of the class with indigo_init_*_property()
            return system_alpaca_attach(device) == INDIGO_OK ? focuser_enumerate_properties(device, NULL, NULL) : INDIGO_FAILED;
          }
          return INDIGO_FAILED;
        }

 3. enumerate_properties and change_property (bus thread: never send a request from here, only queue a handler).

        static indigo_result focuser_change_property(indigo_device *device, indigo_client *client, indigo_property *property) {
          if (system_alpaca_change_property(device, property)) {     // CONNECTION
            return INDIGO_OK;
          }
          if (indigo_property_match_changeable(FOCUSER_POSITION_PROPERTY, property)) {
            INDIGO_COPY_VALUES_PROCESS_CHANGE(FOCUSER_POSITION_PROPERTY, focuser_position_handler);
            return INDIGO_OK;
          }
          return indigo_focuser_change_property(device, client, property);
        }

 4. detach (driver queue; for a secondary device the handler queue of its primary device, or the driver queue with the
    device lock held when the primary device is detached).

        static indigo_result focuser_detach(indigo_device *device) {
          system_alpaca_detach(device);              // disconnects the device if it is still connected
          ... indigo_release_property() for the X_ properties of the class
          INDIGO_DEVICE_DETACH_LOG(DRIVER_NAME, device->name);
          return indigo_focuser_detach(device);
        }

 5. Hooks. All of them run on the handler queue of the device, one at a time, so the code of one device needs no
    locking. The only exception is on_disconnect when a connected device is detached: it then runs on the driver
    queue, with the device lock held, so still no handler of the device runs at the same time.

    on_probe       After the Alpaca device is connected and before anything is defined. Read the Can* flags and probe
                   the optional members with system_alpaca_probe_bool() / system_alpaca_probe_member(), read the static
                   values. Return false to fail the connection (e.g. after a transport error).
    on_connect     Set up the properties from what on_probe read: hidden flags, item counts, limits, initial values
                   of the base class properties (they are defined by the base class right after the hook) and, as the
                   last step, indigo_define_property() for the X_ properties of the class. Attach a guider with
                   system_alpaca_attach_secondary() here. Return false to fail the connection; nothing may stay
                   defined then.
    on_disconnect  Called exactly once for a connection whose on_connect returned true, before the Alpaca device is
                   disconnected: on a user disconnect, on detach and after the transport was lost. The core has
                   cancelled the pending handlers and finalizers of the device by then. Stop what has to be stopped,
                   call system_alpaca_operation_end() for the operations of the class, reset the properties that a
                   cancelled handler left BUSY and indigo_delete_property() the X_ properties of the class.
                   Requests still work unless the transport was lost; then they fail at once with
                   ALPACA_UNREACHABLE. (For a secondary device the pending handlers are cancelled right after.)
    on_poll        Called on every poll tick while connected. Read the state with system_alpaca_state_*() and
                   publish changed properties. Do not touch a property that is BUSY because of a running operation
                   unless the finalizer of the operation relies on it.

 6. Requests. Use system_alpaca_get_*() and system_alpaca_put() for the ordinary cases. For everything else call the
    transport layer directly with the channel of the device and pass the result through system_alpaca_check():

        int offsets[32], count = 0;
        alpaca_result result = system_alpaca_check(device, alpaca_get_int_array(system_alpaca_channel(device), "focusoffsets", NULL, 0, ALPACA_WAIT_STANDARD, offsets, 32, &count));

    system_alpaca_check() is what feeds the transport-loss detection, so no result may bypass it.
    A request that leaves its channel locked (alpaca_get_value(), alpaca_put_value(), alpaca_get_raw()) is ended with
    alpaca_end() on the same channel pointer before the handler returns: take the pointer once,
    "alpaca_channel *channel = system_alpaca_channel(device);", and use it for the request and for alpaca_end(), because
    system_alpaca_channel() returns NULL as soon as the transport counts as lost.
    Parameter names of a PUT are case sensitive: write them exactly as in the Alpaca specification ("Position").
    Mark every idempotent PUT with ALPACA_REPLAYABLE and leave every other one without it; after a failure for which
    alpaca_may_have_executed() is true, read the state of the device instead of sending the request again.

 7. Long operations use the handler + finalizer pattern, never a waiting loop:

        static void focuser_position_finalizer(indigo_device *device) {
          bool moving = false;
          if (!IS_CONNECTED) {
            return;
          }
          alpaca_result result = system_alpaca_get_bool(device, "ismoving", &moving);
          if (result == ALPACA_OK && moving && system_alpaca_operation_continue(device, &FOCUSER_DATA->move, focuser_position_finalizer)) {
            return;                                          // still moving, the finalizer runs again
          }
          system_alpaca_operation_end(device, &FOCUSER_DATA->move);
          system_alpaca_finish(device, FOCUSER_POSITION_PROPERTY, result == ALPACA_OK && moving ? ALPACA_TIMED_OUT : result, "Move");
        }

        static void focuser_position_handler(indigo_device *device) {
          alpaca_param params[] = { ALPACA_INT_PARAM("Position", (int)FOCUSER_POSITION_ITEM->number.target) };
          alpaca_result result = system_alpaca_put(device, "move", params, 1, ALPACA_WAIT_LONG);
          if (result == ALPACA_OK) {
            system_alpaca_operation_start(device, &FOCUSER_DATA->move, 600, focuser_position_finalizer);
          } else {
            system_alpaca_finish(device, FOCUSER_POSITION_PROPERTY, result, "Move");
          }
        }

    Completion is decided by the completion member of the Alpaca specification (IsMoving, Slewing, ImageReady, ...),
    never by comparing positions. An error while reading it means that the operation failed. Every handler and
    finalizer starts with "if (!IS_CONNECTED) return;" because it may have been queued just before a disconnect.

 8. Secondary devices. A class with a name_suffix and without a device_type is the class of a secondary device: the
    guider of a camera or a telescope (system_alpaca_guider_class). The primary class attaches it from on_connect with
    system_alpaca_attach_secondary(); the core detaches it when the primary device disconnects. Both devices talk to
    the same Alpaca device through the same channel and share alpaca_private_data, so system_alpaca_*() works the same
    way for both. A secondary class gets the same callbacks and hooks; its connect and disconnect send nothing to the
    Alpaca device, because the primary device holds the connection. Code that has to know which one it runs for
    compares device with PRIVATE_DATA->secondary.

 9. Register the class: the descriptor is declared at the end of this header and listed in system_alpaca_classes[]
    in the core. Both lines exist for all classes of the first version, so a module only fills its own file.

 10. Symbols. Everything in a module is static except the class descriptor system_alpaca_<class>_class.
     Custom properties are prefixed X_ALPACA_ and documented in indigo_docs/PROPERTIES.md.

 11. Tests. The cases of a class live in indigo_test/integration/system_alpaca/<class>_cases.h and run against
     system_alpaca_simulator; system_alpaca_test_common.h in the same directory describes how a case is written.

 WHAT THE CORE DOES FOR EVERY CLASS

 - CONNECTION: connect, disconnect, the secondary device, the messages, the call of the base class at the end.
 - INFO: DEVICE_MODEL (Description of the device), the driver behind the Alpaca device, the interface version and the UniqueID.
 - Polling: one tick per device every X_ALPACA_POLLING.IDLE seconds, every X_ALPACA_POLLING.ACTIVE seconds while an
   operation started with system_alpaca_operation_start() runs. A tick reads devicestate (Platform 7) or "connected".
 - Transport loss: two requests in a row that fail with a transport error, or one answer NotConnected, take the device
   to the disconnected state with CONNECTION in ALERT at the next tick; on_disconnect is called on the way. The user
   (or an agent) connects again. A class never has to detect this itself; it only reports the failed request.
 - A property that is changed without INDIGO_COPY_VALUES_PROCESS_CHANGE has to be answered all the same: the bus drops
   an update that changes neither a value nor the state, unless property->do_update is set before indigo_update_property().
 */

#ifndef system_alpaca_private_h
#define system_alpaca_private_h

#include <indigo/indigo_driver.h>
#include <indigo/indigo_timer.h>

#include "indigo_system_alpaca_transport.h"

#ifdef __cplusplus
extern "C" {
#endif

#define DRIVER_VERSION										0x03000001
#define DRIVER_NAME												"indigo_system_alpaca"
#define DRIVER_LABEL											"ASCOM Alpaca Client"

/** Private data of a proxy device, shared by the primary device and its secondary device.
 */
#define PRIVATE_DATA											((alpaca_private_data *)device->private_data)

/** Class data of the device the code runs for (the primary or the secondary one).
 */
#define CLASS_DATA												(device == PRIVATE_DATA->secondary ? PRIVATE_DATA->secondary_data : PRIVATE_DATA->class_data)

/** Largest number of cached capabilities of one device.
 */
#define ALPACA_MAX_CAPABILITIES						128

/** Descriptor of a device class module.
 */
typedef struct {
	/** Alpaca DeviceType the class is a proxy of, compared without regard to case, e.g. "Focuser". NULL for a class that is only used for secondary devices. */
	const char *device_type;
	/** Suffix of the name of a secondary device, e.g. " (guider)". NULL for the class of a primary device. */
	const char *name_suffix;
	/** First InterfaceVersion of the device type that has the Platform 7 members connect, disconnect, connecting and devicestate. Not used for secondary devices. */
	int platform7_version;
	/** Size of the class data in bytes, 0 if the class has none. */
	size_t data_size;
	/** Device callbacks, see the description at the top of this file. */
	indigo_result (*attach)(indigo_device *device);
	indigo_result (*enumerate_properties)(indigo_device *device, indigo_client *client, indigo_property *property);
	indigo_result (*change_property)(indigo_device *device, indigo_client *client, indigo_property *property);
	indigo_result (*detach)(indigo_device *device);
	/** change_property of the INDIGO base class, e.g. indigo_focuser_change_property. The core calls it to finish every change of CONNECTION. */
	indigo_result (*base_change_property)(indigo_device *device, indigo_client *client, indigo_property *property);
	/** Hooks, any of them may be NULL. */
	bool (*on_probe)(indigo_device *device);
	bool (*on_connect)(indigo_device *device);
	void (*on_disconnect)(indigo_device *device);
	void (*on_poll)(indigo_device *device);
} alpaca_class;

/** One entry of the capability cache: the result of reading a member once per connection.
 */
typedef struct {
	char member[ALPACA_MEMBER_SIZE];
	bool supported;			///< false if the device answered "not implemented" or HTTP 400
	bool value;					///< value of a boolean capability, false if it is not supported
} alpaca_capability;

/** State of one long operation of a class, see system_alpaca_operation_start().
 */
typedef struct {
	bool active;
	double deadline;
} alpaca_operation;

/** Private data of one Alpaca device. Class modules read the members marked "read only" and never write the others.
 */
typedef struct {
	// identity, set before attach (read only)
	alpaca_server *server;										///< record of the server the device belongs to
	const alpaca_class *device_class;					///< class of the primary device
	char device_type[ALPACA_TYPE_SIZE];				///< DeviceType as reported by the server, e.g. "Focuser"
	int device_number;												///< DeviceNumber
	char device_name[ALPACA_TEXT_SIZE];				///< DeviceName as reported by the server
	char unique_id[ALPACA_TEXT_SIZE];					///< UniqueID
	indigo_device *device;										///< primary INDIGO device
	indigo_device *secondary;									///< secondary INDIGO device (guider), NULL if there is none
	const alpaca_class *secondary_class;			///< class of the secondary device
	void *class_data;													///< class data of the primary device, use CLASS_DATA
	void *secondary_data;											///< class data of the secondary device, use CLASS_DATA
	// connection (read only)
	int interface_version;										///< InterfaceVersion, read when the device is attached and again on every connect
	bool platform7;														///< the device has connect, disconnect, connecting and devicestate
	// owned by the core
	alpaca_channel *channel;									///< connection used for all ordinary requests, use system_alpaca_channel()
	alpaca_channel *transfer;									///< connection for long transfers, use system_alpaca_transfer_channel()
	int count;																///< logical devices (primary, secondary) that hold the connection to the Alpaca device open
	bool session;															///< on_connect of the primary class succeeded and on_disconnect was not called yet
	bool secondary_session;										///< the same for the secondary class
	bool offline;															///< the transport is lost: requests fail at once until the next connect
	bool detaching;														///< the device is being detached, no handler may start anything
	int transport_errors;											///< consecutive requests that failed with a transport error
	bool not_connected;												///< the device answered NotConnected
	double connect_deadline;									///< end of the time a Platform 7 connect may take
	int operations;														///< running operations, see system_alpaca_operation_start()
	bool polling;															///< a devicestate snapshot is being served to on_poll
	bool has_device_state;										///< devicestate is usable on this device
	alpaca_device_state state;								///< devicestate snapshot of the current poll tick
	int capability_count;
	alpaca_capability capabilities[ALPACA_MAX_CAPABILITIES];
} alpaca_private_data;

#pragma mark - lifecycle helpers, called from the device callbacks of a class

/** Common part of attach. Call it after the attach of the base class and after the properties of the class are created.
 It fills INFO, hides the properties that make no sense for a proxy and logs the attach. Returns INDIGO_OK.
 */
extern indigo_result system_alpaca_attach(indigo_device *device);

/** Common part of change_property. Call it first; if it returns true the request was a change of CONNECTION and is handled.
 The connection is established on the handler queue of the device: InterfaceVersion is read, the device is connected
 (Platform 7: PUT connect and a finalizer on "connecting" bounded by the establish timeout; older devices: PUT connected),
 INFO is filled, on_probe and on_connect are called, polling starts. A disconnect calls on_disconnect, detaches the
 secondary device and sends disconnect / Connected=False to the Alpaca device.
 */
extern bool system_alpaca_change_property(indigo_device *device, indigo_property *property);

/** Common part of detach. Call it first. A device that is still connected is disconnected here.
 */
extern void system_alpaca_detach(indigo_device *device);

/** Create and attach a secondary device of the given class for the primary device, e.g. system_alpaca_attach_secondary(device, &system_alpaca_guider_class)
 from on_connect of a camera or a telescope that can pulse guide. The secondary device is named "<primary name><name_suffix>", shares the
 private data and the handler queue of the primary one and exists while the primary device is connected: the core detaches and releases it
 on disconnect. Returns false if the device already has a secondary device or the attach failed.
 */
extern bool system_alpaca_attach_secondary(indigo_device *device, const alpaca_class *secondary_class);

#pragma mark - requests

/** Channel for the ordinary requests to the Alpaca device, for direct calls of the transport layer. NULL while the transport is lost;
 the transport layer answers ALPACA_UNREACHABLE to a NULL channel, so the result can be used without a check.
 */
extern alpaca_channel *system_alpaca_channel(indigo_device *device);

/** Second channel to the same Alpaca device with its own socket and buffers, for long transfers (imagearray) that must not delay the
 ordinary requests. It is created by the first call with the given limit of the reply body and closed on disconnect. NULL while the transport is lost.
 */
extern alpaca_channel *system_alpaca_transfer_channel(indigo_device *device, size_t max_body_size);

/** Record the result of a request made directly through the transport layer and return it unchanged. Transport errors are counted
 (two in a row mark the transport as lost; the next poll tick then takes the device to the disconnected state) and NotConnected is noted.
 */
extern alpaca_result system_alpaca_check(indigo_device *device, alpaca_result result);

/** GET a member without parameters with the standard timeout. The result is already passed through system_alpaca_check().
 */
extern alpaca_result system_alpaca_get_bool(indigo_device *device, const char *member, bool *value);
extern alpaca_result system_alpaca_get_int(indigo_device *device, const char *member, int *value);
extern alpaca_result system_alpaca_get_double(indigo_device *device, const char *member, double *value);
extern alpaca_result system_alpaca_get_string(indigo_device *device, const char *member, char *value, size_t size);

/** PUT a method or a setter, see alpaca_put(). The result is already passed through system_alpaca_check().
 */
extern alpaca_result system_alpaca_put(indigo_device *device, const char *member, const alpaca_param *params, int count, int options);

/** Text of the failure of the last request on the ordinary channel: the ErrorMessage of the device or a description of the transport failure.
 */
extern const char *system_alpaca_error(indigo_device *device);

#pragma mark - state

/** Read one value of the operational state by its ASCOM name, e.g. system_alpaca_state_bool(device, "IsMoving", &moving).
 Inside on_poll the value comes from the devicestate snapshot the core read for this tick (Platform 7). If the snapshot has no such
 entry, on older devices and outside on_poll the member is read with a GET of its own. A member the device does not implement is
 remembered in the capability cache and answered with ALPACA_UNSUPPORTED without a request from then on.
 */
extern alpaca_result system_alpaca_state_bool(indigo_device *device, const char *name, bool *value);
extern alpaca_result system_alpaca_state_int(indigo_device *device, const char *name, int *value);
extern alpaca_result system_alpaca_state_double(indigo_device *device, const char *name, double *value);
extern alpaca_result system_alpaca_state_string(indigo_device *device, const char *name, char *value, size_t size);

#pragma mark - capabilities

/** Read a boolean capability (canpark, absolute, tempcompavailable...) once per connection. A member the device does not implement
 gives false and ALPACA_OK, and is cached like a real answer. Any other failure is returned and not cached.
 */
extern alpaca_result system_alpaca_probe_bool(indigo_device *device, const char *member, bool *value);

/** Find out once per connection whether the device implements an optional member that has no Can* flag (temperature, position of a
 relative focuser, a weather sensor...). *supported is false if the device answers "not implemented" (ErrorNumber 0x400 or HTTP 400)
 and true for a value and for any other ErrorNumber of the device. When there is no usable answer (a transport error,
 ALPACA_PROTOCOL_ERROR, ALPACA_SERVER_ERROR) that result is returned and nothing is cached.
 */
extern alpaca_result system_alpaca_probe_member(indigo_device *device, const char *member, bool *supported);

/** Cached value of a boolean capability; false if it was not probed, is not supported or is false.
 */
extern bool system_alpaca_can(indigo_device *device, const char *member);

/** False if the member is known not to be implemented by the device, true otherwise.
 */
extern bool system_alpaca_supported(indigo_device *device, const char *member);

/** Remember that the device does not implement a member, e.g. after a PUT answered with ALPACA_UNSUPPORTED.
 */
extern void system_alpaca_set_unsupported(indigo_device *device, const char *member);

#pragma mark - operations and property states

/** Start watching a long operation: remember that it has to end within timeout seconds, switch the polling of the device to the
 faster rhythm (the next tick comes one active interval from now) and schedule the finalizer on the handler queue of the device.
 Like all helpers it is called from a handler, a finalizer or a hook of the device, never from a bus callback.
 */
extern void system_alpaca_operation_start(indigo_device *device, alpaca_operation *operation, double timeout, indigo_timer_callback finalizer);

/** Called by a finalizer that found the operation still running: schedule the finalizer again and return true, or return false if the
 time of the operation is over (the caller then ends the operation and reports a timeout).
 */
extern bool system_alpaca_operation_continue(indigo_device *device, alpaca_operation *operation, indigo_timer_callback finalizer);

/** Stop watching an operation; the polling returns to the idle rhythm when no operation is left. Safe to call for an operation that
 is not active. The core cancels the pending finalizers on disconnect; on_disconnect calls this for the operations of the class.
 */
extern void system_alpaca_operation_end(indigo_device *device, alpaca_operation *operation);

/** Property state for a result: INDIGO_OK_STATE for ALPACA_OK, INDIGO_ALERT_STATE for everything else.
 */
extern indigo_property_state system_alpaca_property_state(alpaca_result result);

/** Finish a request of a client: set the state of the property from the result and publish it, on failure with the message
 "<action> failed: <reason>" where the reason is the ErrorMessage of the device or the transport failure. action may be NULL.
 */
extern void system_alpaca_finish(indigo_device *device, indigo_property *property, alpaca_result result, const char *action);

/** Poll interval in seconds: the idle one, or the one used while an operation runs (X_ALPACA_POLLING of the bridge device).
 */
extern double system_alpaca_poll_interval(bool active);

#pragma mark - device classes

extern const alpaca_class system_alpaca_focuser_class;
extern const alpaca_class system_alpaca_wheel_class;
extern const alpaca_class system_alpaca_rotator_class;
extern const alpaca_class system_alpaca_mount_class;
extern const alpaca_class system_alpaca_ccd_class;
extern const alpaca_class system_alpaca_guider_class;
extern const alpaca_class system_alpaca_dome_class;
extern const alpaca_class system_alpaca_lightbox_class;
extern const alpaca_class system_alpaca_switch_class;
extern const alpaca_class system_alpaca_weather_class;
extern const alpaca_class system_alpaca_safety_class;

#ifdef __cplusplus
}
#endif

#endif /* system_alpaca_private_h */
