indigo_rotator_lunatico.c: ../focuser_lunatico/shared/lunatico_shared.c
	touch indigo_rotator_lunatico.c

indigo_rotator_lunatico_main.c: ../focuser_lunatico/shared/lunatico_main_shared.c
	touch indigo_rotator_lunatico_main.c
